<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>data_summaries</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="08-data_summaries_files/libs/clipboard/clipboard.min.js"></script>
<script src="08-data_summaries_files/libs/quarto-html/quarto.js"></script>
<script src="08-data_summaries_files/libs/quarto-html/popper.min.js"></script>
<script src="08-data_summaries_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="08-data_summaries_files/libs/quarto-html/anchor.min.js"></script>
<link href="08-data_summaries_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="08-data_summaries_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="08-data_summaries_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="08-data_summaries_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="08-data_summaries_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="summarizing-smart_cle1" class="level1">
<h1>Summarizing <code>smart_cle1</code></h1>
<p>In this chapter, we’ll work with the two data files we built in <strong>?@sec-single-imp</strong>.</p>
<section id="r-setup-used-here" class="level2">
<h2 class="anchored" data-anchor-id="r-setup-used-here">R Setup Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-load" class="level3">
<h3 class="anchored" data-anchor-id="data-load">Data Load</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/smart_cle1_sh.Rds"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>smart_cle1_cc <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/smart_cle1_cc.Rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="whats-in-these-data" class="level2">
<h2 class="anchored" data-anchor-id="whats-in-these-data">What’s in these data?</h2>
<p>Those files (<code>_sh</code> contains single imputations, and a shadow set of variables which have _NA at the end of their names, while <code>_cc</code> contains only the complete cases) describe information on the following variables from the BRFSS 2017, who live in the Cleveland-Elyria, OH, Metropolitan Statistical Area.</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 84%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>SEQNO</code></td>
<td>respondent identification number (all begin with 2016)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>physhealth</code></td>
<td>Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>genhealth</code></td>
<td>Would you say that in general, your health is … (five categories: Excellent, Very Good, Good, Fair or Poor)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>bmi</code></td>
<td>Body mass index, in kg/m<sup>2</sup></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>age_imp</code></td>
<td>Age, imputed, in years</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>female</code></td>
<td>Sex, 1 = female, 0 = male</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>race_eth</code></td>
<td>Race and Ethnicity, in five categories</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>internet30</code></td>
<td>Have you used the internet in the past 30 days? (1 = yes, 0 = no)</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>smoke100</code></td>
<td>Have you smoked at least 100 cigarettes in your life? (1 = yes, 0 = no)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>activity</code></td>
<td>Physical activity (Highly Active, Active, Insufficiently Active, Inactive)</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>drinks_wk</code></td>
<td>On average, how many drinks of alcohol do you consume in a week?</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>veg_day</code></td>
<td>How many servings of vegetables do you consume per day, on average?</td>
</tr>
</tbody>
</table>
</section>
<section id="general-approaches-to-obtaining-numeric-summaries" class="level2">
<h2 class="anchored" data-anchor-id="general-approaches-to-obtaining-numeric-summaries">General Approaches to Obtaining Numeric Summaries</h2>
<section id="summary-for-a-data-frame" class="level3">
<h3 class="anchored" data-anchor-id="summary-for-a-data-frame"><code>summary</code> for a data frame</h3>
<p>Of course, we can use the usual <code>summary</code> to get some basic information about the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(smart_cle1_cc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     SEQNO             physhealth           genhealth        bmi       
 Min.   :2.017e+09   Min.   : 0.000   1_Excellent:134   Min.   :13.30  
 1st Qu.:2.017e+09   1st Qu.: 0.000   2_VeryGood :314   1st Qu.:24.23  
 Median :2.017e+09   Median : 0.000   3_Good     :284   Median :27.48  
 Mean   :2.017e+09   Mean   : 4.361   4_Fair     :114   Mean   :28.51  
 3rd Qu.:2.017e+09   3rd Qu.: 3.000   5_Poor     : 46   3rd Qu.:31.82  
 Max.   :2.017e+09   Max.   :30.000                     Max.   :63.00  
    age_imp          female                           race_eth  
 Min.   :18.00   Min.   :0.0000   White non-Hispanic      :661  
 1st Qu.:43.00   1st Qu.:0.0000   Black non-Hispanic      :168  
 Median :58.00   Median :1.0000   Other race non-Hispanic : 20  
 Mean   :56.46   Mean   :0.5807   Multiracial non-Hispanic: 17  
 3rd Qu.:69.00   3rd Qu.:1.0000   Hispanic                : 26  
 Max.   :95.00   Max.   :1.0000                                 
   internet30       smoke100                       activity     drinks_wk     
 Min.   :0.000   Min.   :0.0000   Highly_Active        :308   Min.   : 0.000  
 1st Qu.:1.000   1st Qu.:0.0000   Active               :155   1st Qu.: 0.000  
 Median :1.000   Median :0.0000   Insufficiently_Active:167   Median : 0.470  
 Mean   :0.833   Mean   :0.4787   Inactive             :262   Mean   : 2.727  
 3rd Qu.:1.000   3rd Qu.:1.0000                               3rd Qu.: 2.850  
 Max.   :1.000   Max.   :1.0000                               Max.   :56.000  
    veg_day     
 Min.   :0.000  
 1st Qu.:1.280  
 Median :1.730  
 Mean   :1.919  
 3rd Qu.:2.422  
 Max.   :7.300  </code></pre>
</div>
</div>
</section>
<section id="the-inspect-function-from-the-mosaic-package" class="level3">
<h3 class="anchored" data-anchor-id="the-inspect-function-from-the-mosaic-package">The <code>inspect</code> function from the <code>mosaic</code> package</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(smart_cle1_cc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
       name  class levels   n missing
1 genhealth factor      5 892       0
2  race_eth factor      5 892       0
3  activity factor      4 892       0
                                   distribution
1 2_VeryGood (35.2%), 3_Good (31.8%) ...       
2 White non-Hispanic (74.1%) ...               
3 Highly_Active (34.5%) ...                    

quantitative variables:  
        name   class       min         Q1       median           Q3
1      SEQNO numeric 2.017e+09 2.0170e+09 2.017001e+09 2.017001e+09
2 physhealth numeric 0.000e+00 0.0000e+00 0.000000e+00 3.000000e+00
3        bmi numeric 1.330e+01 2.4235e+01 2.747500e+01 3.181500e+01
4    age_imp numeric 1.800e+01 4.3000e+01 5.800000e+01 6.900000e+01
5     female numeric 0.000e+00 0.0000e+00 1.000000e+00 1.000000e+00
6 internet30 numeric 0.000e+00 1.0000e+00 1.000000e+00 1.000000e+00
7   smoke100 numeric 0.000e+00 0.0000e+00 0.000000e+00 1.000000e+00
8  drinks_wk numeric 0.000e+00 0.0000e+00 4.700000e-01 2.850000e+00
9    veg_day numeric 0.000e+00 1.2800e+00 1.730000e+00 2.422500e+00
           max         mean          sd   n missing
1 2017001133.0 2.017001e+09 326.8928344 892       0
2         30.0 4.360987e+00   8.8153373 892       0
3         63.0 2.850905e+01   6.5057975 892       0
4         95.0 5.645516e+01  18.0333027 892       0
5          1.0 5.807175e-01   0.4937185 892       0
6          1.0 8.329596e-01   0.3732212 892       0
7          1.0 4.786996e-01   0.4998263 892       0
8         56.0 2.726525e+00   5.7172011 892       0
9          7.3 1.918643e+00   1.0262415 892       0</code></pre>
</div>
</div>
</section>
<section id="the-describe-function-in-hmisc" class="level3">
<h3 class="anchored" data-anchor-id="the-describe-function-in-hmisc">The <code>describe</code> function in <code>Hmisc</code></h3>
<p>This provides some useful additional summaries, including a list of the lowest and highest values (which is very helpful when checking data.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_cc <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(bmi, genhealth, female) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>select(smart_cle1_cc, bmi, genhealth, female) 

 3  Variables      892  Observations
--------------------------------------------------------------------------------
bmi 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     892        0      481        1    28.51    6.952    20.09    21.40 
     .25      .50      .75      .90      .95 
   24.23    27.48    31.81    36.78    41.09 

lowest : 13.30 13.64 15.71 15.75 17.07, highest: 52.74 56.31 57.12 58.98 63.00
--------------------------------------------------------------------------------
genhealth 
       n  missing distinct 
     892        0        5 

lowest : 1_Excellent 2_VeryGood  3_Good      4_Fair      5_Poor     
highest: 1_Excellent 2_VeryGood  3_Good      4_Fair      5_Poor     
                                                                      
Value      1_Excellent  2_VeryGood      3_Good      4_Fair      5_Poor
Frequency          134         314         284         114          46
Proportion       0.150       0.352       0.318       0.128       0.052
--------------------------------------------------------------------------------
female 
       n  missing distinct     Info      Sum     Mean      Gmd 
     892        0        2     0.73      518   0.5807   0.4875 

--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<ul>
<li>The <code>Info</code> measure is used for quantitative and binary variables. It is a relative information measure that increases towards 1 for variables with no ties, and is smaller for variables with many ties.</li>
<li>The <code>Gmd</code> is the Gini mean difference. It is a measure of spread (or dispersion), where larger values indicate greater spread in the distribution, like the standard deviation or the interquartile range. It is defined as the mean absolute difference between any pairs of observations.</li>
</ul>
<p>See the Help file for <code>describe</code> in the <code>Hmisc</code> package for more details on these measures, and on the settings for <code>describe</code>.</p>
</section>
</section>
<section id="counting-as-exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counting-as-exploratory-data-analysis">Counting as exploratory data analysis</h2>
<p>Counting and/or tabulating things can be amazingly useful. Suppose we want to understand the <code>genhealth</code> values, after our single imputation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> <span class="fu">count</span>(genhealth) <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="dv">100</span><span class="sc">*</span>n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  genhealth       n percent
  &lt;fct&gt;       &lt;int&gt;   &lt;dbl&gt;
1 1_Excellent   164   14.5 
2 2_VeryGood    386   34.1 
3 3_Good        365   32.2 
4 4_Fair        158   13.9 
5 5_Poor         60    5.30</code></pre>
</div>
</div>
<p>We might use <code>tabyl</code> to do this job…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(genhealth) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_pct_formatting</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">genhealth</th>
<th style="text-align: right;">n</th>
<th style="text-align: left;">percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1_Excellent</td>
<td style="text-align: right;">164</td>
<td style="text-align: left;">14.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2_VeryGood</td>
<td style="text-align: right;">386</td>
<td style="text-align: left;">34.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3_Good</td>
<td style="text-align: right;">365</td>
<td style="text-align: left;">32.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">4_Fair</td>
<td style="text-align: right;">158</td>
<td style="text-align: left;">13.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5_Poor</td>
<td style="text-align: right;">60</td>
<td style="text-align: left;">5.3%</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="did-genhealth-vary-by-smoking-status" class="level3">
<h3 class="anchored" data-anchor-id="did-genhealth-vary-by-smoking-status">Did <code>genhealth</code> vary by smoking status?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(genhealth, smoke100) <span class="sc">|&gt;</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="dv">100</span><span class="sc">*</span>n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   genhealth   smoke100     n percent
   &lt;fct&gt;          &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
 1 1_Excellent        0   105    9.27
 2 1_Excellent        1    59    5.21
 3 2_VeryGood         0   220   19.4 
 4 2_VeryGood         1   166   14.7 
 5 3_Good             0   184   16.2 
 6 3_Good             1   181   16.0 
 7 4_Fair             0    67    5.91
 8 4_Fair             1    91    8.03
 9 5_Poor             0    24    2.12
10 5_Poor             1    36    3.18</code></pre>
</div>
</div>
<p>Suppose we want to find the percentage within each smoking status group. Here’s one approach…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(smoke100, genhealth) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(smoke100) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="dv">100</span><span class="sc">*</span>n <span class="sc">/</span> <span class="fu">sum</span>(n)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
# Groups:   smoke100 [2]
   smoke100 genhealth       n  prob
      &lt;dbl&gt; &lt;fct&gt;       &lt;int&gt; &lt;dbl&gt;
 1        0 1_Excellent   105 17.5 
 2        0 2_VeryGood    220 36.7 
 3        0 3_Good        184 30.7 
 4        0 4_Fair         67 11.2 
 5        0 5_Poor         24  4   
 6        1 1_Excellent    59 11.1 
 7        1 2_VeryGood    166 31.1 
 8        1 3_Good        181 34.0 
 9        1 4_Fair         91 17.1 
10        1 5_Poor         36  6.75</code></pre>
</div>
</div>
<p>And here’s another …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(smoke100, genhealth) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="at">where =</span> <span class="fu">c</span>(<span class="st">"row"</span>, <span class="st">"col"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_percentages</span>(<span class="at">denominator =</span> <span class="st">"row"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_pct_formatting</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_ns</span>(<span class="at">position =</span> <span class="st">"front"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> smoke100 1_Excellent  2_VeryGood      3_Good      4_Fair    5_Poor
        0 105 (17.5%) 220 (36.7%) 184 (30.7%)  67 (11.2%) 24 (4.0%)
        1  59 (11.1%) 166 (31.1%) 181 (34.0%)  91 (17.1%) 36 (6.8%)
    Total 164 (14.5%) 386 (34.1%) 365 (32.2%) 158 (13.9%) 60 (5.3%)
         Total
  600 (100.0%)
  533 (100.0%)
 1133 (100.0%)</code></pre>
</div>
</div>
</section>
<section id="whats-the-distribution-of-physhealth" class="level3">
<h3 class="anchored" data-anchor-id="whats-the-distribution-of-physhealth">What’s the distribution of <code>physhealth</code>?</h3>
<p>We can count quantitative variables with discrete sets of possible values, like <code>physhealth</code>, which is captured as an integer (that must fall between 0 and 30.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> <span class="fu">count</span>(physhealth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 2
   physhealth     n
        &lt;dbl&gt; &lt;int&gt;
 1          0   690
 2          1    49
 3          2    61
 4          3    39
 5          4    17
 6          5    43
 7          6    13
 8          7    18
 9          8     5
10         10    32
# … with 11 more rows</code></pre>
</div>
</div>
<p>Of course, a natural summary of a quantitative variable like this would be graphical.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(physhealth)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> <span class="st">"dodgerblue"</span>, <span class="at">col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Days with Poor Physical Health in the Past 30"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"Most subjects are pretty healthy in this regard, but there are some 30s"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-data_summaries_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="whats-the-distribution-of-bmi" class="level3">
<h3 class="anchored" data-anchor-id="whats-the-distribution-of-bmi">What’s the distribution of <code>bmi</code>?</h3>
<p><code>bmi</code> is the body-mass index, an indicator of size (thickness, really.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(bmi)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> <span class="st">"firebrick"</span>, <span class="at">col =</span> <span class="st">"white"</span>) <span class="sc">+</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Body-Mass Index for "</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">nrow</span>(smart_cle1_sh), </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">" BRFSS respondents"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-data_summaries_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="how-many-of-the-respondents-have-a-bmi-below-30" class="level3">
<h3 class="anchored" data-anchor-id="how-many-of-the-respondents-have-a-bmi-below-30">How many of the respondents have a BMI below 30?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> <span class="fu">count</span>(bmi <span class="sc">&lt;</span> <span class="dv">30</span>) <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  `bmi &lt; 30`     n proportion
  &lt;lgl&gt;      &lt;int&gt;      &lt;dbl&gt;
1 FALSE        330      0.291
2 TRUE         803      0.709</code></pre>
</div>
</div>
</section>
<section id="how-many-of-the-respondents-with-a-bmi-30-are-highly-active" class="level3">
<h3 class="anchored" data-anchor-id="how-many-of-the-respondents-with-a-bmi-30-are-highly-active">How many of the respondents with a BMI &lt; 30 are highly active?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bmi <span class="sc">&lt;</span> <span class="dv">30</span>) <span class="sc">|&gt;</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(activity) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_pct_formatting</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              activity   n percent
         Highly_Active 343   42.7%
                Active 133   16.6%
 Insufficiently_Active 129   16.1%
              Inactive 198   24.7%</code></pre>
</div>
</div>
</section>
<section id="is-obesity-associated-with-smoking-history" class="level3">
<h3 class="anchored" data-anchor-id="is-obesity-associated-with-smoking-history">Is obesity associated with smoking history?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> <span class="fu">count</span>(smoke100, bmi <span class="sc">&lt;</span> <span class="dv">30</span>) <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(smoke100) <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="dv">100</span><span class="sc">*</span>n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   smoke100 [2]
  smoke100 `bmi &lt; 30`     n percent
     &lt;dbl&gt; &lt;lgl&gt;      &lt;int&gt;   &lt;dbl&gt;
1        0 FALSE        163    27.2
2        0 TRUE         437    72.8
3        1 FALSE        167    31.3
4        1 TRUE         366    68.7</code></pre>
</div>
</div>
</section>
<section id="comparing-drinks_wk-summaries-by-obesity-status" class="level3">
<h3 class="anchored" data-anchor-id="comparing-drinks_wk-summaries-by-obesity-status">Comparing <code>drinks_wk</code> summaries by obesity status</h3>
<p>Can we compare the <code>drinks_wk</code> means, medians and 75<sup>th</sup> percentiles for respondents whose BMI is below 30 to the respondents whose BMI is not?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(bmi <span class="sc">&lt;</span> <span class="dv">30</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="fu">mean</span>(drinks_wk), <span class="fu">median</span>(drinks_wk), </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">q75 =</span> <span class="fu">quantile</span>(drinks_wk, <span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  `bmi &lt; 30` `mean(drinks_wk)` `median(drinks_wk)`   q75
  &lt;lgl&gt;                  &lt;dbl&gt;               &lt;dbl&gt; &lt;dbl&gt;
1 FALSE                   1.67                0.23  1.17
2 TRUE                    2.80                0.23  2.8 </code></pre>
</div>
</div>
</section>
</section>
<section id="can-bmi-predict-physhealth" class="level2">
<h2 class="anchored" data-anchor-id="can-bmi-predict-physhealth">Can <code>bmi</code> predict <code>physhealth</code>?</h2>
<p>We’ll start with an effort to predict <code>physhealth</code> using <code>bmi</code>. A natural graph would be a scatterplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> physhealth)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-data_summaries_files/figure-html/scatter_physhealth_bmi_1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A good question to ask ourselves here might be: “In what BMI range can we make a reasonable prediction of <code>physhealth</code>?”</p>
<p>Now, we might take the plot above and add a simple linear model …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> physhealth)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-data_summaries_files/figure-html/c2_scatter_physhealth_bmi_2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>which shows the same least squares regression model that we can fit with the <code>lm</code> command.</p>
<section id="fitting-a-simple-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-simple-regression-model">Fitting a Simple Regression Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>model_A <span class="ot">&lt;-</span> <span class="fu">lm</span>(physhealth <span class="sc">~</span> bmi, <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>model_A</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = physhealth ~ bmi, data = smart_cle1_sh)

Coefficients:
(Intercept)          bmi  
    -2.8121       0.2643  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = physhealth ~ bmi, data = smart_cle1_sh)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.5258  -4.5943  -3.5608  -0.5106  29.2965 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.81208    1.21672  -2.311    0.021 *  
bmi          0.26433    0.04188   6.312 3.95e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.968 on 1131 degrees of freedom
Multiple R-squared:  0.03403,   Adjusted R-squared:  0.03317 
F-statistic: 39.84 on 1 and 1131 DF,  p-value: 3.95e-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_A, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %     97.5 %
(Intercept) -5.1993624 -0.4247909
bmi          0.1821599  0.3464915</code></pre>
</div>
</div>
<p>The model coefficients can be obtained by printing the model object, and the <code>summary</code> function provides several useful descriptions of the model’s residuals, its statistical significance, and quality of fit.</p>
</section>
<section id="model-summary-for-a-simple-one-predictor-regression" class="level3">
<h3 class="anchored" data-anchor-id="model-summary-for-a-simple-one-predictor-regression">Model Summary for a Simple (One-Predictor) Regression</h3>
<p>The fitted model predicts <code>physhealth</code> using a prediction equation we can read off from the model coefficient estimates. Specifically, we have:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         bmi 
 -2.8120766   0.2643257 </code></pre>
</div>
</div>
<p>so the equation is <code>physhealth</code> = -2.82 + 0.265 <code>bmi</code>.</p>
<p>Each of the 1133 respondents included in the <code>smart_cle1_sh</code> data makes a contribution to this model.</p>
<section id="residuals" class="level4">
<h4 class="anchored" data-anchor-id="residuals">Residuals</h4>
<p>Suppose Harry is one of the people in that group, and Harry’s data is <code>bmi</code> = 20, and <code>physhealth</code> = 3.</p>
<ul>
<li>Harry’s <em>observed</em> value of <code>physhealth</code> is just the value we have in the data for them, in this case, observed <code>physhealth</code> = 3 for Harry.</li>
<li>Harry’s <em>fitted</em> or <em>predicted</em> <code>physhealth</code> value is the result of calculating -2.82 + 0.265 <code>bmi</code> for Harry. So, if Harry’s BMI was 20, then Harry’s predicted <code>physhealth</code> value is -2.82 + 0.265 (20) = 2.48.</li>
<li>The <em>residual</em> for Harry is then his <em>observed</em> outcome minus his <em>fitted</em> outcome, so Harry has a residual of 3 - 2.48 = 0.52.</li>
<li>Graphically, a residual represents vertical distance between the observed point and the fitted regression line.</li>
<li>Points above the regression line will have positive residuals, and points below the regression line will have negative residuals. Points on the line have zero residuals.</li>
</ul>
<p>The residuals are summarized at the top of the <code>summary</code> output for linear model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = physhealth ~ bmi, data = smart_cle1_sh)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.5258  -4.5943  -3.5608  -0.5106  29.2965 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.81208    1.21672  -2.311    0.021 *  
bmi          0.26433    0.04188   6.312 3.95e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.968 on 1131 degrees of freedom
Multiple R-squared:  0.03403,   Adjusted R-squared:  0.03317 
F-statistic: 39.84 on 1 and 1131 DF,  p-value: 3.95e-10</code></pre>
</div>
</div>
<ul>
<li>The mean residual will always be zero in an ordinary least squares model, but a five number summary of the residuals is provided by the summary, as is an estimated standard deviation of the residuals (called here the Residual standard error.)</li>
<li>In the <code>smart_cle1_sh</code> data, the minimum residual was -10.53, so for one subject, the observed value was 10.53 days smaller than the predicted value. This means that the prediction was 10.53 days too large for that subject.</li>
<li>Similarly, the maximum residual was 29.30 days, so for one subject the prediction was 29.30 days too small. Not a strong performance.</li>
<li>In a least squares model, the residuals are assumed to follow a Normal distribution, with mean zero, and standard deviation (for the <code>smart_cle1_sh</code> data) of about 9.0 days. We know this because the residual standard error is specified as 8.968 later in the linear model output. Thus, by the definition of a Normal distribution, we’d expect</li>
<li>about 68% of the residuals to be between -9 and +9 days,</li>
<li>about 95% of the residuals to be between -18 and +18 days,</li>
<li>about all (99.7%) of the residuals to be between -27 and +27 days.</li>
</ul>
</section>
<section id="coefficients-section" class="level4">
<h4 class="anchored" data-anchor-id="coefficients-section">Coefficients section</h4>
<p>The <code>summary</code> for a linear model shows Estimates, Standard Errors, t values and <em>p</em> values for each coefficient fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = physhealth ~ bmi, data = smart_cle1_sh)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.5258  -4.5943  -3.5608  -0.5106  29.2965 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.81208    1.21672  -2.311    0.021 *  
bmi          0.26433    0.04188   6.312 3.95e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.968 on 1131 degrees of freedom
Multiple R-squared:  0.03403,   Adjusted R-squared:  0.03317 
F-statistic: 39.84 on 1 and 1131 DF,  p-value: 3.95e-10</code></pre>
</div>
</div>
<ul>
<li>The Estimates are the point estimates of the intercept and slope of <code>bmi</code> in our model.</li>
<li>In this case, our estimated slope is 0.265, which implies that if Harry’s BMI is 20 and Sally’s BMI is 21, we predict that Sally’s <code>physhealth</code> will be 0.265 days larger than Harry’s.</li>
<li>The Standard Errors are also provided for each estimate. We can create rough 95% uncertainty intervals for these estimated coefficients by adding and subtracting two standard errors from each coefficient, or we can get a slightly more accurate answer with the <code>confint</code> function.</li>
<li>Here, the 95% uncertainty interval for the slope of <code>bmi</code> is estimated to be (0.18, 0.35). This is a good measure of the uncertainty in the slope that is captured by our model. We are 95% confident in the process of building this interval, but this doesn’t mean we’re 95% sure that the true slope is actually in that interval.</li>
</ul>
<p>Also available are a <em>t</em> value (just the Estimate divided by the Standard Error) and the appropriate <em>p</em> value for testing the null hypothesis that the true value of the coefficient is 0 against a two-tailed alternative.</p>
<ul>
<li>If a slope coefficient is statistically detectably different from 0, this implies that 0 will not be part of the uncertainty interval obtained through <code>confint</code>.</li>
<li>If the slope was zero, it would suggest that <code>bmi</code> would add no predictive value to the model. But that’s unlikely here.</li>
</ul>
<p>If the <code>bmi</code> slope coefficient is associated with a small <em>p</em> value, as in the case of our <code>model_A</code>, it suggests that the model including <code>bmi</code> is statistically detectably better at predicting <code>physhealth</code> than the model without <code>bmi</code>.</p>
<ul>
<li>Without <code>bmi</code> our <code>model_A</code> would become an <em>intercept-only</em> model, in this case, which would predict the mean <code>physhealth</code> for everyone, regardless of any other information.</li>
</ul>
</section>
<section id="model-fit-summaries" class="level4">
<h4 class="anchored" data-anchor-id="model-fit-summaries">Model Fit Summaries</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = physhealth ~ bmi, data = smart_cle1_sh)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.5258  -4.5943  -3.5608  -0.5106  29.2965 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.81208    1.21672  -2.311    0.021 *  
bmi          0.26433    0.04188   6.312 3.95e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.968 on 1131 degrees of freedom
Multiple R-squared:  0.03403,   Adjusted R-squared:  0.03317 
F-statistic: 39.84 on 1 and 1131 DF,  p-value: 3.95e-10</code></pre>
</div>
</div>
<p>The <code>summary</code> of a linear model also displays:</p>
<ul>
<li>The residual standard error and associated degrees of freedom for the residuals.</li>
<li>For a simple (one-predictor) least regression like this, the residual degrees of freedom will be the sample size minus 2.</li>
<li>The multiple R-squared (or coefficient of determination)</li>
<li>This is interpreted as the proportion of variation in the outcome (<code>physhealth</code>) accounted for by the model, and will always fall between 0 and 1 as a result.</li>
<li>Our model_A accounts for a mere 3.4% of the variation in <code>physhealth</code>.</li>
<li>The Adjusted R-squared value “adjusts” for the size of our model in terms of the number of coefficients included in the model.</li>
<li>The adjusted R-squared will always be smaller than the Multiple R-squared.</li>
<li>We still hope to find models with relatively large adjusted <span class="math inline">\(R^2\)</span> values.</li>
<li>In particular, we hope to find models where the adjusted <span class="math inline">\(R^2\)</span> isn’t substantially less than the Multiple R-squared.</li>
<li>The adjusted R-squared is usually a better estimate of likely performance of our model in new data than is the Multiple R-squared.</li>
<li>The adjusted R-squared result is no longer interpretable as a proportion of anything - in fact, it can fall below 0.</li>
<li>We can obtain the adjusted <span class="math inline">\(R^2\)</span> from the raw <span class="math inline">\(R^2\)</span>, the number of observations <em>N</em> and the number of predictors <em>p</em> included in the model, as follows:</li>
</ul>
<p><span class="math display">\[
R^2_{adj} = 1 - \frac{(1 - R^2)(N - 1)}{N - p - 1},
\]</span></p>
<ul>
<li>The F statistic and <em>p</em> value from a global ANOVA test of the model.
<ul>
<li>Obtaining a statistically significant result here is usually pretty straightforward, since the comparison is between our model, and a model which simply predicts the mean value of the outcome for everyone.</li>
<li>In a simple (one-predictor) linear regression like this, the t statistic for the slope is just the square root of the F statistic, and the resulting <em>p</em> values for the slope’s t test and for the global F test will be identical.</li>
</ul></li>
<li>To see the complete ANOVA F test for this model, we can run <code>anova(model_A)</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: physhealth
            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
bmi          1   3204  3204.4   39.84 3.95e-10 ***
Residuals 1131  90968    80.4                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
<section id="using-the-broom-package" class="level3">
<h3 class="anchored" data-anchor-id="using-the-broom-package">Using the <code>broom</code> package</h3>
<p>The <code>broom</code> package has three functions of particular use in a linear regression model:</p>
<section id="the-tidy-function" class="level4">
<h4 class="anchored" data-anchor-id="the-tidy-function">The <code>tidy</code> function</h4>
<p><code>tidy</code> builds a data frame/tibble containing information about the coefficients in the model, their standard errors, t statistics and <em>p</em> values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)   -2.81     1.22       -2.31 2.10e- 2
2 bmi            0.264    0.0419      6.31 3.95e-10</code></pre>
</div>
</div>
<p>It’s often useful to include other summaries in this tidying, for instance:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_A, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.9</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, conf.low, conf.high)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  term        estimate conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   -2.81    -4.82     -0.809
2 bmi            0.264    0.195     0.333</code></pre>
</div>
</div>
</section>
<section id="the-glance-function" class="level4">
<h4 class="anchored" data-anchor-id="the-glance-function">The <code>glance</code> function</h4>
<p>glance` builds a data frame/tibble containing summary statistics about the model, including</p>
<ul>
<li>the (raw) multiple <span class="math inline">\(R^2\)</span> and adjusted R^2</li>
<li><code>sigma</code> which is the residual standard error</li>
<li>the F <code>statistic</code>, <code>p.value</code> model <code>df</code> and <code>df.residual</code> associated with the global ANOVA test, plus</li>
<li>several statistics that will be useful in comparing models down the line:</li>
<li>the model’s log likelihood function value, <code>logLik</code></li>
<li>the model’s Akaike’s Information Criterion value, <code>AIC</code></li>
<li>the model’s Bayesian Information Criterion value, <code>BIC</code></li>
<li>and the model’s <code>deviance</code> statistic</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squa…¹ sigma stati…²  p.value    df logLik   AIC   BIC devia…³
      &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1    0.0340       0.0332  8.97    39.8 3.95e-10     1 -4092. 8190. 8205.  90968.
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance</code></pre>
</div>
</div>
</section>
<section id="the-augment-function" class="level4">
<h4 class="anchored" data-anchor-id="the-augment-function">The <code>augment</code> function</h4>
<p><code>augment</code> builds a data frame/tibble which adds fitted values, residuals and other diagnostic summaries that describe each observation to the original data used to fit the model, and this includes</p>
<ul>
<li><code>.fitted</code> and <code>.resid</code>, the fitted and residual values, in addition to</li>
<li><code>.hat</code>, the leverage value for this observation</li>
<li><code>.cooksd</code>, the Cook’s distance measure of <em>influence</em> for this observation</li>
<li><code>.stdresid</code>, the standardized residual (think of this as a z-score - a measure of the residual divided by its associated standard deviation <code>.sigma</code>)</li>
<li>and <code>se.fit</code> which will help us generate prediction intervals for the model downstream</li>
</ul>
<p>Note that each of the new columns begins with <code>.</code> to avoid overwriting any data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">augment</span>(model_A))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  physhealth   bmi .fitted .resid     .hat .sigma    .cooksd .std.resid
       &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1          4  27.9    4.57 -0.572 0.000886   8.97 0.00000181    -0.0638
2          0  23.0    3.28 -3.28  0.00149    8.97 0.000100      -0.366 
3          0  26.9    4.31 -4.31  0.000927   8.97 0.000107      -0.480 
4          0  26.5    4.20 -4.20  0.000956   8.97 0.000105      -0.468 
5          0  24.2    3.60 -3.60  0.00125    8.97 0.000101      -0.401 
6          2  27.7    4.51 -2.51  0.000891   8.97 0.0000351     -0.281 </code></pre>
</div>
</div>
<p>For more on the <code>broom</code> package, you may want to look at <a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html">this vignette</a>.</p>
</section>
</section>
<section id="how-does-the-model-do-residuals-vs.-fitted-values" class="level3">
<h3 class="anchored" data-anchor-id="how-does-the-model-do-residuals-vs.-fitted-values">How does the model do? (Residuals vs.&nbsp;Fitted Values)</h3>
<ul>
<li>Remember that the <span class="math inline">\(R^2\)</span> value was about 3.4%.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_A, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-data_summaries_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is a plot of residuals vs.&nbsp;fitted values. The goal here is for this plot to look like a random scatter of points, perhaps like a “fuzzy football”, and that’s <strong>not</strong> what we have. Why?</p>
<p>If you prefer, here’s a <code>ggplot2</code> version of a similar plot, now looking at standardized residuals instead of raw residuals, and adding a loess smooth and a linear fit to the result.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">augment</span>(model_A), <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">col =</span> <span class="st">"navy"</span>) <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="08-data_summaries_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The problem we’re having here becomes, I think, a little more obvious if we look at what we’re predicting. Does <code>physhealth</code> look like a good candidate for a linear model?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> physhealth)) <span class="sc">+</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"dodgerblue"</span>, </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"royalblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-data_summaries_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> <span class="fu">count</span>(physhealth <span class="sc">==</span> <span class="dv">0</span>, physhealth <span class="sc">==</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  `physhealth == 0` `physhealth == 30`     n
  &lt;lgl&gt;             &lt;lgl&gt;              &lt;int&gt;
1 FALSE             FALSE                343
2 FALSE             TRUE                 100
3 TRUE              FALSE                690</code></pre>
</div>
</div>
<p>No matter what model we fit, if we are predicting <code>physhealth</code>, and most of the data are values of 0 and 30, we have limited variation in our outcome, and so our linear model will be somewhat questionable just on that basis.</p>
<p>A normal Q-Q plot of the standardized residuals for our <code>model_A</code> shows this problem, too.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_A, <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08-data_summaries_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We’re going to need a method to deal with this sort of outcome, that has both a floor and a ceiling. We’ll get there eventually, but linear regression alone doesn’t look promising.</p>
<p>All right, so that didn’t go anywhere great. We’ll try again, with a new outcome, in the next chapter.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>