project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Biological, Medical and Health Research"
  subtitle: "Notes for PQHS/CRSP/MPHP 432 at CWRU"  
  author: "Thomas E. Love"
  date: last-modified
  date-format: iso
  search: true
  downloads: [pdf]
  chapters:
    - index.qmd
    - incomplete.qmd
    - setup.qmd
    - nhanes.qmd
    - nh432cb.qmd
    - 431review1.qmd
    - 431review2.qmd
    - 431review3.qmd
    - smart.qmd
    - singleimputation.qmd
    - datasummaries.qmd
    - anovasmart.qmd
    - anovaexamples.qmd
    - ancova_emphysema.qmd
    - ancova_smart.qmd
    - nonlinearity.qmd
    - olsfitting.qmd
    - prostate1.qmd
    - prostate2.qmd
    - multiple_imp.qmd
    - tableone.qmd
    - logistic1.qmd
    - logistic2.qmd
    - logistic3.qmd
    - effectsize.qmd
    - binaryregression.qmd
    - count1.qmd
    - count2.qmd
    - count3.qmd
    - ordinaloutcome.qmd
    - multinomial.qmd
    - survival_data.qmd
    - cox1.qmd
    - cox2.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    code-overflow: wrap
    bibliography: references.bib
  pdf:
    documentclass: scrreprt

editor: source

