project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Biological, Medical and Health Research"
  subtitle: "Spring 2023 Notes for 432"  
  author: "Thomas E. Love"
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - setup.qmd
    - nhanes.qmd
    - nh432cb.qmd
    - 431review1.qmd
    - 431review2.qmd
    - 431review3.qmd
    - smart.qmd
    - singleimputation.qmd
    - datasummaries.qmd
    - anovasmart.qmd
    - anovaexamples.qmd
    - ancova_emphysema.qmd
    - ancova_smart.qmd
    - nonlinearity.qmd
    - olsfitting.qmd
    - prostate1.qmd
    - prostate2.qmd
    - multiple_imp.qmd
    - tableone.qmd
    - logistic1.qmd
    - logistic2.qmd
    - logistic3.qmd
    - effectsize.qmd
    - binaryregression.qmd
    - incomplete.qmd

format:
  html:
    theme: cosmo
    code-overflow: wrap

