# R Setup {.unnumbered}

Here, we'll show all of the R packages used in these notes. The list of R Packages we will use in 432 is even more extensive, and is [available on our course website](https://thomaselove.github.io/432-2024/software.html#r-packages-to-install).

```{r}
#| eval: false
#| message: false
#| warning: false

knitr::opts_chunk$set(comment = NA) ## Dr. Love always includes this

library(arm)
library(boot)
library(car)
library(caret)
library(countreg) # install via R-Forge
library(DescTools)
library(distributions3)
library(Epi)
library(GGally)
library(ggridges)
library(glue)
library(gmodels)
library(gt)
library(gtsummary)
library(Hmisc)
library(janitor) 
library(knitr)
library(lmboot)
library(lmtest)
library(MASS)
library(mice)
library(MKinfer)
library(mosaic)
library(naniar)
library(nhanesA)
library(nnet)
library(patchwork)
library(pROC)
library(pscl)
library(rms)
library(ROCR)
library(rstatix)
library(sandwich)
library(simputation)
library(survival)
library(survminer)
library(tableone)
library(topmodels) # install via R-Forge
library(vcd)
library(VGAM)
library(visdat)

library(tidymodels)
library(tidyverse)

```

## General Theme for `ggplot` work {.unnumbered}

Dr. Love prefers `theme_bw()` to the default choice.

```{r}
#| eval: false
theme_set(theme_bw())
```

