<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 4&nbsp; 431 Review: Comparing Rates</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-431review3.html" rel="next">
<link href="./03-431review1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">R Setup</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-nh432cb.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-431review1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-431review2.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-431review3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-singleimputation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-datasummaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-anovasmart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-anovaexamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-nonlinearity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ancova_emphysema.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-ancova_smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./90-incomplete.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">NOTE: Work in progress.</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup" id="toc-r-setup" class="nav-link active" data-scroll-target="#r-setup"><span class="toc-section-number">4.1</span>  R Setup</a>
  <ul class="collapse">
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="toc-section-number">4.1.1</span>  Data Load</a></li>
  </ul></li>
  <li><a href="#x2-contingency-table-dr_lose-and-nowlose" id="toc-x2-contingency-table-dr_lose-and-nowlose" class="nav-link" data-scroll-target="#x2-contingency-table-dr_lose-and-nowlose"><span class="toc-section-number">4.2</span>  2x2 Contingency Table: DR_LOSE and NOWLOSE</a>
  <ul class="collapse">
  <li><a href="#standard-epidemiological-format" id="toc-standard-epidemiological-format" class="nav-link" data-scroll-target="#standard-epidemiological-format"><span class="toc-section-number">4.2.1</span>  Standard Epidemiological Format</a></li>
  <li><a href="#obtaining-key-summaries-with-twoby2" id="toc-obtaining-key-summaries-with-twoby2" class="nav-link" data-scroll-target="#obtaining-key-summaries-with-twoby2"><span class="toc-section-number">4.2.2</span>  Obtaining Key Summaries with <code>twoby2()</code></a></li>
  </ul></li>
  <li><a href="#x2-table-sedate-category-and-now_exer" id="toc-x2-table-sedate-category-and-now_exer" class="nav-link" data-scroll-target="#x2-table-sedate-category-and-now_exer"><span class="toc-section-number">4.3</span>  2x2 Table: SEDATE category and NOW_EXER</a>
  <ul class="collapse">
  <li><a href="#creating-a-low-and-high-group-on-sedate" id="toc-creating-a-low-and-high-group-on-sedate" class="nav-link" data-scroll-target="#creating-a-low-and-high-group-on-sedate"><span class="toc-section-number">4.3.1</span>  Creating a Low and High Group on SEDATE</a></li>
  <li><a href="#two-by-two-table-summaries" id="toc-two-by-two-table-summaries" class="nav-link" data-scroll-target="#two-by-two-table-summaries"><span class="toc-section-number">4.3.2</span>  Two-by-Two Table Summaries</a></li>
  <li><a href="#flipping-levels" id="toc-flipping-levels" class="nav-link" data-scroll-target="#flipping-levels"><span class="toc-section-number">4.3.3</span>  Flipping Levels</a></li>
  </ul></li>
  <li><a href="#a-larger-5x3-2-way-table-dietqual-and-wtgoal-in-lighter-men" id="toc-a-larger-5x3-2-way-table-dietqual-and-wtgoal-in-lighter-men" class="nav-link" data-scroll-target="#a-larger-5x3-2-way-table-dietqual-and-wtgoal-in-lighter-men"><span class="toc-section-number">4.4</span>  A Larger (5x3) 2-Way Table: DIETQUAL and WTGOAL in Lighter Men</a>
  <ul class="collapse">
  <li><a href="#what-would-independence-look-like" id="toc-what-would-independence-look-like" class="nav-link" data-scroll-target="#what-would-independence-look-like"><span class="toc-section-number">4.4.1</span>  What would independence look like?</a></li>
  <li><a href="#back-to-the-dietqual-and-wtgoal-table" id="toc-back-to-the-dietqual-and-wtgoal-table" class="nav-link" data-scroll-target="#back-to-the-dietqual-and-wtgoal-table"><span class="toc-section-number">4.4.2</span>  Back to the DIETQUAL and WTGOAL table</a></li>
  </ul></li>
  <li><a href="#phq9-category-and-raceethnicity" id="toc-phq9-category-and-raceethnicity" class="nav-link" data-scroll-target="#phq9-category-and-raceethnicity"><span class="toc-section-number">4.5</span>  PHQ9 Category and Race/Ethnicity</a>
  <ul class="collapse">
  <li><a href="#the-cochran-conditions" id="toc-the-cochran-conditions" class="nav-link" data-scroll-target="#the-cochran-conditions"><span class="toc-section-number">4.5.1</span>  The Cochran conditions</a></li>
  <li><a href="#collapsing-categories" id="toc-collapsing-categories" class="nav-link" data-scroll-target="#collapsing-categories"><span class="toc-section-number">4.5.2</span>  Collapsing Categories</a></li>
  <li><a href="#pearson-chi2-analysis" id="toc-pearson-chi2-analysis" class="nav-link" data-scroll-target="#pearson-chi2-analysis"><span class="toc-section-number">4.5.3</span>  Pearson <span class="math inline">\(\chi^2\)</span> Analysis</a></li>
  <li><a href="#mosaic-plot" id="toc-mosaic-plot" class="nav-link" data-scroll-target="#mosaic-plot"><span class="toc-section-number">4.5.4</span>  Mosaic Plot</a></li>
  <li><a href="#examining-the-fit" id="toc-examining-the-fit" class="nav-link" data-scroll-target="#examining-the-fit"><span class="toc-section-number">4.5.5</span>  Examining the Fit</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-431-rates" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this Chapter, we will review some key issues about comparing proportions or rates, mostly drawn from the 431 course. This and the other Chapters labeled “431 Review” show elements of the two studies involved in a “<a href="https://thomaselove.github.io/431-projectB-2022/">431 Project B</a>” using the pre-pandemic (2017 - March 2020) data from the National Health and Nutrition Examination Survey (NHANES) called <strong>nh432</strong> that we developed in <a href="01-nhanes.html"><span>Chapter&nbsp;1</span></a> and then summarized in <a href="02-nh432cb.html"><span>Chapter&nbsp;2</span></a>. Note that we’ll ignore the issue of sampling weights and assume a “missing completely at random” (MCAR) mechanism in these “431 Review” chapters, so that we can work with complete cases.</p>
<p>The 431 course notes are at <a href="https://thomaselove.github.io/431-notes/" class="uri">https://thomaselove.github.io/431-notes/</a> and will remain there until 2023-06-01.</p>
<section id="r-setup" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="r-setup"><span class="header-section-number">4.1</span> R Setup</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Epi)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-load" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="data-load"><span class="header-section-number">4.1.1</span> Data Load</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>nh432 <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/nh432.Rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="x2-contingency-table-dr_lose-and-nowlose" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="x2-contingency-table-dr_lose-and-nowlose"><span class="header-section-number">4.2</span> 2x2 Contingency Table: DR_LOSE and NOWLOSE</h2>
<p>Let’s compare the probability that NOWLOSE is 1 (The subject is currently working on losing or controlling their body weight) between NHANES participants who have (vs.&nbsp;who have not) been told by a doctor to lose or control their weight in the past 12 months (DR_LOSE). Each of these (DR_LOSE and NOWLOSE) is stored in R as a numeric variable with non-missing values equal to 0 or 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> nh432 <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, DR_LOSE, NOW_LOSE) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As with any categorical variable, we start by counting, and the natural way to display the counts of these two variables (DR_LOSE and NOW_LOSE) is in a table, rather than a graph, I think.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>temp <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(DR_LOSE, NOW_LOSE) <span class="sc">|&gt;</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="at">where =</span> <span class="fu">c</span>(<span class="st">"row"</span>, <span class="st">"col"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_title</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         NOW_LOSE           
 DR_LOSE        0    1 Total
       0     1198 1541  2739
       1      246  943  1189
   Total     1444 2484  3928</code></pre>
</div>
</div>
<p>Now that we have a 2x2 table, we could consider obtaining some more detailed summary statistics, with a tool like the <code>twoby2()</code> function in the <strong>Epi</strong> package. There is a problem with this, though.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twoby2</span>(temp<span class="sc">$</span>DR_LOSE, temp<span class="sc">$</span>NOW_LOSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : 0 
Comparing : 0 vs. 1 

     0    1    P(0) 95% conf. interval
0 1198 1541  0.4374    0.4189   0.4560
1  246  943  0.2069    0.1848   0.2309

                                   95% conf. interval
             Relative Risk: 2.1140    1.8766   2.3815
         Sample Odds Ratio: 2.9801    2.5412   3.4949
Conditional MLE Odds Ratio: 2.9793    2.5350   3.5096
    Probability difference: 0.2305    0.2002   0.2594

             Exact P-value: 0.0000 
        Asymptotic P-value: 0.0000 
------------------------------------------------------</code></pre>
</div>
</div>
<p>The code runs fine, but the table isn’t really in a useful format. This table shows the probability that NOWLOSE = 0 (“No”) comparing DR_LOSE = 0 (“No”) to DR_LOSE = 1 (“Yes”), and that’s just confusing.</p>
<p>It would be much better if we did two things:</p>
<ol type="1">
<li>used factors with meaningful labels to represent the 1/0 variables for this table</li>
<li>set up the table in standard epidemiological format, and then made a better choice as to what combination should be in the top left of the 2x2 table.</li>
</ol>
<p>So let’s do that.</p>
<section id="standard-epidemiological-format" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="standard-epidemiological-format"><span class="header-section-number">4.2.1</span> Standard Epidemiological Format</h3>
<p>Standard Epidemiological Format for a 2x2 table places the exposure in the rows, and the outcome in the columns, with the top left representing the combination of interest when we obtain things like an odds ratio or probability difference. Typically this means we want to put the “Yes” and “Yes” combination in the top left.</p>
<p>First, let’s create factor versions (with more meaningful labels than 1 and 0) out of the two variables of interest: DR_LOSE and NOW_LOSE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>dat1 <span class="ot">&lt;-</span> nh432 <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, DR_LOSE, NOW_LOSE) <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DR_LOSE_f =</span> <span class="fu">fct_recode</span>(<span class="fu">factor</span>(DR_LOSE), <span class="st">"Dr_said_Lose_Wt"</span> <span class="ot">=</span> <span class="st">"1"</span>, <span class="at">No =</span> <span class="st">"0"</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">DR_LOSE_f =</span> <span class="fu">fct_relevel</span>(DR_LOSE_f, <span class="st">"Dr_said_Lose_Wt"</span>, <span class="st">"No"</span>),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">NOW_LOSE_f =</span> <span class="fu">fct_recode</span>(<span class="fu">factor</span>(NOW_LOSE), <span class="st">"Now_losing_Wt"</span> <span class="ot">=</span> <span class="st">"1"</span>, <span class="at">No =</span> <span class="st">"0"</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">NOW_LOSE_f =</span> <span class="fu">fct_relevel</span>(NOW_LOSE_f, <span class="st">"Now_losing_Wt"</span>, <span class="st">"No"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that after recoding the levels to more meaningful labels, we also re-leveled the factors so that the “Yes” result comes first rather than last.</p>
<p>This produces the following table, which is now in standard epidemiological format, where we are using the DR_LOSE_f information to predict NOW_LOSE_f.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dat1 <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(DR_LOSE_f, NOW_LOSE_f) <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="at">where =</span> <span class="fu">c</span>(<span class="st">"row"</span>, <span class="st">"col"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_title</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    NOW_LOSE_f           
       DR_LOSE_f Now_losing_Wt   No Total
 Dr_said_Lose_Wt           943  246  1189
              No          1541 1198  2739
           Total          2484 1444  3928</code></pre>
</div>
</div>
<p>We could, I suppose, make the table even prettier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>tab1 <span class="ot">&lt;-</span> dat1 <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(DR_LOSE_f, NOW_LOSE_f) <span class="sc">|&gt;</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="at">where =</span> <span class="fu">c</span>(<span class="st">"row"</span>, <span class="st">"col"</span>)) </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gt</span>(tab1, <span class="at">rowname_col =</span> <span class="st">"DR_LOSE_f"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_header</span>(<span class="at">title =</span> <span class="st">"DR_LOSE vs. NOW_LOSE"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">subtitle =</span> <span class="st">"Standard Epidemiological Format"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_stubhead</span>(<span class="at">label =</span> <span class="st">"Dr said Lose Weight?"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_spanner</span>(<span class="at">label =</span> <span class="st">"Currently Losing Weight?"</span>, </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">columns =</span> <span class="fu">c</span>(Now_losing_Wt, No))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="gssityhnbi" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#gssityhnbi) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#gssityhnbi) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#gssityhnbi) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#gssityhnbi) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#gssityhnbi) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#gssityhnbi) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#gssityhnbi) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#gssityhnbi) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#gssityhnbi) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#gssityhnbi) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#gssityhnbi) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#gssityhnbi) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#gssityhnbi) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#gssityhnbi) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#gssityhnbi) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#gssityhnbi) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#gssityhnbi) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#gssityhnbi) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#gssityhnbi) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#gssityhnbi) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#gssityhnbi) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#gssityhnbi) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#gssityhnbi) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#gssityhnbi) .gt_left {
  text-align: left;
}

:where(#gssityhnbi) .gt_center {
  text-align: center;
}

:where(#gssityhnbi) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#gssityhnbi) .gt_font_normal {
  font-weight: normal;
}

:where(#gssityhnbi) .gt_font_bold {
  font-weight: bold;
}

:where(#gssityhnbi) .gt_font_italic {
  font-style: italic;
}

:where(#gssityhnbi) .gt_super {
  font-size: 65%;
}

:where(#gssityhnbi) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#gssityhnbi) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#gssityhnbi) .gt_indent_1 {
  text-indent: 5px;
}

:where(#gssityhnbi) .gt_indent_2 {
  text-indent: 10px;
}

:where(#gssityhnbi) .gt_indent_3 {
  text-indent: 15px;
}

:where(#gssityhnbi) .gt_indent_4 {
  text-indent: 20px;
}

:where(#gssityhnbi) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="4" class="gt_heading gt_title gt_font_normal" style="">DR_LOSE vs. NOW_LOSE</td>
    </tr>
    <tr>
      <td colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="">Standard Epidemiological Format</td>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="Dr said Lose Weight?">Dr said Lose Weight?</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup" id="Currently Losing Weight?">
        <span class="gt_column_spanner">Currently Losing Weight?</span>
      </th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col" id="Total">Total</th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Now_losing_Wt">Now_losing_Wt</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="No">No</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_left gt_stub">Dr_said_Lose_Wt</th>
<td headers="stub_1_1 Now_losing_Wt" class="gt_row gt_right">943</td>
<td headers="stub_1_1 No" class="gt_row gt_right">246</td>
<td headers="stub_1_1 Total" class="gt_row gt_right">1189</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_left gt_stub">No</th>
<td headers="stub_1_2 Now_losing_Wt" class="gt_row gt_right">1541</td>
<td headers="stub_1_2 No" class="gt_row gt_right">1198</td>
<td headers="stub_1_2 Total" class="gt_row gt_right">2739</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_left gt_stub">Total</th>
<td headers="stub_1_3 Now_losing_Wt" class="gt_row gt_right">2484</td>
<td headers="stub_1_3 No" class="gt_row gt_right">1444</td>
<td headers="stub_1_3 Total" class="gt_row gt_right">3928</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</section>
<section id="obtaining-key-summaries-with-twoby2" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="obtaining-key-summaries-with-twoby2"><span class="header-section-number">4.2.2</span> Obtaining Key Summaries with <code>twoby2()</code></h3>
<p>And, finally, we can obtain necessary summaries (including estimates and confidence intervals) using the <code>twoby2()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twoby2</span>(dat1<span class="sc">$</span>DR_LOSE_f, dat1<span class="sc">$</span>NOW_LOSE_f, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Now_losing_Wt 
Comparing : Dr_said_Lose_Wt vs. No 

                Now_losing_Wt   No    P(Now_losing_Wt) 90% conf. interval
Dr_said_Lose_Wt           943  246              0.7931    0.7731   0.8118
No                       1541 1198              0.5626    0.5470   0.5781

                                   90% conf. interval
             Relative Risk: 1.4097    1.3586   1.4627
         Sample Odds Ratio: 2.9801    2.6071   3.4065
Conditional MLE Odds Ratio: 2.9793    2.5998   3.4195
    Probability difference: 0.2305    0.2052   0.2548

             Exact P-value: 0.0000 
        Asymptotic P-value: 0.0000 
------------------------------------------------------</code></pre>
</div>
</div>
<p>Some brief descriptions of these results:</p>
<ul>
<li>The probability that a participant is now losing weight (NOW_LOSE is 1) is estimated to be 0.79 (with 90% CI 0.77, 0.81) if the participant has been told to lose weight by a doctor in the past 12 months (DR_LOSE = 1), but only 0.56 (with 90% CI 0.55, 0.58) if the participant has not been told this.</li>
<li>The relative risk of a participant now losing weight is estimated to be <span class="math inline">\(\frac{0.7931}{0.5626}\)</span> = 1.41 (with 90% CI 1.36, 1.46) for a participant who has been told to lose weight vs.&nbsp;a participant who has not.</li>
<li>The odds of a participant now losing weight are <span class="math inline">\(\frac{0.7931(1-0.5626)}{0.5626(1-0.7931)}\)</span> = 2.98 times as high for a participant who has been told to lose weight than for one who has not, with 90% CI (2.61, 3.41).</li>
<li>The difference in probability is estimated to be 0.7931 - 0.5626 = 0.2305 (90% CI: 0.21, 0.25), indicating again that the true probability of now losing weight is higher in participants who have been told to lose weight than in those who have not.</li>
</ul>
<p>The “exact” p-value listed comes from the Fisher exact test, while the “asymptotic” p-value comes from a Pearson <span class="math inline">\(\chi^2\)</span> (chi-squared) test. I would focus on the meaningful estimates (those with confidence intervals) in making comparisons, rather than on trying to determine “statistical significance” with the p-values.</p>
</section>
</section>
<section id="x2-table-sedate-category-and-now_exer" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="x2-table-sedate-category-and-now_exer"><span class="header-section-number">4.3</span> 2x2 Table: SEDATE category and NOW_EXER</h2>
<p>Let’s now look at another example, where we compare the probability that a participant is “now exercising” (NOW_EXER = 1) on the basis of their level of sedentary activity in a typical day (collected in the SEDATE variable, in minutes.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> nh432 <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, SEDATE, NOW_EXER) <span class="sc">|&gt;</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat2 <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="sc">-</span>SEQN))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     SEDATE          NOW_EXER     
 Min.   :   2.0   Min.   :0.0000  
 1st Qu.: 180.0   1st Qu.:0.0000  
 Median : 300.0   Median :1.0000  
 Mean   : 332.8   Mean   :0.6019  
 3rd Qu.: 480.0   3rd Qu.:1.0000  
 Max.   :1320.0   Max.   :1.0000  </code></pre>
</div>
</div>
<p>As you can see above, the information in SEDATE is quantitative, and suppose we want to compare a High SEDATE group vs.&nbsp;a Low SEDATE group.</p>
<section id="creating-a-low-and-high-group-on-sedate" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="creating-a-low-and-high-group-on-sedate"><span class="header-section-number">4.3.1</span> Creating a Low and High Group on SEDATE</h3>
<p>We can use the <code>cut2()</code> function from the <strong>Hmisc</strong> package to partition the data by the SEDATE variable into three groups of equal sample size. At the same time, we’ll make NOW_EXER into a more useful (for tabulation) factor with more meaningful level descriptions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> dat2 <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SED_f =</span> <span class="fu">cut2</span>(SEDATE, <span class="at">g =</span> <span class="dv">3</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">NOW_EXER_f =</span> <span class="fu">fct_recode</span>(<span class="fu">factor</span>(NOW_EXER), <span class="st">"Now_exercising"</span> <span class="ot">=</span> <span class="st">"1"</span>, <span class="at">No =</span> <span class="st">"0"</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">NOW_EXER_f =</span> <span class="fu">fct_relevel</span>(NOW_EXER_f, <span class="st">"Now_exercising"</span>, <span class="st">"No"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see, we now have three groups defined by their SEDATE values, of roughly equal sample sizes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(SED_f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      SED_f    n   percent
 [  2, 200) 1323 0.3387097
 [200, 420) 1301 0.3330773
 [420,1320] 1282 0.3282130</code></pre>
</div>
</div>
<p>The group labeled [2, 200) contains the 1323 subjects who had SEDATE values ranging from 2 up to (but not including) 200 minutes, for example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat2, <span class="fu">aes</span>(<span class="at">x =</span> SEDATE)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill =</span> SED_f), <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">bins =</span> <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"seagreen"</span>, <span class="st">"white"</span>, <span class="st">"seagreen"</span>)) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Comparing Low SEDATE to High SEDATE"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Identification of Groups"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-431review2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now, we want to compare the Lowest SEDATE group (SED_F = [2, 200)) to the Highest SEDATE group (SED_F = [420, 1320]). To do that, we’ll drop the middle group, and then look at the cross-tabulation of our two remaining SEDATE groups with our outcome: NOW_EXER (in factor form.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> dat2 <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SED_f <span class="sc">!=</span> <span class="st">"[200, 420)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SED_f =</span> <span class="fu">fct_drop</span>(SED_f))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>dat2 <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(SED_f, NOW_EXER_f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      SED_f Now_exercising  No
 [  2, 200)            776 547
 [420,1320]            789 493</code></pre>
</div>
</div>
</section>
<section id="two-by-two-table-summaries" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="two-by-two-table-summaries"><span class="header-section-number">4.3.2</span> Two-by-Two Table Summaries</h3>
<p>Let’s look at the analytic results for this table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twoby2</span>(dat2<span class="sc">$</span>SED_f, dat2<span class="sc">$</span>NOW_EXER_f) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Now_exercising 
Comparing : [  2, 200) vs. [420,1320] 

           Now_exercising  No    P(Now_exercising) 95% conf. interval
[  2, 200)            776 547               0.5865    0.5598   0.6128
[420,1320]            789 493               0.6154    0.5885   0.6417

                                    95% conf. interval
             Relative Risk:  0.9530    0.8952   1.0146
         Sample Odds Ratio:  0.8864    0.7577   1.0371
Conditional MLE Odds Ratio:  0.8865    0.7553   1.0403
    Probability difference: -0.0289   -0.0664   0.0087

             Exact P-value: 0.1388 
        Asymptotic P-value: 0.1322 
------------------------------------------------------</code></pre>
</div>
</div>
<p>Uh, oh. There’s a bit of a problem here now. We have the right rows and the right columns, but they’re not in the best possible order, since the estimated probability of Now Exercising for the group on top (SED = [2, 200)) is smaller than it is for the people in the high group in terms of sedentary activity As a result of this problem with ordering, our relative risk and odds ratio estimates are less than 1, and our probability difference is negative.</p>
</section>
<section id="flipping-levels" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="flipping-levels"><span class="header-section-number">4.3.3</span> Flipping Levels</h3>
<p>Since which exposure goes at the top is an arbitrary decision, let’s switch the factor levels in SED_f, so that the people with high sedentary activity and who are now exercising are shown in the top left cell of the table. This should flip the point estimates of the relative risk and odds ratio above 1, and the estimated probability difference to a positive number. Note the use of the <code>fct_rev()</code> function from the <strong>forcats</strong> package to accomplish this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> dat2 <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SED_f =</span> <span class="fu">fct_rev</span>(SED_f))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>dat2 <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(SED_f, NOW_EXER_f) <span class="sc">|&gt;</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="at">where =</span> <span class="fu">c</span>(<span class="st">"row"</span>, <span class="st">"col"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_title</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NOW_EXER_f           
      SED_f Now_exercising   No Total
 [420,1320]            789  493  1282
 [  2, 200)            776  547  1323
      Total           1565 1040  2605</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twoby2</span>(dat2<span class="sc">$</span>SED_f, dat2<span class="sc">$</span>NOW_EXER_f, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Now_exercising 
Comparing : [420,1320] vs. [  2, 200) 

           Now_exercising  No    P(Now_exercising) 90% conf. interval
[420,1320]            789 493               0.6154    0.5929   0.6375
[  2, 200)            776 547               0.5865    0.5641   0.6086

                                   90% conf. interval
             Relative Risk: 1.0493    0.9956   1.1059
         Sample Odds Ratio: 1.1281    0.9889   1.2869
Conditional MLE Odds Ratio: 1.1281    0.9858   1.2910
    Probability difference: 0.0289   -0.0027   0.0604

             Exact P-value: 0.1388 
        Asymptotic P-value: 0.1322 
------------------------------------------------------</code></pre>
</div>
</div>
<p>We conclude now that the participants who were in the high SEDATION group (as compared to those in the low SEDATION group) had:</p>
<ul>
<li>a relative risk of 1.05 (90% CI: 0.995, 1.106) for Now exercising,</li>
<li>a sample odds ratio of 1.13 (90% CI: 0.989, 1.287) for Now exercising,</li>
<li>and probability for Now exercising that was 0.029 higher (-0.003, 0.060) than for those in the low SEDATION group.</li>
</ul>
</section>
</section>
<section id="a-larger-5x3-2-way-table-dietqual-and-wtgoal-in-lighter-men" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="a-larger-5x3-2-way-table-dietqual-and-wtgoal-in-lighter-men"><span class="header-section-number">4.4</span> A Larger (5x3) 2-Way Table: DIETQUAL and WTGOAL in Lighter Men</h2>
<p>Here, we’ll look at Male participants who weighed less than 100 kg (approximately 220 pounds) and ask whether their DIETQUAL (diet quality: self-rated as Excellent to poor in 5 categories) response is associated with their response to WTGOAL (would you like to weigh more, about the same, or less than you do now: 3 categories.)</p>
<p>The resulting two-way contingency table includes 5 rows and 3 columns. We are interested in evaluating the relationship between the rows and the columns. It’s called a two-way table because there are two categorical variables (DIETQUAL and WTGOAL) under study.</p>
<p>If the rows and columns were found to be <em>independent</em> of one another, this would mean that the probabilities of falling in each column do not change, regardless of what row of the table we look at.</p>
<p>If the rows and columns are <em>associated</em>, then the probabilities of falling in each column do depend on which row we’re looking at.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>dat3 <span class="ot">&lt;-</span> nh432 <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, DIETQUAL, WTGOAL, WEIGHT, SEX) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(WEIGHT <span class="sc">&lt;</span> <span class="dv">100</span> <span class="sc">&amp;</span> SEX <span class="sc">==</span> <span class="st">"Male"</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>dat3 <span class="sc">|&gt;</span> </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(DIETQUAL, WTGOAL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  DIETQUAL More Same Less
 Excellent   16   53   32
 Very Good   37  153  117
      Good   68  179  238
      Fair   44  111  144
      Poor   15   18   43</code></pre>
</div>
</div>
<p>If we want a graphical representation of a two-way table, the most common choice is probably a <strong>mosaic plot</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>vcd<span class="sc">::</span><span class="fu">mosaic</span>(<span class="sc">~</span> DIETQUAL <span class="sc">+</span> WTGOAL, <span class="at">data =</span> dat3,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">highlighting =</span> <span class="st">"WTGOAL"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-431review2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Larger observed frequencies in the contingency table show up with larger tile areas in the in the mosaic plot. So, for instance, we see the larger proportion of “less” WTGOAL in the “Poor” DIETQUAL category, as compared to most of the other DIETQUAL categories.</p>
<section id="what-would-independence-look-like" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="what-would-independence-look-like"><span class="header-section-number">4.4.1</span> What would independence look like?</h3>
<p>A mosaic plot displaying perfect independence (using simulated data) might look something like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>var1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"A"</span>, <span class="dv">48</span>), <span class="fu">rep</span>(<span class="st">"B"</span>, <span class="dv">54</span>), <span class="fu">rep</span>(<span class="st">"C"</span>, <span class="dv">60</span>), <span class="fu">rep</span>(<span class="st">"D"</span>, <span class="dv">24</span>) )</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>var2 <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"G1"</span>, <span class="st">"G1"</span>, <span class="st">"G2"</span>, <span class="st">"G2"</span>, <span class="st">"G2"</span>, <span class="st">"G3"</span>), <span class="dv">31</span>) )</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>temp_tab <span class="ot">&lt;-</span> <span class="fu">tibble</span>(var1, var2); <span class="fu">rm</span>(var1, var2)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>vcd<span class="sc">::</span><span class="fu">mosaic</span>(<span class="sc">~</span> var1 <span class="sc">+</span> var2, <span class="at">data =</span> temp_tab, <span class="at">highlighting =</span> <span class="st">"var1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-431review2_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here’s the table for our simulated data, where independence holds perfectly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> var1 <span class="sc">+</span> var2, <span class="at">data =</span> temp_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    var2
var1 G1 G2 G3
   A 16 24  8
   B 18 27  9
   C 20 30 10
   D  8 12  4</code></pre>
</div>
</div>
<p>Note that in these simulated data, we have the same fraction of people in each of the four var1 categories (A, B, C, and D) regardless of which of the three var2 categories (G1, G2 and G3) we are in, and vice versa. That’s what it means for rows and columns to be independent.</p>
</section>
<section id="back-to-the-dietqual-and-wtgoal-table" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="back-to-the-dietqual-and-wtgoal-table"><span class="header-section-number">4.4.2</span> Back to the DIETQUAL and WTGOAL table</h3>
<p>Now, returning to our problem, to obtain detailed results from the Pearson <span class="math inline">\(\chi^2\)</span> test, I use the <code>xtabs()</code> function and then the <code>chisq.test()</code> function, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>chi3 <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="fu">xtabs</span>(<span class="sc">~</span> DIETQUAL <span class="sc">+</span> WTGOAL, <span class="at">data =</span> dat3))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>chi3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  xtabs(~DIETQUAL + WTGOAL, data = dat3)
X-squared = 32.603, df = 8, p-value = 7.261e-05</code></pre>
</div>
</div>
<p>The null hypothesis being tested here is that DIETQUAL and WTGOAL are independent of each other. A small <em>p</em> value like this is indicative of an association between the two variables.</p>
<p>The <code>chi3</code> object we have created also contains:</p>
<ul>
<li>the observed frequencies in each cell, as well as</li>
<li>the expected frequencies under the hypothesis of independence of the rows and the columns<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, and</li>
<li>the Pearson residuals <span class="math inline">\((\mbox{observed - expected})/\sqrt{\mbox{expected}}\)</span> for each cell, among other things.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>chi3<span class="sc">$</span>observed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           WTGOAL
DIETQUAL    More Same Less
  Excellent   16   53   32
  Very Good   37  153  117
  Good        68  179  238
  Fair        44  111  144
  Poor        15   18   43</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>chi3<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           WTGOAL
DIETQUAL        More      Same      Less
  Excellent 14.33754  40.94164  45.72082
  Very Good 43.58044 124.44637 138.97319
  Good      68.84858 196.60095 219.55047
  Fair      42.44479 121.20347 135.35174
  Poor      10.78864  30.80757  34.40379</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>chi3<span class="sc">$</span>residuals <span class="co"># Pearson residuals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           WTGOAL
DIETQUAL          More       Same       Less
  Excellent  0.4390501  1.8845411 -2.0291917
  Very Good -0.9968028  2.5595886 -1.8639211
  Good      -0.1022694 -1.2552875  1.2451396
  Fair       0.2387127 -0.9268093  0.7433564
  Poor       1.2821492 -2.3074805  1.4655618</code></pre>
</div>
</div>
<p>An <strong>association plot</strong> presents a graphical description of the Pearson residuals, with the area of each box shown proportional to the difference between the observed and expected frequencies.</p>
<ul>
<li>If the observed frequency of a cell is greater than the expectation under the hypothesis of independence, then the box rises above the baseline.
<ul>
<li>An example here is the (DIETQUAL = Very Good, WTGOAL = Same) which had an observed frequency of 153 but an expected frequency of 124.4, yielding the largest positive Pearson residual at 2.56.</li>
</ul></li>
<li>Boxes shown below the baseline indicate that the observed frequency was less than the expectation under the independence hypothesis.
<ul>
<li>The largest negative Pearson residual is the (DIETQUAL = Poor, WTGOAL = Same) cell, where we observed 18 observations but the independence model would predict 30.8, yielding a Pearson residual of -2.31.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>vcd<span class="sc">::</span><span class="fu">assoc</span>(<span class="sc">~</span> DIETQUAL <span class="sc">+</span> WTGOAL, <span class="at">data =</span> dat3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-431review2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Some people also like to calculate a correlation between categorical variables. If each of your categorical variables is ordinal (as in this case) then Kendall’s tau (version b) is probably the best choice. As with a Pearson correlation for quantities, the value for this measure ranges from -1 to 1, with -1 indicating a strong negative correlation, and +1 a strong positive correlation, with 0 indicating no correlation.</p>
<p>To use this approach, though, we first have to be willing to treat our multi-categorical variables as if they were numeric, which may or may not be reasonable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>dat3 <span class="ot">&lt;-</span> dat3 <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DIETQUAL_num =</span> <span class="fu">as.numeric</span>(DIETQUAL))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>dat3 <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(DIETQUAL_num, DIETQUAL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> DIETQUAL_num Excellent Very Good Good Fair Poor
            1       101         0    0    0    0
            2         0       307    0    0    0
            3         0         0  485    0    0
            4         0         0    0  299    0
            5         0         0    0    0   76</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>dat3 <span class="ot">&lt;-</span> dat3 <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">WTGOAL_num =</span> <span class="fu">as.numeric</span>(WTGOAL))</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>dat3 <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(WTGOAL_num, WTGOAL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> WTGOAL_num More Same Less
          1  180    0    0
          2    0  514    0
          3    0    0  574</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dat3<span class="sc">$</span>DIETQUAL_num, dat3<span class="sc">$</span>WTGOAL_num, <span class="at">method =</span> <span class="st">"kendall"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07193663</code></pre>
</div>
</div>
<p>If you want to obtain a confidence interval for this correlation coefficient, then you would need to use the <code>KendallTauB()</code> function from the <strong>DescTools</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">KendallTauB</span>(dat3<span class="sc">$</span>DIETQUAL_num, dat3<span class="sc">$</span>WTGOAL_num, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     tau_b     lwr.ci     upr.ci 
0.07193663 0.03147130 0.11240196 </code></pre>
</div>
</div>
<p>Again, it’s just a number, and not especially valuable.</p>
</section>
</section>
<section id="phq9-category-and-raceethnicity" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="phq9-category-and-raceethnicity"><span class="header-section-number">4.5</span> PHQ9 Category and Race/Ethnicity</h2>
<p>Let’s look next at the association of race-ethnicity (RACEETH, which has 5 levels) and the depression category (minimal, mild, moderate, moderately severe, or severe) available in PHQ9_CAT, which we derived from the PHQ-9 depression screener score. We’ll restrict this small analysis to NHANES participants who did not receive care from a mental health provider (so MENTALH is 0) in the last 12 months.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> nh432 <span class="sc">|&gt;</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, RACEETH, PHQ9_CAT, MENTALH) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(MENTALH <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So here’s our first attempt at a 5x5 table describing this association.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>temp <span class="sc">|&gt;</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(RACEETH, PHQ9_CAT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     RACEETH minimal mild moderate moderately severe severe
 Non-H White     770  151       41                20      8
 Non-H Black     668  143       34                13      1
    Hispanic     581  133       36                12      5
 Non-H Asian     428   49       11                 1      1
  Other Race     105   34       12                 5      1</code></pre>
</div>
</div>
<p>We note some very small observed frequencies, especially in the bottom right of the table. Should we try to run a Pearson <span class="math inline">\(\chi^2\)</span> test on these results, we will generate a warning that the Chi-square approximation may be incorrect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>( <span class="sc">~</span> RACEETH <span class="sc">+</span> PHQ9_CAT, <span class="at">data =</span> temp ) <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">chisq.test</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in stats::chisq.test(x, y, ...): Chi-squared approximation may be
incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  xtabs(~RACEETH + PHQ9_CAT, data = temp)
X-squared = 49.288, df = 16, p-value = 2.974e-05</code></pre>
</div>
</div>
<section id="the-cochran-conditions" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="the-cochran-conditions"><span class="header-section-number">4.5.1</span> The Cochran conditions</h3>
<p>R sets off this warning when the “Cochran conditions” are not met. The Cochran conditions require that we have:</p>
<ul>
<li>no cells with 0 counts</li>
<li>at least 80% of the cells in our table with counts of 5 or higher</li>
<li>expected counts in each cell of the table should be 5 or more</li>
</ul>
<p>In our table, we have four cells with observed counts below 5 (all have count 1) and two more with observed counts of exactly 5. If we look at the expected frequencies under the hypothesis of independence, what do we see?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>temp_chi <span class="ot">&lt;-</span> <span class="fu">xtabs</span>( <span class="sc">~</span> RACEETH <span class="sc">+</span> PHQ9_CAT, <span class="at">data =</span> temp ) <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">chisq.test</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in stats::chisq.test(x, y, ...): Chi-squared approximation may be
incorrect</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>temp_chi<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             PHQ9_CAT
RACEETH        minimal      mild  moderate moderately severe    severe
  Non-H White 774.2813 154.73491 40.655838         15.473491 4.8544284
  Non-H Black 671.8259 134.25988 35.276126         13.425988 4.2120748
  Hispanic    599.8725 119.88048 31.498008         11.988048 3.7609562
  Non-H Asian 383.2302  76.58596 20.122587          7.658596 2.4026969
  Other Race  122.7901  24.53877  6.447441          2.453877 0.7698437</code></pre>
</div>
</div>
<p>Every cell in the “severe” category has an expected frequency below 5, and we also have some generally small counts, in the Non-Hispanic Asian and Other Race categories, as well as the “moderately severe” category.</p>
</section>
<section id="collapsing-categories" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="collapsing-categories"><span class="header-section-number">4.5.2</span> Collapsing Categories</h3>
<p>So what might we do about this?</p>
<p>Let us consider two approaches that we’ll use simultaneously:</p>
<ol type="1">
<li>drop two of the RACEETH groups, and just use the top 3 (Non-H White, Non-H Black and Hispanic) using <code>filter()</code></li>
<li>collapse together the two right-most levels of PHQ9_CAT (moderately severe and severe) into a new level which I’ll call “More Severe”, using <code>fct_lump_n()</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>dat5 <span class="ot">&lt;-</span> nh432 <span class="sc">|&gt;</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, RACEETH, PHQ9_CAT, MENTALH) <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(MENTALH <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(RACEETH <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Non-H White"</span>, <span class="st">"Non-H Black"</span>, <span class="st">"Hispanic"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">RACEETH =</span> <span class="fu">fct_drop</span>(RACEETH),</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">PHQ9_CAT =</span> <span class="fu">fct_lump_n</span>(PHQ9_CAT, <span class="dv">3</span>, </span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>                               <span class="at">other_level =</span> <span class="st">"More Severe"</span>))</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>dat5 <span class="sc">|&gt;</span> </span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(RACEETH, PHQ9_CAT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     RACEETH minimal mild moderate More Severe
 Non-H White     770  151       41          28
 Non-H Black     668  143       34          14
    Hispanic     581  133       36          17</code></pre>
</div>
</div>
<p>Now, we have at least 14 participants in every cell of the table.</p>
</section>
<section id="pearson-chi2-analysis" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="pearson-chi2-analysis"><span class="header-section-number">4.5.3</span> Pearson <span class="math inline">\(\chi^2\)</span> Analysis</h3>
<p>Now, let’s consider what the Pearson <span class="math inline">\(\chi^2\)</span> test suggests.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>tab5 <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span> RACEETH <span class="sc">+</span> PHQ9_CAT, <span class="at">data =</span> dat5)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>tab5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             PHQ9_CAT
RACEETH       minimal mild moderate More Severe
  Non-H White     770  151       41          28
  Non-H Black     668  143       34          14
  Hispanic        581  133       36          17</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab5
X-squared = 5.0157, df = 6, p-value = 0.5418</code></pre>
</div>
</div>
<p>Now we have no warning, and notice also how large a change this has meant in terms of the p-value, as compared to our original <span class="math inline">\(\chi^2\)</span> result.</p>
</section>
<section id="mosaic-plot" class="level3" data-number="4.5.4">
<h3 data-number="4.5.4" class="anchored" data-anchor-id="mosaic-plot"><span class="header-section-number">4.5.4</span> Mosaic Plot</h3>
<p>Here’s a mosaic plot<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> of the table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>vcd<span class="sc">::</span><span class="fu">mosaic</span>(tab5, <span class="at">highlighting =</span> <span class="st">"PHQ9_CAT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-431review2_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="examining-the-fit" class="level3" data-number="4.5.5">
<h3 data-number="4.5.5" class="anchored" data-anchor-id="examining-the-fit"><span class="header-section-number">4.5.5</span> Examining the Fit</h3>
<p>We’ll finish up with a look at the expected frequencies, and a table and association plot of the Pearson residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab5)<span class="sc">$</span>observed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             PHQ9_CAT
RACEETH       minimal mild moderate More Severe
  Non-H White     770  151       41          28
  Non-H Black     668  143       34          14
  Hispanic        581  133       36          17</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab5)<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             PHQ9_CAT
RACEETH        minimal     mild moderate More Severe
  Non-H White 764.0711 161.5940 42.00688    22.32798
  Non-H Black 662.9667 140.2114 36.44839    19.37347
  Hispanic    591.9622 125.1946 32.54472    17.29855</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab5)<span class="sc">$</span>residuals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             PHQ9_CAT
RACEETH           minimal        mild    moderate More Severe
  Non-H White  0.21449006 -0.83339100 -0.15535235  1.20036381
  Non-H Black  0.19548040  0.23550271 -0.40554793 -1.22081874
  Hispanic    -0.45055624  0.69759600  0.60567876 -0.07178083</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">assoc</span>(tab5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-431review2_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The expected frequency for a call under independence is the total for the cell’s row multiplied by the total for the cell’s column, divided by the grand total for the whole table.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The <strong>ggmosaic</strong> package has a <code>geom_mosaic()</code> tool for building such plots but its maintenance has been spotty in recent weeks.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-431review1.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-431review3.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>