<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 5&nbsp; 431 Review: Fitting Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./smart.html" rel="next">
<link href="./431review2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./431review3.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
        <div class="sidebar-tools-main">
    <a href="./Data-Science-for-Biological,-Medical-and-Health-Research.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./incomplete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">This is work in progress</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinaloutcome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Time To Event / Survival Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lasso.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">NEW!! A Few LASSO Ideas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">NEW!! Bayes and a Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup" id="toc-r-setup" class="nav-link active" data-scroll-target="#r-setup"><span class="header-section-number">5.1</span> R Setup</a>
  <ul class="collapse">
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="header-section-number">5.1.1</span> Data Load</a></li>
  </ul></li>
  <li><a href="#modeling-weekend-sleep-hours" id="toc-modeling-weekend-sleep-hours" class="nav-link" data-scroll-target="#modeling-weekend-sleep-hours"><span class="header-section-number">5.2</span> Modeling Weekend Sleep Hours</a>
  <ul class="collapse">
  <li><a href="#should-we-transform-our-outcome" id="toc-should-we-transform-our-outcome" class="nav-link" data-scroll-target="#should-we-transform-our-outcome"><span class="header-section-number">5.2.1</span> Should we transform our outcome?</a></li>
  <li><a href="#scatterplot-matrix" id="toc-scatterplot-matrix" class="nav-link" data-scroll-target="#scatterplot-matrix"><span class="header-section-number">5.2.2</span> Scatterplot Matrix</a></li>
  <li><a href="#collinearity" id="toc-collinearity" class="nav-link" data-scroll-target="#collinearity"><span class="header-section-number">5.2.3</span> Collinearity?</a></li>
  <li><a href="#fitting-and-displaying-model-m1" id="toc-fitting-and-displaying-model-m1" class="nav-link" data-scroll-target="#fitting-and-displaying-model-m1"><span class="header-section-number">5.2.4</span> Fitting and Displaying Model <code>m1</code></a></li>
  <li><a href="#using-broom-functions-on-model-m1" id="toc-using-broom-functions-on-model-m1" class="nav-link" data-scroll-target="#using-broom-functions-on-model-m1"><span class="header-section-number">5.2.5</span> Using <strong>broom</strong> functions on Model <code>m1</code></a></li>
  <li><a href="#residual-plots-for-model-m1" id="toc-residual-plots-for-model-m1" class="nav-link" data-scroll-target="#residual-plots-for-model-m1"><span class="header-section-number">5.2.6</span> Residual Plots for Model <code>m1</code></a></li>
  <li><a href="#fitting-and-displaying-model-m2" id="toc-fitting-and-displaying-model-m2" class="nav-link" data-scroll-target="#fitting-and-displaying-model-m2"><span class="header-section-number">5.2.7</span> Fitting and Displaying Model <code>m2</code></a></li>
  <li><a href="#using-broom-functions-on-m2" id="toc-using-broom-functions-on-m2" class="nav-link" data-scroll-target="#using-broom-functions-on-m2"><span class="header-section-number">5.2.8</span> Using <code>broom</code> functions on <code>m2</code></a></li>
  <li><a href="#residual-plots-for-model-m2" id="toc-residual-plots-for-model-m2" class="nav-link" data-scroll-target="#residual-plots-for-model-m2"><span class="header-section-number">5.2.9</span> Residual Plots for Model <code>m2</code></a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">5.2.10</span> Conclusions</a></li>
  </ul></li>
  <li><a href="#modeling-high-sensitivity-c-reactive-protein" id="toc-modeling-high-sensitivity-c-reactive-protein" class="nav-link" data-scroll-target="#modeling-high-sensitivity-c-reactive-protein"><span class="header-section-number">5.3</span> Modeling High-Sensitivity C-Reactive Protein</a>
  <ul class="collapse">
  <li><a href="#partitioning-the-data" id="toc-partitioning-the-data" class="nav-link" data-scroll-target="#partitioning-the-data"><span class="header-section-number">5.3.1</span> Partitioning the Data</a></li>
  <li><a href="#transforming-the-outcome" id="toc-transforming-the-outcome" class="nav-link" data-scroll-target="#transforming-the-outcome"><span class="header-section-number">5.3.2</span> Transforming the Outcome?</a></li>
  <li><a href="#scatterplot-matrix-and-collinearity" id="toc-scatterplot-matrix-and-collinearity" class="nav-link" data-scroll-target="#scatterplot-matrix-and-collinearity"><span class="header-section-number">5.3.3</span> Scatterplot Matrix and Collinearity</a></li>
  <li><a href="#fit-model-m3" id="toc-fit-model-m3" class="nav-link" data-scroll-target="#fit-model-m3"><span class="header-section-number">5.3.4</span> Fit Model <code>m3</code></a></li>
  <li><a href="#residual-plots-for-m3" id="toc-residual-plots-for-m3" class="nav-link" data-scroll-target="#residual-plots-for-m3"><span class="header-section-number">5.3.5</span> Residual Plots for <code>m3</code></a></li>
  <li><a href="#fit-model-m4" id="toc-fit-model-m4" class="nav-link" data-scroll-target="#fit-model-m4"><span class="header-section-number">5.3.6</span> Fit Model <code>m4</code></a></li>
  <li><a href="#residual-plots-for-m4" id="toc-residual-plots-for-m4" class="nav-link" data-scroll-target="#residual-plots-for-m4"><span class="header-section-number">5.3.7</span> Residual Plots for <code>m4</code></a></li>
  <li><a href="#in-sample-fit-quality-comparison-m3-vs.-m4" id="toc-in-sample-fit-quality-comparison-m3-vs.-m4" class="nav-link" data-scroll-target="#in-sample-fit-quality-comparison-m3-vs.-m4"><span class="header-section-number">5.3.8</span> In-Sample Fit Quality Comparison (<code>m3</code> vs.&nbsp;<code>m4</code>)</a></li>
  <li><a href="#testing-the-models-in-new-data" id="toc-testing-the-models-in-new-data" class="nav-link" data-scroll-target="#testing-the-models-in-new-data"><span class="header-section-number">5.3.9</span> Testing the models in new data</a></li>
  <li><a href="#conclusions-1" id="toc-conclusions-1" class="nav-link" data-scroll-target="#conclusions-1"><span class="header-section-number">5.3.10</span> Conclusions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-431-regression" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this Chapter, we will review some key issues about comparing proportions or rates, mostly drawn from the 431 course. This and the other Chapters labeled “431 Review” show elements of the two studies involved in a “<a href="https://thomaselove.github.io/431-projectB-2022/">431 Project B</a>” using the pre-pandemic (2017 - March 2020) data from the National Health and Nutrition Examination Survey (NHANES) called <strong>nh432</strong> that we developed in <a href="nhanes.html"><span>Chapter&nbsp;1</span></a> and then summarized in <a href="nh432cb.html"><span>Chapter&nbsp;2</span></a>. Note that we’ll ignore the issue of sampling weights and assume a “missing completely at random” (MCAR) mechanism in these “431 Review” chapters, so that we can work with complete cases.</p>
<p>The 431 course notes are at <a href="https://thomaselove.github.io/431-notes/" class="uri">https://thomaselove.github.io/431-notes/</a> and will remain there until June 1.</p>
<section id="r-setup" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="r-setup"><span class="header-section-number">5.1</span> R Setup</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-load" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="data-load"><span class="header-section-number">5.1.1</span> Data Load</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>nh432 <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/nh432.Rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="modeling-weekend-sleep-hours" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="modeling-weekend-sleep-hours"><span class="header-section-number">5.2</span> Modeling Weekend Sleep Hours</h2>
<p>In this example, we’ll try to build an effective model to predict our outcome: average weekend hours of sleep (SLPWKEND) on the basis of four predictors:</p>
<ul>
<li>average weekday hours of sleep (SLPWKDAY)</li>
<li>systolic blood pressure (SBP)</li>
<li>PHQ-9 depression screener score (PHQ9), and</li>
<li>whether or not the participant has mentioned trouble sleeping to a physician (SLPTROUB)</li>
</ul>
<p>We’ll compare a model using all four of these predictors to a model using just the two directly related to sleep (SLPWKDAY and SLPTROUB), and we’ll restrict our analysis to those participants whose self-reported overall health (SROH) was “Good”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dat1 <span class="ot">&lt;-</span> nh432 <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, SLPWKEND, SLPWKDAY, SBP, PHQ9, SLPTROUB, SROH) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SROH <span class="sc">==</span> <span class="st">"Good"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>dat1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,293 × 7
   SEQN   SLPWKEND SLPWKDAY   SBP  PHQ9 SLPTROUB SROH 
   &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;fct&gt;
 1 109273      8        6.5   110    15        1 Good 
 2 109293      6.5      7.5   130     3        0 Good 
 3 109295      7        7     161     0        1 Good 
 4 109305      6.5      6     125     0        0 Good 
 5 109307     11        7.5   114     0        0 Good 
 6 109315      5        5     123     1        0 Good 
 7 109336      8        4     148     1        1 Good 
 8 109342      8        6.5   107    16        1 Good 
 9 109365      9.5      9.5   133     7        0 Good 
10 109378      9        9     133     0        0 Good 
# ℹ 1,283 more rows</code></pre>
</div>
</div>
<section id="should-we-transform-our-outcome" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="should-we-transform-our-outcome"><span class="header-section-number">5.2.1</span> Should we transform our outcome?</h3>
<p>We can develop a Box-Cox plot to help us choose between potential transformations of our outcome, so as to improve the adherence to regression assumptions. To do so, we first fit our larger model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SLPWKEND <span class="sc">~</span> SLPWKDAY <span class="sc">+</span> SBP <span class="sc">+</span> PHQ9 <span class="sc">+</span> SLPTROUB, <span class="at">data =</span> dat1)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxCox</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Box-Cox suggested set of transformations centers near <span class="math inline">\(\lambda = 1\)</span>. As we saw back in <a href="431review1.html"><span>Chapter&nbsp;3</span></a>, The <strong>ladder of power transformations</strong> looks like this:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(\lambda\)</span></th>
<th style="text-align: center;">Transformation</th>
<th style="text-align: center;">Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-2</td>
<td style="text-align: center;">inverse square</td>
<td style="text-align: center;"><span class="math inline">\(1/y^2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">-1</td>
<td style="text-align: center;">inverse</td>
<td style="text-align: center;"><span class="math inline">\(1/y\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.5</td>
<td style="text-align: center;">inverse square root</td>
<td style="text-align: center;"><span class="math inline">\(1/\sqrt{y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: center;">logarithm</td>
<td style="text-align: center;"><span class="math inline">\(log y\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.5</td>
<td style="text-align: center;">square root</td>
<td style="text-align: center;"><span class="math inline">\(\sqrt{y}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: center;">no transformation</td>
<td style="text-align: center;">y</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: center;">square</td>
<td style="text-align: center;"><span class="math inline">\(y^2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: center;">cube</td>
<td style="text-align: center;"><span class="math inline">\(y^3\)</span></td>
</tr>
</tbody>
</table>
<p>So, in this case, the Box-Cox approach (again, with <span class="math inline">\(\lambda\)</span> near 1) suggests that we leave the existing SLPWKEND outcome alone.</p>
</section>
<section id="scatterplot-matrix" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="scatterplot-matrix"><span class="header-section-number">5.2.2</span> Scatterplot Matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(dat1, <span class="at">columns =</span> <span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">2</span>), <span class="at">switch =</span> <span class="st">"both"</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">lower=</span><span class="fu">list</span>(<span class="at">combo=</span><span class="fu">wrap</span>(<span class="st">"facethist"</span>, <span class="at">bins=</span><span class="dv">25</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The reason I included column 2 (our outcome: SLPWKEND) last in this plot is so that the bottom row would include each of our predictors plotted on the X (horizontal) axis against the outcome on the Y (vertical) axis, next to a density plot of the outcome.</li>
<li>I also switched the locations of the facet labels on both the x and y axis from their defaults, so that the labels are to the left and below the plots, since I find that a bit easier to work with.</li>
<li>The <code>lower</code> business is to avoid getting a warning about binwidths.</li>
<li>The binary variable (SLPTROUB) is included here as a 1-0 numeric variable, rather than a factor, which is why the scatterplot matrix looks as it does, rather than creating a series of boxplots (as we’ll see when we work with a factor later.)</li>
</ul>
</section>
<section id="collinearity" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="collinearity"><span class="header-section-number">5.2.3</span> Collinearity?</h3>
<p>In any multiple regression setting, two or more of the predictors might be highly correlated with one another, and this is referred to as multicollinearity or just collinearity. If we have a serious problem with collinearity, this can cause several problems, including difficulty fitting and interpreting the resulting model.</p>
<p>Is collinearity a serious concern in our situation? Looking at the scatterplot matrix, we see that the largest observed correlation between two predictors is between PHQ9 and SLPTROUB. Does that rise to the level of a problem?</p>
<p>I usually use the <code>vif()</code> function from the <strong>car</strong> package to help make this decision. The <em>variance inflation factor</em> (or VIF) measures how much the variance of a regression coefficient is inflated due to collinearity in the model. The smallest possible VIF value is 1, and VIFs near 1, as we’ll see here, indicate no problems with collinearity worth worrying about.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SLPWKDAY      SBP     PHQ9 SLPTROUB 
1.002807 1.006778 1.102341 1.098187 </code></pre>
</div>
</div>
<p>Should we see a VIF (or generalized VIF, which is produced by the <code>vif()</code> function when we have factor variables in the model) above, say, 5, that would be an indication that the model would be improved by not including the variable that exhibits collinearity. Here, we have no such issues, and will proceed to fit the model including all of these predictors.</p>
</section>
<section id="fitting-and-displaying-model-m1" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="fitting-and-displaying-model-m1"><span class="header-section-number">5.2.4</span> Fitting and Displaying Model <code>m1</code></h3>
<p>Here are the coefficients obtained from fitting the model <code>m1</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SLPWKEND <span class="sc">~</span> SLPWKDAY <span class="sc">+</span> SBP <span class="sc">+</span> PHQ9 <span class="sc">+</span> SLPTROUB, <span class="at">data =</span> dat1)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SLPWKEND ~ SLPWKDAY + SBP + PHQ9 + SLPTROUB, data = dat1)

Coefficients:
(Intercept)     SLPWKDAY          SBP         PHQ9     SLPTROUB  
    5.26266      0.52661     -0.00560     -0.02945     -0.20813  </code></pre>
</div>
</div>
<p>If Harry and Sally have the same values of SLPWKDAY, SBP and SLPTROUB, but Harry’s PHQ9 is one point higher than Sally’s, then model <code>m1</code> predicts that Harry will sleep 0.029 hours less than Sally on the weekends.</p>
<p>A summary of the regression model <code>m1</code> provides lots of useful information about the parameters (including their standard errors) and the quality of fit (at least as measured by <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SLPWKEND ~ SLPWKDAY + SBP + PHQ9 + SLPTROUB, data = dat1)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.1173 -0.9609 -0.1005  0.9248  6.3659 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.262657   0.388427  13.549  &lt; 2e-16 ***
SLPWKDAY     0.526612   0.028950  18.190  &lt; 2e-16 ***
SBP         -0.005600   0.002515  -2.227  0.02613 *  
PHQ9        -0.029450   0.010955  -2.688  0.00727 ** 
SLPTROUB    -0.208129   0.098758  -2.107  0.03527 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.554 on 1288 degrees of freedom
Multiple R-squared:  0.2171,    Adjusted R-squared:  0.2147 
F-statistic:  89.3 on 4 and 1288 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="using-broom-functions-on-model-m1" class="level3" data-number="5.2.5">
<h3 data-number="5.2.5" class="anchored" data-anchor-id="using-broom-functions-on-model-m1"><span class="header-section-number">5.2.5</span> Using <strong>broom</strong> functions on Model <code>m1</code></h3>
<p>If we want to actually use the information in the model summary elsewhere, we use the <code>tidy()</code> and <code>glance()</code> functions from the <strong>broom</strong> package to help us.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  5.26      0.388       13.5  3.41e-39  4.62      5.90   
2 SLPWKDAY     0.527     0.0290      18.2  5.52e-66  0.479     0.574  
3 SBP         -0.00560   0.00251     -2.23 2.61e- 2 -0.00974  -0.00146
4 PHQ9        -0.0294    0.0110      -2.69 7.27e- 3 -0.0475   -0.0114 
5 SLPTROUB    -0.208     0.0988      -2.11 3.53e- 2 -0.371    -0.0456 </code></pre>
</div>
</div>
<p>We can produce a neater version of the <code>tidy()</code> output, produced using the <code>gt()</code> function, but I will just show the code here, since it causes trouble when I build a PDF of these Notes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>) <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="sc">-</span><span class="fu">c</span>(term), \(x) <span class="fu">round_half_up</span>(x, <span class="at">digits =</span> <span class="dv">3</span>))) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that none of the 90% confidence intervals here cross zero. This just means that we have a pretty good handle on the direction of effects - for example, our estimate for the slope of SLPWKDAY is positive, suggesting that people who sleep more during the week also sleep more on the weekend, after accounting for SBP, PHQ9 and SLPTROUB.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.217         0.215  1.55      89.3 4.93e-67     4 -2402. 4817. 4848.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>Model <code>m1</code> shows an <span class="math inline">\(R^2\)</span> value of 0.217, which means that 21.7% of the variation in our outcome SLPWKEND is accounted for by the model using SLPWKDAY, SBP, PHQ9 and SLPTROUBLE.</p>
<p>The adjusted <span class="math inline">\(R^2\)</span> value isn’t a percentage or proportion of anything, but it is a handy index when comparing two models fit to the same outcome for the same observations. It penalizes the raw <span class="math inline">\(R^2\)</span> value for models that require more coefficients to be fit. If the raw <span class="math inline">\(R^2\)</span> is much larger than the adjusted <span class="math inline">\(R^2\)</span> value, this is also an indication that the model may be “overfit” - capitalizing on noise in the data more than we’d like, so that the amount of signal in the predictors may be overstated by raw <span class="math inline">\(R^2\)</span>.</p>
<p>Here’s a cleaner presentation of some of the more important elements in the <code>glance()</code> output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(m1) <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">r2 =</span> r.squared, <span class="at">adjr2 =</span> adj.r.squared, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>         AIC, BIC, sigma, nobs, df, <span class="at">df.res =</span> df.residual) <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">r2</th>
<th style="text-align: right;">adjr2</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">nobs</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">df.res</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.217</td>
<td style="text-align: right;">0.215</td>
<td style="text-align: right;">4816.6</td>
<td style="text-align: right;">4847.6</td>
<td style="text-align: right;">1.55</td>
<td style="text-align: right;">1293</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1288</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>AIC and BIC are measures used to compare models for the same outcome using the same data, so we’ll see those again when we fit a second model to these data. In those comparisons, smaller values of AIC and BIC indicate better fitting models.</li>
<li>nobs is the number of observations used to actually fit our model <code>m1</code>,</li>
<li>df indicates the number of degrees of freedom used by the model, and represents the number of estimated coefficients fit, while</li>
<li>df.res = nobs - df - 1 = residual degrees of freedom.</li>
</ul>
</section>
<section id="residual-plots-for-model-m1" class="level3" data-number="5.2.6">
<h3 data-number="5.2.6" class="anchored" data-anchor-id="residual-plots-for-model-m1"><span class="header-section-number">5.2.6</span> Residual Plots for Model <code>m1</code></h3>
<p>The key assumptions for a linear regression model include:</p>
<ol type="1">
<li>Linearity of the association under study</li>
<li>Normality of the residuals</li>
<li>Constant Variance (Homoscedasticity)</li>
<li>Independence (not an issue with cross-sectional data like this)</li>
</ol>
<p>A residual for a point in a regression model is just the observed value of our outcome (here, SLPWKEND) minus the value predicted by the model based on the predictor values (also called the fitted value.)</p>
<p>The four key plots that R will generate for you to help assess these results are shown below for model <code>m1</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## I used </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="do">## #| fig.height: 8 </span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="do">## at the top of this code chunk</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="do">## to make the plots tall enough to see well</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)); <span class="fu">plot</span>(m1); <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="residuals-vs.-fitted-values" class="level4" data-number="5.2.6.1">
<h4 data-number="5.2.6.1" class="anchored" data-anchor-id="residuals-vs.-fitted-values"><span class="header-section-number">5.2.6.1</span> Residuals vs.&nbsp;Fitted values</h4>
<p>The top left plot (Residuals vs.&nbsp;Fitted Values) helps us to assess the linearity and constant variance assumptions.</p>
<ul>
<li>We want to see a “fuzzy football” shape.</li>
<li>A clear curve is indicative of a problem with linearity, and suggests that perhaps a transformation of the outcome (or perhaps one or more predictors) may be in order</li>
<li>A fan shape, with much more variation at one end of the fitted values (left or right) than the other indicates a problem with the constant variance assumption, and again a transformation may be needed.</li>
</ul>
<p>The diagonal lines we see in the Residuals vs.&nbsp;Fitted plot are the result of the fact that both the outcome (SLPWKEND) and a key predictor (SLPWKDAYS) aren’t really continuous in the data, as most of the responses to those questions were either integers, or used 0.5 as the fraction. So those two variables are more discrete than we might have expected.</p>
</section>
<section id="normal-q-q-plot-of-standardized-residuals" class="level4" data-number="5.2.6.2">
<h4 data-number="5.2.6.2" class="anchored" data-anchor-id="normal-q-q-plot-of-standardized-residuals"><span class="header-section-number">5.2.6.2</span> Normal Q-Q plot of standardized residuals</h4>
<p>The top right plot (Normal Q-Q) is a Normal Q-Q plot of the standardized regression residuals for our model <code>m1</code>. Substantial issues with skew (a curve in the plot) or a major problem with outliers (as indicated by a reverse S-shape) indicate potential concerns with the Normality assumption. Since the y-axis here shows standardized residuals, we can also assess whether what we’re seeing is especially surprising relative to our expectations for any standardized values (for example, we should see values above +3 or below -3 approximately 3 times in 1000).</p>
<ul>
<li>Remember that this plot represents <strong>nobs</strong> = 1293 residuals, so a few values near 3 in absolute value aren’t surprising.</li>
<li>We’re looking for big deviations from Normality here.</li>
<li>The <code>plot()</code> function in R will always identify three of the cases, by default, in these four plots.</li>
</ul>
<p>Suppose we wanted to look at the data for case 210, identified by these plots as a potential outlier, or at least a poorly fit point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dat1_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(m1, <span class="at">data =</span> dat1)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>dat1_aug <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">210</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, SLPWKEND, .fitted, .resid, .std.resid, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 13
  SEQN   SLPWKEND .fitted .resid .std.resid SLPWKDAY   SBP  PHQ9 SLPTROUB SROH 
  &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;fct&gt;
1 111688       13    6.63   6.37       4.11        4   126     1        0 Good 
# ℹ 3 more variables: .hat &lt;dbl&gt;, .sigma &lt;dbl&gt;, .cooksd &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We see that row 210 contains SEQN 111688, whose</p>
<ul>
<li>observed SLPWKEND is 13</li>
<li>fitted SLPWKEND is 6.63</li>
<li>yielding a residual of 6.37,</li>
<li>or a standardized residual of 4.11</li>
</ul>
<p>We can use the <code>outlierTest()</code> function in the <strong>car</strong> package to help assess whether this value is unusual enough to merit more careful consideration. This function actually works with the studentized residual, which is similar to the standardized residual we saw above. Here, this point (SEQN 111688) is fit poorly enough to be flagged by the Bonferroni outlier test as a mean-shift outlier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">outlierTest</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    rstudent unadjusted p-value Bonferroni p
210 4.131972         3.8289e-05     0.049508</code></pre>
</div>
</div>
<p>Having seen that, though, I’m going to essentially ignore it for the moment, and press on to the rest of our residual analysis.</p>
</section>
<section id="scale-location-plot" class="level4" data-number="5.2.6.3">
<h4 data-number="5.2.6.3" class="anchored" data-anchor-id="scale-location-plot"><span class="header-section-number">5.2.6.3</span> Scale-Location plot</h4>
<p>The bottom left plot in our set of four residual plots is the Scale-Location plot, which presents the square root of the standardized residuals against the fitted values. This plot provides another check on the “equal variance” assumption - if the plot shows a clear trend either up or down as we move left to right, then that indicates an issue with constant variance. While a loess smooth is provided (red curve) to help guide our thinking, it’s important not to get too excited about small changes or changes associated with small numbers of observations.</p>
<p>You’ll also note the presence of curves (in particular, little “V” shapes) formed by the points of the plot. Again, this is caused by the discrete nature of the outcome (and one of the key predictors) and wouldn’t be evident if our outcome was more continuous.</p>
<p>Despite the drop in the red loess smooth as fitted values move from 5 to about 8, I don’t see much of a pattern here to indicate trouble with non-constant variance.</p>
</section>
<section id="residuals-vs.-leverage-plot" class="level4" data-number="5.2.6.4">
<h4 data-number="5.2.6.4" class="anchored" data-anchor-id="residuals-vs.-leverage-plot"><span class="header-section-number">5.2.6.4</span> Residuals vs.&nbsp;Leverage plot</h4>
<p>The bottom-left plot is a plot of residuals vs.&nbsp;leverage, with influence contours.</p>
<p>Highly leveraged points have unusual combinations of predictor values.</p>
<p>Highly influential points have a big impact on the model, in that the model’s coefficients or quality of fit would change markedly were those points to be removed from the model. To measure influence, we combine leverage and residuals together, with a measure like Cook’s distance.</p>
<ul>
<li>To look for points with substantial <strong>leverage</strong> on the model by virtue of having unusual values of the predictors - look for points whose leverage is at least 3 times as large as the average leverage value.</li>
<li>The average leverage is always k/n, where k is the number of coefficients fit by the model (including the slopes and intercept), and n is the number of observations in the model.</li>
<li>To obtain the leverage values, the <code>augment()</code> function stores them in <code>.hat</code>.</li>
<li>To look for points with substantial <strong>influence</strong> on the model, that is, removing them from the model would change it substantially, consider the Cook’s distance, plotted in contours here.</li>
<li>Any Cook’s distance point &gt; 1 will likely have a substantial impact on the model.</li>
<li>Any points with Cook’s distance &gt; 0.5, if any, will be indicated in the bottom-right (Residuals vs.&nbsp;Leverage) plot, and are worthy of investigation.</li>
<li>In model <code>m1</code>, we have no points with values of Cook’s distance &gt; 0.5. To obtain the Cook’s distance values for each point, use the <code>augment()</code> function, which stores them in <code>.cooksd</code>.</li>
</ul>
<p>Here, for example, we identify the points with largest leverage and with largest Cook’s distance, across the points used to fit <code>m1</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dat1_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(m1, <span class="at">data =</span> dat1)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>dat1_aug <span class="sc">|&gt;</span> <span class="fu">slice_max</span>(.hat) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, .hat, .resid, .fitted, .cooksd, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 13
  SEQN     .hat .resid .fitted .cooksd SLPWKEND SLPWKDAY   SBP  PHQ9 SLPTROUB
  &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
1 123474 0.0268  -1.03    8.03 0.00250        7        8   126    25        0
# ℹ 3 more variables: SROH &lt;fct&gt;, .sigma &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dat1_aug <span class="sc">|&gt;</span> <span class="fu">slice_max</span>(.cooksd) <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, .hat, .resid, .fitted, .cooksd, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 13
  SEQN     .hat .resid .fitted .cooksd SLPWKEND SLPWKDAY   SBP  PHQ9 SLPTROUB
  &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
1 122894 0.0113   5.38    5.62  0.0277       11        2   114     2        0
# ℹ 3 more variables: SROH &lt;fct&gt;, .sigma &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
<p>It turns out that SEQN 123474 has the largest value of leverage (<code>.hat</code>) and SEQN 122894 has the largest value of influence (<code>.cooksd</code>) in our model. We will worry about <code>.cooksd</code> values above 0.5, but the largest value in this model is much smaller than that, so I think we’re OK for now.</p>
</section>
</section>
<section id="fitting-and-displaying-model-m2" class="level3" data-number="5.2.7">
<h3 data-number="5.2.7" class="anchored" data-anchor-id="fitting-and-displaying-model-m2"><span class="header-section-number">5.2.7</span> Fitting and Displaying Model <code>m2</code></h3>
<p>We will now move on to compare the results of this model (<code>m1</code>) to a smaller model.</p>
<p>Our second model, <code>m2</code> is a subset of <code>m1</code>, including only the two predictors directly related to sleep, SLPWKDAY and SLPTROUB.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SLPWKEND <span class="sc">~</span> SLPWKDAY <span class="sc">+</span> SLPTROUB, <span class="at">data =</span> dat1)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SLPWKEND ~ SLPWKDAY + SLPTROUB, data = dat1)

Coefficients:
(Intercept)     SLPWKDAY     SLPTROUB  
     4.4813       0.5301      -0.2862  </code></pre>
</div>
</div>
<p>Note that the slopes of both SLPWKDAY and SLPTROUB have changed from model <code>m1</code> (although not very much), and that the intercept has changed more substantially.</p>
</section>
<section id="using-broom-functions-on-m2" class="level3" data-number="5.2.8">
<h3 data-number="5.2.8" class="anchored" data-anchor-id="using-broom-functions-on-m2"><span class="header-section-number">5.2.8</span> Using <code>broom</code> functions on <code>m2</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m2, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>) <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">4.481</td>
<td style="text-align: right;">0.219</td>
<td style="text-align: right;">20.475</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">4.121</td>
<td style="text-align: right;">4.842</td>
</tr>
<tr class="even">
<td style="text-align: left;">SLPWKDAY</td>
<td style="text-align: right;">0.530</td>
<td style="text-align: right;">0.029</td>
<td style="text-align: right;">18.268</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.482</td>
<td style="text-align: right;">0.578</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SLPTROUB</td>
<td style="text-align: right;">-0.286</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">-3.025</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">-0.442</td>
<td style="text-align: right;">-0.130</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(m2) <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">r2 =</span> r.squared, <span class="at">adjr2 =</span> adj.r.squared, </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>         AIC, BIC, sigma, nobs, df, <span class="at">df.res =</span> df.residual) <span class="sc">|&gt;</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">r2</th>
<th style="text-align: right;">adjr2</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">nobs</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">df.res</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.209</td>
<td style="text-align: right;">4824.1</td>
<td style="text-align: right;">4844.8</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: right;">1293</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1290</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Since we want to compare the fit of <code>m1</code> to that of <code>m2</code>, we probably want to do so in a single table, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>temp1 <span class="ot">&lt;-</span> <span class="fu">glance</span>(m1) <span class="sc">|&gt;</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">r2 =</span> r.squared, <span class="at">adjr2 =</span> adj.r.squared, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>         AIC, BIC, sigma, nobs, df, <span class="at">df.res =</span> df.residual) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"m1"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(model)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>temp2 <span class="ot">&lt;-</span> <span class="fu">glance</span>(m2) <span class="sc">|&gt;</span> </span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">r2 =</span> r.squared, <span class="at">adjr2 =</span> adj.r.squared, </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>         AIC, BIC, sigma, nobs, df, <span class="at">df.res =</span> df.residual) <span class="sc">|&gt;</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"m2"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(model)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(temp1, temp2) <span class="sc">|&gt;</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">r2</th>
<th style="text-align: right;">adjr2</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">nobs</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">df.res</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">m1</td>
<td style="text-align: right;">0.217</td>
<td style="text-align: right;">0.215</td>
<td style="text-align: right;">4816.6</td>
<td style="text-align: right;">4847.6</td>
<td style="text-align: right;">1.55</td>
<td style="text-align: right;">1293</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1288</td>
</tr>
<tr class="even">
<td style="text-align: left;">m2</td>
<td style="text-align: right;">0.210</td>
<td style="text-align: right;">0.209</td>
<td style="text-align: right;">4824.1</td>
<td style="text-align: right;">4844.8</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: right;">1293</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1290</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each model uses the same number of observations to predict the same outcome (SLPWKEND). So we can compare them directly. As compared to model <code>m2</code>, model <code>m1</code> has:</p>
<ul>
<li>the larger <span class="math inline">\(R^2\)</span> (as it must, since model <code>m2</code> includes a subset of the predictors in model <code>m1</code>),</li>
<li>the larger adjusted <span class="math inline">\(R^2\)</span>,</li>
<li>the smaller AIC (Akaike Information Criterion: smaller values are better),</li>
<li>the larger BIC (Bayes Information Criterion: again, smaller values are better),<br>
</li>
<li>and the smaller residual standard error (<span class="math inline">\(\sigma\)</span>) (smaller values are better.)</li>
</ul>
<p>The key realizations for these data are that the AIC, adjusted <span class="math inline">\(R^2\)</span> and <span class="math inline">\(\sigma\)</span> results favor model <code>m1</code> while the BIC favors model <code>m2</code>.</p>
</section>
<section id="residual-plots-for-model-m2" class="level3" data-number="5.2.9">
<h3 data-number="5.2.9" class="anchored" data-anchor-id="residual-plots-for-model-m2"><span class="header-section-number">5.2.9</span> Residual Plots for Model <code>m2</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## I used #| fig.height: 8 in this code chunk</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="do">## to make the plots tall enough to see well</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)); <span class="fu">plot</span>(m2); <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The residual plots here show (even more starkly than in model <code>m1</code>) the discrete nature of our outcome and the two variables we’re using to predict it. I see no especially serious problems with the assumptions of linearity or constant variance here, and while there are still some fairly poorly fit values, there are no highly influential points, so I’ll accept these residual plots as indicative of a fairly reasonable model on the whole.</p>
</section>
<section id="conclusions" class="level3" data-number="5.2.10">
<h3 data-number="5.2.10" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">5.2.10</span> Conclusions</h3>
<p>Three of our four in-sample measures of fit quality (AIC, <span class="math inline">\(\sigma\)</span> and adjusted <span class="math inline">\(R^2\)</span>) favor the larger model <code>m1</code> over <code>m2</code>, but there’s not a lot to choose from here. Neither model showed important problems with regression assumptions, so I would probably wind up choosing <code>m1</code> based on the analyses we’ve done in this Chapter.</p>
<p>However, a more appropriate strategy for prediction assessment would be to partition the data into separate samples for model training (the development or building sample) and model testing. We adopt such a model validation strategy in our next little study.</p>
</section>
</section>
<section id="modeling-high-sensitivity-c-reactive-protein" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="modeling-high-sensitivity-c-reactive-protein"><span class="header-section-number">5.3</span> Modeling High-Sensitivity C-Reactive Protein</h2>
<p>In this, our second linear modeling example, we will try to predict High-Sensitivity C-Reactive Protein levels (HSCRP) on the basis of these three predictor variables:</p>
<ul>
<li>the participant’s mean pulse rate, specifically the mean of the two gathered pulse rates, PULSE1 and PULSE2</li>
<li>the participant’s self-reported overall health (SROH, which is an ordinal factor with levels Excellent, Very Good, Good, Fair and Poor)</li>
<li>HOSPITAL, a 1-0 binary variable indicating whether or not the participant was hospitalized in the past year.</li>
</ul>
<p>In this case, we’ll use all NHANES participants with complete data on the relevant variables to fit the three-predictor model, and then a second model using mean pulse rate alone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> nh432 <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, HSCRP, PULSE1, PULSE2, SROH, HOSPITAL) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MEANPULSE =</span> <span class="fl">0.5</span><span class="sc">*</span>(PULSE1 <span class="sc">+</span> PULSE2))</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dat2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,117
Columns: 7
$ SEQN      &lt;chr&gt; "109271", "109273", "109291", "109292", "109293", "109295", …
$ HSCRP     &lt;dbl&gt; 28.68, 0.98, 5.31, 3.08, 15.10, 6.28, 0.56, 1.45, 0.32, 0.86…
$ PULSE1    &lt;dbl&gt; 73, 71, 77, 93, 62, 93, 74, 59, 66, 83, 64, 55, 54, 63, 68, …
$ PULSE2    &lt;dbl&gt; 71, 70, 76, 91, 64, 93, 74, 58, 64, 87, 68, 55, 54, 63, 70, …
$ SROH      &lt;fct&gt; Fair, Good, Fair, Very Good, Good, Good, Very Good, Excellen…
$ HOSPITAL  &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ MEANPULSE &lt;dbl&gt; 72.0, 70.5, 76.5, 92.0, 63.0, 93.0, 74.0, 58.5, 65.0, 85.0, …</code></pre>
</div>
</div>
<section id="partitioning-the-data" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="partitioning-the-data"><span class="header-section-number">5.3.1</span> Partitioning the Data</h3>
<p>Before partitioning, it’s always a good idea to be sure that the number of rows in the tibble matches the number of distinct (unique) values in the identifier column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">identical</span>(<span class="fu">nrow</span>(dat2), <span class="fu">n_distinct</span>(dat2 <span class="sc">|&gt;</span> <span class="fu">select</span>(SEQN)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>OK. Now, be sure to set a seed so that we can replicate the selection. We’ll put 70% of the data in our training sample, setting aside the remaining 30% for the test sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">432005</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>dat2_train <span class="ot">&lt;-</span> <span class="fu">slice_sample</span>(dat2, <span class="at">prop =</span> <span class="fl">0.70</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>dat2_test <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(dat2, dat2_train, <span class="at">by =</span> <span class="st">"SEQN"</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">nrow</span>(dat2), <span class="fu">nrow</span>(dat2_train), <span class="fu">nrow</span>(dat2_test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3117 2181  936</code></pre>
</div>
</div>
<p>In what follows, we’ll work with the <code>dat2_train</code> sample, and set aside the <code>dat2_test</code> sample for a while.</p>
</section>
<section id="transforming-the-outcome" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="transforming-the-outcome"><span class="header-section-number">5.3.2</span> Transforming the Outcome?</h3>
<p>Let’s use the Box-Cox approach to help us think about which potential transformations of our outcome might be helpful, within our training sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>m_temp <span class="ot">&lt;-</span> <span class="fu">lm</span>(HSCRP <span class="sc">~</span> MEANPULSE <span class="sc">+</span> SROH <span class="sc">+</span> HOSPITAL, <span class="at">data =</span> dat2_train)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxCox</span>(m_temp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The estimated <span class="math inline">\(\lambda\)</span> value is very close to 0, which according to the ladder of power transformations, suggests we take the logarithm of our outcome, so as to improve the residual plots for the model. This will also, as it turns out, lead to a much less right-skewed outcome variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat2_train, <span class="fu">aes</span>(<span class="at">sample =</span> HSCRP)) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normal Q-Q: untransformed HSCRP"</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat2_train, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">log</span>(HSCRP))) <span class="sc">+</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normal Q-Q: Natural Log of HSCRP"</span>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Clearly, one benefit of the transformation is some improvement in the Normality of our outcome’s distribution.</p>
</section>
<section id="scatterplot-matrix-and-collinearity" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="scatterplot-matrix-and-collinearity"><span class="header-section-number">5.3.3</span> Scatterplot Matrix and Collinearity</h3>
<p>To build the relevant scatterplot matrix with our transformed outcome, I’ll create a variable containing the result of the transformation within our training sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>dat2_train <span class="ot">&lt;-</span> dat2_train <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">logHSCRP =</span> <span class="fu">log</span>(HSCRP))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dat2_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "SEQN"      "HSCRP"     "PULSE1"    "PULSE2"    "SROH"      "HOSPITAL" 
[7] "MEANPULSE" "logHSCRP" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(dat2_train, <span class="at">columns =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">8</span>), <span class="at">switch =</span> <span class="st">"both"</span>,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">lower=</span><span class="fu">list</span>(<span class="at">combo=</span><span class="fu">wrap</span>(<span class="st">"facethist"</span>, <span class="at">bins=</span><span class="dv">25</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As a collinearity check, we’ll run <code>vif()</code> from the <strong>car</strong> package here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(HSCRP) <span class="sc">~</span> MEANPULSE <span class="sc">+</span> SROH <span class="sc">+</span> HOSPITAL,</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> dat2_train)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              GVIF Df GVIF^(1/(2*Df))
MEANPULSE 1.036382  1        1.018028
SROH      1.063545  4        1.007731
HOSPITAL  1.027860  1        1.013834</code></pre>
</div>
</div>
<p>Again, no signs of meaningful collinearity. Note the presentation of the factor variable <code>SROH</code> in the scatterplot matrix, and in the generalized VIF output.</p>
</section>
<section id="fit-model-m3" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="fit-model-m3"><span class="header-section-number">5.3.4</span> Fit Model <code>m3</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(HSCRP) <span class="sc">~</span> MEANPULSE <span class="sc">+</span> SROH <span class="sc">+</span> HOSPITAL,</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> dat2_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m3, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.108</td>
<td style="text-align: right;">0.160</td>
<td style="text-align: right;">-6.914</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-1.372</td>
<td style="text-align: right;">-0.845</td>
</tr>
<tr class="even">
<td style="text-align: left;">MEANPULSE</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">9.359</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SROHVery Good</td>
<td style="text-align: right;">0.237</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">2.939</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.370</td>
</tr>
<tr class="even">
<td style="text-align: left;">SROHGood</td>
<td style="text-align: right;">0.532</td>
<td style="text-align: right;">0.078</td>
<td style="text-align: right;">6.857</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.404</td>
<td style="text-align: right;">0.660</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SROHFair</td>
<td style="text-align: right;">0.641</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">7.353</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.497</td>
<td style="text-align: right;">0.784</td>
</tr>
<tr class="even">
<td style="text-align: left;">SROHPoor</td>
<td style="text-align: right;">0.860</td>
<td style="text-align: right;">0.143</td>
<td style="text-align: right;">6.020</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: right;">1.095</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HOSPITAL</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">0.594</td>
<td style="text-align: right;">0.552</td>
<td style="text-align: right;">-0.092</td>
<td style="text-align: right;">0.197</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>If Harry and Sally have the same values of HOSPITAL and MEANPULSE, but Harry’s SROH is “Very Good” while Sally’s is “Excellent”, then model <code>m3</code> predicts that Harry will have a log(HSCRP) that is 0.237 (90% CI: 0.104, 0.370) larger than Sally’s log(HSCRP).</li>
<li>On the other hand, if Harry and Gary have the same values of HOSPITAL and MEANPULSE, but Harry’s SROH remains “Very Good” while Gary’s is only “Good”, then model <code>m3</code> predicts that <em>Gary</em> will have a log(HSCRP) that is (0.532 - 0.237 = 0.295) larger than Harry’s log(HSCRP).</li>
</ul>
</section>
<section id="residual-plots-for-m3" class="level3" data-number="5.3.5">
<h3 data-number="5.3.5" class="anchored" data-anchor-id="residual-plots-for-m3"><span class="header-section-number">5.3.5</span> Residual Plots for <code>m3</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="do">## don't forget to use #| fig.height: 8</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="do">## to make the residual plots taller</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)); <span class="fu">plot</span>(m3); <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I see no serious concerns with regression assumptions here. The residuals vs.&nbsp;fitted plot shows no signs of meaningful non-linearity or heteroscedasticity. The standardized residuals in the Normal Q-Q plot follow the reference line closely. There is no clear trend in the scale-location plot, and the residuals vs.&nbsp;leverage plot reveals no particularly influential points.</p>
</section>
<section id="fit-model-m4" class="level3" data-number="5.3.6">
<h3 data-number="5.3.6" class="anchored" data-anchor-id="fit-model-m4"><span class="header-section-number">5.3.6</span> Fit Model <code>m4</code></h3>
<p>Let’s now fit the simple regression model, <code>m4</code>, with only MEANPULSE as a predictor of the log of HSCRP.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(HSCRP) <span class="sc">~</span> MEANPULSE,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> dat2_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s look at the tidied coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m4, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.929</td>
<td style="text-align: right;">0.154</td>
<td style="text-align: right;">-6.048</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-1.181</td>
<td style="text-align: right;">-0.676</td>
</tr>
<tr class="even">
<td style="text-align: left;">MEANPULSE</td>
<td style="text-align: right;">0.023</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">10.934</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.027</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>If Harry’s mean pulse rate is one beat per minute higher than Sally’s, then model <code>m4</code> predicts that the logarithm of Harry’s HSCRP will be 0.023 higher than Sally’s, with 90% CI (0.020, 0.027).</li>
<li>Note that if Harry’s mean pulse rate is <em>ten</em> beats per minute higher than Sally’s, then model <code>m4</code> predicts that the logarithm of Harry’s HSCRP will be 0.23 higher than Sally’s, with 90% CI (0.20, 0.27).</li>
</ul>
</section>
<section id="residual-plots-for-m4" class="level3" data-number="5.3.7">
<h3 data-number="5.3.7" class="anchored" data-anchor-id="residual-plots-for-m4"><span class="header-section-number">5.3.7</span> Residual Plots for <code>m4</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)); <span class="fu">plot</span>(m4); <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="431review3_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="in-sample-fit-quality-comparison-m3-vs.-m4" class="level3" data-number="5.3.8">
<h3 data-number="5.3.8" class="anchored" data-anchor-id="in-sample-fit-quality-comparison-m3-vs.-m4"><span class="header-section-number">5.3.8</span> In-Sample Fit Quality Comparison (<code>m3</code> vs.&nbsp;<code>m4</code>)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">glance</span>(m3) <span class="sc">|&gt;</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">r2 =</span> r.squared, <span class="at">adjr2 =</span> adj.r.squared, </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>         AIC, BIC, sigma, nobs, df, <span class="at">df.res =</span> df.residual) <span class="sc">|&gt;</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"m3"</span>) <span class="sc">|&gt;</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(model)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>g4 <span class="ot">&lt;-</span> <span class="fu">glance</span>(m4) <span class="sc">|&gt;</span> </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">r2 =</span> r.squared, <span class="at">adjr2 =</span> adj.r.squared, </span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>         AIC, BIC, sigma, nobs, df, <span class="at">df.res =</span> df.residual) <span class="sc">|&gt;</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"m4"</span>) <span class="sc">|&gt;</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(model)</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(g3, g4) <span class="sc">|&gt;</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">r2</th>
<th style="text-align: right;">adjr2</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">nobs</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">df.res</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">m3</td>
<td style="text-align: right;">0.0907079</td>
<td style="text-align: right;">0.0881984</td>
<td style="text-align: right;">6636.024</td>
<td style="text-align: right;">6681.525</td>
<td style="text-align: right;">1.105532</td>
<td style="text-align: right;">2181</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2174</td>
</tr>
<tr class="even">
<td style="text-align: left;">m4</td>
<td style="text-align: right;">0.0520082</td>
<td style="text-align: right;">0.0515731</td>
<td style="text-align: right;">6716.928</td>
<td style="text-align: right;">6733.990</td>
<td style="text-align: right;">1.127517</td>
<td style="text-align: right;">2181</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2179</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The larger model (model <code>m3</code>) has better results than model <code>m4</code> in the sense that it produces a larger adjusted <span class="math inline">\(R^2\)</span>, and smaller values for AIC, BIC and <span class="math inline">\(\sigma\)</span>. Based on this comparison within the training sample, we clearly prefer <code>m3</code>, since each model shows reasonable adherence to the assumptions of a linear regression model.</p>
</section>
<section id="testing-the-models-in-new-data" class="level3" data-number="5.3.9">
<h3 data-number="5.3.9" class="anchored" data-anchor-id="testing-the-models-in-new-data"><span class="header-section-number">5.3.9</span> Testing the models in new data</h3>
<p>At last we return to the <code>dat2_test</code> sample which was not used in fitting models <code>m3</code> and <code>m4</code> to investigate which of these models has better predictive results in new data. When doing this sort of testing, I recommend a look at the following 4 summaries, each of which is based on the fitted (predicted) and observed values of our outcome in our new data, using the models we want to compare:</p>
<ul>
<li>squared correlation of predicted with observed values (validated <span class="math inline">\(R^2\)</span>; higher values are better)</li>
<li>mean absolute prediction error (MAPE; smaller values indicate smaller errors, hence better prediction)</li>
<li>square root of the mean squared prediction error (RMSPE; again, smaller values indicate better predictions)</li>
<li>maximum (in absolute value) prediction error (Max Error)</li>
</ul>
<p>To obtain observed, predicted, and error (observed - predicted) values for each new data point when we apply model <code>m3</code>, we first use the <code>augment()</code> function from the <strong>broom</strong> package to obtain our <code>.fitted</code> values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>m3_test_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(m3, <span class="at">newdata =</span> dat2_test)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(m3_test_aug)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  SEQN   HSCRP PULSE1 PULSE2 SROH      HOSPITAL MEANPULSE .fitted .resid
  &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt;        &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1 109273  0.98     71     70 Good             0      70.5   0.839 -0.859
2 109293 15.1      62     64 Good             0      63     0.688  2.03 
3 109312  0.86     83     87 Very Good        0      85     0.835 -0.985
4 109332  2.29     63     63 Excellent        0      63     0.156  0.673
5 109340  4.64     78     78 Fair             0      78     1.10   0.437
6 109342  5.51     72     70 Good             0      71     0.849  0.858</code></pre>
</div>
</div>
<p>Remember, however, that our models <code>m3</code> and <code>m4</code> do not predict HSCRP, but rather the logarithm of HSCRP, so we need to exponentiate the .fitted values to get what we want.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>m3_test_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(m3, <span class="at">newdata =</span> dat2_test) <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fits =</span> <span class="fu">exp</span>(.fitted),</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">resid =</span> HSCRP <span class="sc">-</span> fits) <span class="sc">|&gt;</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, HSCRP, fits, resid, <span class="fu">everything</span>())</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(m3_test_aug)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  SEQN   HSCRP  fits resid PULSE1 PULSE2 SROH  HOSPITAL MEANPULSE .fitted .resid
  &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1 109273  0.98  2.31 -1.33     71     70 Good         0      70.5   0.839 -0.859
2 109293 15.1   1.99 13.1      62     64 Good         0      63     0.688  2.03 
3 109312  0.86  2.30 -1.44     83     87 Very…        0      85     0.835 -0.985
4 109332  2.29  1.17  1.12     63     63 Exce…        0      63     0.156  0.673
5 109340  4.64  3.00  1.64     78     78 Fair         0      78     1.10   0.437
6 109342  5.51  2.34  3.17     72     70 Good         0      71     0.849  0.858</code></pre>
</div>
</div>
<p>Now, we can obtain our summaries, as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>m3_test_results <span class="ot">&lt;-</span> m3_test_aug <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">validated_R_sq =</span> <span class="fu">cor</span>(HSCRP, fits)<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">MAPE =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(resid)),</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSPE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(resid<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_Error =</span> <span class="fu">max</span>(<span class="fu">abs</span>(resid)))</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>m3_test_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  validated_R_sq  MAPE RMSPE max_Error
           &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
1          0.114  3.45  10.7      177.</code></pre>
</div>
</div>
<p>For model <code>m4</code>, we have:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>m4_test_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(m4, <span class="at">newdata =</span> dat2_test) <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fits =</span> <span class="fu">exp</span>(.fitted),</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">resid =</span> HSCRP <span class="sc">-</span> fits) <span class="sc">|&gt;</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEQN, HSCRP, fits, resid, <span class="fu">everything</span>())</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>m4_test_results <span class="ot">&lt;-</span> m4_test_aug <span class="sc">|&gt;</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">validated_R_sq =</span> <span class="fu">cor</span>(HSCRP, fits)<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">MAPE =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(resid)),</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSPE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(resid<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_Error =</span> <span class="fu">max</span>(<span class="fu">abs</span>(resid)))</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>m4_test_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  validated_R_sq  MAPE RMSPE max_Error
           &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
1          0.102  3.50  10.8      177.</code></pre>
</div>
</div>
<p>And we can put the two sets of results together into a nice table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(m3_test_results, m4_test_results) <span class="sc">|&gt;</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="fu">c</span>(<span class="st">"m3"</span>, <span class="st">"m4"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(model) <span class="sc">|&gt;</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">validated_R_sq</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">RMSPE</th>
<th style="text-align: right;">max_Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">m3</td>
<td style="text-align: right;">0.1135858</td>
<td style="text-align: right;">3.451295</td>
<td style="text-align: right;">10.72894</td>
<td style="text-align: right;">176.9855</td>
</tr>
<tr class="even">
<td style="text-align: left;">m4</td>
<td style="text-align: right;">0.1015280</td>
<td style="text-align: right;">3.496673</td>
<td style="text-align: right;">10.79613</td>
<td style="text-align: right;">177.0716</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Based on these out-of-sample validation results, it seems that Model <code>m3</code> has the better results across each of these four summaries than Model 4 does.</p>
</section>
<section id="conclusions-1" class="level3" data-number="5.3.10">
<h3 data-number="5.3.10" class="anchored" data-anchor-id="conclusions-1"><span class="header-section-number">5.3.10</span> Conclusions</h3>
<p>We fit two models to predict HSCRP, a larger model (<code>m3</code>) containing three predictors (MEANPULSE, SROH and HOSPITAL), and a smaller model (<code>m4</code>) containing only the MEANPULSE as a predictor.</p>
<ul>
<li>Both models (after transforming to log(HSCRP) for our outcome) seem to generally meet the assumptions of linear regression</li>
<li>Model <code>m3</code> had a raw <span class="math inline">\(R^2\)</span> value of 0.091, so it accounted for about 9.1% of the variation in log(HSCRP) within our training sample. Model <code>m4</code> accounted for 5.2%.</li>
<li>In our in-sample checks, Model <code>m3</code> had better results in terms of adjusted <span class="math inline">\(R^2\)</span>, AIC, BIC and <span class="math inline">\(\sigma\)</span>.</li>
<li>In a validation (test) sample, our Model <code>m3</code> also showed superior predictive performance, including better results in terms of MAPE, RMSPE and maximum absolute error, as well as a validated <span class="math inline">\(R^2\)</span> of 11.4%, higher than model <code>m4</code>’s result of 10.2%.</li>
</ul>
<p>Overall, model <code>m3</code> seems like the meaningfully better choice.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./431review2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./smart.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>