<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Analysis of Covariance with the SMART data – Data Science for Biological, Medical and Health Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./nonlinearity.html" rel="next">
<link href="./ancova_emphysema.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-56845be1c3e1e64cc04b6f7b628b8285.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ancova_smart.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
        <div class="sidebar-tools-main">
    <a href="./Data-Science-for-Biological,-Medical-and-Health-Research.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinaloutcome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Time To Event / Survival Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lasso.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">NEW!! A Few LASSO Ideas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">NEW!! Bayes and a Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">NEW!! Bayes and a Logistic Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup-used-here" id="toc-r-setup-used-here" class="nav-link active" data-scroll-target="#r-setup-used-here"><span class="header-section-number">12.1</span> R Setup Used Here</a>
  <ul class="collapse">
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="header-section-number">12.1.1</span> Data Load</a></li>
  </ul></li>
  <li><a href="#a-new-small-study-predicting-bmi" id="toc-a-new-small-study-predicting-bmi" class="nav-link" data-scroll-target="#a-new-small-study-predicting-bmi"><span class="header-section-number">12.2</span> A New Small Study: Predicting BMI</a>
  <ul class="collapse">
  <li><a href="#does-smoke100-predict-bmi-well" id="toc-does-smoke100-predict-bmi-well" class="nav-link" data-scroll-target="#does-smoke100-predict-bmi-well"><span class="header-section-number">12.2.1</span> Does <code>smoke100</code> predict <code>bmi</code> well?</a></li>
  </ul></li>
  <li><a href="#mod1-a-simple-t-test-model" id="toc-mod1-a-simple-t-test-model" class="nav-link" data-scroll-target="#mod1-a-simple-t-test-model"><span class="header-section-number">12.3</span> <code>mod1</code>: A simple t-test model</a></li>
  <li><a href="#mod2-adding-another-predictor-two-way-anova-without-interaction" id="toc-mod2-adding-another-predictor-two-way-anova-without-interaction" class="nav-link" data-scroll-target="#mod2-adding-another-predictor-two-way-anova-without-interaction"><span class="header-section-number">12.4</span> <code>mod2</code>: Adding another predictor (two-way ANOVA without interaction)</a></li>
  <li><a href="#mod3-adding-the-interaction-term-two-way-anova-with-interaction" id="toc-mod3-adding-the-interaction-term-two-way-anova-with-interaction" class="nav-link" data-scroll-target="#mod3-adding-the-interaction-term-two-way-anova-with-interaction"><span class="header-section-number">12.5</span> <code>mod3</code>: Adding the interaction term (Two-way ANOVA with interaction)</a></li>
  <li><a href="#mod4-using-smoke100-and-physhealth-in-a-model-for-bmi" id="toc-mod4-using-smoke100-and-physhealth-in-a-model-for-bmi" class="nav-link" data-scroll-target="#mod4-using-smoke100-and-physhealth-in-a-model-for-bmi"><span class="header-section-number">12.6</span> <code>mod4</code>: Using <code>smoke100</code> and <code>physhealth</code> in a model for <code>bmi</code></a></li>
  <li><a href="#making-predictions-with-a-linear-regression-model" id="toc-making-predictions-with-a-linear-regression-model" class="nav-link" data-scroll-target="#making-predictions-with-a-linear-regression-model"><span class="header-section-number">12.7</span> Making Predictions with a Linear Regression Model</a>
  <ul class="collapse">
  <li><a href="#fitting-an-individual-prediction-and-95-prediction-interval" id="toc-fitting-an-individual-prediction-and-95-prediction-interval" class="nav-link" data-scroll-target="#fitting-an-individual-prediction-and-95-prediction-interval"><span class="header-section-number">12.7.1</span> Fitting an Individual Prediction and 95% Prediction Interval</a></li>
  <li><a href="#confidence-interval-for-an-average-prediction" id="toc-confidence-interval-for-an-average-prediction" class="nav-link" data-scroll-target="#confidence-interval-for-an-average-prediction"><span class="header-section-number">12.7.2</span> Confidence Interval for an Average Prediction</a></li>
  <li><a href="#fitting-multiple-individual-predictions-to-new-data" id="toc-fitting-multiple-individual-predictions-to-new-data" class="nav-link" data-scroll-target="#fitting-multiple-individual-predictions-to-new-data"><span class="header-section-number">12.7.3</span> Fitting Multiple Individual Predictions to New Data</a></li>
  </ul></li>
  <li><a href="#centering-the-model" id="toc-centering-the-model" class="nav-link" data-scroll-target="#centering-the-model"><span class="header-section-number">12.8</span> Centering the model</a>
  <ul class="collapse">
  <li><a href="#plot-of-model-4-on-centered-physhealth-mod4_c" id="toc-plot-of-model-4-on-centered-physhealth-mod4_c" class="nav-link" data-scroll-target="#plot-of-model-4-on-centered-physhealth-mod4_c"><span class="header-section-number">12.8.1</span> Plot of Model 4 on Centered <code>physhealth</code>: <code>mod4_c</code></a></li>
  </ul></li>
  <li><a href="#rescaling-an-input-by-subtracting-the-mean-and-dividing-by-2-standard-deviations" id="toc-rescaling-an-input-by-subtracting-the-mean-and-dividing-by-2-standard-deviations" class="nav-link" data-scroll-target="#rescaling-an-input-by-subtracting-the-mean-and-dividing-by-2-standard-deviations"><span class="header-section-number">12.9</span> Rescaling an input by subtracting the mean and dividing by 2 standard deviations</a>
  <ul class="collapse">
  <li><a href="#refitting-model-mod4-to-the-rescaled-data" id="toc-refitting-model-mod4-to-the-rescaled-data" class="nav-link" data-scroll-target="#refitting-model-mod4-to-the-rescaled-data"><span class="header-section-number">12.9.1</span> Refitting model <code>mod4</code> to the rescaled data</a></li>
  <li><a href="#interpreting-the-model-on-rescaled-data" id="toc-interpreting-the-model-on-rescaled-data" class="nav-link" data-scroll-target="#interpreting-the-model-on-rescaled-data"><span class="header-section-number">12.9.2</span> Interpreting the model on rescaled data</a></li>
  <li><a href="#plot-of-model-on-rescaled-data" id="toc-plot-of-model-on-rescaled-data" class="nav-link" data-scroll-target="#plot-of-model-on-rescaled-data"><span class="header-section-number">12.9.3</span> Plot of model on rescaled data</a></li>
  </ul></li>
  <li><a href="#mod5-what-if-we-add-more-variables" id="toc-mod5-what-if-we-add-more-variables" class="nav-link" data-scroll-target="#mod5-what-if-we-add-more-variables"><span class="header-section-number">12.10</span> <code>mod5</code>: What if we add more variables?</a></li>
  <li><a href="#mod6-would-adding-self-reported-health-help" id="toc-mod6-would-adding-self-reported-health-help" class="nav-link" data-scroll-target="#mod6-would-adding-self-reported-health-help"><span class="header-section-number">12.11</span> <code>mod6</code>: Would adding self-reported health help?</a></li>
  <li><a href="#key-regression-assumptions-for-building-effective-prediction-models" id="toc-key-regression-assumptions-for-building-effective-prediction-models" class="nav-link" data-scroll-target="#key-regression-assumptions-for-building-effective-prediction-models"><span class="header-section-number">12.12</span> Key Regression Assumptions for Building Effective Prediction Models</a>
  <ul class="collapse">
  <li><a href="#checking-assumptions-in-model-mod6" id="toc-checking-assumptions-in-model-mod6" class="nav-link" data-scroll-target="#checking-assumptions-in-model-mod6"><span class="header-section-number">12.12.1</span> Checking Assumptions in model <code>mod6</code></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this chapter, we’ll work with the <code>smart_cle1_sh</code> data file that we developed in <a href="singleimputation.html" class="quarto-xref"><span>Chapter 7</span></a>.</p>
<section id="r-setup-used-here" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="r-setup-used-here"><span class="header-section-number">12.1</span> R Setup Used Here</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="data-load" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="data-load"><span class="header-section-number">12.1.1</span> Data Load</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/smart_cle1_sh.Rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="a-new-small-study-predicting-bmi" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="a-new-small-study-predicting-bmi"><span class="header-section-number">12.2</span> A New Small Study: Predicting BMI</h2>
<p>We’ll begin by investigating the problem of predicting <code>bmi</code>, at first with just three regression inputs: <code>smoke100</code>, <code>female</code> and <code>physhealth</code>, in our <code>smart_cle1_sh</code> data set.</p>
<ul>
<li>The outcome of interest is <code>bmi</code>.</li>
<li>Inputs to the regression model are:
<ul>
<li><code>smoke100</code> = 1 if the subject has smoked 100 cigarettes in their lifetime</li>
<li><code>female</code> = 1 if the subject is female, and 0 if they are male</li>
<li><code>physhealth</code> = number of poor physical health days in past 30 (treated as quantitative)</li>
</ul></li>
</ul>
<section id="does-smoke100-predict-bmi-well" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="does-smoke100-predict-bmi-well"><span class="header-section-number">12.2.1</span> Does <code>smoke100</code> predict <code>bmi</code> well?</h3>
<section id="graphical-assessment" class="level4" data-number="12.2.1.1">
<h4 data-number="12.2.1.1" class="anchored" data-anchor-id="graphical-assessment"><span class="header-section-number">12.2.1.1</span> Graphical Assessment</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> smoke100, <span class="at">y =</span> bmi)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Not so helpful. We should probably specify that <code>smoke100</code> is a factor, and try another plotting approach.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(smoke100), <span class="at">y =</span> bmi)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The median BMI looks a little higher for those who have smoked 100 cigarettes. Let’s see if a model reflects that.</p>
</section>
</section>
</section>
<section id="mod1-a-simple-t-test-model" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="mod1-a-simple-t-test-model"><span class="header-section-number">12.3</span> <code>mod1</code>: A simple t-test model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> smoke100, <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>mod1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ smoke100, data = smart_cle1_sh)

Coefficients:
(Intercept)     smoke100  
    27.9150       0.8996  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ smoke100, data = smart_cle1_sh)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.515  -3.995  -0.844   2.865  41.745 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  27.9150     0.2624 106.387   &lt;2e-16 ***
smoke100      0.8996     0.3776   2.382   0.0174 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.352 on 1131 degrees of freedom
Multiple R-squared:  0.004993,  Adjusted R-squared:  0.004113 
F-statistic: 5.675 on 1 and 1131 DF,  p-value: 0.01737</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) 27.4001291 28.429781
smoke100     0.1586812  1.640556</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mod1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   27.9       0.262    106.    0        27.4       28.4 
2 smoke100       0.900     0.378      2.38  0.0174    0.159      1.64</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1   0.00499       0.00411  6.35      5.68  0.0174     1 -3701. 7409. 7424.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>The model suggests, based on these 1133 subjects, that</p>
<ul>
<li>our best prediction for non-smokers is BMI = 27.94 kg/m<sup>2</sup>, and</li>
<li>our best prediction for those who have smoked 100 cigarettes is BMI = 27.94 + 0.87 = 28.81 kg/m<sup>2</sup>.</li>
<li>the mean difference between smokers and non-smokers is +0.87 kg/m<sup>2</sup> in BMI</li>
<li>a 95% confidence (uncertainty) interval for that mean smoker - non-smoker difference in BMI ranges from 0.13 to 1.61</li>
<li>the model accounts for 0.47% of the variation in BMI, so that knowing the respondent’s tobacco status does very little to reduce the size of the prediction errors as compared to an intercept only model that would predict the overall mean BMI for each of our subjects.</li>
<li>the model makes some enormous errors, with one subject being predicted to have a BMI 42 points lower than his/her actual BMI.</li>
</ul>
<p>Note that this simple regression model just gives us the t-test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bmi <span class="sc">~</span> smoke100, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">data =</span> smart_cle1_sh)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  bmi by smoke100
t = -2.3823, df = 1131, p-value = 0.01737
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -1.6405563 -0.1586812
sample estimates:
mean in group 0 mean in group 1 
       27.91495        28.81457 </code></pre>
</div>
</div>
</section>
<section id="mod2-adding-another-predictor-two-way-anova-without-interaction" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="mod2-adding-another-predictor-two-way-anova-without-interaction"><span class="header-section-number">12.4</span> <code>mod2</code>: Adding another predictor (two-way ANOVA without interaction)</h2>
<p>When we add in the information about <code>female</code> (sex) to our original model, we might first picture the data. We could look at separate histograms,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> bmi)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(female <span class="sc">~</span> smoke100, <span class="at">labeller =</span> label_both)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>or maybe boxplots?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(female), <span class="at">y =</span> bmi)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> smoke100, <span class="at">labeller =</span> label_both)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> female, <span class="at">y =</span> bmi))<span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> smoke100, <span class="at">labeller =</span> label_both)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>OK. Let’s try fitting a model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> female <span class="sc">+</span> smoke100, <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mod2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ female + smoke100, data = smart_cle1_sh)

Coefficients:
(Intercept)       female     smoke100  
    28.0101      -0.1479       0.8842  </code></pre>
</div>
</div>
<p>This new model predicts only four predicted values:</p>
<ul>
<li><code>bmi</code> = 28.0265 if the subject is male and has not smoked 100 cigarettes (so <code>female</code> = 0 and <code>smoke100</code> = 0)</li>
<li><code>bmi</code> = 28.0265 - 0.1342 = 27.8923 if the subject is female and has not smoked 100 cigarettes (<code>female</code> = 1 and <code>smoke100</code> = 0)</li>
<li><code>bmi</code> = 28.0265 + 0.8555 = 28.8820 if the subject is male and has smoked 100 cigarettes (so <code>female</code> = 0 and <code>smoke100</code> = 1), and, finally</li>
<li><code>bmi</code> = 28.0265 - 0.1342 + 0.8555 = 28.7478 if the subject is female and has smoked 100 cigarettes (so both <code>female</code> and <code>smoke100</code> = 1).</li>
</ul>
<p>Another way to put this is that for those who have not smoked 100 cigarettes, the model is:</p>
<ul>
<li><code>bmi</code> = 28.0265 - 0.1342 <code>female</code></li>
</ul>
<p>and for those who have smoked 100 cigarettes, the model is:</p>
<ul>
<li><code>bmi</code> = 28.8820 - 0.1342 <code>female</code></li>
</ul>
<p>Only the intercept of the <code>bmi-female</code> model changes depending on <code>smoke100</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ female + smoke100, data = smart_cle1_sh)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.446  -3.960  -0.854   2.790  41.666 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  28.0101     0.3615  77.475   &lt;2e-16 ***
female       -0.1479     0.3864  -0.383   0.7019    
smoke100      0.8842     0.3799   2.327   0.0201 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.354 on 1130 degrees of freedom
Multiple R-squared:  0.005122,  Adjusted R-squared:  0.003361 
F-statistic: 2.909 on 2 and 1130 DF,  p-value: 0.05495</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %     97.5 %
(Intercept) 27.3007728 28.7194992
female      -0.9061739  0.6102793
smoke100     0.1388225  1.6296303</code></pre>
</div>
</div>
<p>The slopes of both <code>female</code> and <code>smoke100</code> have confidence intervals that are completely below zero, indicating that both <code>female</code> sex and <code>smoke100</code> appear to be associated with reductions in <code>bmi</code>.</p>
<p>The <span class="math inline">\(R^2\)</span> value suggests that 0.4788% of the variation in <code>bmi</code> is accounted for by this ANOVA model.</p>
<p>In fact, this regression (on two binary indicator variables) is simply a two-way ANOVA model without an interaction term.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bmi
            Df Sum Sq Mean Sq F value  Pr(&gt;F)  
female       1     16  16.163  0.4003 0.52705  
smoke100     1    219 218.721  5.4171 0.02012 *
Residuals 1130  45625  40.376                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="mod3-adding-the-interaction-term-two-way-anova-with-interaction" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="mod3-adding-the-interaction-term-two-way-anova-with-interaction"><span class="header-section-number">12.5</span> <code>mod3</code>: Adding the interaction term (Two-way ANOVA with interaction)</h2>
<p>Suppose we want to let the effect of <code>female</code> vary depending on the <code>smoke100</code> status. Then we need to incorporate an interaction term in our model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> female <span class="sc">*</span> smoke100, <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>mod3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ female * smoke100, data = smart_cle1_sh)

Coefficients:
    (Intercept)           female         smoke100  female:smoke100  
        28.2687          -0.5499           0.4112           0.7996  </code></pre>
</div>
</div>
<p>So, for example, for a male who has smoked 100 cigarettes, this model predicts</p>
<ul>
<li><code>bmi</code> = 28.269 - 0.506 (0) + 0.412 (1) + 0.754 (0)(1) = 28.269 + 0.412 = 28.681</li>
</ul>
<p>And for a female who has smoked 100 cigarettes, the model predicts</p>
<ul>
<li><code>bmi</code> = 28.269 - 0.506 (1) + 0.412 (1) + 0.754 (1)(1) = 28.269 - 0.506 + 0.412 + 0.754 = 28.929</li>
</ul>
<p>For those who have not smoked 100 cigarettes, the model is:</p>
<ul>
<li><code>bmi</code> = 28.269 - 0.506 <code>female</code></li>
</ul>
<p>But for those who have smoked 100 cigarettes, the model is:</p>
<ul>
<li><code>bmi</code> = (28.269 + 0.412) + (-0.506 + 0.754) <code>female</code>, or ,,,</li>
<li><code>bmi</code> = 28.681 - 0.248 <code>female</code></li>
</ul>
<p>Now, both the slope and the intercept of the <code>bmi-female</code> model change depending on <code>smoke100</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ female * smoke100, data = smart_cle1_sh)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.630  -3.939  -0.879   2.760  41.880 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      28.2687     0.4395  64.318   &lt;2e-16 ***
female           -0.5499     0.5480  -1.004    0.316    
smoke100          0.4112     0.5945   0.692    0.489    
female:smoke100   0.7996     0.7729   1.035    0.301    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.354 on 1129 degrees of freedom
Multiple R-squared:  0.006064,  Adjusted R-squared:  0.003423 
F-statistic: 2.296 on 3 and 1129 DF,  p-value: 0.07614</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     2.5 %     97.5 %
(Intercept)     27.4063786 29.1310929
female          -1.6250493  0.5252321
smoke100        -0.7552196  1.5775258
female:smoke100 -0.7167828  2.3160753</code></pre>
</div>
</div>
<p>In fact, this regression (on two binary indicator variables and a product term) is simply a two-way ANOVA model with an interaction term.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bmi
                  Df Sum Sq Mean Sq F value  Pr(&gt;F)  
female             1     16  16.163  0.4003 0.52704  
smoke100           1    219 218.721  5.4175 0.02011 *
female:smoke100    1     43  43.219  1.0705 0.30106  
Residuals       1129  45581  40.373                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The interaction term doesn’t change very much here. Its uncertainty interval includes zero, and the overall model still accounts for less than 1% of the variation in <code>bmi</code>.</p>
</section>
<section id="mod4-using-smoke100-and-physhealth-in-a-model-for-bmi" class="level2" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="mod4-using-smoke100-and-physhealth-in-a-model-for-bmi"><span class="header-section-number">12.6</span> <code>mod4</code>: Using <code>smoke100</code> and <code>physhealth</code> in a model for <code>bmi</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> physhealth, <span class="at">y =</span> bmi, <span class="at">color =</span> <span class="fu">factor</span>(smoke100))) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">col =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> smoke100, <span class="at">labeller =</span> label_both) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Does the difference in slopes of <code>bmi</code> and <code>physhealth</code> for those who have and haven’t smoked at least 100 cigarettes appear to be substantial and important?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> smoke100 <span class="sc">*</span> physhealth, <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ smoke100 * physhealth, data = smart_cle1_sh)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.800  -3.785  -0.596   2.615  38.460 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         27.48538    0.28609  96.073  &lt; 2e-16 ***
smoke100             0.63964    0.41697   1.534 0.125302    
physhealth           0.10617    0.03026   3.509 0.000467 ***
smoke100:physhealth  0.02631    0.04084   0.644 0.519497    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.259 on 1129 degrees of freedom
Multiple R-squared:  0.03544,   Adjusted R-squared:  0.03288 
F-statistic: 13.83 on 3 and 1129 DF,  p-value: 7.37e-09</code></pre>
</div>
</div>
<p>Does it seem as though the addition of <code>physhealth</code> has improved our model substantially over a model with <code>smoke100</code> alone (which, you recall, was <code>mod1</code>)?</p>
<p>Since the <code>mod4</code> model contains the <code>mod1</code> model’s predictors as a subset and the outcome is the same for each model, we consider the models <em>nested</em> and have some extra tools available to compare them.</p>
<ul>
<li>I might start by looking at the basic summaries for each model.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(mod4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic       p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    0.0354        0.0329  6.26      13.8 0.00000000737     3 -3684. 7377. 7403.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1   0.00499       0.00411  6.35      5.68  0.0174     1 -3701. 7409. 7424.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<ul>
<li>The <span class="math inline">\(R^2\)</span> is much larger for the model with <code>physhealth</code>, but still very tiny.</li>
<li>Smaller AIC and smaller BIC statistics are more desirable. Here, there’s little to choose from, so <code>mod4</code> looks better, too.</li>
<li>We might also consider a significance test by looking at an ANOVA model comparison. This is only appropriate because <code>mod1</code> is nested in <code>mod4</code>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod4, mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: bmi ~ smoke100 * physhealth
Model 2: bmi ~ smoke100
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1129 44234                                  
2   1131 45630 -2   -1396.3 17.819 2.405e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The addition of the <code>physhealth</code> term appears to be an improvement, not that that means very much.</p>
</section>
<section id="making-predictions-with-a-linear-regression-model" class="level2" data-number="12.7">
<h2 data-number="12.7" class="anchored" data-anchor-id="making-predictions-with-a-linear-regression-model"><span class="header-section-number">12.7</span> Making Predictions with a Linear Regression Model</h2>
<p>Recall model 4, which yields predictions for body mass index on the basis of the main effects of having smoked (<code>smoke100</code>) and days of poor physical health (<code>physhealth</code>) and their interaction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>mod4</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ smoke100 * physhealth, data = smart_cle1_sh)

Coefficients:
        (Intercept)             smoke100           physhealth  
           27.48538              0.63964              0.10617  
smoke100:physhealth  
            0.02631  </code></pre>
</div>
</div>
<section id="fitting-an-individual-prediction-and-95-prediction-interval" class="level3" data-number="12.7.1">
<h3 data-number="12.7.1" class="anchored" data-anchor-id="fitting-an-individual-prediction-and-95-prediction-interval"><span class="header-section-number">12.7.1</span> Fitting an Individual Prediction and 95% Prediction Interval</h3>
<p>What do we predict for the <code>bmi</code> of a subject who has smoked at least 100 cigarettes in their life and had 8 poor physical health days in the past 30?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>new1 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">smoke100 =</span> <span class="dv">1</span>, <span class="at">physhealth =</span> <span class="dv">8</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod4, <span class="at">newdata =</span> new1, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 29.18491 16.89142 41.47839</code></pre>
</div>
</div>
<p>The predicted <code>bmi</code> for this new subject is shown above. The prediction interval shows the bounds of a 95% uncertainty interval for a predicted <code>bmi</code> for an individual smoker<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> who has 8 days of poor physical health out of the past 30. From the <code>predict</code> function applied to a linear model, we can get the prediction intervals for any new data points in this manner.</p>
</section>
<section id="confidence-interval-for-an-average-prediction" class="level3" data-number="12.7.2">
<h3 data-number="12.7.2" class="anchored" data-anchor-id="confidence-interval-for-an-average-prediction"><span class="header-section-number">12.7.2</span> Confidence Interval for an Average Prediction</h3>
<ul>
<li>What do we predict for the <strong>average body mass index of a population of subjects</strong> who are smokers and have <code>physhealth = 8</code>?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod4, <span class="at">newdata =</span> new1, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 29.18491 28.63866 29.73115</code></pre>
</div>
</div>
<ul>
<li>How does this result compare to the prediction interval?</li>
</ul>
</section>
<section id="fitting-multiple-individual-predictions-to-new-data" class="level3" data-number="12.7.3">
<h3 data-number="12.7.3" class="anchored" data-anchor-id="fitting-multiple-individual-predictions-to-new-data"><span class="header-section-number">12.7.3</span> Fitting Multiple Individual Predictions to New Data</h3>
<ul>
<li>How does our prediction change for a respondent if they instead have 7, or 9 poor physical health days? What if they have or don’t have a history of smoking?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>c8_new2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">subjectid =</span> <span class="dv">1001</span><span class="sc">:</span><span class="dv">1006</span>, <span class="at">smoke100 =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="at">physhealth =</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>))</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>pred2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod4, <span class="at">newdata =</span> c8_new2, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>result2 <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(c8_new2, pred2)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>result2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  subjectid smoke100 physhealth   fit   lwr   upr
      &lt;int&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1      1001        1          7  29.1  16.8  41.3
2      1002        1          8  29.2  16.9  41.5
3      1003        1          9  29.3  17.0  41.6
4      1004        0          7  28.2  15.9  40.5
5      1005        0          8  28.3  16.0  40.6
6      1006        0          9  28.4  16.1  40.7</code></pre>
</div>
</div>
<p>The <code>result2</code> tibble contains predictions for each scenario.</p>
<ul>
<li>Which has a bigger impact on these predictions and prediction intervals? A one category change in <code>smoke100</code> or a one hour change in <code>physhealth</code>?</li>
</ul>
</section>
</section>
<section id="centering-the-model" class="level2" data-number="12.8">
<h2 data-number="12.8" class="anchored" data-anchor-id="centering-the-model"><span class="header-section-number">12.8</span> Centering the model</h2>
<p>Our model <code>mod4</code> has four predictors (the constant, <code>physhealth</code>, <code>smoke100</code> and their interaction) but just two inputs (<code>smoke100</code> and <code>physhealth</code>.) If we <strong>center</strong> the quantitative input <code>physhealth</code> before building the model, we get a more interpretable interaction term.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh_c <span class="ot">&lt;-</span> smart_cle1_sh <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">physhealth_c =</span> physhealth <span class="sc">-</span> <span class="fu">mean</span>(physhealth))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>mod4_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> smoke100 <span class="sc">*</span> physhealth_c, <span class="at">data =</span> smart_cle1_sh_c)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4_c)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ smoke100 * physhealth_c, data = smart_cle1_sh_c)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.800  -3.785  -0.596   2.615  38.460 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           27.97435    0.25913 107.956  &lt; 2e-16 ***
smoke100               0.76083    0.37289   2.040 0.041544 *  
physhealth_c           0.10617    0.03026   3.509 0.000467 ***
smoke100:physhealth_c  0.02631    0.04084   0.644 0.519497    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.259 on 1129 degrees of freedom
Multiple R-squared:  0.03544,   Adjusted R-squared:  0.03288 
F-statistic: 13.83 on 3 and 1129 DF,  p-value: 7.37e-09</code></pre>
</div>
</div>
<p>What has changed as compared to the original <code>mod4</code>?</p>
<ul>
<li>Our original model was <code>bmi</code> = 27.5 + 0.57 <code>smoke100</code> + 0.11 <code>physhealth</code> - 0.03 <code>smoke100</code> x <code>physhealth</code></li>
<li>Our new model is <code>bmi</code> = 28.0 + 0.73 <code>smoke100</code> + 0.11 centered <code>physhealth</code> + 0.03 <code>smoke100</code> x centered <code>physhealth</code>.</li>
</ul>
<p>So our new model on centered data is:</p>
<ul>
<li>28.0 + 0.11 centered <code>physhealth_c</code> for non-smokers, and</li>
<li>(28.0 + 0.73) + (0.11 - 0.03) centered <code>physhealth_c</code>, or 28.73 + 0.08 centered <code>physhealth_c</code> for smokers.</li>
</ul>
<p>In our new (centered <code>physhealth_c</code>) model,</p>
<ul>
<li>the main effect of <code>smoke100</code> now corresponds to a predictive difference (smoker - non-smoker) in <code>bmi</code> with <code>physhealth</code> at its mean value, 4.68 days,</li>
<li>the intercept term is now the predicted <code>bmi</code> for a non-smoker with an average <code>physhealth</code>, and</li>
<li>the product term corresponds to the change in the slope of centered <code>physhealth_c</code> on <code>bmi</code> for a smoker rather than a non-smoker, while</li>
<li>the residual standard deviation and the R-squared values remain unchanged from the model before centering.</li>
</ul>
<section id="plot-of-model-4-on-centered-physhealth-mod4_c" class="level3" data-number="12.8.1">
<h3 data-number="12.8.1" class="anchored" data-anchor-id="plot-of-model-4-on-centered-physhealth-mod4_c"><span class="header-section-number">12.8.1</span> Plot of Model 4 on Centered <code>physhealth</code>: <code>mod4_c</code></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh_c, <span class="fu">aes</span>(<span class="at">x =</span> physhealth_c, <span class="at">y =</span> bmi, <span class="at">group =</span> smoke100, <span class="at">col =</span> <span class="fu">factor</span>(smoke100))) <span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">formula =</span> y <span class="sc">~</span> x) <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">color =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Poor Physical Health Days, centered"</span>, <span class="at">y =</span> <span class="st">"Body Mass Index"</span>,</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Model `mod4` on centered data"</span>) <span class="sc">+</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> smoke100, <span class="at">labeller =</span> label_both)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="rescaling-an-input-by-subtracting-the-mean-and-dividing-by-2-standard-deviations" class="level2" data-number="12.9">
<h2 data-number="12.9" class="anchored" data-anchor-id="rescaling-an-input-by-subtracting-the-mean-and-dividing-by-2-standard-deviations"><span class="header-section-number">12.9</span> Rescaling an input by subtracting the mean and dividing by 2 standard deviations</h2>
<p>Centering helped us interpret the main effects in the regression, but it still leaves a scaling problem.</p>
<ul>
<li>The <code>smoke100</code> coefficient estimate is much larger than that of <code>physhealth</code>, but this is misleading, considering that we are comparing the complete change in one variable (smoking or not) to a 1-day change in <code>physhealth</code>.</li>
<li><span class="citation" data-cites="GelmanHill2007">Gelman and Hill (<a href="references.html#ref-GelmanHill2007" role="doc-biblioref">2007</a>)</span> recommend all continuous predictors be scaled by dividing by 2 standard deviations, so that:
<ul>
<li>a 1-unit change in the rescaled predictor corresponds to a change from 1 standard deviation below the mean, to 1 standard deviation above.</li>
<li>an unscaled binary (1/0) predictor with 50% probability of occurring will be exactly comparable to a rescaled continuous predictor done in this way.</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh_rescale <span class="ot">&lt;-</span> smart_cle1_sh <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">physhealth_z =</span> (physhealth <span class="sc">-</span> <span class="fu">mean</span>(physhealth))<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(physhealth)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="refitting-model-mod4-to-the-rescaled-data" class="level3" data-number="12.9.1">
<h3 data-number="12.9.1" class="anchored" data-anchor-id="refitting-model-mod4-to-the-rescaled-data"><span class="header-section-number">12.9.1</span> Refitting model <code>mod4</code> to the rescaled data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>mod4_z <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> smoke100 <span class="sc">*</span> physhealth_z, <span class="at">data =</span> smart_cle1_sh_rescale)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4_z)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ smoke100 * physhealth_z, data = smart_cle1_sh_rescale)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.800  -3.785  -0.596   2.615  38.460 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            27.9743     0.2591 107.956  &lt; 2e-16 ***
smoke100                0.7608     0.3729   2.040 0.041544 *  
physhealth_z            1.9477     0.5550   3.509 0.000467 ***
smoke100:physhealth_z   0.4827     0.7492   0.644 0.519497    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.259 on 1129 degrees of freedom
Multiple R-squared:  0.03544,   Adjusted R-squared:  0.03288 
F-statistic: 13.83 on 3 and 1129 DF,  p-value: 7.37e-09</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-model-on-rescaled-data" class="level3" data-number="12.9.2">
<h3 data-number="12.9.2" class="anchored" data-anchor-id="interpreting-the-model-on-rescaled-data"><span class="header-section-number">12.9.2</span> Interpreting the model on rescaled data</h3>
<p>What has changed as compared to the original <code>mod4</code>?</p>
<ul>
<li>Our original model was <code>bmi</code> = 27.5 + 0.57 <code>smoke100</code> + 0.11 <code>physhealth</code> + 0.03 <code>smoke100</code> x <code>physhealth</code></li>
<li>Our model on centered <code>physhealth</code> was <code>bmi</code> = 28.0 + 0.73 <code>smoke100</code> + 0.11 centered <code>physhealth</code> + 0.03 <code>smoke100</code> x centered <code>physhealth</code>.</li>
<li>Our new model on rescaled <code>physhealth</code> is <code>bmi</code> = 28.0 + 0.73 <code>smoke100</code> + 1.98 rescaled <code>physhealth</code> + 0.61 <code>smoke100</code> x rescaled <code>physhealth</code></li>
</ul>
<p>So our rescaled model is:</p>
<ul>
<li>28.0 + 1.98 rescaled <code>physhealth_z</code> for non-smokers, and</li>
<li>(28.0 + 0.73) + (1.98 + 0.61) rescaled <code>physhealth_z</code>, or 28.73 + 2.59 rescaled <code>physhealth_z</code> for smokers.</li>
</ul>
<p>In this new rescaled (<code>physhealth_z</code>) model, then,</p>
<ul>
<li>the main effect of <code>smoke100</code>, 0.73, still corresponds to a predictive difference (smoker - non-smoker) in <code>bmi</code> with <code>physhealth</code> at its mean value, 4.68 days,</li>
<li>the intercept term is still the predicted <code>bmi</code> for a non-smoker with an average <code>physhealth</code> count, and</li>
<li>the residual standard deviation and the R-squared values remain unchanged,</li>
</ul>
<p>as before, but now we also have that:</p>
<ul>
<li>the coefficient of <code>physhealth_z</code> indicates the predictive difference in <code>bmi</code> associated with a change in <code>physhealth</code> of 2 standard deviations (from one standard deviation below the mean of 4.68 to one standard deviation above 4.68.)
<ul>
<li>Since the standard deviation of <code>physhealth</code> is 9.12 (see below), this covers a massive range of potential values of <code>physhealth</code> from 0 all the way up to 4.68 + 2(9.12) = 22.92 days.</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span> physhealth, <span class="at">data =</span> smart_cle1_sh)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> min Q1 median Q3 max     mean       sd    n missing
   0  0      0  3  30 4.605472 9.172505 1133       0</code></pre>
</div>
</div>
<ul>
<li>the coefficient of the product term (0.61) corresponds to the change in the coefficient of <code>physhealth_z</code> for smokers as compared to non-smokers.</li>
</ul>
</section>
<section id="plot-of-model-on-rescaled-data" class="level3" data-number="12.9.3">
<h3 data-number="12.9.3" class="anchored" data-anchor-id="plot-of-model-on-rescaled-data"><span class="header-section-number">12.9.3</span> Plot of model on rescaled data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh_rescale, <span class="fu">aes</span>(<span class="at">x =</span> physhealth_z, <span class="at">y =</span> bmi, </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">group =</span> smoke100, <span class="at">col =</span> <span class="fu">factor</span>(smoke100))) <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_discrete</span>(<span class="at">name =</span> <span class="st">"Is subject a smoker?"</span>) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Poor Physical Health Days, standardized (2 sd)"</span>, <span class="at">y =</span> <span class="st">"Body Mass Index"</span>,</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Model `mod4_z` on rescaled data"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There’s very little difference here.</p>
</section>
</section>
<section id="mod5-what-if-we-add-more-variables" class="level2" data-number="12.10">
<h2 data-number="12.10" class="anchored" data-anchor-id="mod5-what-if-we-add-more-variables"><span class="header-section-number">12.10</span> <code>mod5</code>: What if we add more variables?</h2>
<p>We can boost our <span class="math inline">\(R^2\)</span> a bit, to nearly 5%, by adding in two new variables, related to whether or not the subject (in the past 30 days) used the internet, and the average number of alcoholic drinks per week consumed by ths subject.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>mod5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> smoke100 <span class="sc">+</span> female <span class="sc">+</span>physhealth <span class="sc">+</span> internet30 <span class="sc">+</span> drinks_wk,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ smoke100 + female + physhealth + internet30 + 
    drinks_wk, data = smart_cle1_sh)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.271  -3.841  -0.723   2.654  38.187 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 27.59416    0.55756  49.491  &lt; 2e-16 ***
smoke100     0.85750    0.37612   2.280  0.02280 *  
female      -0.44346    0.38471  -1.153  0.24928    
physhealth   0.11875    0.02060   5.765 1.05e-08 ***
internet30   0.38241    0.48782   0.784  0.43326    
drinks_wk   -0.10307    0.03352  -3.074  0.00216 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.238 on 1127 degrees of freedom
Multiple R-squared:  0.04373,   Adjusted R-squared:  0.03949 
F-statistic: 10.31 on 5 and 1127 DF,  p-value: 1.114e-09</code></pre>
</div>
</div>
<ol type="1">
<li>Here’s the ANOVA for this model. What can we study with this?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bmi
             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
smoke100      1    229  228.97  5.8842   0.01543 *  
female        1      6    5.92  0.1521   0.69663    
physhealth    1   1394 1393.62 35.8147 2.912e-09 ***
internet30    1      9    9.26  0.2379   0.62586    
drinks_wk     1    368  367.80  9.4521   0.00216 ** 
Residuals  1127  43854   38.91                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Consider the revised output below. Now what can we study?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(bmi <span class="sc">~</span> smoke100 <span class="sc">+</span> internet30 <span class="sc">+</span> drinks_wk <span class="sc">+</span> female <span class="sc">+</span> physhealth,</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> smart_cle1_sh))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bmi
             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
smoke100      1    229  228.97  5.8842 0.0154334 *  
internet30    1      8    8.38  0.2155 0.6426003    
drinks_wk     1    440  439.87 11.3042 0.0007993 ***
female        1     35   34.92  0.8973 0.3437094    
physhealth    1   1293 1293.42 33.2397 1.051e-08 ***
Residuals  1127  43854   38.91                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>What does the output below let us conclude?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(bmi <span class="sc">~</span> smoke100 <span class="sc">+</span> internet30 <span class="sc">+</span> drinks_wk <span class="sc">+</span> female <span class="sc">+</span> physhealth, </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> smart_cle1_sh),</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">lm</span>(bmi <span class="sc">~</span> smoke100 <span class="sc">+</span> female <span class="sc">+</span> drinks_wk, </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> smart_cle1_sh))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: bmi ~ smoke100 + internet30 + drinks_wk + female + physhealth
Model 2: bmi ~ smoke100 + female + drinks_wk
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1127 43854                                  
2   1129 45148 -2   -1293.8 16.625 7.661e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>What does it mean for the models to be “nested”?</li>
</ol>
</section>
<section id="mod6-would-adding-self-reported-health-help" class="level2" data-number="12.11">
<h2 data-number="12.11" class="anchored" data-anchor-id="mod6-would-adding-self-reported-health-help"><span class="header-section-number">12.11</span> <code>mod6</code>: Would adding self-reported health help?</h2>
<p>And we can do even a bit better than that by adding in a multi-categorical measure: self-reported general health.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>mod6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> female <span class="sc">+</span> smoke100 <span class="sc">+</span> physhealth <span class="sc">+</span> internet30 <span class="sc">+</span> drinks_wk <span class="sc">+</span> genhealth,</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ female + smoke100 + physhealth + internet30 + 
    drinks_wk + genhealth, data = smart_cle1_sh)

Residuals:
    Min      1Q  Median      3Q     Max 
-19.205  -3.637  -0.750   2.667  36.839 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         25.21949    0.71005  35.518  &lt; 2e-16 ***
female              -0.32079    0.37604  -0.853   0.3938    
smoke100             0.48496    0.37062   1.309   0.1910    
physhealth           0.03710    0.02475   1.499   0.1341    
internet30           0.91322    0.48259   1.892   0.0587 .  
drinks_wk           -0.07751    0.03293  -2.354   0.0187 *  
genhealth2_VeryGood  1.21718    0.56839   2.141   0.0325 *  
genhealth3_Good      3.23814    0.58002   5.583 2.97e-08 ***
genhealth4_Fair      4.19627    0.73221   5.731 1.28e-08 ***
genhealth5_Poor      6.00832    1.08770   5.524 4.12e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.091 on 1123 degrees of freedom
Multiple R-squared:  0.09148,   Adjusted R-squared:  0.0842 
F-statistic: 12.56 on 9 and 1123 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="1">
<li><p>If Harry and Marty have the same values of <code>female</code>, <code>smoke100</code>, <code>physhealth</code>, <code>internet30</code> and <code>drinks_wk</code>, but Harry rates his health as Good, and Marty rates his as Fair, then what is the difference in the predictions? Who is predicted to have a larger BMI, and by how much?</p></li>
<li><p>What does this normal probability plot of the residuals suggest?</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod6, <span class="at">which =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="key-regression-assumptions-for-building-effective-prediction-models" class="level2" data-number="12.12">
<h2 data-number="12.12" class="anchored" data-anchor-id="key-regression-assumptions-for-building-effective-prediction-models"><span class="header-section-number">12.12</span> Key Regression Assumptions for Building Effective Prediction Models</h2>
<ol type="1">
<li>Validity - the data you are analyzing should map to the research question you are trying to answer.
<ul>
<li>The outcome should accurately reflect the phenomenon of interest.</li>
<li>The model should include all relevant predictors. (It can be difficult to decide which predictors are necessary, and what to do with predictors that have large standard errors.)</li>
<li>The model should generalize to all of the cases to which it will be applied.</li>
<li>Can the available data answer our question reliably?</li>
</ul></li>
<li>Additivity and linearity - most important assumption of a regression model is that its deterministic component is a linear function of the predictors. We often think about transformations in this setting.</li>
<li>Independence of errors - errors from the prediction line are independent of each other</li>
<li>Equal variance of errors - if this is violated, we can more efficiently estimate parameters using <em>weighted least squares</em> approaches, where each point is weighted inversely proportional to its variance, but this doesn’t affect the coefficients much, if at all.</li>
<li>Normality of errors - not generally important for estimating the regression line</li>
</ol>
<section id="checking-assumptions-in-model-mod6" class="level3" data-number="12.12.1">
<h3 data-number="12.12.1" class="anchored" data-anchor-id="checking-assumptions-in-model-mod6"><span class="header-section-number">12.12.1</span> Checking Assumptions in model <code>mod6</code></h3>
<ol type="1">
<li>How does the assumption of linearity behind this model look?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod6, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see no strong signs of serious non-linearity here. There’s no obvious curve in the plot, for example. We may have a problem with increasing variance as we move to the right.</p>
<ol start="2" type="1">
<li>What can we conclude from the plot below?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod6, <span class="at">which =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot can help us identify points with large standardized residuals, large leverage values, and large influence on the model (as indicated by large values of Cook’s distance.) In this case, I see no signs of any points used in the model with especially large influence, although there are some poorly fitted points (with especially large standardized residuals.)</p>
<p>We might want to identify the point listed here as 961, which appears to have an enormous standardized residual. To do so, we can use the <code>slice</code> function from <code>dplyr</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">961</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(SEQNO)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
       SEQNO
       &lt;dbl&gt;
1 2017000961</code></pre>
</div>
</div>
<p>Now we know exactly which subject we’re talking about.</p>
<ol start="3" type="1">
<li>What other residual plots are available with <code>plot</code> and how do we interpret them?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod6, <span class="at">which =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot is simply a Normal Q-Q plot of the standardized residuals from our model. We’re looking here for serious problems with the assumption of Normality.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod6, <span class="at">which =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This is a scale-location plot, designed to help us see non-constant variance in the residuals as we move across the fitted values as a linear trend, rather than as a fan shape, by plotting the square root of the residuals on the vertical axis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod6, <span class="at">which =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ancova_smart_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, this is an index plot of the Cook’s distance values, allowing us to identify points that are particularly large. Remember that a value of 0.5 (or perhaps even 1.0) is a reasonable boundary for a substantially influential point.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-GelmanHill2007" class="csl-entry" role="listitem">
Gelman, Andrew, and Jennifer Hill. 2007. <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. New York: Cambridge University Press.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>I’ll now refer to those who have smoked at least 100 cigarettes in their life as smokers, and those who have not as non-smokers to save some space.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ancova_emphysema.html" class="pagination-link" aria-label="Analysis of Covariance">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./nonlinearity.html" class="pagination-link" aria-label="Adding Non-linear Terms to a Linear Regression">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>