<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 9&nbsp; Analysis of Variance with SMART</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./anovaexamples.html" rel="next">
<link href="./datasummaries.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./incomplete.html" class="sidebar-item-text sidebar-link">This is work in progress</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">R Setup</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinaloutcome.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Time To Event / Survival Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup-used-here" id="toc-r-setup-used-here" class="nav-link active" data-scroll-target="#r-setup-used-here"><span class="toc-section-number">9.1</span>  R Setup Used Here</a>
  <ul class="collapse">
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="toc-section-number">9.1.1</span>  Data Load</a></li>
  </ul></li>
  <li><a href="#a-one-factor-analysis-of-variance" id="toc-a-one-factor-analysis-of-variance" class="nav-link" data-scroll-target="#a-one-factor-analysis-of-variance"><span class="toc-section-number">9.2</span>  A One-Factor Analysis of Variance</a>
  <ul class="collapse">
  <li><a href="#can-activity-be-used-to-predict-bmi" id="toc-can-activity-be-used-to-predict-bmi" class="nav-link" data-scroll-target="#can-activity-be-used-to-predict-bmi"><span class="toc-section-number">9.2.1</span>  Can <code>activity</code> be used to predict <code>bmi</code>?</a></li>
  <li><a href="#should-we-transform-bmi" id="toc-should-we-transform-bmi" class="nav-link" data-scroll-target="#should-we-transform-bmi"><span class="toc-section-number">9.2.2</span>  Should we transform <code>bmi</code>?</a></li>
  <li><a href="#building-the-anova-model" id="toc-building-the-anova-model" class="nav-link" data-scroll-target="#building-the-anova-model"><span class="toc-section-number">9.2.3</span>  Building the ANOVA model</a></li>
  <li><a href="#the-anova-table" id="toc-the-anova-table" class="nav-link" data-scroll-target="#the-anova-table"><span class="toc-section-number">9.2.4</span>  The ANOVA table</a></li>
  <li><a href="#the-model-coefficients" id="toc-the-model-coefficients" class="nav-link" data-scroll-target="#the-model-coefficients"><span class="toc-section-number">9.2.5</span>  The Model Coefficients</a></li>
  <li><a href="#using-tidy-to-explore-the-coefficients" id="toc-using-tidy-to-explore-the-coefficients" class="nav-link" data-scroll-target="#using-tidy-to-explore-the-coefficients"><span class="toc-section-number">9.2.6</span>  Using <code>tidy</code> to explore the coefficients</a></li>
  <li><a href="#using-glance-to-summarize-the-models-fit" id="toc-using-glance-to-summarize-the-models-fit" class="nav-link" data-scroll-target="#using-glance-to-summarize-the-models-fit"><span class="toc-section-number">9.2.7</span>  Using <code>glance</code> to summarize the model’s fit</a></li>
  <li><a href="#using-augment-to-make-predictions" id="toc-using-augment-to-make-predictions" class="nav-link" data-scroll-target="#using-augment-to-make-predictions"><span class="toc-section-number">9.2.8</span>  Using <code>augment</code> to make predictions</a></li>
  </ul></li>
  <li><a href="#a-two-factor-anova-without-interaction" id="toc-a-two-factor-anova-without-interaction" class="nav-link" data-scroll-target="#a-two-factor-anova-without-interaction"><span class="toc-section-number">9.3</span>  A Two-Factor ANOVA (without Interaction)</a>
  <ul class="collapse">
  <li><a href="#model-coefficients" id="toc-model-coefficients" class="nav-link" data-scroll-target="#model-coefficients"><span class="toc-section-number">9.3.1</span>  Model Coefficients</a></li>
  </ul></li>
  <li><a href="#a-two-factor-anova-with-interaction" id="toc-a-two-factor-anova-with-interaction" class="nav-link" data-scroll-target="#a-two-factor-anova-with-interaction"><span class="toc-section-number">9.4</span>  A Two-Factor ANOVA (with Interaction)</a>
  <ul class="collapse">
  <li><a href="#model-coefficients-1" id="toc-model-coefficients-1" class="nav-link" data-scroll-target="#model-coefficients-1"><span class="toc-section-number">9.4.1</span>  Model Coefficients</a></li>
  <li><a href="#is-the-interaction-term-necessary" id="toc-is-the-interaction-term-necessary" class="nav-link" data-scroll-target="#is-the-interaction-term-necessary"><span class="toc-section-number">9.4.2</span>  Is the interaction term necessary?</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this chapter, we’ll work with the <code>smart_cle1_sh</code> data file again.</p>
<section id="r-setup-used-here" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="r-setup-used-here"><span class="header-section-number">9.1</span> R Setup Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-load" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="data-load"><span class="header-section-number">9.1.1</span> Data Load</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/smart_cle1_sh.Rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The variables we’ll look at in this chapter are as follows.</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 84%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>SEQNO</code></td>
<td>respondent identification number (all begin with 2016)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>bmi</code></td>
<td>Body mass index, in kg/m<sup>2</sup></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>female</code></td>
<td>Sex, 1 = female, 0 = male</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>smoke100</code></td>
<td>Have you smoked at least 100 cigarettes in your life? (1 = yes, 0 = no)</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>activity</code></td>
<td>Physical activity (Highly Active, Active, Insufficiently Active, Inactive)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>drinks_wk</code></td>
<td>On average, how many drinks of alcohol do you consume in a week?</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>physhealth</code></td>
<td>Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="a-one-factor-analysis-of-variance" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="a-one-factor-analysis-of-variance"><span class="header-section-number">9.2</span> A One-Factor Analysis of Variance</h2>
<p>We’ll be predicting body mass index, at first using a single factor as a predictor: the <code>activity</code> level.</p>
<section id="can-activity-be-used-to-predict-bmi" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="can-activity-be-used-to-predict-bmi"><span class="header-section-number">9.2.1</span> Can <code>activity</code> be used to predict <code>bmi</code>?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> activity, <span class="at">y =</span> bmi, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">fill =</span> activity)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">notch =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"BMI as a function of Activity Level"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Subjects in the SMART CLE data"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Body Mass Index"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="anovasmart_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here’s a numerical summary of the distributions of <code>bmi</code> within each <code>activity</code> group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(bmi <span class="sc">~</span> activity, <span class="at">data =</span> smart_cle1_sh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               activity   min      Q1   median     Q3   max     mean       sd
1         Highly_Active 13.30 23.6275 26.99000 28.930 50.46 27.02253 5.217496
2                Active 17.07 24.2400 27.06930 29.520 44.67 27.36157 5.151796
3 Insufficiently_Active 17.49 25.0500 27.93776 32.180 49.98 29.04328 6.051823
4              Inactive 13.64 25.2150 28.34000 33.775 70.56 30.15978 7.832675
    n missing
1 428       0
2 173       0
3 201       0
4 331       0</code></pre>
</div>
</div>
</section>
<section id="should-we-transform-bmi" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="should-we-transform-bmi"><span class="header-section-number">9.2.2</span> Should we transform <code>bmi</code>?</h3>
<p>The analysis of variance is something of a misnomer. What we’re doing is using the variance to say something about population means. In light of the apparent right skew of the <code>bmi</code> results in each <code>activity</code> group, might it be a better choice to use a logarithmic transformation? We’ll use the natural logarithm here, which in R, is symbolized by <code>log</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smart_cle1_sh, <span class="fu">aes</span>(<span class="at">x =</span> activity, <span class="at">y =</span> <span class="fu">log</span>(bmi), </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">fill =</span> activity)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">notch =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"log(BMI) as a function of Activity Level"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Subjects in the SMART CLE data"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"log(Body Mass Index)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="anovasmart_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The logarithmic transformation yields distributions that look much more symmetric in each <code>activity</code> group, so we’ll proceed to build our regression model predicting <code>log(bmi)</code> using <code>activity</code>. Here’s the numerical summary of these logged results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="fu">log</span>(bmi) <span class="sc">~</span> activity, <span class="at">data =</span> smart_cle1_sh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               activity      min       Q1   median       Q3      max     mean
1         Highly_Active 2.587764 3.162411 3.295466 3.364879 3.921181 3.279246
2                Active 2.837323 3.188004 3.298400 3.385068 3.799302 3.292032
3 Insufficiently_Active 2.861629 3.220874 3.329979 3.471345 3.911623 3.348383
4              Inactive 2.613007 3.227439 3.344274 3.519721 4.256463 3.376468
         sd   n missing
1 0.1851478 428       0
2 0.1850568 173       0
3 0.2007241 201       0
4 0.2411196 331       0</code></pre>
</div>
</div>
</section>
<section id="building-the-anova-model" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="building-the-anova-model"><span class="header-section-number">9.2.3</span> Building the ANOVA model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>model_5a <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(bmi) <span class="sc">~</span> activity, <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>model_5a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(bmi) ~ activity, data = smart_cle1_sh)

Coefficients:
                  (Intercept)                 activityActive  
                      3.27925                        0.01279  
activityInsufficiently_Active               activityInactive  
                      0.06914                        0.09722  </code></pre>
</div>
</div>
<p>The <code>activity</code> data is categorical and there are four levels. The model equation is:</p>
<pre><code>log(bmi) = 3.279 + 0.013 (activity = Active)
                 + 0.069 (activity = Insufficiently Active)
                 + 0.097 (activity = Inactive)</code></pre>
<p>where, for example, <code>(activity = Active)</code> is 1 if <code>activity</code> is Active, and 0 otherwise. The fourth level (Highly Active) is not shown here and is used as a baseline. Thus the model above can be interpreted as follows.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><code>activity</code></th>
<th style="text-align: center;">Predicted <code>log(bmi)</code></th>
<th style="text-align: center;">Predicted <code>bmi</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Highly Active</td>
<td style="text-align: center;">3.279</td>
<td style="text-align: center;">exp(3.279) = 26.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">Active</td>
<td style="text-align: center;">3.279 + 0.013 = 3.292</td>
<td style="text-align: center;">exp(3.292) = 26.90</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Insufficiently Active</td>
<td style="text-align: center;">3.279 + 0.069 = 3.348</td>
<td style="text-align: center;">exp(3.348) = 28.45</td>
</tr>
<tr class="even">
<td style="text-align: center;">Inactive</td>
<td style="text-align: center;">3.279 + 0.097 = 3.376</td>
<td style="text-align: center;">exp(3.376) = 29.25</td>
</tr>
</tbody>
</table>
<p>Those predicted <code>log(bmi)</code> values should look familiar. They are just the means of <code>log(bmi)</code> in each group, but I’m sure you’ll also notice that the predicted <code>bmi</code> values are not exact matches for the observed means of <code>bmi</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>smart_cle1_sh <span class="sc">|&gt;</span> <span class="fu">group_by</span>(activity) <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean</span>(<span class="fu">log</span>(bmi)), <span class="fu">mean</span>(bmi))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  activity              `mean(log(bmi))` `mean(bmi)`
  &lt;fct&gt;                            &lt;dbl&gt;       &lt;dbl&gt;
1 Highly_Active                     3.28        27.0
2 Active                            3.29        27.4
3 Insufficiently_Active             3.35        29.0
4 Inactive                          3.38        30.2</code></pre>
</div>
</div>
</section>
<section id="the-anova-table" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="the-anova-table"><span class="header-section-number">9.2.4</span> The ANOVA table</h3>
<p>Now, let’s press on to look at the ANOVA results for this model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_5a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log(bmi)
            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
activity     3  2.060 0.68652  16.225 2.496e-10 ***
Residuals 1129 47.772 0.04231                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>The total variation in <code>log(bmi)</code>, our outcome, is captured by the sums of squares here. SS(Total) = 2.058 + 47.770 = 49.828</li>
<li>Here, the <code>activity</code> variable (with 4 levels, so 4-1 = 3 degrees of freedom) accounts for 4.13% (2.058 / 49.828) of the variation in <code>log(bmi)</code>. Another way of saying this is that the model <span class="math inline">\(R^2\)</span> or <span class="math inline">\(\eta^2\)</span> is 0.0413.</li>
<li>The variation accounted for by the <code>activity</code> categories meets the standard for a statistically detectable result, according to the ANOVA F test, although that’s not really important.</li>
<li>The square root of the Mean Square(Residuals) is the residual standard error, <span class="math inline">\(\sigma\)</span>, we’ve seen in the past. MS(Residual) estimates the variance (0.0423), so the residual standard error is <span class="math inline">\(\sqrt{0.0423} \approx 0.206\)</span>.</li>
</ul>
</section>
<section id="the-model-coefficients" class="level3" data-number="9.2.5">
<h3 data-number="9.2.5" class="anchored" data-anchor-id="the-model-coefficients"><span class="header-section-number">9.2.5</span> The Model Coefficients</h3>
<p>To address the question of effect size for the various levels of <code>activity</code> on <code>log(bmi)</code>, we could look directly at the regression model coefficients. For that, we might look at the model <code>summary</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_5a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(bmi) ~ activity, data = smart_cle1_sh)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.76346 -0.12609 -0.00286  0.11055  0.88000 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   3.279246   0.009943 329.806  &lt; 2e-16 ***
activityActive                0.012785   0.018532   0.690     0.49    
activityInsufficiently_Active 0.069137   0.017589   3.931 8.99e-05 ***
activityInactive              0.097221   0.015056   6.457 1.58e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2057 on 1129 degrees of freedom
Multiple R-squared:  0.04133,   Adjusted R-squared:  0.03878 
F-statistic: 16.22 on 3 and 1129 DF,  p-value: 2.496e-10</code></pre>
</div>
</div>
<p>If we want to see the confidence intervals around these estimates, we could use</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_5a, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                    2.5 %     97.5 %
(Intercept)                    3.25973769 3.29875522
activityActive                -0.02357630 0.04914707
activityInsufficiently_Active  0.03462572 0.10364764
activityInactive               0.06767944 0.12676300</code></pre>
</div>
</div>
<p>The model suggests, based on these 1133 subjects, that (remember that the baseline category is Highly Active)</p>
<ul>
<li>a 95% confidence (uncertainty) interval for the difference between Active and Highly Active subjects in log(BMI) ranges from -0.024 to 0.049</li>
<li>a 95% confidence (uncertainty) interval for the difference between Insufficiently Active and Highly Active subjects in log(BMI) ranges from 0.035 to 0.104</li>
<li>a 95% confidence (uncertainty) interval for the difference between Inactive and Highly Active subjects in log(BMI) ranges from 0.068 to 0.127</li>
<li>the model accounts for 4.13% of the variation in log(BMI), so that knowing the respondent’s activity level somewhat reduces the size of the prediction errors as compared to an intercept only model that would predict the overall mean log(BMI), regardless of activity level, for all subjects.</li>
<li>from the summary of residuals, we see that one subject had a residual of 0.88 - that means they were predicted to have a log(BMI) 0.88 lower than their actual log(BMI) and one subject had a log(BMI) that is 0.76 larger than their actual log(BMI), at the extremes.</li>
</ul>
</section>
<section id="using-tidy-to-explore-the-coefficients" class="level3" data-number="9.2.6">
<h3 data-number="9.2.6" class="anchored" data-anchor-id="using-tidy-to-explore-the-coefficients"><span class="header-section-number">9.2.6</span> Using <code>tidy</code> to explore the coefficients</h3>
<p>A better strategy for displaying the coefficients in any regression model is to use the <code>tidy</code> function from the <code>broom</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_5a, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 34%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.279</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">329.806</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">3.260</td>
<td style="text-align: right;">3.299</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityActive</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.690</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.049</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInsufficiently_Active</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">3.931</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">0.104</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInactive</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">6.457</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.068</td>
<td style="text-align: right;">0.127</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="using-glance-to-summarize-the-models-fit" class="level3" data-number="9.2.7">
<h3 data-number="9.2.7" class="anchored" data-anchor-id="using-glance-to-summarize-the-models-fit"><span class="header-section-number">9.2.7</span> Using <code>glance</code> to summarize the model’s fit</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_5a) <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">|&gt;</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.0413</td>
<td style="text-align: right;">0.0388</td>
<td style="text-align: right;">0.206</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The <code>r.squared</code> or <span class="math inline">\(R^2\)</span> value is interpreted for a linear model as the percentage of variation in the outcome (here, <code>log(bmi)</code>) that is accounted for by the model.</li>
<li>The <code>adj.r.squared</code> or adjusted <span class="math inline">\(R^2\)</span> value incorporates a small penalty for the number of predictors included in the model. Adjusted <span class="math inline">\(R^2\)</span> is useful for models with more than one predictor, not simple regression models like this one. Like <span class="math inline">\(R^2\)</span> and most of these other summaries, its primary value comes when making comparisons between models for the same outcome.</li>
<li>The <code>sigma</code> or <span class="math inline">\(\sigma\)</span> is the residual standard error. Doubling this value gives us a good idea of the range of errors made by the model (approximately 95% of the time if the normal distribution assumption for the residuals holds perfectly.)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_5a) <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="dv">4</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">16.22</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">185.99</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The <code>statistic</code> and <code>p.value</code> shown here refer to the ANOVA F test and p value. They test the null hypothesis that the <code>activity</code> information is of no use in separating out the <code>bmi</code> data, or, equivalently, that the true <span class="math inline">\(R^2\)</span> is 0.</li>
<li>The <code>df</code> indicates the model degrees of freedom, and in this case simply specifies the number of parameters fitted attributed to the model. Models that require more <code>df</code> for estimation require larger sample sizes.</li>
<li>The <code>logLik</code> is the log likelihood for the model. This is a function of the sample size, but we can compare the fit of multiple models by comparing this value across different models for the same outcome. You want to maximize the log-likelihood.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_5a) <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="dv">8</span><span class="sc">:</span><span class="dv">9</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-361.98</td>
<td style="text-align: right;">-336.82</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The <code>AIC</code> (or Akaike information criterion) and <code>BIC</code> (Bayes information criterion) are also used only to compare models. You want to minimize AIC and BIC in selecting a model. AIC and BIC are unique only up to a constant, so different packages or routines in R may give differing values, but in comparing two models - the difference in AIC (or BIC) should be consistent.</li>
</ul>
</section>
<section id="using-augment-to-make-predictions" class="level3" data-number="9.2.8">
<h3 data-number="9.2.8" class="anchored" data-anchor-id="using-augment-to-make-predictions"><span class="header-section-number">9.2.8</span> Using <code>augment</code> to make predictions</h3>
<p>We can obtain residuals and predicted (fitted) values for the points used to fit the model with <code>augment</code> from the <code>broom</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model_5a, <span class="at">se_fit =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">log(bmi)</th>
<th style="text-align: left;">activity</th>
<th style="text-align: right;">.fitted</th>
<th style="text-align: right;">.se.fit</th>
<th style="text-align: right;">.resid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3.330</td>
<td style="text-align: left;">Inactive</td>
<td style="text-align: right;">3.376</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">-0.047</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.138</td>
<td style="text-align: left;">Inactive</td>
<td style="text-align: right;">3.376</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">-0.239</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3.293</td>
<td style="text-align: left;">Insufficiently_Active</td>
<td style="text-align: right;">3.348</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">-0.055</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.278</td>
<td style="text-align: left;">Highly_Active</td>
<td style="text-align: right;">3.279</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">-0.002</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The <code>.fitted</code> value is the predicted value of <code>log(bmi)</code> for this subject.</li>
<li>The <code>.se.fit</code> value shows the standard error associated with the fitted value.</li>
<li>The <code>.resid</code> is the residual value (observed - fitted <code>log(bmi)</code>)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model_5a, <span class="at">se_fit =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">6</span><span class="sc">:</span><span class="dv">9</span>) <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">log(bmi)</th>
<th style="text-align: left;">activity</th>
<th style="text-align: right;">.hat</th>
<th style="text-align: right;">.sigma</th>
<th style="text-align: right;">.cooksd</th>
<th style="text-align: right;">.std.resid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3.330</td>
<td style="text-align: left;">Inactive</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.206</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.227</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.138</td>
<td style="text-align: left;">Inactive</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.206</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">-1.163</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3.293</td>
<td style="text-align: left;">Insufficiently_Active</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.206</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.269</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.278</td>
<td style="text-align: left;">Highly_Active</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.206</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.008</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The <code>.hat</code> value shows the leverage index associated with the observation (this is a function of the predictors - higher leveraged points have more unusual predictor values)</li>
<li>The <code>.sigma</code> value shows the estimate of the residual standard deviation if this observation were to be dropped from the model, and thus indexes how much of an outlier this observation’s residual is.</li>
<li>The <code>.cooksd</code> or Cook’s distance value shows the influence that the observation has on the model - it is one of a class of leave-one-out diagnostic measures. Larger values of Cook’s distance indicate more influential points.</li>
<li>The <code>.std.resid</code> shows the standardized residual (which is designed to have mean 0 and standard deviation 1, facilitating comparisons across models for differing outcomes)</li>
</ul>
</section>
</section>
<section id="a-two-factor-anova-without-interaction" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="a-two-factor-anova-without-interaction"><span class="header-section-number">9.3</span> A Two-Factor ANOVA (without Interaction)</h2>
<p>Let’s add <code>race_eth</code> to the predictor set for <code>log(BMI)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>model_5b <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(bmi) <span class="sc">~</span> activity <span class="sc">+</span> race_eth, <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_5b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log(bmi)
            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
activity     3  2.060 0.68652 16.5090 1.676e-10 ***
race_eth     4  0.989 0.24716  5.9435 9.843e-05 ***
Residuals 1125 46.783 0.04158                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Notice that the ANOVA model assesses these variables sequentially, so the SS(activity) = 2.058 is accounted for before we consider the SS(race_eth) = 0.990. Thus, in total, the model accounts for 2.058 + 0.990 = 3.048 of the sums of squares in <code>log(bmi)</code> in these data.</p>
<p>If we flip the order in the model, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="fu">log</span>(bmi) <span class="sc">~</span> race_eth <span class="sc">+</span> activity, <span class="at">data =</span> smart_cle1_sh) <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log(bmi)
            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
race_eth     4  1.119 0.27981  6.7287 2.371e-05 ***
activity     3  1.929 0.64299 15.4620 7.332e-10 ***
Residuals 1125 46.783 0.04158                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>After flipping the order of the predictors, <code>race_eth</code> accounts for a larger Sum of Squares than it did previously, but <code>activity</code> accounts for a smaller amount, and the total between <code>race_eth</code> and <code>activity</code> remains the same, as 1.121 + 1.927 is still 3.048.</li>
</ul>
<section id="model-coefficients" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="model-coefficients"><span class="header-section-number">9.3.1</span> Model Coefficients</h3>
<p>The model coefficients are unchanged regardless of the order of the variables in our two-factor ANOVA model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_5b, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, std.error, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 46%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.268</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">3.247</td>
<td style="text-align: right;">3.288</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityActive</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.048</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInsufficiently_Active</td>
<td style="text-align: right;">0.073</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">0.108</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInactive</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.122</td>
</tr>
<tr class="odd">
<td style="text-align: left;">race_ethBlack non-Hispanic</td>
<td style="text-align: right;">0.066</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">0.096</td>
</tr>
<tr class="even">
<td style="text-align: left;">race_ethOther race non-Hispanic</td>
<td style="text-align: right;">-0.086</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">-0.169</td>
<td style="text-align: right;">-0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">race_ethMultiracial non-Hispanic</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">-0.063</td>
<td style="text-align: right;">0.103</td>
</tr>
<tr class="even">
<td style="text-align: left;">race_ethHispanic</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">-0.057</td>
<td style="text-align: right;">0.082</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The <code>model_5b</code> equation is:</p>
<pre><code>log(BMI) = 3.268
      + 0.012 (activity = Active)
      + 0.073 (activity = Insufficiently Active)
      + 0.092 (activity = Inactive)
      + 0.066 (race_eth = Black non-Hispanic)
      - 0.086 (race_eth = Other race non-Hispanic)
      + 0.020 (race_eth = Multiracial non-Hispanic)
      + 0.012 (race_eth = Hispanic)</code></pre>
<p>and we can make predictions by filling in appropriate 1s and 0s for the indicator variables in parentheses.</p>
<p>For example, the predicted <code>log(BMI)</code> for a White Highly Active person is 3.268, as White and Highly Active are the baseline categories in our two factors.</p>
<p>For all other combinations, we can make predictions as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>new_dat <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">race_eth =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"White non-Hispanic"</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Black non-Hispanic"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Other race non-Hispanic"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Multiracial non-Hispanic"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Hispanic"</span>), <span class="dv">4</span>),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">activity =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Highly_Active"</span>, <span class="dv">5</span>),</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>               <span class="fu">rep</span>(<span class="st">"Active"</span>, <span class="dv">5</span>),</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>               <span class="fu">rep</span>(<span class="st">"Insufficiently_Active"</span>, <span class="dv">5</span>),</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>               <span class="fu">rep</span>(<span class="st">"Inactive"</span>, <span class="dv">5</span>))</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model_5b, <span class="at">newdata =</span> new_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 3
   race_eth                 activity              .fitted
   &lt;chr&gt;                    &lt;chr&gt;                   &lt;dbl&gt;
 1 White non-Hispanic       Highly_Active            3.27
 2 Black non-Hispanic       Highly_Active            3.33
 3 Other race non-Hispanic  Highly_Active            3.18
 4 Multiracial non-Hispanic Highly_Active            3.29
 5 Hispanic                 Highly_Active            3.28
 6 White non-Hispanic       Active                   3.28
 7 Black non-Hispanic       Active                   3.35
 8 Other race non-Hispanic  Active                   3.19
 9 Multiracial non-Hispanic Active                   3.30
10 Hispanic                 Active                   3.29
11 White non-Hispanic       Insufficiently_Active    3.34
12 Black non-Hispanic       Insufficiently_Active    3.41
13 Other race non-Hispanic  Insufficiently_Active    3.26
14 Multiracial non-Hispanic Insufficiently_Active    3.36
15 Hispanic                 Insufficiently_Active    3.35
16 White non-Hispanic       Inactive                 3.36
17 Black non-Hispanic       Inactive                 3.43
18 Other race non-Hispanic  Inactive                 3.27
19 Multiracial non-Hispanic Inactive                 3.38
20 Hispanic                 Inactive                 3.37</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model_5b, <span class="at">newdata =</span> new_dat) <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">race_eth =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(race_eth),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"White non-Hispanic"</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Black non-Hispanic"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Other race non-Hispanic"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Multiracial non-Hispanic"</span>,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Hispanic"</span>),</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">activity =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(activity),</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Highly_Active"</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Active"</span>,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Insufficiently_Active"</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Inactive"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x =</span> activity, <span class="at">y =</span> .fitted, </span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> race_eth, <span class="at">group =</span> race_eth)) <span class="sc">+</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model 5b predictions for log(BMI)"</span>,</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"race_eth and activity, no interaction so lines are parallel"</span>,</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Model Predicted log(BMI)"</span>,</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="anovasmart_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The lines joining the points for each <code>race_eth</code> category are parallel to each other. The groups always hold the same position relative to each other, regardless of their activity levels, and vice versa. There is no interaction in this model allowing the predicted effects of, say, <code>activity</code> on <code>log(BMI)</code> values to differ for the various <code>race_eth</code> groups. To do that, we’d have to fit the two-factor ANOVA model incorporating an interaction term.</p>
</section>
</section>
<section id="a-two-factor-anova-with-interaction" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="a-two-factor-anova-with-interaction"><span class="header-section-number">9.4</span> A Two-Factor ANOVA (with Interaction)</h2>
<p>Let’s add the interaction of <code>activity</code> and <code>race_eth</code> (symbolized in R by <code>activity * race_eth</code>) to the model for <code>log(BMI)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model_5c <span class="ot">&lt;-</span>  </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="fu">log</span>(bmi) <span class="sc">~</span> activity <span class="sc">*</span> race_eth, <span class="at">data =</span> smart_cle1_sh)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_5c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log(bmi)
                    Df Sum Sq Mean Sq F value    Pr(&gt;F)    
activity             3  2.060 0.68652 16.4468 1.839e-10 ***
race_eth             4  0.989 0.24716  5.9211 0.0001026 ***
activity:race_eth   12  0.324 0.02700  0.6469 0.8028368    
Residuals         1113 46.459 0.04174                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The ANOVA model shows that the SS(interaction) = SS(activity:race_eth) is 0.324, and uses 12 degrees of freedom. The model including the interaction term now accounts for 2.058 + 0.990 + 0.324 = 3.372, which is 6.8% of the variation in <code>log(BMI)</code> overall (which is calculated as SS(Total) = 2.058 + 0.990 + 0.324 + 46.456 = 49.828.)</p>
<section id="model-coefficients-1" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="model-coefficients-1"><span class="header-section-number">9.4.1</span> Model Coefficients</h3>
<p>The model coefficients now include additional product terms that incorporate indicator variables for both activity and race_eth. For each of the product terms to take effect, both their activity and race_eth status must yield a 1 in the indicator variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_5c, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, std.error, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 62%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.264</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">3.242</td>
<td style="text-align: right;">3.287</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityActive</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">-0.021</td>
<td style="text-align: right;">0.062</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInsufficiently_Active</td>
<td style="text-align: right;">0.079</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">0.118</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInactive</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">race_ethBlack non-Hispanic</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">0.026</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">0.113</td>
</tr>
<tr class="even">
<td style="text-align: left;">race_ethOther race non-Hispanic</td>
<td style="text-align: right;">-0.070</td>
<td style="text-align: right;">0.078</td>
<td style="text-align: right;">-0.223</td>
<td style="text-align: right;">0.083</td>
</tr>
<tr class="odd">
<td style="text-align: left;">race_ethMultiracial non-Hispanic</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.060</td>
<td style="text-align: right;">-0.051</td>
<td style="text-align: right;">0.185</td>
</tr>
<tr class="even">
<td style="text-align: left;">race_ethHispanic</td>
<td style="text-align: right;">0.110</td>
<td style="text-align: right;">0.060</td>
<td style="text-align: right;">-0.008</td>
<td style="text-align: right;">0.228</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityActive:race_ethBlack non-Hispanic</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">-0.096</td>
<td style="text-align: right;">0.094</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInsufficiently_Active:race_ethBlack non-Hispanic</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.046</td>
<td style="text-align: right;">-0.086</td>
<td style="text-align: right;">0.096</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInactive:race_ethBlack non-Hispanic</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.037</td>
<td style="text-align: right;">-0.065</td>
<td style="text-align: right;">0.080</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityActive:race_ethOther race non-Hispanic</td>
<td style="text-align: right;">-0.065</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">-0.389</td>
<td style="text-align: right;">0.259</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInsufficiently_Active:race_ethOther race non-Hispanic</td>
<td style="text-align: right;">-0.035</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">-0.233</td>
<td style="text-align: right;">0.163</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInactive:race_ethOther race non-Hispanic</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">-0.221</td>
<td style="text-align: right;">0.287</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityActive:race_ethMultiracial non-Hispanic</td>
<td style="text-align: right;">-0.208</td>
<td style="text-align: right;">0.134</td>
<td style="text-align: right;">-0.470</td>
<td style="text-align: right;">0.054</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInsufficiently_Active:race_ethMultiracial non-Hispanic</td>
<td style="text-align: right;">-0.050</td>
<td style="text-align: right;">0.120</td>
<td style="text-align: right;">-0.285</td>
<td style="text-align: right;">0.184</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInactive:race_ethMultiracial non-Hispanic</td>
<td style="text-align: right;">-0.056</td>
<td style="text-align: right;">0.110</td>
<td style="text-align: right;">-0.272</td>
<td style="text-align: right;">0.160</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityActive:race_ethHispanic</td>
<td style="text-align: right;">-0.104</td>
<td style="text-align: right;">0.096</td>
<td style="text-align: right;">-0.291</td>
<td style="text-align: right;">0.084</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInsufficiently_Active:race_ethHispanic</td>
<td style="text-align: right;">-0.240</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.660</td>
<td style="text-align: right;">0.179</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInactive:race_ethHispanic</td>
<td style="text-align: right;">-0.169</td>
<td style="text-align: right;">0.082</td>
<td style="text-align: right;">-0.331</td>
<td style="text-align: right;">-0.008</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The <code>model_5c</code> equation is:</p>
<pre><code>log(BMI) = 3.264
  + 0.021 (activity = Active)
  + 0.079 (activity = Insufficiently Active)
  + 0.097 (activity = Inactive)
  + 0.062 (race_eth = Black non-Hispanic)
  - 0.070 (race_eth = Other race non-Hispanic)
  + 0.067 (race_eth = Multiracial non-Hispanic)
  + 0.110 (race_eth = Hispanic)
  - 0.002 (activity = Active)(race_eth = Black non-Hispanic)
  + 0.005 (Insufficiently Active)(Black non-Hispanic)
  + 0.008 (Inactive)(Black non-Hispanic)
  - 0.065 (Active)(Other race non-Hispanic)
  - 0.035 (Insufficiently Active)(Other race non-Hispanic)
  + 0.033 (Inactive)(Other race non-Hispanic)
  - 0.208 (Active)(Multiracial non-Hispanic)
  - 0.050 (Insufficiently Active)(Multiracial non-Hispanic)
  - 0.056 (Inactive)(Multiracial non-Hispanic)
  - 0.104 (Active)(Hispanic)
  - 0.240 (Insufficiently Active)(Hispanic)
  - 0.169 (Inactive)(Hispanic)
  </code></pre>
<p>and again, we can make predictions by filling in appropriate 1s and 0s for the indicator variables in parentheses.</p>
<p>For example, the predicted <code>log(BMI)</code> for a White Highly Active person is 3.264, as White and Highly Active are the baseline categories in our two factors.</p>
<p>But the predicted <code>log(BMI)</code> for a Hispanic Inactive person would be 3.264 + 0.097 + 0.110 - 0.169 = 3.302.</p>
<p>Again, we’ll plot the predicted <code>log(BMI)</code> predictions for each possible combination.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>new_dat <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">race_eth =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"White non-Hispanic"</span>,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Black non-Hispanic"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Other race non-Hispanic"</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Multiracial non-Hispanic"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Hispanic"</span>), <span class="dv">4</span>),</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">activity =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Highly_Active"</span>, <span class="dv">5</span>),</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>               <span class="fu">rep</span>(<span class="st">"Active"</span>, <span class="dv">5</span>),</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>               <span class="fu">rep</span>(<span class="st">"Insufficiently_Active"</span>, <span class="dv">5</span>),</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>               <span class="fu">rep</span>(<span class="st">"Inactive"</span>, <span class="dv">5</span>))</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model_5c, <span class="at">newdata =</span> new_dat) <span class="sc">|&gt;</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">race_eth =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(race_eth),</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"White non-Hispanic"</span>,</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Black non-Hispanic"</span>,</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Other race non-Hispanic"</span>,</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Multiracial non-Hispanic"</span>,</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Hispanic"</span>),</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">activity =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(activity),</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Highly_Active"</span>,</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Active"</span>,</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Insufficiently_Active"</span>,</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Inactive"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x =</span> activity, <span class="at">y =</span> .fitted, </span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> race_eth, <span class="at">group =</span> race_eth)) <span class="sc">+</span></span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model 5c predictions for log(BMI)"</span>,</span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"race_eth and activity, with interaction"</span>,</span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Model Predicted log(BMI)"</span>,</span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="anovasmart_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note that the lines joining the points for each <code>race_eth</code> category are no longer parallel to each other. The race-ethnicity group relative positions on <code>log(BMI)</code> is now changing depending on the <code>activity</code> status.</p>
</section>
<section id="is-the-interaction-term-necessary" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="is-the-interaction-term-necessary"><span class="header-section-number">9.4.2</span> Is the interaction term necessary?</h3>
<p>We can assess this in three ways, in order of importance:</p>
<ol type="1">
<li>With an interaction plot</li>
<li>By assessing the fraction of the variation in the outcome accounted for by the interaction</li>
<li>By assessing whether the interaction accounts for statistically detectable outcome variation</li>
</ol>
<section id="the-interaction-plot" class="level4" data-number="9.4.2.1">
<h4 data-number="9.4.2.1" class="anchored" data-anchor-id="the-interaction-plot"><span class="header-section-number">9.4.2.1</span> The Interaction Plot</h4>
<p>A simple interaction plot is just a plot of the unadjusted outcome means, stratified by the two factors. For example, consider this plot for our two-factor ANOVA model. To obtain this plot, we first summarize the means within each group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>summaries_5 <span class="ot">&lt;-</span> smart_cle1_sh <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(activity, race_eth) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">mean =</span> <span class="fu">mean</span>(<span class="fu">log</span>(bmi)), </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(<span class="fu">log</span>(bmi)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'activity'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>summaries_5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 5
# Groups:   activity [4]
   activity              race_eth                     n  mean      sd
   &lt;fct&gt;                 &lt;fct&gt;                    &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1 Highly_Active         White non-Hispanic         320  3.26  0.176 
 2 Highly_Active         Black non-Hispanic          77  3.33  0.190 
 3 Highly_Active         Other race non-Hispanic      7  3.19  0.198 
 4 Highly_Active         Multiracial non-Hispanic    12  3.33  0.187 
 5 Highly_Active         Hispanic                    12  3.37  0.296 
 6 Active                White non-Hispanic         129  3.28  0.173 
 7 Active                Black non-Hispanic          31  3.35  0.224 
 8 Active                Other race non-Hispanic      2  3.15  0.0845
 9 Active                Multiracial non-Hispanic     3  3.14  0.121 
10 Active                Hispanic                     8  3.29  0.213 
11 Insufficiently_Active White non-Hispanic         150  3.34  0.194 
12 Insufficiently_Active Black non-Hispanic          35  3.41  0.213 
13 Insufficiently_Active Other race non-Hispanic     11  3.24  0.137 
14 Insufficiently_Active Multiracial non-Hispanic     4  3.36  0.374 
15 Insufficiently_Active Hispanic                     1  3.21 NA     
16 Inactive              White non-Hispanic         225  3.36  0.238 
17 Inactive              Black non-Hispanic          83  3.43  0.247 
18 Inactive              Other race non-Hispanic      4  3.32  0.238 
19 Inactive              Multiracial non-Hispanic     5  3.37  0.129 
20 Inactive              Hispanic                    14  3.30  0.264 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summaries_5, <span class="fu">aes</span>(<span class="at">x =</span> activity, <span class="at">y =</span> mean, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">color =</span> race_eth, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">group =</span> race_eth)) <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Simple Interaction Plot for log(BMI)"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"SMART CLE means by activity and race_eth"</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Mean of log(BMI)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="anovasmart_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The interaction plot suggests that there is a modest interaction here. The White non-Hispanic and Black non-Hispanic groups appear pretty parallel (and they are the two largest groups) and Other race non-Hispanic has a fairly similar pattern, but the other two groups (Hispanic and Multiracial non-Hispanic) bounce around quite a bit based on activity level.</p>
<p>An alternative would be to include a small “dodge” for each point and include error bars (means <span class="math inline">\(\pm\)</span> standard deviation) for each combination.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">=</span> <span class="fu">position_dodge</span>(<span class="fl">0.2</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summaries_5, <span class="fu">aes</span>(<span class="at">x =</span> activity, <span class="at">y =</span> mean, </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">color =</span> race_eth, </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">group =</span> race_eth)) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> sd,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean <span class="sc">+</span> sd),</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">position =</span> pd) <span class="sc">+</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">position =</span> pd) <span class="sc">+</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">position =</span> pd) <span class="sc">+</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Interaction Plot for log(BMI) with Error Bars"</span>,</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"SMART CLE means by activity and race_eth"</span>,</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Mean of log(BMI)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="anovasmart_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, we see a warning flag because we have one combination (which turns out to be Insufficiently Active and Hispanic) with only one observation in it, so a standard deviation cannot be calculated. In general, I’ll stick with the simpler means plot most of the time.</p>
</section>
<section id="does-the-interaction-account-for-substantial-variation" class="level4" data-number="9.4.2.2">
<h4 data-number="9.4.2.2" class="anchored" data-anchor-id="does-the-interaction-account-for-substantial-variation"><span class="header-section-number">9.4.2.2</span> Does the interaction account for substantial variation?</h4>
<p>In this case, we can look at the fraction of the overall sums of squares accounted for by the interaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_5c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log(bmi)
                    Df Sum Sq Mean Sq F value    Pr(&gt;F)    
activity             3  2.060 0.68652 16.4468 1.839e-10 ***
race_eth             4  0.989 0.24716  5.9211 0.0001026 ***
activity:race_eth   12  0.324 0.02700  0.6469 0.8028368    
Residuals         1113 46.459 0.04174                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Here we have</p>
<p><span class="math display">\[
\eta^2(Interaction) = \frac{0.324}{2.058+0.990+0.324+46.456} = 0.0065
\]</span></p>
<p>so the interaction accounts for 0.65% of the variation in <code>bmi</code>. That looks pretty modest.</p>
</section>
<section id="does-the-interaction-account-for-statistically-detectable-variation" class="level4" data-number="9.4.2.3">
<h4 data-number="9.4.2.3" class="anchored" data-anchor-id="does-the-interaction-account-for-statistically-detectable-variation"><span class="header-section-number">9.4.2.3</span> Does the interaction account for statistically detectable variation?</h4>
<p>We can test this directly with the p value from the ANOVA table, which shows p = 0.803, which is far above any of our usual standards for a statistically detectable effect.</p>
<p>On the whole, I don’t think the interaction term is especially helpful in improving this model.</p>
<p>In the next chapter, we’ll look at two different examples of ANOVA models, now in more designed experiments. We’ll also add some additional details on how the analyses might proceed.</p>
<p>We’ll return to the SMART CLE data later in these Notes.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./datasummaries.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./anovaexamples.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>