<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 26&nbsp; Zero-Inflated Models for Count Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ordinaloutcome.html" rel="next">
<link href="./count2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
        <div class="sidebar-tools-main">
    <a href="./Data-Science-for-Biological,-Medical-and-Health-Research.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./incomplete.html" class="sidebar-item-text sidebar-link">This is work in progress</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">R Setup</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinaloutcome.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Time To Event / Survival Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup-used-here" id="toc-r-setup-used-here" class="nav-link active" data-scroll-target="#r-setup-used-here"><span class="toc-section-number">26.1</span>  R Setup Used Here</a></li>
  <li><a href="#data-load-and-subset-creation" id="toc-data-load-and-subset-creation" class="nav-link" data-scroll-target="#data-load-and-subset-creation"><span class="toc-section-number">26.2</span>  Data Load and Subset Creation</a></li>
  <li><a href="#setup-for-this-chapter" id="toc-setup-for-this-chapter" class="nav-link" data-scroll-target="#setup-for-this-chapter"><span class="toc-section-number">26.3</span>  Setup for this Chapter</a>
  <ul class="collapse">
  <li><a href="#what-will-we-demonstrate" id="toc-what-will-we-demonstrate" class="nav-link" data-scroll-target="#what-will-we-demonstrate"><span class="toc-section-number">26.3.1</span>  What Will We Demonstrate?</a></li>
  <li><a href="#extra-data-file-for-harry-and-sally" id="toc-extra-data-file-for-harry-and-sally" class="nav-link" data-scroll-target="#extra-data-file-for-harry-and-sally"><span class="toc-section-number">26.3.2</span>  Extra Data File for Harry and Sally</a></li>
  <li><a href="#previous-models-for-comparison" id="toc-previous-models-for-comparison" class="nav-link" data-scroll-target="#previous-models-for-comparison"><span class="toc-section-number">26.3.3</span>  Previous Models (for comparison)</a></li>
  </ul></li>
  <li><a href="#the-zero-inflated-poisson-regression-model" id="toc-the-zero-inflated-poisson-regression-model" class="nav-link" data-scroll-target="#the-zero-inflated-poisson-regression-model"><span class="toc-section-number">26.4</span>  The Zero-Inflated Poisson Regression Model</a>
  <ul class="collapse">
  <li><a href="#comparison-to-a-null-model" id="toc-comparison-to-a-null-model" class="nav-link" data-scroll-target="#comparison-to-a-null-model"><span class="toc-section-number">26.4.1</span>  Comparison to a null model</a></li>
  <li><a href="#comparison-to-a-poisson-model-with-the-vuong-test" id="toc-comparison-to-a-poisson-model-with-the-vuong-test" class="nav-link" data-scroll-target="#comparison-to-a-poisson-model-with-the-vuong-test"><span class="toc-section-number">26.4.2</span>  Comparison to a Poisson Model with the Vuong test</a></li>
  <li><a href="#the-fitted-equation" id="toc-the-fitted-equation" class="nav-link" data-scroll-target="#the-fitted-equation"><span class="toc-section-number">26.4.3</span>  The Fitted Equation</a></li>
  <li><a href="#interpreting-the-coefficients" id="toc-interpreting-the-coefficients" class="nav-link" data-scroll-target="#interpreting-the-coefficients"><span class="toc-section-number">26.4.4</span>  Interpreting the Coefficients</a></li>
  <li><a href="#testing-the-predictors" id="toc-testing-the-predictors" class="nav-link" data-scroll-target="#testing-the-predictors"><span class="toc-section-number">26.4.5</span>  Testing the Predictors</a></li>
  <li><a href="#store-fitted-values-and-residuals" id="toc-store-fitted-values-and-residuals" class="nav-link" data-scroll-target="#store-fitted-values-and-residuals"><span class="toc-section-number">26.4.6</span>  Store fitted values and residuals</a></li>
  <li><a href="#modeled-number-of-zero-counts" id="toc-modeled-number-of-zero-counts" class="nav-link" data-scroll-target="#modeled-number-of-zero-counts"><span class="toc-section-number">26.4.7</span>  Modeled Number of Zero Counts</a></li>
  <li><a href="#rootogram-for-zip-model" id="toc-rootogram-for-zip-model" class="nav-link" data-scroll-target="#rootogram-for-zip-model"><span class="toc-section-number">26.4.8</span>  Rootogram for ZIP model</a></li>
  <li><a href="#specify-the-r2-and-log-likelihood-values" id="toc-specify-the-r2-and-log-likelihood-values" class="nav-link" data-scroll-target="#specify-the-r2-and-log-likelihood-values"><span class="toc-section-number">26.4.9</span>  Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</a></li>
  <li><a href="#check-model-assumptions" id="toc-check-model-assumptions" class="nav-link" data-scroll-target="#check-model-assumptions"><span class="toc-section-number">26.4.10</span>  Check model assumptions</a></li>
  <li><a href="#predictions-for-harry-and-sally" id="toc-predictions-for-harry-and-sally" class="nav-link" data-scroll-target="#predictions-for-harry-and-sally"><span class="toc-section-number">26.4.11</span>  Predictions for Harry and Sally</a></li>
  </ul></li>
  <li><a href="#the-zero-inflated-negative-binomial-regression-model" id="toc-the-zero-inflated-negative-binomial-regression-model" class="nav-link" data-scroll-target="#the-zero-inflated-negative-binomial-regression-model"><span class="toc-section-number">26.5</span>  The Zero-Inflated Negative Binomial Regression Model</a>
  <ul class="collapse">
  <li><a href="#comparison-to-a-null-model-1" id="toc-comparison-to-a-null-model-1" class="nav-link" data-scroll-target="#comparison-to-a-null-model-1"><span class="toc-section-number">26.5.1</span>  Comparison to a null model</a></li>
  <li><a href="#comparison-to-a-negative-binomial-model-vuong-test" id="toc-comparison-to-a-negative-binomial-model-vuong-test" class="nav-link" data-scroll-target="#comparison-to-a-negative-binomial-model-vuong-test"><span class="toc-section-number">26.5.2</span>  Comparison to a Negative Binomial Model: Vuong test</a></li>
  <li><a href="#the-fitted-equation-1" id="toc-the-fitted-equation-1" class="nav-link" data-scroll-target="#the-fitted-equation-1"><span class="toc-section-number">26.5.3</span>  The Fitted Equation</a></li>
  <li><a href="#interpreting-the-coefficients-1" id="toc-interpreting-the-coefficients-1" class="nav-link" data-scroll-target="#interpreting-the-coefficients-1"><span class="toc-section-number">26.5.4</span>  Interpreting the Coefficients</a></li>
  <li><a href="#testing-the-predictors-1" id="toc-testing-the-predictors-1" class="nav-link" data-scroll-target="#testing-the-predictors-1"><span class="toc-section-number">26.5.5</span>  Testing the Predictors</a></li>
  <li><a href="#store-fitted-values-and-residuals-1" id="toc-store-fitted-values-and-residuals-1" class="nav-link" data-scroll-target="#store-fitted-values-and-residuals-1"><span class="toc-section-number">26.5.6</span>  Store fitted values and residuals</a></li>
  <li><a href="#modeled-number-of-zero-counts-1" id="toc-modeled-number-of-zero-counts-1" class="nav-link" data-scroll-target="#modeled-number-of-zero-counts-1"><span class="toc-section-number">26.5.7</span>  Modeled Number of Zero Counts</a></li>
  <li><a href="#rootogram-for-zero-inflated-negative-binomial-model" id="toc-rootogram-for-zero-inflated-negative-binomial-model" class="nav-link" data-scroll-target="#rootogram-for-zero-inflated-negative-binomial-model"><span class="toc-section-number">26.5.8</span>  Rootogram for Zero-Inflated Negative Binomial model</a></li>
  <li><a href="#specify-the-r2-and-log-likelihood-values-1" id="toc-specify-the-r2-and-log-likelihood-values-1" class="nav-link" data-scroll-target="#specify-the-r2-and-log-likelihood-values-1"><span class="toc-section-number">26.5.9</span>  Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</a></li>
  <li><a href="#check-model-assumptions-1" id="toc-check-model-assumptions-1" class="nav-link" data-scroll-target="#check-model-assumptions-1"><span class="toc-section-number">26.5.10</span>  Check model assumptions</a></li>
  <li><a href="#predictions-for-harry-and-sally-1" id="toc-predictions-for-harry-and-sally-1" class="nav-link" data-scroll-target="#predictions-for-harry-and-sally-1"><span class="toc-section-number">26.5.11</span>  Predictions for Harry and Sally</a></li>
  </ul></li>
  <li><a href="#a-hurdle-model-with-poisson" id="toc-a-hurdle-model-with-poisson" class="nav-link" data-scroll-target="#a-hurdle-model-with-poisson"><span class="toc-section-number">26.6</span>  A “hurdle” model (with Poisson)</a>
  <ul class="collapse">
  <li><a href="#comparison-to-a-null-model-2" id="toc-comparison-to-a-null-model-2" class="nav-link" data-scroll-target="#comparison-to-a-null-model-2"><span class="toc-section-number">26.6.1</span>  Comparison to a null model</a></li>
  <li><a href="#comparison-to-a-poisson-model-vuong-test" id="toc-comparison-to-a-poisson-model-vuong-test" class="nav-link" data-scroll-target="#comparison-to-a-poisson-model-vuong-test"><span class="toc-section-number">26.6.2</span>  Comparison to a Poisson Model: Vuong test</a></li>
  <li><a href="#comparison-to-a-zero-inflated-poisson-model-vuong-test" id="toc-comparison-to-a-zero-inflated-poisson-model-vuong-test" class="nav-link" data-scroll-target="#comparison-to-a-zero-inflated-poisson-model-vuong-test"><span class="toc-section-number">26.6.3</span>  Comparison to a Zero-Inflated Poisson Model: Vuong test</a></li>
  <li><a href="#the-fitted-equation-2" id="toc-the-fitted-equation-2" class="nav-link" data-scroll-target="#the-fitted-equation-2"><span class="toc-section-number">26.6.4</span>  The Fitted Equation</a></li>
  <li><a href="#interpreting-the-coefficients-2" id="toc-interpreting-the-coefficients-2" class="nav-link" data-scroll-target="#interpreting-the-coefficients-2"><span class="toc-section-number">26.6.5</span>  Interpreting the Coefficients</a></li>
  <li><a href="#testing-the-predictors-2" id="toc-testing-the-predictors-2" class="nav-link" data-scroll-target="#testing-the-predictors-2"><span class="toc-section-number">26.6.6</span>  Testing the Predictors</a></li>
  <li><a href="#store-fitted-values-and-residuals-2" id="toc-store-fitted-values-and-residuals-2" class="nav-link" data-scroll-target="#store-fitted-values-and-residuals-2"><span class="toc-section-number">26.6.7</span>  Store fitted values and residuals</a></li>
  <li><a href="#modeled-number-of-zero-counts-2" id="toc-modeled-number-of-zero-counts-2" class="nav-link" data-scroll-target="#modeled-number-of-zero-counts-2"><span class="toc-section-number">26.6.8</span>  Modeled Number of Zero Counts</a></li>
  <li><a href="#rootogram-for-hurdle-model" id="toc-rootogram-for-hurdle-model" class="nav-link" data-scroll-target="#rootogram-for-hurdle-model"><span class="toc-section-number">26.6.9</span>  Rootogram for Hurdle Model</a></li>
  <li><a href="#understanding-the-modeled-counts-in-detail" id="toc-understanding-the-modeled-counts-in-detail" class="nav-link" data-scroll-target="#understanding-the-modeled-counts-in-detail"><span class="toc-section-number">26.6.10</span>  Understanding the Modeled Counts in Detail</a></li>
  <li><a href="#specify-the-r2-and-log-likelihood-values-2" id="toc-specify-the-r2-and-log-likelihood-values-2" class="nav-link" data-scroll-target="#specify-the-r2-and-log-likelihood-values-2"><span class="toc-section-number">26.6.11</span>  Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</a></li>
  <li><a href="#check-model-assumptions-2" id="toc-check-model-assumptions-2" class="nav-link" data-scroll-target="#check-model-assumptions-2"><span class="toc-section-number">26.6.12</span>  Check model assumptions</a></li>
  <li><a href="#predictions-for-harry-and-sally-2" id="toc-predictions-for-harry-and-sally-2" class="nav-link" data-scroll-target="#predictions-for-harry-and-sally-2"><span class="toc-section-number">26.6.13</span>  Predictions for Harry and Sally</a></li>
  </ul></li>
  <li><a href="#a-hurdle-model-with-negative-binomial-for-overdispersion" id="toc-a-hurdle-model-with-negative-binomial-for-overdispersion" class="nav-link" data-scroll-target="#a-hurdle-model-with-negative-binomial-for-overdispersion"><span class="toc-section-number">26.7</span>  A “hurdle” model (with negative binomial for overdispersion)</a>
  <ul class="collapse">
  <li><a href="#comparison-to-a-null-model-3" id="toc-comparison-to-a-null-model-3" class="nav-link" data-scroll-target="#comparison-to-a-null-model-3"><span class="toc-section-number">26.7.1</span>  Comparison to a null model</a></li>
  <li><a href="#comparison-to-a-negative-binomial-model-vuong-test-1" id="toc-comparison-to-a-negative-binomial-model-vuong-test-1" class="nav-link" data-scroll-target="#comparison-to-a-negative-binomial-model-vuong-test-1"><span class="toc-section-number">26.7.2</span>  Comparison to a Negative Binomial Model: Vuong test</a></li>
  <li><a href="#comparison-to-a-zero-inflated-nb-model-vuong-test" id="toc-comparison-to-a-zero-inflated-nb-model-vuong-test" class="nav-link" data-scroll-target="#comparison-to-a-zero-inflated-nb-model-vuong-test"><span class="toc-section-number">26.7.3</span>  Comparison to a Zero-Inflated NB Model: Vuong test</a></li>
  <li><a href="#comparing-the-hurdle-models-with-aic-and-bic" id="toc-comparing-the-hurdle-models-with-aic-and-bic" class="nav-link" data-scroll-target="#comparing-the-hurdle-models-with-aic-and-bic"><span class="toc-section-number">26.7.4</span>  Comparing the Hurdle Models with AIC and BIC</a></li>
  <li><a href="#the-fitted-equation-3" id="toc-the-fitted-equation-3" class="nav-link" data-scroll-target="#the-fitted-equation-3"><span class="toc-section-number">26.7.5</span>  The Fitted Equation</a></li>
  <li><a href="#interpreting-the-coefficients-3" id="toc-interpreting-the-coefficients-3" class="nav-link" data-scroll-target="#interpreting-the-coefficients-3"><span class="toc-section-number">26.7.6</span>  Interpreting the Coefficients</a></li>
  <li><a href="#testing-the-predictors-3" id="toc-testing-the-predictors-3" class="nav-link" data-scroll-target="#testing-the-predictors-3"><span class="toc-section-number">26.7.7</span>  Testing the Predictors</a></li>
  <li><a href="#store-fitted-values-and-residuals-3" id="toc-store-fitted-values-and-residuals-3" class="nav-link" data-scroll-target="#store-fitted-values-and-residuals-3"><span class="toc-section-number">26.7.8</span>  Store fitted values and residuals</a></li>
  <li><a href="#rootogram-for-nb-hurdle-model" id="toc-rootogram-for-nb-hurdle-model" class="nav-link" data-scroll-target="#rootogram-for-nb-hurdle-model"><span class="toc-section-number">26.7.9</span>  Rootogram for NB Hurdle Model</a></li>
  <li><a href="#specify-the-r2-and-log-likelihood-values-3" id="toc-specify-the-r2-and-log-likelihood-values-3" class="nav-link" data-scroll-target="#specify-the-r2-and-log-likelihood-values-3"><span class="toc-section-number">26.7.10</span>  Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</a></li>
  <li><a href="#check-model-assumptions-3" id="toc-check-model-assumptions-3" class="nav-link" data-scroll-target="#check-model-assumptions-3"><span class="toc-section-number">26.7.11</span>  Check model assumptions</a></li>
  <li><a href="#predictions-for-harry-and-sally-3" id="toc-predictions-for-harry-and-sally-3" class="nav-link" data-scroll-target="#predictions-for-harry-and-sally-3"><span class="toc-section-number">26.7.12</span>  Predictions for Harry and Sally</a></li>
  <li><a href="#note-fitting-a-different-hurdle-model-for-counts-and-przero" id="toc-note-fitting-a-different-hurdle-model-for-counts-and-przero" class="nav-link" data-scroll-target="#note-fitting-a-different-hurdle-model-for-counts-and-przero"><span class="toc-section-number">26.7.13</span>  Note: Fitting a Different Hurdle Model for Counts and Pr(zero)</a></li>
  <li><a href="#hanging-rootogram-for-this-new-hurdle-model" id="toc-hanging-rootogram-for-this-new-hurdle-model" class="nav-link" data-scroll-target="#hanging-rootogram-for-this-new-hurdle-model"><span class="toc-section-number">26.7.14</span>  Hanging Rootogram for this new Hurdle Model</a></li>
  </ul></li>
  <li><a href="#a-tobit-censored-regression-model" id="toc-a-tobit-censored-regression-model" class="nav-link" data-scroll-target="#a-tobit-censored-regression-model"><span class="toc-section-number">26.8</span>  A Tobit (Censored) Regression Model</a>
  <ul class="collapse">
  <li><a href="#the-fitted-equation-4" id="toc-the-fitted-equation-4" class="nav-link" data-scroll-target="#the-fitted-equation-4"><span class="toc-section-number">26.8.1</span>  The Fitted Equation</a></li>
  <li><a href="#interpreting-the-coefficients-4" id="toc-interpreting-the-coefficients-4" class="nav-link" data-scroll-target="#interpreting-the-coefficients-4"><span class="toc-section-number">26.8.2</span>  Interpreting the Coefficients</a></li>
  <li><a href="#testing-the-predictors-4" id="toc-testing-the-predictors-4" class="nav-link" data-scroll-target="#testing-the-predictors-4"><span class="toc-section-number">26.8.3</span>  Testing the Predictors</a></li>
  <li><a href="#store-fitted-values-and-residuals-4" id="toc-store-fitted-values-and-residuals-4" class="nav-link" data-scroll-target="#store-fitted-values-and-residuals-4"><span class="toc-section-number">26.8.4</span>  Store fitted values and residuals</a></li>
  <li><a href="#building-something-like-a-rootogram" id="toc-building-something-like-a-rootogram" class="nav-link" data-scroll-target="#building-something-like-a-rootogram"><span class="toc-section-number">26.8.5</span>  Building Something Like a Rootogram</a></li>
  <li><a href="#tables-of-the-observed-and-fitted-physhealth-from-tobit" id="toc-tables-of-the-observed-and-fitted-physhealth-from-tobit" class="nav-link" data-scroll-target="#tables-of-the-observed-and-fitted-physhealth-from-tobit"><span class="toc-section-number">26.8.6</span>  Tables of the Observed and Fitted <code>physhealth</code> from Tobit</a></li>
  <li><a href="#specify-the-r2-and-log-likelihood-values-4" id="toc-specify-the-r2-and-log-likelihood-values-4" class="nav-link" data-scroll-target="#specify-the-r2-and-log-likelihood-values-4"><span class="toc-section-number">26.8.7</span>  Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</a></li>
  <li><a href="#check-model-assumptions-4" id="toc-check-model-assumptions-4" class="nav-link" data-scroll-target="#check-model-assumptions-4"><span class="toc-section-number">26.8.8</span>  Check model assumptions</a></li>
  <li><a href="#predictions-for-harry-and-sally-4" id="toc-predictions-for-harry-and-sally-4" class="nav-link" data-scroll-target="#predictions-for-harry-and-sally-4"><span class="toc-section-number">26.8.9</span>  Predictions for Harry and Sally</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-count3" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>We will continue to use a count outcome (# of poor physical health days out of the last 30) in OHIO SMART data created in <a href="smart.html"><span>Chapter&nbsp;6</span></a> to demonstrate regression models for count outcomes, as we did in <a href="count1.html"><span>Chapter&nbsp;24</span></a> and <a href="count2.html"><span>Chapter&nbsp;25</span></a>.</p>
<p>Methods discussed in the chapter include:</p>
<ul>
<li>Zero-inflated Poisson Regression</li>
<li>Zero-inflated Negative Binomial Regression</li>
<li>Two different types of “hurdle” model</li>
<li>A Tobit (Censored) Regression Model</li>
</ul>
<section id="r-setup-used-here" class="level2" data-number="26.1">
<h2 data-number="26.1" class="anchored" data-anchor-id="r-setup-used-here"><span class="header-section-number">26.1</span> R Setup Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pscl)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(VGAM)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-load-and-subset-creation" class="level2" data-number="26.2">
<h2 data-number="26.2" class="anchored" data-anchor-id="data-load-and-subset-creation"><span class="header-section-number">26.2</span> Data Load and Subset Creation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>smart_oh <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/smart_ohio.Rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As in <a href="count1.html"><span>Chapter&nbsp;24</span></a> and <a href="count2.html"><span>Chapter&nbsp;25</span></a>, we’ll create a subset of these data for analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ohioA <span class="ot">&lt;-</span> smart_oh <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(SEQNO, mmsa_name, genhealth, physhealth, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>           menthealth, healthplan, costprob, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>           agegroup, female, incomegroup, bmi, smoke100, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>           alcdays) <span class="sc">|&gt;</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">drop_na</span>()</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>ohioA_young <span class="ot">&lt;-</span> ohioA <span class="sc">|&gt;</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(agegroup <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"18-24"</span>, <span class="st">"25-29"</span>, <span class="st">"30-34"</span>, </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"35-39"</span>, <span class="st">"40-44"</span>, <span class="st">"45-49"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">droplevels</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bmi_c =</span> bmi <span class="sc">-</span> <span class="fu">mean</span>(bmi))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="setup-for-this-chapter" class="level2" data-number="26.3">
<h2 data-number="26.3" class="anchored" data-anchor-id="setup-for-this-chapter"><span class="header-section-number">26.3</span> Setup for this Chapter</h2>
<p>Again, we’re going to predict <code>physhealth</code> using <code>bmi_c</code> and <code>smoke100</code>.</p>
<ul>
<li>Remember that <code>physhealth</code> is a count of the number of poor physical health days in the past 30.</li>
<li>As a result, <code>physhealth</code> is restricted to taking values between 0 and 30.</li>
</ul>
<p>In this chapter, we demonstrate:</p>
<ul>
<li>Zero-inflated Poisson models</li>
<li>Zero-inflated Negative Binomial models</li>
<li>Hurdle models</li>
<li>Tobit models</li>
</ul>
<section id="what-will-we-demonstrate" class="level3" data-number="26.3.1">
<h3 data-number="26.3.1" class="anchored" data-anchor-id="what-will-we-demonstrate"><span class="header-section-number">26.3.1</span> What Will We Demonstrate?</h3>
<p>With each new approach, we again will fit the model and specify procedures for doing so in R. Then we will:</p>
<ol type="1">
<li>Specify the fitted model equation</li>
<li>Interpret the model’s coefficient estimates and 95% confidence intervals around those estimates.</li>
<li>Perform a test of whether each variable adds value to the model, when the other one is already included.</li>
<li>Store the fitted values and appropriate residuals for each model.</li>
<li>Summarize the model’s apparent <span class="math inline">\(R^2\)</span> value, the proportion of variation explained, and the model log likelihood.</li>
<li>Perform checks of model assumptions as appropriate.</li>
<li>Describe how predictions would be made for two new subjects.
<ul>
<li>Harry has a BMI that is 10 kg/m<sup>2</sup> higher than the average across all respondents and has smoked more than 100 cigarettes in his life.</li>
<li>Sally has a BMI that is 5 kg/m<sup>2</sup> less than the average across all respondents and has not smoked more than 100 cigarettes in her life.</li>
</ul></li>
</ol>
<p>In addition, for some of the new models, we provide a little of the mathematical background, and point to other resources you can use to learn more about the model.</p>
</section>
<section id="extra-data-file-for-harry-and-sally" class="level3" data-number="26.3.2">
<h3 data-number="26.3.2" class="anchored" data-anchor-id="extra-data-file-for-harry-and-sally"><span class="header-section-number">26.3.2</span> Extra Data File for Harry and Sally</h3>
<p>To make our lives a little easier, I’ll create a little tibble containing the necessary data for Harry and Sally.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hs_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">subj =</span> <span class="fu">c</span>(<span class="st">"Harry"</span>, <span class="st">"Sally"</span>),</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">bmi_c =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="sc">-</span><span class="dv">5</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">smoke100 =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>hs_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  subj  bmi_c smoke100
  &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;
1 Harry    10        1
2 Sally    -5        0</code></pre>
</div>
</div>
</section>
<section id="previous-models-for-comparison" class="level3" data-number="26.3.3">
<h3 data-number="26.3.3" class="anchored" data-anchor-id="previous-models-for-comparison"><span class="header-section-number">26.3.3</span> Previous Models (for comparison)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mod_poiss1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(physhealth <span class="sc">~</span> bmi_c <span class="sc">+</span> smoke100, </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">poisson</span>(),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> ohioA_young)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>mod_nb1 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(physhealth <span class="sc">~</span> bmi_c <span class="sc">+</span> smoke100, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">link =</span> log,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> ohioA_young)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="the-zero-inflated-poisson-regression-model" class="level2" data-number="26.4">
<h2 data-number="26.4" class="anchored" data-anchor-id="the-zero-inflated-poisson-regression-model"><span class="header-section-number">26.4</span> The Zero-Inflated Poisson Regression Model</h2>
<p>There are at least two ways to tackle the problem of not predicting enough 0 values.</p>
<ul>
<li>Fitting a model which deliberately inflates the number of zeros that are fitted</li>
<li>Fitting a hurdle model</li>
</ul>
<p>The zero-inflated Poisson or (ZIP) model is used to describe count data with an excess of zero counts<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. The model posits that there are two processes involved:</p>
<ul>
<li>a logit model is used to predict excess zeros</li>
<li>while a Poisson model is used to predict the counts, generally</li>
</ul>
<p>The <code>pscl</code> package is used here, which can conflict with the <code>countreg</code> package we used to fit rootograms.</p>
<p>To run the zero-inflated Poisson model, we use the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mod_zip1 <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(physhealth <span class="sc">~</span> bmi_c <span class="sc">+</span> smoke100, </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> ohioA_young)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_zip1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
zeroinfl(formula = physhealth ~ bmi_c + smoke100, data = ohioA_young)

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-1.4389 -0.6987 -0.6138 -0.1947  9.3036 

Count model coefficients (poisson with log link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 1.997594   0.018797   106.3   &lt;2e-16 ***
bmi_c       0.018176   0.001398    13.0   &lt;2e-16 ***
smoke100    0.393383   0.024889    15.8   &lt;2e-16 ***

Zero-inflation model coefficients (binomial with logit link):
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  0.682427   0.062853  10.857  &lt; 2e-16 ***
bmi_c       -0.027731   0.006509  -4.260 2.04e-05 ***
smoke100    -0.237224   0.095318  -2.489   0.0128 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Number of iterations in BFGS optimization: 8 
Log-likelihood: -5680 on 6 Df</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_zip1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        2.5 %      97.5 %
count_(Intercept)  1.96075280  2.03443546
count_bmi_c        0.01543576  0.02091718
count_smoke100     0.34460096  0.44216461
zero_(Intercept)   0.55923725  0.80561744
zero_bmi_c        -0.04048828 -0.01497359
zero_smoke100     -0.42404310 -0.05040515</code></pre>
</div>
</div>
<p>The output describes two separate regression models. Below the model call, we see information on a Poisson regression model. Then we see another block describing the inflation model.</p>
<p>Each predictor (<code>bmi_c</code> and <code>smoke100</code>) appears to be statistically significant in each part of the model.</p>
<section id="comparison-to-a-null-model" class="level3" data-number="26.4.1">
<h3 data-number="26.4.1" class="anchored" data-anchor-id="comparison-to-a-null-model"><span class="header-section-number">26.4.1</span> Comparison to a null model</h3>
<p>To show that this model fits better than the null model (the model with intercept only), we can compare them directly with a chi-squared test. Since we have two predictors in the full model, the degrees of freedom for this test is 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mod_zipnull <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">zeroinfl</span>(physhealth <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> ohioA_young)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_zipnull)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
pscl::zeroinfl(formula = physhealth ~ 1, data = ohioA_young)

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-0.6934 -0.6934 -0.6934 -0.2779  5.5400 

Count model coefficients (poisson with log link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  2.22764    0.01233   180.7   &lt;2e-16 ***

Zero-inflation model coefficients (binomial with logit link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.5767     0.0469   12.29   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Number of iterations in BFGS optimization: 2 
Log-likelihood: -5908 on 2 Df</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(mod_zip1) <span class="sc">-</span> <span class="fu">logLik</span>(mod_zipnull)), <span class="at">df =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' 8.59676e-100 (df=6)</code></pre>
</div>
</div>
</section>
<section id="comparison-to-a-poisson-model-with-the-vuong-test" class="level3" data-number="26.4.2">
<h3 data-number="26.4.2" class="anchored" data-anchor-id="comparison-to-a-poisson-model-with-the-vuong-test"><span class="header-section-number">26.4.2</span> Comparison to a Poisson Model with the Vuong test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vuong</span>(mod_zip1, mod_poiss1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Vuong Non-Nested Hypothesis Test-Statistic: 
(test-statistic is asymptotically distributed N(0,1) under the
 null that the models are indistinguishible)
-------------------------------------------------------------
              Vuong z-statistic             H_A    p-value
Raw                    19.90843 model1 &gt; model2 &lt; 2.22e-16
AIC-corrected          19.89681 model1 &gt; model2 &lt; 2.22e-16
BIC-corrected          19.86434 model1 &gt; model2 &lt; 2.22e-16</code></pre>
</div>
</div>
<p>Certainly, the ZIP model is a significant improvement over the standard Poisson model, as the Vuong test reveals.</p>
</section>
<section id="the-fitted-equation" class="level3" data-number="26.4.3">
<h3 data-number="26.4.3" class="anchored" data-anchor-id="the-fitted-equation"><span class="header-section-number">26.4.3</span> The Fitted Equation</h3>
<p>The form of the model equation for a zero-inflated Poisson regression requires us to take two separate models into account. First we have a logistic regression model to predict the log odds of zero <code>physhealth</code> days. That takes care of the <em>extra</em> zeros. Then, to predict the number of <code>physhealth</code> days, we have a Poisson model, which may produce some additional zero count estimates.</p>
</section>
<section id="interpreting-the-coefficients" class="level3" data-number="26.4.4">
<h3 data-number="26.4.4" class="anchored" data-anchor-id="interpreting-the-coefficients"><span class="header-section-number">26.4.4</span> Interpreting the Coefficients</h3>
<p>We can exponentiate the logistic regression coefficients to obtain results in terms of odds ratios for that model, and that can be of some help in understanding the process behind excess zeros.</p>
<p>Also, exponentiating the coefficients of the count model help us describe those counts on the original scale of <code>physhealth</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mod_zip1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>count_(Intercept)       count_bmi_c    count_smoke100  zero_(Intercept) 
        7.3713003         1.0183427         1.4819856         1.9786748 
       zero_bmi_c     zero_smoke100 
        0.9726500         0.7888145 </code></pre>
</div>
</div>
<p>For example,</p>
<ul>
<li>in the model for <code>physhealth</code> = 0, the odds of <code>physhealth</code> = 0 are 79% as high for subjects with <code>smoke100</code> = 1 as for non-smokers with the same BMI.</li>
<li>in the Poisson model for <code>physhealth</code>, the <code>physhealth</code> count is estimated to increase by 1.48 for smokers as compared to non-smokers with the same BMI.</li>
</ul>
</section>
<section id="testing-the-predictors" class="level3" data-number="26.4.5">
<h3 data-number="26.4.5" class="anchored" data-anchor-id="testing-the-predictors"><span class="header-section-number">26.4.5</span> Testing the Predictors</h3>
<p>We can test the model with and without <code>bmi_c</code>, for example, by fitting the model both ways, and comparing the results with either a Wald or Likelihood Ratio test, each of which is available in the <code>lmtest</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mod_zip1_nobmi <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(physhealth <span class="sc">~</span> smoke100, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> ohioA_young)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">waldtest</span>(mod_zip1, mod_zip1_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  Res.Df Df Chisq Pr(&gt;Chisq)    
1   1968                        
2   1970 -2 187.2  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">lrtest</span>(mod_zip1, mod_zip1_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  #Df  LogLik Df  Chisq Pr(&gt;Chisq)    
1   6 -5679.8                         
2   4 -5769.5 -2 179.35  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="store-fitted-values-and-residuals" class="level3" data-number="26.4.6">
<h3 data-number="26.4.6" class="anchored" data-anchor-id="store-fitted-values-and-residuals"><span class="header-section-number">26.4.6</span> Store fitted values and residuals</h3>
<p>The <code>broom</code> package does not work with the <code>zeroinfl</code> tool. So we need to build up the fitted values and residuals ourselves.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sm_zip1 <span class="ot">&lt;-</span> ohioA_young <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(mod_zip1, <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">resid =</span> <span class="fu">resid</span>(mod_zip1, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>sm_zip1 <span class="sc">|&gt;</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(physhealth, fitted, resid) <span class="sc">|&gt;</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  physhealth fitted resid
       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1          0   2.21 -2.21
2          0   2.28 -2.28
3          0   3.12 -3.12
4         30   5.27 24.7 
5          0   3.17 -3.17
6          0   3.71 -3.71</code></pre>
</div>
</div>
</section>
<section id="modeled-number-of-zero-counts" class="level3" data-number="26.4.7">
<h3 data-number="26.4.7" class="anchored" data-anchor-id="modeled-number-of-zero-counts"><span class="header-section-number">26.4.7</span> Modeled Number of Zero Counts</h3>
<p>The zero-inflated model is designed to perfectly match the number of observed zeros. We can compare the observed number of zero <code>physhealth</code> results to the expected number of zero values from the likelihood-based models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="st">"Obs"</span> <span class="ot">=</span> <span class="fu">sum</span>(ohioA_young<span class="sc">$</span>physhealth <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Poisson"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">dpois</span>(<span class="dv">0</span>, <span class="fu">fitted</span>(mod_poiss1))),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"NB"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">dnbinom</span>(<span class="dv">0</span>, <span class="at">mu =</span> <span class="fu">fitted</span>(mod_nb1), <span class="at">size =</span> mod_nb1<span class="sc">$</span>theta)),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ZIP"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">predict</span>(mod_zip1, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">1</span>])), <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Obs Poisson      NB     ZIP 
   1264     124    1250    1264 </code></pre>
</div>
</div>
</section>
<section id="rootogram-for-zip-model" class="level3" data-number="26.4.8">
<h3 data-number="26.4.8" class="anchored" data-anchor-id="rootogram-for-zip-model"><span class="header-section-number">26.4.8</span> Rootogram for ZIP model</h3>
<p>Here’s the rootogram for the zero-inflated Poisson model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>countreg<span class="sc">::</span><span class="fu">rootogram</span>(mod_zip1, <span class="at">max =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The zero frequencies are perfectly matched here, but we can see that counts of 1 and 2 are now substantially underfit, and values between 6 and 13 are overfit.</p>
</section>
<section id="specify-the-r2-and-log-likelihood-values" class="level3" data-number="26.4.9">
<h3 data-number="26.4.9" class="anchored" data-anchor-id="specify-the-r2-and-log-likelihood-values"><span class="header-section-number">26.4.9</span> Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</h3>
<p>We can calculate a proxy for <span class="math inline">\(R^2\)</span> as the squared correlation of the fitted values and the observed values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The correlation of observed and fitted values</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>(zip_r <span class="ot">&lt;-</span> <span class="fu">with</span>(sm_zip1, <span class="fu">cor</span>(physhealth, fitted)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.187328</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R-square</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>zip_r<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03509178</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(mod_zip1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -5679.794 (df=6)</code></pre>
</div>
</div>
<p>Here, we have</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Model</th>
<th style="text-align: right;">Scale</th>
<th style="text-align: right;"><span class="math inline">\(R^2\)</span></th>
<th style="text-align: right;">log(likelihood)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Zero-Inflated Poisson</td>
<td style="text-align: right;">Complex: log(<code>physhealth</code>)</td>
<td style="text-align: right;">.035</td>
<td style="text-align: right;">-5679.83</td>
</tr>
</tbody>
</table>
</section>
<section id="check-model-assumptions" class="level3" data-number="26.4.10">
<h3 data-number="26.4.10" class="anchored" data-anchor-id="check-model-assumptions"><span class="header-section-number">26.4.10</span> Check model assumptions</h3>
<p>Here is a plot of residuals vs.&nbsp;fitted values on the original <code>physhealth</code> scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_zip1, <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> resid)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs. Fitted `physhealth`"</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"Zero-Inflated Poisson Regression model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="predictions-for-harry-and-sally" class="level3" data-number="26.4.11">
<h3 data-number="26.4.11" class="anchored" data-anchor-id="predictions-for-harry-and-sally"><span class="header-section-number">26.4.11</span> Predictions for Harry and Sally</h3>
<p>The predictions from this ZIP regression model are obtained as follows…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod_zip1, <span class="at">newdata =</span> hs_data, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
6.002212 2.056525 </code></pre>
</div>
</div>
<p>As we’ve seen in the past, when we use <code>response</code> as the type, the predictions fall on the original <code>physhealth</code> scale. The prediction for Harry is 6.0 days, and for Sally is 2.1 days.</p>
</section>
</section>
<section id="the-zero-inflated-negative-binomial-regression-model" class="level2" data-number="26.5">
<h2 data-number="26.5" class="anchored" data-anchor-id="the-zero-inflated-negative-binomial-regression-model"><span class="header-section-number">26.5</span> The Zero-Inflated Negative Binomial Regression Model</h2>
<p>As an alternative to the ZIP model, we might consider a zero-inflated negative binomial regression<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. This will involve a logistic regression to predict the probability of a 0, and then a negative binomial model to describe the counts of <code>physhealth</code>.</p>
<p>To run the zero-inflated negative binomial model, we use the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>mod_zinb1 <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">zeroinfl</span>(physhealth <span class="sc">~</span> bmi_c <span class="sc">+</span> smoke100, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">dist =</span> <span class="st">"negbin"</span>, <span class="at">data =</span> ohioA_young)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_zinb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
pscl::zeroinfl(formula = physhealth ~ bmi_c + smoke100, data = ohioA_young, 
    dist = "negbin")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-0.5579 -0.4192 -0.3957 -0.1166  6.4358 

Count model coefficients (negbin with log link):
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.545599   0.099781  15.490  &lt; 2e-16 ***
bmi_c        0.024614   0.006641   3.707  0.00021 ***
smoke100     0.517559   0.110772   4.672 2.98e-06 ***
Log(theta)  -0.874034   0.143876  -6.075 1.24e-09 ***

Zero-inflation model coefficients (binomial with logit link):
             Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept) -0.071629   0.164039  -0.437  0.66236   
bmi_c       -0.027607   0.009313  -2.964  0.00303 **
smoke100    -0.127004   0.137171  -0.926  0.35451   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Theta = 0.4173 
Number of iterations in BFGS optimization: 14 
Log-likelihood: -3469 on 7 Df</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_zinb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        2.5 %       97.5 %
count_(Intercept)  1.35003234  1.741165036
count_bmi_c        0.01159892  0.037629890
count_smoke100     0.30045008  0.734668671
zero_(Intercept)  -0.39313901  0.249880357
zero_bmi_c        -0.04585974 -0.009354261
zero_smoke100     -0.39585468  0.141845790</code></pre>
</div>
</div>
<section id="comparison-to-a-null-model-1" class="level3" data-number="26.5.1">
<h3 data-number="26.5.1" class="anchored" data-anchor-id="comparison-to-a-null-model-1"><span class="header-section-number">26.5.1</span> Comparison to a null model</h3>
<p>To show that this model fits better than the null model (the model with intercept only), we can compare them directly with a chi-squared test. Since we have two predictors in the full model, the degrees of freedom for this test is 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>mod_zinbnull <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">zeroinfl</span>(physhealth <span class="sc">~</span> <span class="dv">1</span>, <span class="at">dist =</span> <span class="st">"negbin"</span>,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> ohioA_young)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_zinbnull)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
pscl::zeroinfl(formula = physhealth ~ 1, data = ohioA_young, dist = "negbin")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-0.4048 -0.4048 -0.4048 -0.1622  3.2340 

Count model coefficients (negbin with log link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   1.7766     0.0964  18.429  &lt; 2e-16 ***
Log(theta)   -1.0445     0.1612  -6.479 9.25e-11 ***

Zero-inflation model coefficients (binomial with logit link):
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)  -0.2605     0.1920  -1.357    0.175
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Theta = 0.3519 
Number of iterations in BFGS optimization: 12 
Log-likelihood: -3498 on 3 Df</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(mod_nb1) <span class="sc">-</span> <span class="fu">logLik</span>(mod_zinbnull)), <span class="at">df =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' 8.538917e-07 (df=4)</code></pre>
</div>
</div>
</section>
<section id="comparison-to-a-negative-binomial-model-vuong-test" class="level3" data-number="26.5.2">
<h3 data-number="26.5.2" class="anchored" data-anchor-id="comparison-to-a-negative-binomial-model-vuong-test"><span class="header-section-number">26.5.2</span> Comparison to a Negative Binomial Model: Vuong test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vuong</span>(mod_zinb1, mod_nb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Vuong Non-Nested Hypothesis Test-Statistic: 
(test-statistic is asymptotically distributed N(0,1) under the
 null that the models are indistinguishible)
-------------------------------------------------------------
              Vuong z-statistic             H_A   p-value
Raw                   3.0753499 model1 &gt; model2 0.0010513
AIC-corrected         2.4597116 model1 &gt; model2 0.0069524
BIC-corrected         0.7396743 model1 &gt; model2 0.2297488</code></pre>
</div>
</div>
<p>The zero-inflated negative binomial model is a significant improvement over the standard negative binomial model according to the the raw or AIC-corrected Vuong tests, but not according to the BIC-corrected test.</p>
</section>
<section id="the-fitted-equation-1" class="level3" data-number="26.5.3">
<h3 data-number="26.5.3" class="anchored" data-anchor-id="the-fitted-equation-1"><span class="header-section-number">26.5.3</span> The Fitted Equation</h3>
<p>Like the ZIP, the zero-inflated negative binomial regression also requires us to take two separate models into account. First we have a logistic regression model to predict the log odds of zero <code>physhealth</code> days. That takes care of the <em>extra</em> zeros. Then, to predict the number of <code>physhealth</code> days, we have a negative binomial regression, with a <span class="math inline">\(\theta\)</span> term, and this negative binomial regression model may also produce some additional zero count estimates.</p>
</section>
<section id="interpreting-the-coefficients-1" class="level3" data-number="26.5.4">
<h3 data-number="26.5.4" class="anchored" data-anchor-id="interpreting-the-coefficients-1"><span class="header-section-number">26.5.4</span> Interpreting the Coefficients</h3>
<p>As with the zip, we can exponentiate the logistic regression coefficients to obtain results in terms of odds ratios for that model, and that can be of some help in understanding the process behind excess zeros.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mod_zinb1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>count_(Intercept)       count_bmi_c    count_smoke100  zero_(Intercept) 
        4.6907791         1.0249198         1.6779275         0.9308759 
       zero_bmi_c     zero_smoke100 
        0.9727706         0.8807298 </code></pre>
</div>
</div>
<p>For example,</p>
<ul>
<li>in the model for <code>physhealth</code> = 0, the odds of <code>physhealth</code> = 0 are 88.1% as high for subjects with <code>smoke100</code> = 1 as for non-smokers with the same BMI.</li>
</ul>
<p>Interpreting the negative binomial piece works the same way as it did in the negative binomial regression.</p>
</section>
<section id="testing-the-predictors-1" class="level3" data-number="26.5.5">
<h3 data-number="26.5.5" class="anchored" data-anchor-id="testing-the-predictors-1"><span class="header-section-number">26.5.5</span> Testing the Predictors</h3>
<p>We can test the model with and without <code>bmi_c</code>, for example, by fitting the model both ways, and comparing the results with either a Wald or Likelihood Ratio test, each of which is available in the <code>lmtest</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>mod_zinb1_nobmi <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">zeroinfl</span>(physhealth <span class="sc">~</span> smoke100, </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">dist =</span> <span class="st">"negbin"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">data =</span> ohioA_young)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">waldtest</span>(mod_zinb1, mod_zinb1_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  Res.Df Df  Chisq Pr(&gt;Chisq)    
1   1967                         
2   1969 -2 29.589  3.757e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">lrtest</span>(mod_zinb1, mod_zinb1_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  #Df  LogLik Df  Chisq Pr(&gt;Chisq)    
1   7 -3469.3                         
2   5 -3485.0 -2 31.418  1.506e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="store-fitted-values-and-residuals-1" class="level3" data-number="26.5.6">
<h3 data-number="26.5.6" class="anchored" data-anchor-id="store-fitted-values-and-residuals-1"><span class="header-section-number">26.5.6</span> Store fitted values and residuals</h3>
<p>Again, we need to build up the fitted values and residuals without the <code>broom</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>sm_zinb1 <span class="ot">&lt;-</span> ohioA_young <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(mod_zinb1, <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">resid =</span> <span class="fu">resid</span>(mod_zinb1, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>sm_zip1 <span class="sc">|&gt;</span> </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(physhealth, fitted, resid) <span class="sc">|&gt;</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  physhealth fitted resid
       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1          0   2.21 -2.21
2          0   2.28 -2.28
3          0   3.12 -3.12
4         30   5.27 24.7 
5          0   3.17 -3.17
6          0   3.71 -3.71</code></pre>
</div>
</div>
</section>
<section id="modeled-number-of-zero-counts-1" class="level3" data-number="26.5.7">
<h3 data-number="26.5.7" class="anchored" data-anchor-id="modeled-number-of-zero-counts-1"><span class="header-section-number">26.5.7</span> Modeled Number of Zero Counts</h3>
<p>Once again, we can compare the observed number of zero <code>physhealth</code> results to the expected number of zero values from the likelihood-based models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="st">"Obs"</span> <span class="ot">=</span> <span class="fu">sum</span>(ohioA_young<span class="sc">$</span>physhealth <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Poisson"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">dpois</span>(<span class="dv">0</span>, <span class="fu">fitted</span>(mod_poiss1))),</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"NB"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">dnbinom</span>(<span class="dv">0</span>, <span class="at">mu =</span> <span class="fu">fitted</span>(mod_nb1), <span class="at">size =</span> mod_nb1<span class="sc">$</span>theta)),</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ZIP"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">predict</span>(mod_zip1, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">1</span>]),</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ZINB"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">predict</span>(mod_zinb1, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">1</span>])),<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Obs Poisson      NB     ZIP    ZINB 
   1264     124    1250    1264    1264 </code></pre>
</div>
</div>
<p>So, the Poisson model is clearly inappropriate, but the zero-inflated (Poisson and NB) and the negative binomial model all give reasonable fits in this regard.</p>
</section>
<section id="rootogram-for-zero-inflated-negative-binomial-model" class="level3" data-number="26.5.8">
<h3 data-number="26.5.8" class="anchored" data-anchor-id="rootogram-for-zero-inflated-negative-binomial-model"><span class="header-section-number">26.5.8</span> Rootogram for Zero-Inflated Negative Binomial model</h3>
<p>Here’s the rootogram for the zero-inflated negative binomial model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>countreg<span class="sc">::</span><span class="fu">rootogram</span>(mod_zinb1, <span class="at">max =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As in the ZIP model, the zero frequencies are perfectly matched here, but we can see that counts of 1 and 2 are now closer to the data we observe than in the ZIP model. We are still substantially underfitting values of 30.</p>
</section>
<section id="specify-the-r2-and-log-likelihood-values-1" class="level3" data-number="26.5.9">
<h3 data-number="26.5.9" class="anchored" data-anchor-id="specify-the-r2-and-log-likelihood-values-1"><span class="header-section-number">26.5.9</span> Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</h3>
<p>We can calculate a proxy for <span class="math inline">\(R^2\)</span> as the squared correlation of the fitted values and the observed values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The correlation of observed and fitted values</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>(zinb_r <span class="ot">&lt;-</span> <span class="fu">with</span>(sm_zinb1, <span class="fu">cor</span>(physhealth, fitted)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1858969</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R-square</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>zinb_r<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03455767</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(mod_zinb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -3469.29 (df=7)</code></pre>
</div>
</div>
<p>Here, we have</p>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 18%">
<col style="width: 24%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Model</th>
<th style="text-align: right;">Scale</th>
<th style="text-align: right;"><span class="math inline">\(R^2\)</span></th>
<th style="text-align: right;">log(likelihood)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Zero-Inflated Negative Binomial</td>
<td style="text-align: right;">Complex: log(<code>physhealth</code>)</td>
<td style="text-align: right;">.035</td>
<td style="text-align: right;">-3469.27</td>
</tr>
</tbody>
</table>
</section>
<section id="check-model-assumptions-1" class="level3" data-number="26.5.10">
<h3 data-number="26.5.10" class="anchored" data-anchor-id="check-model-assumptions-1"><span class="header-section-number">26.5.10</span> Check model assumptions</h3>
<p>Here is a plot of residuals vs.&nbsp;fitted values on the original <code>physhealth</code> scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_zinb1, <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> resid)) <span class="sc">+</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs. Fitted `physhealth`"</span>,</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"Zero-Inflated Negative Binomial Regression model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="predictions-for-harry-and-sally-1" class="level3" data-number="26.5.11">
<h3 data-number="26.5.11" class="anchored" data-anchor-id="predictions-for-harry-and-sally-1"><span class="header-section-number">26.5.11</span> Predictions for Harry and Sally</h3>
<p>The predictions from this zero-inflated negative binomial regression model are obtained as follows…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod_zinb1, <span class="at">newdata =</span> hs_data, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
6.206514 2.004963 </code></pre>
</div>
</div>
<p>As we’ve seen in the past, when we use <code>response</code> as the type, the predictions fall on the original <code>physhealth</code> scale. The prediction for Harry is 6.2 days, and for Sally is 2.0 days.</p>
</section>
</section>
<section id="a-hurdle-model-with-poisson" class="level2" data-number="26.6">
<h2 data-number="26.6" class="anchored" data-anchor-id="a-hurdle-model-with-poisson"><span class="header-section-number">26.6</span> A “hurdle” model (with Poisson)</h2>
<p>Much of the discussion here of hurdle models comes from Clay Ford at the University of Virginia<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Ford describes a hurdle model as follows:</p>
<blockquote class="blockquote">
<p>The hurdle model is a two-part model that specifies one process for zero counts and another process for positive counts. The idea is that positive counts occur once a threshold is crossed, or put another way, a hurdle is cleared. If the hurdle is not cleared, then we have a count of 0.</p>
</blockquote>
<blockquote class="blockquote">
<p>The first part of the model is typically a binary logit model. This models whether an observation takes a positive count or not. The second part of the model is usually a truncated Poisson or Negative Binomial model. Truncated means we’re only fitting positive counts. If we were to fit a hurdle model to our [medicare] data, the interpretation would be that one process governs whether a patient visits a doctor or not, and another process governs how many visits are made.</p>
</blockquote>
<p>To fit a hurdle model, we’ll use the <code>hurdle</code> function in the <code>pscl</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>mod_hur1 <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">hurdle</span>(physhealth <span class="sc">~</span> bmi_c <span class="sc">+</span> smoke100,</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dist =</span> <span class="st">"poisson"</span>, <span class="at">zero.dist =</span> <span class="st">"binomial"</span>,</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> ohioA_young)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_hur1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
pscl::hurdle(formula = physhealth ~ bmi_c + smoke100, data = ohioA_young, 
    dist = "poisson", zero.dist = "binomial")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-1.4403 -0.6987 -0.6139 -0.1946  9.2997 

Count model coefficients (truncated poisson with log link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 1.997612   0.018797   106.3   &lt;2e-16 ***
bmi_c       0.018178   0.001398    13.0   &lt;2e-16 ***
smoke100    0.393348   0.024889    15.8   &lt;2e-16 ***
Zero hurdle model coefficients (binomial with logit link):
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.683509   0.062827 -10.879  &lt; 2e-16 ***
bmi_c        0.027777   0.006508   4.268 1.97e-05 ***
smoke100     0.238300   0.095301   2.500   0.0124 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Number of iterations in BFGS optimization: 14 
Log-likelihood: -5680 on 6 Df</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_hur1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        2.5 %      97.5 %
count_(Intercept)  1.96077105  2.03445261
count_bmi_c        0.01543722  0.02091901
count_smoke100     0.34456599  0.44212932
zero_(Intercept)  -0.80664805 -0.56037031
zero_bmi_c         0.01502124  0.04053230
zero_smoke100      0.05151314  0.42508607</code></pre>
</div>
</div>
<p>We are using the default settings here, using the same predictors for both models:</p>
<ul>
<li>a <strong>Binomial</strong> model to predict the probability of <code>physhealth</code> = 0 given our predictors, as specified by the <code>zero.dist</code> argument in the <code>hurdle</code> function, and</li>
<li>a (truncated) <strong>Poisson</strong> model to predict the positive-count of <code>physhealth</code> given those same predictors, as specified by the <code>dist</code> argument in the <code>hurdle</code> function.</li>
</ul>
<section id="comparison-to-a-null-model-2" class="level3" data-number="26.6.1">
<h3 data-number="26.6.1" class="anchored" data-anchor-id="comparison-to-a-null-model-2"><span class="header-section-number">26.6.1</span> Comparison to a null model</h3>
<p>To show that this model fits better than the null model (the model with intercept only), we can compare them directly with a chi-squared test. Since we have two predictors in the full model, the degrees of freedom for this test is 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>mod_hurnull <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">hurdle</span>(physhealth <span class="sc">~</span> <span class="dv">1</span>, <span class="at">dist =</span> <span class="st">"poisson"</span>, </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">zero.dist =</span> <span class="st">"binomial"</span>, </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> ohioA_young)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_hurnull)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
pscl::hurdle(formula = physhealth ~ 1, data = ohioA_young, dist = "poisson", 
    zero.dist = "binomial")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-0.6934 -0.6934 -0.6934 -0.2779  5.5399 

Count model coefficients (truncated poisson with log link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  2.22765    0.01233   180.7   &lt;2e-16 ***
Zero hurdle model coefficients (binomial with logit link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.5768     0.0469   -12.3   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Number of iterations in BFGS optimization: 8 
Log-likelihood: -5908 on 2 Df</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(mod_hur1) <span class="sc">-</span> <span class="fu">logLik</span>(mod_hurnull)), <span class="at">df =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' 8.577393e-100 (df=6)</code></pre>
</div>
</div>
</section>
<section id="comparison-to-a-poisson-model-vuong-test" class="level3" data-number="26.6.2">
<h3 data-number="26.6.2" class="anchored" data-anchor-id="comparison-to-a-poisson-model-vuong-test"><span class="header-section-number">26.6.2</span> Comparison to a Poisson Model: Vuong test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vuong</span>(mod_hur1, mod_poiss1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Vuong Non-Nested Hypothesis Test-Statistic: 
(test-statistic is asymptotically distributed N(0,1) under the
 null that the models are indistinguishible)
-------------------------------------------------------------
              Vuong z-statistic             H_A    p-value
Raw                    19.90847 model1 &gt; model2 &lt; 2.22e-16
AIC-corrected          19.89685 model1 &gt; model2 &lt; 2.22e-16
BIC-corrected          19.86438 model1 &gt; model2 &lt; 2.22e-16</code></pre>
</div>
</div>
<p>The hurdle model shows a detectable improvement over the standard Poisson model according to this test.</p>
</section>
<section id="comparison-to-a-zero-inflated-poisson-model-vuong-test" class="level3" data-number="26.6.3">
<h3 data-number="26.6.3" class="anchored" data-anchor-id="comparison-to-a-zero-inflated-poisson-model-vuong-test"><span class="header-section-number">26.6.3</span> Comparison to a Zero-Inflated Poisson Model: Vuong test</h3>
<p>Is the hurdle model comparable to the zero-inflated Poisson?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vuong</span>(mod_hur1, mod_zip1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Vuong Non-Nested Hypothesis Test-Statistic: 
(test-statistic is asymptotically distributed N(0,1) under the
 null that the models are indistinguishible)
-------------------------------------------------------------
              Vuong z-statistic             H_A p-value
Raw                   0.2046181 model1 &gt; model2 0.41894
AIC-corrected         0.2046181 model1 &gt; model2 0.41894
BIC-corrected         0.2046181 model1 &gt; model2 0.41894</code></pre>
</div>
</div>
<p>The hurdle model doesn’t show a substantial improvement over the zero-inflated Poisson model according to this test.</p>
</section>
<section id="the-fitted-equation-2" class="level3" data-number="26.6.4">
<h3 data-number="26.6.4" class="anchored" data-anchor-id="the-fitted-equation-2"><span class="header-section-number">26.6.4</span> The Fitted Equation</h3>
<p>The form of the model equation for this hurdle also requires us to take two separate models into account. First we have a logistic regression model to predict the log odds of zero <code>physhealth</code> days. That takes care of the zeros. Then, to predict the number of <code>physhealth</code> days, we use a truncated Poisson model, which is truncated to produce only estimates greater than zero.</p>
</section>
<section id="interpreting-the-coefficients-2" class="level3" data-number="26.6.5">
<h3 data-number="26.6.5" class="anchored" data-anchor-id="interpreting-the-coefficients-2"><span class="header-section-number">26.6.5</span> Interpreting the Coefficients</h3>
<p>We can exponentiate the logistic regression coefficients to obtain results in terms of odds ratios for that model, and that can be of some help in understanding the process behind excess zeros.</p>
<p>Also, exponentiating the coefficients of the count model help us describe those counts on the original scale of <code>physhealth</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mod_hur1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>count_(Intercept)       count_bmi_c    count_smoke100  zero_(Intercept) 
        7.3714308         1.0183443         1.4819335         0.5048423 
       zero_bmi_c     zero_smoke100 
        1.0281661         1.2690894 </code></pre>
</div>
</div>
<p>For example,</p>
<ul>
<li>in the model for <code>physhealth</code> = 0, the odds of <code>physhealth</code> = 0 are 127% as high for subjects with <code>smoke100</code> = 1 as for non-smokers with the same BMI.</li>
<li>in the Poisson model for <code>physhealth</code>, the <code>physhealth</code> count is estimated to increase by 1.48 for smokers as compared to non-smokers with the same BMI.</li>
</ul>
</section>
<section id="testing-the-predictors-2" class="level3" data-number="26.6.6">
<h3 data-number="26.6.6" class="anchored" data-anchor-id="testing-the-predictors-2"><span class="header-section-number">26.6.6</span> Testing the Predictors</h3>
<p>We can test the model with and without <code>bmi_c</code>, for example, by fitting the model both ways, and comparing the results with either a Wald or Likelihood Ratio test, each of which is available in the <code>lmtest</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>mod_hur1_nobmi <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">hurdle</span>(physhealth <span class="sc">~</span> smoke100,</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">dist =</span> <span class="st">"poisson"</span>, </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">zero.dist =</span> <span class="st">"binomial"</span>,</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> ohioA_young)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">waldtest</span>(mod_hur1, mod_hur1_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  Res.Df Df  Chisq Pr(&gt;Chisq)    
1   1968                         
2   1970 -2 187.19  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">lrtest</span>(mod_hur1, mod_hur1_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  #Df  LogLik Df  Chisq Pr(&gt;Chisq)    
1   6 -5679.8                         
2   4 -5769.5 -2 179.35  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="store-fitted-values-and-residuals-2" class="level3" data-number="26.6.7">
<h3 data-number="26.6.7" class="anchored" data-anchor-id="store-fitted-values-and-residuals-2"><span class="header-section-number">26.6.7</span> Store fitted values and residuals</h3>
<p>The <code>broom</code> package does not work with the <code>hurdle</code> class of models. Again we need to build up the fitted values and residuals ourselves.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>sm_hur1 <span class="ot">&lt;-</span> ohioA_young <span class="sc">|&gt;</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(mod_hur1, <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">resid =</span> <span class="fu">resid</span>(mod_hur1, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>sm_hur1 <span class="sc">|&gt;</span> </span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(physhealth, fitted, resid) <span class="sc">|&gt;</span></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  physhealth fitted resid
       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1          0   2.21 -2.21
2          0   2.28 -2.28
3          0   3.12 -3.12
4         30   5.27 24.7 
5          0   3.17 -3.17
6          0   3.71 -3.71</code></pre>
</div>
</div>
</section>
<section id="modeled-number-of-zero-counts-2" class="level3" data-number="26.6.8">
<h3 data-number="26.6.8" class="anchored" data-anchor-id="modeled-number-of-zero-counts-2"><span class="header-section-number">26.6.8</span> Modeled Number of Zero Counts</h3>
<p>Once again, we can compare the observed number of zero <code>physhealth</code> results to the expected number of zero values from the likelihood-based models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="st">"Obs"</span> <span class="ot">=</span> <span class="fu">sum</span>(ohioA_young<span class="sc">$</span>physhealth <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Poisson"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">dpois</span>(<span class="dv">0</span>, <span class="fu">fitted</span>(mod_poiss1))),</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"NB"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">dnbinom</span>(<span class="dv">0</span>, <span class="at">mu =</span> <span class="fu">fitted</span>(mod_nb1), <span class="at">size =</span> mod_nb1<span class="sc">$</span>theta)),</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ZIP"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">predict</span>(mod_zip1, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">1</span>]),</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ZINB"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">predict</span>(mod_zinb1, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">1</span>]),</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hurdle"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">predict</span>(mod_hur1, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">1</span>])),<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Obs Poisson      NB     ZIP    ZINB  Hurdle 
   1264     124    1250    1264    1264    1264 </code></pre>
</div>
</div>
<p>The hurdle model does about as well as the negative binomial and zero-inflated models. All but the Poisson give reasonable fits in this regard.</p>
</section>
<section id="rootogram-for-hurdle-model" class="level3" data-number="26.6.9">
<h3 data-number="26.6.9" class="anchored" data-anchor-id="rootogram-for-hurdle-model"><span class="header-section-number">26.6.9</span> Rootogram for Hurdle Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>countreg<span class="sc">::</span><span class="fu">rootogram</span>(mod_hur1, <span class="at">max =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The results are still not perfect, of course. In fitting the zeros exactly, we’re underfitting counts of 1, 2, and 30, and overfitting many of the counts between 6 and 20. We still have a problem here with overdispersion. That’s why we’ll consider a hurdle model with a negative binomial regression for the counts in a moment.</p>
</section>
<section id="understanding-the-modeled-counts-in-detail" class="level3" data-number="26.6.10">
<h3 data-number="26.6.10" class="anchored" data-anchor-id="understanding-the-modeled-counts-in-detail"><span class="header-section-number">26.6.10</span> Understanding the Modeled Counts in Detail</h3>
<p>The expected mean count uses both parts of the hurdle model. Mathematically, we want…</p>
<p><span class="math display">\[
E[y | x] = \frac{1 - f_1(0 | x)}{1 - f_2(0 | x)} \mu_2(x)
\]</span></p>
<p>where</p>
<ul>
<li>our count of <code>physhealth</code> is <span class="math inline">\(y\)</span></li>
<li>our predictors are represented by <strong>x</strong></li>
<li>and the expected count is the product of a ratio and a mean.</li>
</ul>
<blockquote class="blockquote">
<p>The ratio is the probability of a non-zero in the first process divided the probability of a non-zero in the second untruncated process. The f symbols represent distributions. Recall these are logistic and Poisson, respectively, by default but can be others. The mean is for the untruncated version of the positive-count process.</p>
</blockquote>
<p>If we want to see the expected hurdle counts, we can get them using some clever applications of the <code>predict</code> function.</p>
<p>The first six expected mean counts (<span class="math inline">\(E[y | x]\)</span> from the equation above) are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(mod_hur1, <span class="at">type =</span> <span class="st">"response"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
2.214179 2.281482 3.116124 5.267881 3.167890 3.712120 </code></pre>
</div>
</div>
<p>The ratio of non-zero probabilities, <span class="math inline">\(\frac{1 - f_1(0 | x)}{1 - f_2(0 | x)}\)</span>, from the mathematical expression above can be extracted by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(mod_hur1, <span class="at">type =</span> <span class="st">"zero"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6 
0.3173312 0.3221978 0.3344433 0.4806542 0.3372292 0.3649208 </code></pre>
</div>
</div>
<p>The mean for the untruncated process, <span class="math inline">\(\mu_2(x)\)</span>, can also be obtained by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(mod_hur1, <span class="at">type =</span> <span class="st">"count"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6 
 6.977501  7.081000  9.317347 10.959814  9.393877 10.172401 </code></pre>
</div>
</div>
<p>and we can multiply these last two pieces together to verify that they match our expected hurdle counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(mod_hur1, <span class="at">type =</span> <span class="st">"zero"</span>) <span class="sc">*</span> <span class="fu">predict</span>(mod_hur1, <span class="at">type =</span> <span class="st">"count"</span>),<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5 
2.214179 2.281482 3.116124 5.267881 3.167890 </code></pre>
</div>
</div>
</section>
<section id="specify-the-r2-and-log-likelihood-values-2" class="level3" data-number="26.6.11">
<h3 data-number="26.6.11" class="anchored" data-anchor-id="specify-the-r2-and-log-likelihood-values-2"><span class="header-section-number">26.6.11</span> Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</h3>
<p>We can calculate a proxy for <span class="math inline">\(R^2\)</span> as the squared correlation of the fitted values and the observed values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The correlation of observed and fitted values</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>(hur1_r <span class="ot">&lt;-</span> <span class="fu">with</span>(sm_hur1, <span class="fu">cor</span>(physhealth, fitted)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1873104</code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R-square</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>hur1_r<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03508517</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(mod_hur1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -5679.792 (df=6)</code></pre>
</div>
</div>
<p>Here, we have</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Model</th>
<th style="text-align: right;">Scale</th>
<th style="text-align: right;"><span class="math inline">\(R^2\)</span></th>
<th style="text-align: right;">log(likelihood)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Hurdle Model (Poisson)</td>
<td style="text-align: right;">Complex: log(<code>physhealth</code>)</td>
<td style="text-align: right;">.035</td>
<td style="text-align: right;">-5679.83</td>
</tr>
</tbody>
</table>
</section>
<section id="check-model-assumptions-2" class="level3" data-number="26.6.12">
<h3 data-number="26.6.12" class="anchored" data-anchor-id="check-model-assumptions-2"><span class="header-section-number">26.6.12</span> Check model assumptions</h3>
<p>Here is a plot of residuals vs.&nbsp;fitted values on the original <code>physhealth</code> scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_hur1, <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> resid)) <span class="sc">+</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs. Fitted `physhealth`"</span>,</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"Hurdle model with Poisson counts"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="predictions-for-harry-and-sally-2" class="level3" data-number="26.6.13">
<h3 data-number="26.6.13" class="anchored" data-anchor-id="predictions-for-harry-and-sally-2"><span class="header-section-number">26.6.13</span> Predictions for Harry and Sally</h3>
<p>The predictions from this zero-inflated negative binomial regression model are obtained as follows…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod_hur1, <span class="at">newdata =</span> hs_data, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
6.003689 2.057127 </code></pre>
</div>
</div>
<p>As we’ve seen in the past, when we use <code>response</code> as the type, the predictions fall on the original <code>physhealth</code> scale. The prediction for Harry is 6.0 days, and for Sally is 2.1 days.</p>
</section>
</section>
<section id="a-hurdle-model-with-negative-binomial-for-overdispersion" class="level2" data-number="26.7">
<h2 data-number="26.7" class="anchored" data-anchor-id="a-hurdle-model-with-negative-binomial-for-overdispersion"><span class="header-section-number">26.7</span> A “hurdle” model (with negative binomial for overdispersion)</h2>
<p>Let’s account for overdispersion better with a negative binomial model for the counts in our hurdle model. We specify that the positive-count process be fit with this NB model using <code>dist = negbin</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>mod_hur_nb1 <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">hurdle</span>(physhealth <span class="sc">~</span> bmi_c <span class="sc">+</span> smoke100,</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dist =</span> <span class="st">"negbin"</span>, <span class="at">zero.dist =</span> <span class="st">"binomial"</span>,</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> ohioA_young)</span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_hur_nb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
pscl::hurdle(formula = physhealth ~ bmi_c + smoke100, data = ohioA_young, 
    dist = "negbin", zero.dist = "binomial")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-0.5749 -0.4178 -0.3948 -0.1165  6.4023 

Count model coefficients (truncated negbin with log link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.54170    0.10101  15.263  &lt; 2e-16 ***
bmi_c        0.02434    0.00677   3.595 0.000324 ***
smoke100     0.51792    0.11101   4.666 3.08e-06 ***
Log(theta)  -0.88245    0.14653  -6.023 1.72e-09 ***
Zero hurdle model coefficients (binomial with logit link):
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.683509   0.062827 -10.879  &lt; 2e-16 ***
bmi_c        0.027777   0.006508   4.268 1.97e-05 ***
smoke100     0.238300   0.095301   2.500   0.0124 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Theta: count = 0.4138
Number of iterations in BFGS optimization: 17 
Log-likelihood: -3469 on 7 Df</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_hur_nb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        2.5 %      97.5 %
count_(Intercept)  1.34373051  1.73966938
count_bmi_c        0.01107002  0.03760871
count_smoke100     0.30035006  0.73549531
zero_(Intercept)  -0.80664805 -0.56037031
zero_bmi_c         0.01502124  0.04053230
zero_smoke100      0.05151314  0.42508607</code></pre>
</div>
</div>
<section id="comparison-to-a-null-model-3" class="level3" data-number="26.7.1">
<h3 data-number="26.7.1" class="anchored" data-anchor-id="comparison-to-a-null-model-3"><span class="header-section-number">26.7.1</span> Comparison to a null model</h3>
<p>To show that this model fits better than the null model (the model with intercept only), we can compare them directly with a chi-squared test. Since we have two predictors in the full model, the degrees of freedom for this test is 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>mod_hur_nb_null <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">hurdle</span>(physhealth <span class="sc">~</span> <span class="dv">1</span>, <span class="at">dist =</span> <span class="st">"negbin"</span>, </span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">zero.dist =</span> <span class="st">"binomial"</span>, </span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> ohioA_young)</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_hur_nb_null)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
pscl::hurdle(formula = physhealth ~ 1, data = ohioA_young, dist = "negbin", 
    zero.dist = "binomial")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-0.4048 -0.4048 -0.4048 -0.1622  3.2340 

Count model coefficients (truncated negbin with log link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.77653    0.09641  18.427  &lt; 2e-16 ***
Log(theta)  -1.04455    0.16123  -6.479 9.25e-11 ***
Zero hurdle model coefficients (binomial with logit link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.5768     0.0469   -12.3   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Theta: count = 0.3518
Number of iterations in BFGS optimization: 12 
Log-likelihood: -3498 on 3 Df</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(mod_hur_nb1) <span class="sc">-</span> <span class="fu">logLik</span>(mod_hur_nb_null)), <span class="at">df =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' 2.17419e-13 (df=7)</code></pre>
</div>
</div>
</section>
<section id="comparison-to-a-negative-binomial-model-vuong-test-1" class="level3" data-number="26.7.2">
<h3 data-number="26.7.2" class="anchored" data-anchor-id="comparison-to-a-negative-binomial-model-vuong-test-1"><span class="header-section-number">26.7.2</span> Comparison to a Negative Binomial Model: Vuong test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vuong</span>(mod_hur_nb1, mod_nb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Vuong Non-Nested Hypothesis Test-Statistic: 
(test-statistic is asymptotically distributed N(0,1) under the
 null that the models are indistinguishible)
-------------------------------------------------------------
              Vuong z-statistic             H_A    p-value
Raw                   3.0953118 model1 &gt; model2 0.00098303
AIC-corrected         2.4837306 model1 &gt; model2 0.00650071
BIC-corrected         0.7750288 model1 &gt; model2 0.21916133</code></pre>
</div>
</div>
<p>The hurdle model is a significant improvement over the standard negative binomial model according to the raw and AIC-corrected versions of this test, but not the BIC-corrected version.</p>
</section>
<section id="comparison-to-a-zero-inflated-nb-model-vuong-test" class="level3" data-number="26.7.3">
<h3 data-number="26.7.3" class="anchored" data-anchor-id="comparison-to-a-zero-inflated-nb-model-vuong-test"><span class="header-section-number">26.7.3</span> Comparison to a Zero-Inflated NB Model: Vuong test</h3>
<p>Is the hurdle model comparable to the zero-inflated Poisson?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vuong</span>(mod_hur_nb1, mod_zinb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Vuong Non-Nested Hypothesis Test-Statistic: 
(test-statistic is asymptotically distributed N(0,1) under the
 null that the models are indistinguishible)
-------------------------------------------------------------
              Vuong z-statistic             H_A p-value
Raw                     0.91178 model1 &gt; model2 0.18094
AIC-corrected           0.91178 model1 &gt; model2 0.18094
BIC-corrected           0.91178 model1 &gt; model2 0.18094</code></pre>
</div>
</div>
<p>The hurdle model is just barely a significant improvement over the zero-inflated Negative Binomial model.</p>
</section>
<section id="comparing-the-hurdle-models-with-aic-and-bic" class="level3" data-number="26.7.4">
<h3 data-number="26.7.4" class="anchored" data-anchor-id="comparing-the-hurdle-models-with-aic-and-bic"><span class="header-section-number">26.7.4</span> Comparing the Hurdle Models with AIC and BIC</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_hur1); <span class="fu">BIC</span>(mod_hur1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11371.58</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11405.11</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_hur_nb1); <span class="fu">BIC</span>(mod_hur_nb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6952.186</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6991.301</code></pre>
</div>
</div>
<p>The negative binomial approach certainly looks better than the Poisson here.</p>
</section>
<section id="the-fitted-equation-3" class="level3" data-number="26.7.5">
<h3 data-number="26.7.5" class="anchored" data-anchor-id="the-fitted-equation-3"><span class="header-section-number">26.7.5</span> The Fitted Equation</h3>
<p>The form of the model equation for this hurdle also requires us to take two separate models into account. First we have a logistic regression model to predict the log odds of zero <code>physhealth</code> days. That takes care of the zeros. Then, to predict the number of <code>physhealth</code> days, we use a truncated negative binomial model, which is truncated to produce only estimates greater than zero, with <span class="math inline">\(\theta\)</span> estimated as <code>exp(-1.123)</code> or 0.325.</p>
</section>
<section id="interpreting-the-coefficients-3" class="level3" data-number="26.7.6">
<h3 data-number="26.7.6" class="anchored" data-anchor-id="interpreting-the-coefficients-3"><span class="header-section-number">26.7.6</span> Interpreting the Coefficients</h3>
<p>We can exponentiate the logistic regression coefficients to obtain results in terms of odds ratios for that model, and that can be of some help in understanding the process behind excess zeros.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mod_hur_nb1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>count_(Intercept)       count_bmi_c    count_smoke100  zero_(Intercept) 
        4.6725266         1.0246380         1.6785372         0.5048423 
       zero_bmi_c     zero_smoke100 
        1.0281661         1.2690894 </code></pre>
</div>
</div>
<p>For example,</p>
<ul>
<li>in the model for <code>physhealth</code> = 0, the odds of <code>physhealth</code> = 0 are 127% as high for subjects with <code>smoke100</code> = 1 as for non-smokers with the same BMI.</li>
</ul>
</section>
<section id="testing-the-predictors-3" class="level3" data-number="26.7.7">
<h3 data-number="26.7.7" class="anchored" data-anchor-id="testing-the-predictors-3"><span class="header-section-number">26.7.7</span> Testing the Predictors</h3>
<p>We can test the model with and without <code>bmi_c</code>, for example, by fitting the model both ways, and comparing the results with either a Wald or Likelihood Ratio test, each of which is available in the <code>lmtest</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>mod_hurnb1_nobmi <span class="ot">&lt;-</span> pscl<span class="sc">::</span><span class="fu">hurdle</span>(physhealth <span class="sc">~</span> smoke100,</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">dist =</span> <span class="st">"negbin"</span>, </span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">zero.dist =</span> <span class="st">"binomial"</span>,</span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> ohioA_young)</span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">waldtest</span>(mod_hur_nb1, mod_hurnb1_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  Res.Df Df  Chisq Pr(&gt;Chisq)    
1   1967                         
2   1969 -2 31.141  1.729e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">lrtest</span>(mod_hur_nb1, mod_hurnb1_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  #Df  LogLik Df  Chisq Pr(&gt;Chisq)    
1   7 -3469.1                         
2   5 -3485.0 -2 31.812  1.236e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="store-fitted-values-and-residuals-3" class="level3" data-number="26.7.8">
<h3 data-number="26.7.8" class="anchored" data-anchor-id="store-fitted-values-and-residuals-3"><span class="header-section-number">26.7.8</span> Store fitted values and residuals</h3>
<p>Again we need to build up the fitted values and residuals, without <code>broom</code> to help.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>sm_hur_nb1 <span class="ot">&lt;-</span> ohioA_young <span class="sc">|&gt;</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(mod_hur_nb1, <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">resid =</span> <span class="fu">resid</span>(mod_hur_nb1, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb131-4"><a href="#cb131-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-5"><a href="#cb131-5" aria-hidden="true" tabindex="-1"></a>sm_hur_nb1 <span class="sc">|&gt;</span> </span>
<span id="cb131-6"><a href="#cb131-6" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(physhealth, fitted, resid) <span class="sc">|&gt;</span></span>
<span id="cb131-7"><a href="#cb131-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  physhealth fitted resid
       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1          0   2.16 -2.16
2          0   2.23 -2.23
3          0   3.09 -3.09
4         30   5.37 24.6 
5          0   3.15 -3.15
6          0   3.72 -3.72</code></pre>
</div>
</div>
</section>
<section id="rootogram-for-nb-hurdle-model" class="level3" data-number="26.7.9">
<h3 data-number="26.7.9" class="anchored" data-anchor-id="rootogram-for-nb-hurdle-model"><span class="header-section-number">26.7.9</span> Rootogram for NB Hurdle Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>countreg<span class="sc">::</span><span class="fu">rootogram</span>(mod_hur_nb1, <span class="at">max =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This improves the situation, but we’re still underfitting the 30s.</p>
</section>
<section id="specify-the-r2-and-log-likelihood-values-3" class="level3" data-number="26.7.10">
<h3 data-number="26.7.10" class="anchored" data-anchor-id="specify-the-r2-and-log-likelihood-values-3"><span class="header-section-number">26.7.10</span> Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</h3>
<p>We can calculate a proxy for <span class="math inline">\(R^2\)</span> as the squared correlation of the fitted values and the observed values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The correlation of observed and fitted values</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>(hurnb1_r <span class="ot">&lt;-</span> <span class="fu">with</span>(sm_hur_nb1, <span class="fu">cor</span>(physhealth, fitted)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1856393</code></pre>
</div>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R-square</span></span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>hurnb1_r<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03446194</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(mod_hur_nb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -3469.093 (df=7)</code></pre>
</div>
</div>
<p>Here, we have</p>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 18%">
<col style="width: 24%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Model</th>
<th style="text-align: right;">Scale</th>
<th style="text-align: right;"><span class="math inline">\(R^2\)</span></th>
<th style="text-align: right;">log(likelihood)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Hurdle Model (Neg. Bin.)</td>
<td style="text-align: right;">Complex: log(<code>physhealth</code>)</td>
<td style="text-align: right;">.035</td>
<td style="text-align: right;">-3469.07</td>
</tr>
</tbody>
</table>
</section>
<section id="check-model-assumptions-3" class="level3" data-number="26.7.11">
<h3 data-number="26.7.11" class="anchored" data-anchor-id="check-model-assumptions-3"><span class="header-section-number">26.7.11</span> Check model assumptions</h3>
<p>Here is a plot of residuals vs.&nbsp;fitted values on the original <code>physhealth</code> scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_hur_nb1, <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> resid)) <span class="sc">+</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs. Fitted `physhealth`"</span>,</span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"Hurdle model with Negative Binomial counts"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="predictions-for-harry-and-sally-3" class="level3" data-number="26.7.12">
<h3 data-number="26.7.12" class="anchored" data-anchor-id="predictions-for-harry-and-sally-3"><span class="header-section-number">26.7.12</span> Predictions for Harry and Sally</h3>
<p>The predictions from this zero-inflated negative binomial regression model are obtained as follows…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod_hur_nb1, <span class="at">newdata =</span> hs_data, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
6.222041 2.007095 </code></pre>
</div>
</div>
<p>The prediction for Harry is 6.22 days, and for Sally is 2.01 days.</p>
</section>
<section id="note-fitting-a-different-hurdle-model-for-counts-and-przero" class="level3" data-number="26.7.13">
<h3 data-number="26.7.13" class="anchored" data-anchor-id="note-fitting-a-different-hurdle-model-for-counts-and-przero"><span class="header-section-number">26.7.13</span> Note: Fitting a Different Hurdle Model for Counts and Pr(zero)</h3>
<p>Suppose we wanted to use only <code>bmi_c</code> to predict the probability of a zero count, but use both predictors in the model for the positive counts. We use the <code>|</code> command.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>mod_hur_new1 <span class="ot">&lt;-</span> </span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>    pscl<span class="sc">::</span><span class="fu">hurdle</span>(physhealth <span class="sc">~</span> bmi_c <span class="sc">+</span> smoke100 <span class="sc">|</span> bmi_c,</span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">dist =</span> <span class="st">"negbin"</span>, <span class="at">zero.dist =</span> <span class="st">"binomial"</span>,</span>
<span id="cb143-4"><a href="#cb143-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> ohioA_young)</span>
<span id="cb143-5"><a href="#cb143-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb143-6"><a href="#cb143-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_hur_new1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
pscl::hurdle(formula = physhealth ~ bmi_c + smoke100 | bmi_c, data = ohioA_young, 
    dist = "negbin", zero.dist = "binomial")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-0.5630 -0.4179 -0.3971 -0.1150  6.1958 

Count model coefficients (truncated negbin with log link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.54170    0.10101  15.263  &lt; 2e-16 ***
bmi_c        0.02434    0.00677   3.595 0.000324 ***
smoke100     0.51792    0.11101   4.666 3.08e-06 ***
Log(theta)  -0.88245    0.14653  -6.023 1.72e-09 ***
Zero hurdle model coefficients (binomial with logit link):
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.58186    0.04718 -12.332  &lt; 2e-16 ***
bmi_c        0.02853    0.00649   4.396  1.1e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Theta: count = 0.4138
Number of iterations in BFGS optimization: 17 
Log-likelihood: -3472 on 6 Df</code></pre>
</div>
</div>
</section>
<section id="hanging-rootogram-for-this-new-hurdle-model" class="level3" data-number="26.7.14">
<h3 data-number="26.7.14" class="anchored" data-anchor-id="hanging-rootogram-for-this-new-hurdle-model"><span class="header-section-number">26.7.14</span> Hanging Rootogram for this new Hurdle Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>countreg<span class="sc">::</span><span class="fu">rootogram</span>(mod_hur_new1, <span class="at">max =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Not a meaningful improvement, certainly.</p>
</section>
</section>
<section id="a-tobit-censored-regression-model" class="level2" data-number="26.8">
<h2 data-number="26.8" class="anchored" data-anchor-id="a-tobit-censored-regression-model"><span class="header-section-number">26.8</span> A Tobit (Censored) Regression Model</h2>
<p>The idea of the <strong>tobit</strong> model (sometimes called a <strong>censored regression</strong> model) is to estimate associations for outcomes where we can see either left-censoring (censoring from below) or right-censoring (censoring from above.)</p>
<p>Consider the variable <code>physhealth</code>, which is restricted to fall between 0 and 30 by the way the measure was constructed. But supposed we think about a broader and latent (unobserved) variable describing physical health. Among the people with <code>physhealth</code> = 0, some would be incredible athletes and others would be in much poorer physical health but still healthy enough to truthfully answer 0. On the other end, some of the people responding 30 are in substantially worse physical health than others with that same response.</p>
<ul>
<li>Censoring from below takes place when values at or below a threshold (in this case 0) take that value.</li>
<li>Censoring from above takes place when values at or above a threshold (here, 30) take that value.</li>
</ul>
<p>Several examples of tobit analysis are available at https://stats.idre.ucla.edu/r/dae/tobit-models/, which is my primary source for the material here on those models.</p>
<p>The tobit model postulates that the value 0 in our model is just the lower limit of the underlying measure of poor physical health that we would actually observe in the population if we had a stronger measure. Similarly, we’ll postulate that 30 is just the upper limit of “poor health” that we can see. The approach I’ll take to run the tobit model comes from the <code>vglm</code> function in the <code>VGAM</code> package.</p>
<p>Here’s the model, and its summary. Note that the default Lower value for a tobit model is 0, so we didn’t technically have to list that here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a>mod_tob1 <span class="ot">&lt;-</span> <span class="fu">vglm</span>(physhealth <span class="sc">~</span> bmi_c <span class="sc">+</span> smoke100, </span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">tobit</span>(<span class="at">Lower =</span> <span class="dv">0</span>, <span class="at">Upper =</span> <span class="dv">30</span>),</span>
<span id="cb146-3"><a href="#cb146-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">type.fitted =</span> <span class="st">"censored"</span>,</span>
<span id="cb146-4"><a href="#cb146-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> ohioA_young)</span>
<span id="cb146-5"><a href="#cb146-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-6"><a href="#cb146-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_tob1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = physhealth ~ bmi_c + smoke100, family = tobit(Lower = 0, 
    Upper = 30), data = ohioA_young, type.fitted = "censored")

Coefficients: 
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1 -9.29104    0.75509 -12.305  &lt; 2e-16 ***
(Intercept):2  2.87081    0.03028  94.818  &lt; 2e-16 ***
bmi_c          0.37434    0.06537   5.727 1.02e-08 ***
smoke100       4.35390    0.97223   4.478 7.52e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: mu, loglink(sd)

Log-likelihood: -3420.605 on 3944 degrees of freedom

Number of Fisher scoring iterations: 6 

No Hauck-Donner effect found in any of the estimates</code></pre>
</div>
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_tob1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %     97.5 %
(Intercept):1 -10.7709932 -7.8110877
(Intercept):2   2.8114721  2.9301560
bmi_c           0.2462244  0.5024551
smoke100        2.4483714  6.2594277</code></pre>
</div>
</div>
<section id="the-fitted-equation-4" class="level3" data-number="26.8.1">
<h3 data-number="26.8.1" class="anchored" data-anchor-id="the-fitted-equation-4"><span class="header-section-number">26.8.1</span> The Fitted Equation</h3>
<p>Because we’ve used the censoring approach, our model will limit its predictions to the range of [0, 30], where any predictions outside that range are censored. Values below 0 are fitted as 0, and values above 30 are fitted as 30.</p>
<p>The model equation is</p>
<pre><code>physhealth = -9.29 + 0.37 bmi_c + 4.35 smoke100</code></pre>
</section>
<section id="interpreting-the-coefficients-4" class="level3" data-number="26.8.2">
<h3 data-number="26.8.2" class="anchored" data-anchor-id="interpreting-the-coefficients-4"><span class="header-section-number">26.8.2</span> Interpreting the Coefficients</h3>
<p>Tobit model regression coefficients are interpreted as we would a set of OLS coefficients, <em>except</em> that the linear effect is on the uncensored <em>latent variable</em>, rather than on the observed outcome.</p>
<p>In our case,</p>
<ul>
<li>a one-unit increase in <code>bmi_c</code> is associated with a 0.37 day increase in the predicted value of <code>physhealth</code>, holding <code>smoke100</code> constant</li>
<li>a move from <code>smoke100</code> = 0 to 1 is associated with a 4.35 day increase in the predicted value of <code>physhealth</code>, holding <code>bmi_c</code> constant</li>
<li>the coefficient labeled <code>(Intercept):1</code> is the intercept for the model and is the predicted value of <code>physhealth</code> when <code>smoke100</code> = 0 and <code>bmi_c</code> = 0. Note that this value is -9.29, which is outside the range of <code>physhealth</code> values we observed.</li>
<li>the coefficient labeled <code>(Intercept):2</code> is a statistic we can use after we exponentiate it, as follows:
<ul>
<li>here <code>(Intercept):2</code> = 2.87, and exp(2.87) = 17.6370182, which is analogous to the square root of the residual variance in OLS regression, which is summarized for our OLS model as <code>Residual standard error: 17.64</code>.</li>
</ul></li>
</ul>
</section>
<section id="testing-the-predictors-4" class="level3" data-number="26.8.3">
<h3 data-number="26.8.3" class="anchored" data-anchor-id="testing-the-predictors-4"><span class="header-section-number">26.8.3</span> Testing the Predictors</h3>
<p>We can test the model with and without <code>bmi_c</code>, for example, by fitting the model both ways, and comparing the results with either a Wald or Likelihood Ratio test, each of which is available in the <code>lmtest</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a>mod_tob_nobmi <span class="ot">&lt;-</span> <span class="fu">vglm</span>(physhealth <span class="sc">~</span> smoke100, </span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">tobit</span>(<span class="at">Lower =</span> <span class="dv">0</span>, <span class="at">Upper =</span> <span class="dv">30</span>),</span>
<span id="cb151-3"><a href="#cb151-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">type.fitted =</span> <span class="st">"censored"</span>,</span>
<span id="cb151-4"><a href="#cb151-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> ohioA_young)</span>
<span id="cb151-5"><a href="#cb151-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-6"><a href="#cb151-6" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">waldtest</span>(mod_tob1, mod_tob_nobmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test

Model 1: physhealth ~ bmi_c + smoke100
Model 2: physhealth ~ smoke100
  Res.Df Df  Chisq Pr(&gt;Chisq)    
1   3944                         
2   3945 -1 32.796  1.023e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The likelihood ratio test we have used in some other settings isn’t available here.</p>
</section>
<section id="store-fitted-values-and-residuals-4" class="level3" data-number="26.8.4">
<h3 data-number="26.8.4" class="anchored" data-anchor-id="store-fitted-values-and-residuals-4"><span class="header-section-number">26.8.4</span> Store fitted values and residuals</h3>
<p>The residuals and fitted values from the tobit model can be stored and then summarized in several ways:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>sm_tob1 <span class="ot">&lt;-</span> ohioA_young <span class="sc">|&gt;</span></span>
<span id="cb153-2"><a href="#cb153-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(mod_tob1,</span>
<span id="cb153-3"><a href="#cb153-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type.fitted =</span> <span class="st">"censored"</span>),</span>
<span id="cb153-4"><a href="#cb153-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">resid =</span> physhealth <span class="sc">-</span> fitted)</span>
<span id="cb153-5"><a href="#cb153-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-6"><a href="#cb153-6" aria-hidden="true" tabindex="-1"></a>sm_tob1 <span class="sc">|&gt;</span> </span>
<span id="cb153-7"><a href="#cb153-7" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(physhealth, fitted, resid) <span class="sc">|&gt;</span></span>
<span id="cb153-8"><a href="#cb153-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  physhealth fitted[,1] resid[,1]
       &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1          0          0         0
2          0          0         0
3          0          0         0
4         30          0        30
5          0          0         0
6          0          0         0</code></pre>
</div>
</div>
</section>
<section id="building-something-like-a-rootogram" class="level3" data-number="26.8.5">
<h3 data-number="26.8.5" class="anchored" data-anchor-id="building-something-like-a-rootogram"><span class="header-section-number">26.8.5</span> Building Something Like a Rootogram</h3>
<p>Building a rootogram is tricky for a tobit model, to say the least, but we can approximate a piece of the issue by plotting the rounded fitted values against the observed <code>physhealth</code> data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_tob1, <span class="fu">aes</span>(<span class="at">x =</span> physhealth, <span class="at">y =</span> <span class="fu">round</span>(fitted))) <span class="sc">+</span></span>
<span id="cb155-2"><a href="#cb155-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb155-3"><a href="#cb155-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-70-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note that the model never predicts a subject to have an underlying <code>physhealth</code> worse than about 13 (remember that larger numbers indicate worse health here.)</p>
</section>
<section id="tables-of-the-observed-and-fitted-physhealth-from-tobit" class="level3" data-number="26.8.6">
<h3 data-number="26.8.6" class="anchored" data-anchor-id="tables-of-the-observed-and-fitted-physhealth-from-tobit"><span class="header-section-number">26.8.6</span> Tables of the Observed and Fitted <code>physhealth</code> from Tobit</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">table</span>(<span class="fu">round</span>(sm_tob1<span class="sc">$</span>physhealth)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1    2    3    4    5    6    7    8   10   12   13   14   15   16   17 
1264  112  139   78   29   50    5   40    9   41    4    1   24   38    2    1 
  18   20   21   25   26   28   29   30  Sum 
   1   23    3    8    2    1    1   98 1974 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb158"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">table</span>(<span class="fu">round</span>(sm_tob1<span class="sc">$</span>fitted)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1    2    3    4    5    6    8   13  Sum 
1924   20    7   10    4    6    1    1    1 1974 </code></pre>
</div>
</div>
</section>
<section id="specify-the-r2-and-log-likelihood-values-4" class="level3" data-number="26.8.7">
<h3 data-number="26.8.7" class="anchored" data-anchor-id="specify-the-r2-and-log-likelihood-values-4"><span class="header-section-number">26.8.7</span> Specify the <span class="math inline">\(R^2\)</span> and log (likelihood) values</h3>
<p>We can calculate a proxy for <span class="math inline">\(R^2\)</span> as the squared correlation of the fitted values and the observed values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb160"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb160-1"><a href="#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The correlation of observed and fitted values</span></span>
<span id="cb160-2"><a href="#cb160-2" aria-hidden="true" tabindex="-1"></a>(tob1_r <span class="ot">&lt;-</span> <span class="fu">with</span>(sm_tob1, <span class="fu">cor</span>(physhealth, fitted)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]
[1,] 0.09329619</code></pre>
</div>
<div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R-square</span></span>
<span id="cb162-2"><a href="#cb162-2" aria-hidden="true" tabindex="-1"></a>tob1_r<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]
[1,] 0.008704178</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb164"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(mod_tob1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3420.605</code></pre>
</div>
</div>
<p>Here, we have</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Model</th>
<th style="text-align: right;">Scale</th>
<th style="text-align: right;"><span class="math inline">\(R^2\)</span></th>
<th style="text-align: right;">log(likelihood)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Tobit</td>
<td style="text-align: right;"><code>physhealth</code></td>
<td style="text-align: right;">.008</td>
<td style="text-align: right;">-3420.58</td>
</tr>
</tbody>
</table>
</section>
<section id="check-model-assumptions-4" class="level3" data-number="26.8.8">
<h3 data-number="26.8.8" class="anchored" data-anchor-id="check-model-assumptions-4"><span class="header-section-number">26.8.8</span> Check model assumptions</h3>
<p>Here is a plot of residuals vs.&nbsp;fitted values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm_tob1, <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> resid)) <span class="sc">+</span></span>
<span id="cb166-2"><a href="#cb166-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb166-3"><a href="#cb166-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs. Fitted Values for Tobit 1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-75-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here is a normal Q-Q plot of the Tobit Model 1 residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb167"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb167-1"><a href="#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(sm_tob1<span class="sc">$</span>resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="count3_files/figure-html/unnamed-chunk-76-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="predictions-for-harry-and-sally-4" class="level3" data-number="26.8.9">
<h3 data-number="26.8.9" class="anchored" data-anchor-id="predictions-for-harry-and-sally-4"><span class="header-section-number">26.8.9</span> Predictions for Harry and Sally</h3>
<p>The predictions from this tobit model are obtained as follows…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod_tob1, <span class="at">newdata =</span> hs_data, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        [,1]
1  -1.193743
2 -11.162739</code></pre>
</div>
</div>
<p>The prediction for both Harry and Sally under the tobit model would be truncated to 0 days.</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>See https://stats.idre.ucla.edu/r/dae/zip/ for more on the zero-inflated poisson model.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>See https://stats.idre.ucla.edu/r/dae/zinb/<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>http://data.library.virginia.edu/getting-started-with-hurdle-models/ is an excellent introduction, by Clay Ford, a Statistical Research Consultant at the University of Virginia Library. I can also recommend https://rpubs.com/kaz_yos/pscl-2 as a place to learn more about the <code>pscl</code> package, and the fitting and interpretation of both hurdle and zero-inflated regression models. That <code>rpubs</code> site has a link to <a href="https://www.ncbi.nlm.nih.gov/pubmed/21854279">this article by Hu, Pavlicova and Nunes from the Am J Drug Alcohol Abuse</a> which provides a real set of examples from a trial of a behavioral health intervention meant to reduce the risk of unprotected sexual occasions as part of a strategy to reduce HIV risk.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./count2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ordinaloutcome.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>