<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 20&nbsp; Logistic Regression with glm</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./logistic3.html" rel="next">
<link href="./logistic1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./incomplete.html" class="sidebar-item-text sidebar-link">This is work in progress</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">R Setup</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinaloutcome.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Time To Event / Survival Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup-used-here" id="toc-r-setup-used-here" class="nav-link active" data-scroll-target="#r-setup-used-here"><span class="toc-section-number">20.1</span>  R Setup Used Here</a>
  <ul class="collapse">
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="toc-section-number">20.1.1</span>  Data Load</a></li>
  </ul></li>
  <li><a href="#the-resect-data" id="toc-the-resect-data" class="nav-link" data-scroll-target="#the-resect-data"><span class="toc-section-number">20.2</span>  The <code>resect</code> data</a></li>
  <li><a href="#running-a-simple-logistic-regression-model" id="toc-running-a-simple-logistic-regression-model" class="nav-link" data-scroll-target="#running-a-simple-logistic-regression-model"><span class="toc-section-number">20.3</span>  Running A Simple Logistic Regression Model</a>
  <ul class="collapse">
  <li><a href="#logistic-regression-can-be-harder-than-linear-regression" id="toc-logistic-regression-can-be-harder-than-linear-regression" class="nav-link" data-scroll-target="#logistic-regression-can-be-harder-than-linear-regression"><span class="toc-section-number">20.3.1</span>  Logistic Regression Can Be Harder than Linear Regression</a></li>
  </ul></li>
  <li><a href="#logistic-regression-using-glm" id="toc-logistic-regression-using-glm" class="nav-link" data-scroll-target="#logistic-regression-using-glm"><span class="toc-section-number">20.4</span>  Logistic Regression using <code>glm</code></a>
  <ul class="collapse">
  <li><a href="#interpreting-the-coefficients-of-a-logistic-regression-model" id="toc-interpreting-the-coefficients-of-a-logistic-regression-model" class="nav-link" data-scroll-target="#interpreting-the-coefficients-of-a-logistic-regression-model"><span class="toc-section-number">20.4.1</span>  Interpreting the Coefficients of a Logistic Regression Model</a></li>
  <li><a href="#using-predict-to-describe-the-models-fits" id="toc-using-predict-to-describe-the-models-fits" class="nav-link" data-scroll-target="#using-predict-to-describe-the-models-fits"><span class="toc-section-number">20.4.2</span>  Using <code>predict</code> to describe the model’s fits</a></li>
  <li><a href="#odds-ratio-interpretation-of-coefficients" id="toc-odds-ratio-interpretation-of-coefficients" class="nav-link" data-scroll-target="#odds-ratio-interpretation-of-coefficients"><span class="toc-section-number">20.4.3</span>  Odds Ratio interpretation of Coefficients</a></li>
  <li><a href="#interpreting-the-rest-of-the-model-output-from-glm" id="toc-interpreting-the-rest-of-the-model-output-from-glm" class="nav-link" data-scroll-target="#interpreting-the-rest-of-the-model-output-from-glm"><span class="toc-section-number">20.4.4</span>  Interpreting the rest of the model output from <code>glm</code></a></li>
  <li><a href="#deviance-and-comparing-our-model-to-the-null-model" id="toc-deviance-and-comparing-our-model-to-the-null-model" class="nav-link" data-scroll-target="#deviance-and-comparing-our-model-to-the-null-model"><span class="toc-section-number">20.4.5</span>  Deviance and Comparing Our Model to the Null Model</a></li>
  <li><a href="#using-glance-with-a-logistic-regression-model" id="toc-using-glance-with-a-logistic-regression-model" class="nav-link" data-scroll-target="#using-glance-with-a-logistic-regression-model"><span class="toc-section-number">20.4.6</span>  Using <code>glance</code> with a logistic regression model</a></li>
  </ul></li>
  <li><a href="#interpreting-the-model-summary" id="toc-interpreting-the-model-summary" class="nav-link" data-scroll-target="#interpreting-the-model-summary"><span class="toc-section-number">20.5</span>  Interpreting the Model Summary</a>
  <ul class="collapse">
  <li><a href="#wald-z-tests-for-coefficients-in-a-logistic-regression" id="toc-wald-z-tests-for-coefficients-in-a-logistic-regression" class="nav-link" data-scroll-target="#wald-z-tests-for-coefficients-in-a-logistic-regression"><span class="toc-section-number">20.5.1</span>  Wald Z tests for Coefficients in a Logistic Regression</a></li>
  <li><a href="#confidence-intervals-for-the-coefficients" id="toc-confidence-intervals-for-the-coefficients" class="nav-link" data-scroll-target="#confidence-intervals-for-the-coefficients"><span class="toc-section-number">20.5.2</span>  Confidence Intervals for the Coefficients</a></li>
  <li><a href="#deviance-residuals" id="toc-deviance-residuals" class="nav-link" data-scroll-target="#deviance-residuals"><span class="toc-section-number">20.5.3</span>  Deviance Residuals</a></li>
  <li><a href="#dispersion-parameter" id="toc-dispersion-parameter" class="nav-link" data-scroll-target="#dispersion-parameter"><span class="toc-section-number">20.5.4</span>  Dispersion Parameter</a></li>
  <li><a href="#fisher-scoring-iterations" id="toc-fisher-scoring-iterations" class="nav-link" data-scroll-target="#fisher-scoring-iterations"><span class="toc-section-number">20.5.5</span>  Fisher Scoring iterations</a></li>
  </ul></li>
  <li><a href="#plotting-a-simple-logistic-regression-model" id="toc-plotting-a-simple-logistic-regression-model" class="nav-link" data-scroll-target="#plotting-a-simple-logistic-regression-model"><span class="toc-section-number">20.6</span>  Plotting a Simple Logistic Regression Model</a>
  <ul class="collapse">
  <li><a href="#using-augment-to-capture-the-fitted-probabilities" id="toc-using-augment-to-capture-the-fitted-probabilities" class="nav-link" data-scroll-target="#using-augment-to-capture-the-fitted-probabilities"><span class="toc-section-number">20.6.1</span>  Using <code>augment</code> to capture the fitted probabilities</a></li>
  <li><a href="#plotting-a-logistic-regression-models-fitted-values" id="toc-plotting-a-logistic-regression-models-fitted-values" class="nav-link" data-scroll-target="#plotting-a-logistic-regression-models-fitted-values"><span class="toc-section-number">20.6.2</span>  Plotting a Logistic Regression Model’s Fitted Values</a></li>
  <li><a href="#plotting-a-simple-logistic-model-using-binomial_smooth" id="toc-plotting-a-simple-logistic-model-using-binomial_smooth" class="nav-link" data-scroll-target="#plotting-a-simple-logistic-model-using-binomial_smooth"><span class="toc-section-number">20.6.3</span>  Plotting a Simple Logistic Model using <code>binomial_smooth</code></a></li>
  </ul></li>
  <li><a href="#how-well-does-model-a-classify-subjects" id="toc-how-well-does-model-a-classify-subjects" class="nav-link" data-scroll-target="#how-well-does-model-a-classify-subjects"><span class="toc-section-number">20.7</span>  How well does Model A classify subjects?</a></li>
  <li><a href="#the-confusion-matrix" id="toc-the-confusion-matrix" class="nav-link" data-scroll-target="#the-confusion-matrix"><span class="toc-section-number">20.8</span>  The Confusion Matrix</a></li>
  <li><a href="#using-the-confusionmatrix-tool-from-the-caret-package" id="toc-using-the-confusionmatrix-tool-from-the-caret-package" class="nav-link" data-scroll-target="#using-the-confusionmatrix-tool-from-the-caret-package"><span class="toc-section-number">20.9</span>  Using the <code>confusionMatrix</code> tool from the <code>caret</code> package</a></li>
  <li><a href="#receiver-operating-characteristic-curve-analysis" id="toc-receiver-operating-characteristic-curve-analysis" class="nav-link" data-scroll-target="#receiver-operating-characteristic-curve-analysis"><span class="toc-section-number">20.10</span>  Receiver Operating Characteristic Curve Analysis</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-area-under-the-roc-curve" id="toc-interpreting-the-area-under-the-roc-curve" class="nav-link" data-scroll-target="#interpreting-the-area-under-the-roc-curve"><span class="toc-section-number">20.10.1</span>  Interpreting the Area under the ROC curve</a></li>
  </ul></li>
  <li><a href="#the-roc-plot-for-res_moda" id="toc-the-roc-plot-for-res_moda" class="nav-link" data-scroll-target="#the-roc-plot-for-res_moda"><span class="toc-section-number">20.11</span>  The ROC Plot for <code>res_modA</code></a>
  <ul class="collapse">
  <li><a href="#another-way-to-plot-the-roc-curve" id="toc-another-way-to-plot-the-roc-curve" class="nav-link" data-scroll-target="#another-way-to-plot-the-roc-curve"><span class="toc-section-number">20.11.1</span>  Another way to plot the ROC Curve</a></li>
  </ul></li>
  <li><a href="#assessing-residual-plots-from-model-a" id="toc-assessing-residual-plots-from-model-a" class="nav-link" data-scroll-target="#assessing-residual-plots-from-model-a"><span class="toc-section-number">20.12</span>  Assessing Residual Plots from Model A</a></li>
  <li><a href="#model-b-a-kitchen-sink-logistic-regression-model" id="toc-model-b-a-kitchen-sink-logistic-regression-model" class="nav-link" data-scroll-target="#model-b-a-kitchen-sink-logistic-regression-model"><span class="toc-section-number">20.13</span>  Model B: A “Kitchen Sink” Logistic Regression Model</a>
  <ul class="collapse">
  <li><a href="#comparing-model-a-to-model-b" id="toc-comparing-model-a-to-model-b" class="nav-link" data-scroll-target="#comparing-model-a-to-model-b"><span class="toc-section-number">20.13.1</span>  Comparing Model A to Model B</a></li>
  <li><a href="#interpreting-model-b" id="toc-interpreting-model-b" class="nav-link" data-scroll-target="#interpreting-model-b"><span class="toc-section-number">20.13.2</span>  Interpreting Model B</a></li>
  </ul></li>
  <li><a href="#plotting-model-b" id="toc-plotting-model-b" class="nav-link" data-scroll-target="#plotting-model-b"><span class="toc-section-number">20.14</span>  Plotting Model B</a>
  <ul class="collapse">
  <li><a href="#using-augment-to-capture-the-fitted-probabilities-1" id="toc-using-augment-to-capture-the-fitted-probabilities-1" class="nav-link" data-scroll-target="#using-augment-to-capture-the-fitted-probabilities-1"><span class="toc-section-number">20.14.1</span>  Using <code>augment</code> to capture the fitted probabilities</a></li>
  <li><a href="#plotting-model-b-fits-by-observed-mortality" id="toc-plotting-model-b-fits-by-observed-mortality" class="nav-link" data-scroll-target="#plotting-model-b-fits-by-observed-mortality"><span class="toc-section-number">20.14.2</span>  Plotting Model B Fits by Observed Mortality</a></li>
  <li><a href="#confusion-matrix-for-model-b" id="toc-confusion-matrix-for-model-b" class="nav-link" data-scroll-target="#confusion-matrix-for-model-b"><span class="toc-section-number">20.14.3</span>  Confusion Matrix for Model B</a></li>
  <li><a href="#the-roc-curve-for-model-b" id="toc-the-roc-curve-for-model-b" class="nav-link" data-scroll-target="#the-roc-curve-for-model-b"><span class="toc-section-number">20.14.4</span>  The ROC curve for Model B</a></li>
  <li><a href="#residuals-leverage-and-influence" id="toc-residuals-leverage-and-influence" class="nav-link" data-scroll-target="#residuals-leverage-and-influence"><span class="toc-section-number">20.14.5</span>  Residuals, Leverage and Influence</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="r-setup-used-here" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="r-setup-used-here"><span class="header-section-number">20.1</span> R Setup Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-load" class="level3" data-number="20.1.1">
<h3 data-number="20.1.1" class="anchored" data-anchor-id="data-load"><span class="header-section-number">20.1.1</span> Data Load</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>resect <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/resect.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="the-resect-data" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="the-resect-data"><span class="header-section-number">20.2</span> The <code>resect</code> data</h2>
<p>My source for these data was <span class="citation" data-cites="Riffenburgh2006">Riffenburgh (<a href="references.html#ref-Riffenburgh2006" role="doc-biblioref">2006</a>)</span>. The data describe 134 patients who had undergone resection of the tracheal carina (most often this is done to address tumors in the trachea), and the <code>resect.csv</code> data file contains the following variables:</p>
<ul>
<li><code>id</code> = a patient ID #,</li>
<li><code>age</code>= the patient’s age at surgery,</li>
<li><code>prior</code> = prior tracheal surgery (1 = yes, 0 = no),</li>
<li><code>resection</code> = extent of the resection (in cm),</li>
<li><code>intubated</code> = whether intubation was required at the end of surgery (1 = yes, 0 = no), and</li>
<li><code>died</code> = the patient’s death status (1 = dead, 0 = alive).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_summary</span>(resect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  variable  n_miss pct_miss
  &lt;chr&gt;      &lt;int&gt;    &lt;dbl&gt;
1 subj_id        0        0
2 age            0        0
3 prior          0        0
4 resection      0        0
5 intubated      0        0
6 died           0        0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>resect <span class="sc">|&gt;</span> <span class="fu">count</span>(died, prior)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
   died prior     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1     0     0    89
2     0     1    28
3     1     0    11
4     1     1     6</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>resect <span class="sc">|&gt;</span> <span class="fu">inspect</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
quantitative variables:  
       name   class min    Q1 median     Q3 max       mean         sd   n
1   subj_id numeric   1 34.25   67.5 100.75 134 67.5000000 38.8265373 134
2       age numeric   8 36.00   51.0  61.00  80 47.8432836 15.7775202 134
3     prior numeric   0  0.00    0.0   0.75   1  0.2537313  0.4367785 134
4 resection numeric   1  2.00    2.5   4.00   6  2.9634328  1.2402123 134
5 intubated numeric   0  0.00    0.0   0.00   1  0.1417910  0.3501447 134
6      died numeric   0  0.00    0.0   0.00   1  0.1268657  0.3340713 134
  missing
1       0
2       0
3       0
4       0
5       0
6       0</code></pre>
</div>
</div>
<p>We have no missing data, and 17 of the 134 patients died. Our goal will be to understand the characteristics of the patients, and how they relate to the binary outcome of interest, death.</p>
</section>
<section id="running-a-simple-logistic-regression-model" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="running-a-simple-logistic-regression-model"><span class="header-section-number">20.3</span> Running A Simple Logistic Regression Model</h2>
<p>In the most common scenario, a logistic regression model is used to predict a binary outcome (which can take on the values 0 or 1.) We will eventually fit a logistic regression model in two ways.</p>
<ol type="1">
<li>Through the <code>glm</code> function in the base package of R (similar to <code>lm</code> for linear regression)</li>
<li>Through the <code>lrm</code> function available in the <code>rms</code> package (similar to <code>ols</code> for linear regression)</li>
</ol>
<p>We’ll focus on the <code>glm</code> approach first, and save the <code>lrm</code> ideas for later in this Chapter.</p>
<section id="logistic-regression-can-be-harder-than-linear-regression" class="level3" data-number="20.3.1">
<h3 data-number="20.3.1" class="anchored" data-anchor-id="logistic-regression-can-be-harder-than-linear-regression"><span class="header-section-number">20.3.1</span> Logistic Regression Can Be Harder than Linear Regression</h3>
<ul>
<li>Logistic regression models are fitted using the method of maximum likelihood in <code>glm</code>, which requires multiple iterations until convergence is reached.</li>
<li>Logistic regression models are harder to interpret (for most people) than linear regressions.</li>
<li>Logistic regression models don’t have the same set of assumptions as linear models.</li>
<li>Logistic regression outcomes (yes/no) carry much less information than quantitative outcomes. As a result, fitting a reasonable logistic regression requires more data than a linear model of similar size.
<ul>
<li>The rule I learned in graduate school was that a logistic regression requires 100 observations to fit an intercept plus another 15 observations for each candidate predictor. That’s not terrible, but it’s a very large sample size.</li>
<li>Frank Harrell recommends that 96 observations + a function of the number of candidate predictors (which depends on the amount of variation in the predictors, but 15 x the number of such predictors isn’t too bad if the signal to noise ratio is pretty good) are required just to get reasonable confidence intervals around your predictions.
<ul>
<li>In a <a href="https://twitter.com/f2harrell/status/936230071219707913">twitter note</a>, Frank suggests that 96 + 8 times the number of candidate parameters might be reasonable so long as the smallest cell of interest (combination of an outcome and a split of the covariates) is 96 or more observations.</li>
</ul></li>
<li><span class="citation" data-cites="Peduzzi1996">Peduzzi et al. (<a href="references.html#ref-Peduzzi1996" role="doc-biblioref">1996</a>)</span> suggest that if we let <span class="math inline">\(\pi\)</span> be the smaller of the proportions of “yes” or “no” cases in the population of interest, and <em>k</em> be the number of inputs under consideration, then <span class="math inline">\(N = 10k/\pi\)</span> is the minimum number of cases to include, except that if N &lt; 100 by this standard, you should increase it to 100, according to <span class="citation" data-cites="Long1997">Long (<a href="references.html#ref-Long1997" role="doc-biblioref">1997</a>)</span>.
<ul>
<li>That suggests that if you have an outcome that happens 10% of the time, and you are running a model with 3 predictors, then you could get away with <span class="math inline">\((10 \times 3)/(0.10) = 300\)</span> observations, but if your outcome happened 40% of the time, you could get away with only <span class="math inline">\((10 \times 3)/(0.40) = 75\)</span> observations, which you’d round up to 100.</li>
</ul></li>
</ul></li>
</ul>
</section>
</section>
<section id="logistic-regression-using-glm" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="logistic-regression-using-glm"><span class="header-section-number">20.4</span> Logistic Regression using <code>glm</code></h2>
<p>We’ll begin by attempting to predict death based on the extent of the resection.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>res_modA <span class="ot">&lt;-</span> <span class="fu">glm</span>(died <span class="sc">~</span> resection, <span class="at">data=</span>resect, </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">family=</span><span class="st">"binomial"</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>res_modA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = died ~ resection, family = binomial(link = "logit"), 
    data = resect)

Coefficients:
(Intercept)    resection  
    -4.4337       0.7417  

Degrees of Freedom: 133 Total (i.e. Null);  132 Residual
Null Deviance:      101.9 
Residual Deviance: 89.49    AIC: 93.49</code></pre>
</div>
</div>
<p>Note that the <code>logit</code> link is the default approach with the <code>binomial</code> family, so we could also have used:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>res_modA <span class="ot">&lt;-</span> <span class="fu">glm</span>(died <span class="sc">~</span> resection, <span class="at">data =</span> resect, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> <span class="st">"binomial"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which yields the same model.</p>
<section id="interpreting-the-coefficients-of-a-logistic-regression-model" class="level3" data-number="20.4.1">
<h3 data-number="20.4.1" class="anchored" data-anchor-id="interpreting-the-coefficients-of-a-logistic-regression-model"><span class="header-section-number">20.4.1</span> Interpreting the Coefficients of a Logistic Regression Model</h3>
<p>Our model is:</p>
<p><span class="math display">\[
logit(died = 1) = log\left(\frac{Pr(died = 1)}{1 - Pr(died = 1)}\right)
\]</span></p>
<p><span class="math display">\[
= \beta_0 + \beta_1 x = -4.4337 + 0.7417 \times resection
\]</span></p>
<p>The predicted log odds of death for a subject with a resection of 4 cm is:</p>
<p><span class="math display">\[
log\left(\frac{Pr(died = 1)}{1 - Pr(died = 1)}\right) = -4.4337 + 0.7417 \times 4 = -1.467
\]</span></p>
<p>The predicted odds of death for a subject with a resection of 4 cm is thus:</p>
<p><span class="math display">\[
\frac{Pr(died = 1)}{1 - Pr(died = 1)} = e^{-4.4337 + 0.7417 \times 4} = e^{-1.467} = 0.2306
\]</span></p>
<p>Since the odds are less than 1, we should find that the probability of death is less than 1/2. With a little algebra, we see that the predicted probability of death for a subject with a resection of 4 cm is:</p>
<p><span class="math display">\[
Pr(died = 1) = \frac{e^{-4.4337 + 0.7417 \times 4}}{1 + e^{-4.4337 + 0.7417 \times 4}} = \frac{e^{-1.467}}{1 + e^{-1.467}} = \frac{0.2306}{1.2306} = 0.187
\]</span></p>
<p>In general, we can frame the model in terms of a statement about probabilities, like this:</p>
<p><span class="math display">\[
Pr(died = 1) = \frac{e^{\beta_0 + \beta_1 x}}{1 + {e^{\beta_0 + \beta_1 x}}} = \frac{e^{-4.4337 + 0.7417 \times resection}}{1 + e^{-4.4337 + 0.7417 \times resection}}
\]</span></p>
<p>and so by substituting in values for <code>resection</code>, we can estimate the model’s fitted probabilities of death.</p>
</section>
<section id="using-predict-to-describe-the-models-fits" class="level3" data-number="20.4.2">
<h3 data-number="20.4.2" class="anchored" data-anchor-id="using-predict-to-describe-the-models-fits"><span class="header-section-number">20.4.2</span> Using <code>predict</code> to describe the model’s fits</h3>
<p>To obtain these fitted odds and probabilities in R, we can use the <code>predict</code> function.</p>
<ul>
<li>The default predictions are on the scale of the log odds. These predictions are also available through the <code>type = "link"</code> command within the <code>predict</code> function for a generalized linear model like logistic regression.</li>
<li>Here are the predicted log odds of death for a subject (Sally) with a 4 cm resection and a subject (Harry) who had a 5 cm resection.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(res_modA, <span class="at">newdata =</span> <span class="fu">tibble</span>(<span class="at">resection =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">5</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2 
-1.4669912 -0.7253027 </code></pre>
</div>
</div>
<ul>
<li>We can also obtain predictions for each subject on the original response (here, probability) scale, backing out of the logit link.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(res_modA, <span class="at">newdata =</span> <span class="fu">tibble</span>(<span class="at">resection =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">5</span>)), </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2 
0.1874004 0.3262264 </code></pre>
</div>
</div>
<p>So the predicted probability of death is 0.187 for Sally, the subject with a 4 cm resection, and 0.326 for Harry, the subject with a 5 cm resection.</p>
</section>
<section id="odds-ratio-interpretation-of-coefficients" class="level3" data-number="20.4.3">
<h3 data-number="20.4.3" class="anchored" data-anchor-id="odds-ratio-interpretation-of-coefficients"><span class="header-section-number">20.4.3</span> Odds Ratio interpretation of Coefficients</h3>
<p>Often, we will exponentiate the estimated slope coefficients of a logistic regression model to help us understand the impact of changing a predictor on the odds of our outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(res_modA))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   resection 
 0.01186995  2.09947754 </code></pre>
</div>
</div>
<p>To interpret this finding, suppose we have two subjects, Harry and Sally. Harry had a resection that was 1 cm larger than Sally. This estimated coefficient suggests that the estimated odds for death associated with Harry is 2.099 times larger than the odds for death associated with Sally. In general, the odds ratio comparing two subjects who differ by 1 cm on the resection length is 2.099.</p>
<p>To illustrate, again let’s assume that Harry’s resection was 5 cm, and Sally’s was 4 cm. Then we have:</p>
<p><span class="math display">\[
log\left(\frac{Pr(Harry died)}{1 - Pr(Harry died)}\right) = -4.4337 + 0.7417 \times 5 = -0.7253
\]</span></p>
<p><span class="math display">\[
log\left(\frac{Pr(Sally died)}{1 - Pr(Sally died)}\right) = -4.4337 + 0.7417 \times 4 = -1.4667.
\]</span></p>
<p>which implies that our estimated odds of death for Harry and Sally are:</p>
<p><span class="math display">\[
Odds(Harry died) = \frac{Pr(Harry died)}{1 - Pr(Harry died)} = e^{-4.4337 + 0.7417 \times 5} = e^{-0.7253} = 0.4842
\]</span></p>
<p><span class="math display">\[
Odds(Sally died) = \frac{Pr(Sally died)}{1 - Pr(Sally died)} = e^{-4.4337 + 0.7417 \times 4} = e^{-1.4667} = 0.2307
\]</span></p>
<p>and so the odds ratio is:</p>
<p><span class="math display">\[
OR = \frac{Odds(Harry died)}{Odds(Sally died)} = \frac{0.4842}{0.2307} = 2.099
\]</span></p>
<ul>
<li>If the odds ratio was 1, that would mean that Harry and Sally had the same estimated odds of death, and thus the same estimated probability of death, despite having different sizes of resections.</li>
<li>Since the odds ratio is greater than 1, it means that Harry has a higher estimated odds of death than Sally, and thus that Harry has a higher estimated probability of death than Sally.</li>
<li>If the odds ratio was less than 1, it would mean that Harry had a lower estimated odds of death than Sally, and thus that Harry had a lower estimated probability of death than Sally.</li>
</ul>
<p>Remember that the odds ratio is a fraction describing two positive numbers (odds can only be non-negative) so that the smallest possible odds ratio is 0.</p>
</section>
<section id="interpreting-the-rest-of-the-model-output-from-glm" class="level3" data-number="20.4.4">
<h3 data-number="20.4.4" class="anchored" data-anchor-id="interpreting-the-rest-of-the-model-output-from-glm"><span class="header-section-number">20.4.4</span> Interpreting the rest of the model output from <code>glm</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>res_modA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = died ~ resection, family = "binomial", data = resect)

Coefficients:
(Intercept)    resection  
    -4.4337       0.7417  

Degrees of Freedom: 133 Total (i.e. Null);  132 Residual
Null Deviance:      101.9 
Residual Deviance: 89.49    AIC: 93.49</code></pre>
</div>
</div>
<p>In addition to specifying the logistic regression coefficients, we are also presented with information on degrees of freedom, deviance (null and residual) and AIC.</p>
<ul>
<li>The degrees of freedom indicate the sample size.
<ul>
<li>Recall that we had <em>n</em> = 134 subjects in the data. The “Null” model includes only an intercept term (which uses 1 df) and we thus have <em>n</em> - 1 (here 133) degrees of freedom available for estimation.</li>
<li>In our <code>res_modA</code> model, a logistic regression is fit including a single slope (resection) and an intercept term. Each uses up one degree of freedom to build an estimate, so we have <em>n</em> - 2 = 134 - 2 = 132 residual df remaining.</li>
</ul></li>
<li>The AIC or Akaike Information Criterion (lower values are better) is also provided. This is helpful if we’re comparing multiple models for the same outcome.</li>
</ul>
</section>
<section id="deviance-and-comparing-our-model-to-the-null-model" class="level3" data-number="20.4.5">
<h3 data-number="20.4.5" class="anchored" data-anchor-id="deviance-and-comparing-our-model-to-the-null-model"><span class="header-section-number">20.4.5</span> Deviance and Comparing Our Model to the Null Model</h3>
<ul>
<li>The deviance (a measure of the model’s <em>lack of fit</em>) is available for both the null model (the model with only an intercept) and for our model (<code>res_modA</code>) predicting our outcome, mortality.</li>
<li>The deviance test, though available in R (see below) isn’t really a test of whether the model works well. Instead, it assumes the model is true, and then tests to see if the coefficients are different from zero. So it isn’t of much practical use.
<ul>
<li>To compare the <code>deviance</code> statistics, we can subtract the residual deviance from the null deviance to describe the impact of our model on fit.</li>
<li>Null Deviance - Residual Deviance can be compared to a <span class="math inline">\(\chi^2\)</span> distribution with Null DF - Residual DF degrees of freedom to obtain a global test of the in-sample predictive power of our model.</li>
<li>We can see this comparison more directly by running <code>anova</code> on our model:</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(res_modA, <span class="at">test =</span> <span class="st">"LRT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: died

Terms added sequentially (first to last)

          Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
NULL                        133    101.943              
resection  1    12.45       132     89.493 0.0004179 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The <code>test = "LRT"</code> section completes a deviance test and provides a <em>p</em> value, which just estimates the probability that a chi-square distribution with a single degree of freedom would exhibit an improvement in deviance as large as 12.45.</p>
<p>The <em>p</em> value for the deviance test here is about 0.0004. But, again, this isn’t a test of whether the model is any good - it assumes the model is true, and then tests some consequences.</p>
<ul>
<li>Specifically, it tests whether (if the model is TRUE) some of the model’s coefficients are non-zero.</li>
<li>That’s not so practically useful, so I discourage you from performing global tests of a logistic regression model with a deviance test.</li>
</ul>
</section>
<section id="using-glance-with-a-logistic-regression-model" class="level3" data-number="20.4.6">
<h3 data-number="20.4.6" class="anchored" data-anchor-id="using-glance-with-a-logistic-regression-model"><span class="header-section-number">20.4.6</span> Using <code>glance</code> with a logistic regression model</h3>
<p>We can use the <code>glance</code> function from the <code>broom</code> package to obtain the null and residual deviance and degrees of freedom. Note that the deviance for our model is related to the log likelihood by -2*<code>logLik</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(res_modA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          102.     133  -44.7  93.5  99.3     89.5         132   134</code></pre>
</div>
</div>
<p>The <code>glance</code> result also provides the AIC, and the BIC (Bayes Information Criterion), each of which is helpful in understanding comparisons between multiple models for the same outcome (with smaller values of either criterion indicating better models.) The AIC is based on the deviance, but penalizes you for making the model more complicated. The BIC does the same sort of thing but with a different penalty.</p>
<p>Again we see that we have a null deviance of 101.94 on 133 degrees of freedom. Including the <code>resection</code> information in the model decreased the deviance to 89.49 points on 132 degrees of freedom, so that’s a decrease of 12.45 points while using one degree of freedom, which looks like a meaningful reduction in deviance.</p>
</section>
</section>
<section id="interpreting-the-model-summary" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="interpreting-the-model-summary"><span class="header-section-number">20.5</span> Interpreting the Model Summary</h2>
<p>Let’s get a more detailed summary of our <code>res_modA</code> model, including 95% confidence intervals for the coefficients:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_modA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = died ~ resection, family = "binomial", data = resect)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.1844  -0.5435  -0.3823  -0.2663   2.4501  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -4.4337     0.8799  -5.039 4.67e-07 ***
resection     0.7417     0.2230   3.327 0.000879 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 101.943  on 133  degrees of freedom
Residual deviance:  89.493  on 132  degrees of freedom
AIC: 93.493

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(res_modA, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) -6.344472 -2.855856
resection    0.322898  1.208311</code></pre>
</div>
</div>
<p>Some elements of this summary are very familiar from our work with linear models.</p>
<ul>
<li>We still have a five-number summary of residuals, although these are called <em>deviance</em> residuals.</li>
<li>We have a table of coefficients with standard errors, and hypothesis tests, although these are Wald z-tests, rather than the t tests we saw in linear modeling.</li>
<li>We have a summary of global fit in the comparison of null deviance and residual deviance, but without a formal p value. And we have the AIC, as discussed above.</li>
<li>We also have some new items related to a <em>dispersion</em> parameter and to the number of Fisher Scoring Iterations.</li>
</ul>
<p>Let’s walk through each of these elements.</p>
<section id="wald-z-tests-for-coefficients-in-a-logistic-regression" class="level3" data-number="20.5.1">
<h3 data-number="20.5.1" class="anchored" data-anchor-id="wald-z-tests-for-coefficients-in-a-logistic-regression"><span class="header-section-number">20.5.1</span> Wald Z tests for Coefficients in a Logistic Regression</h3>
<p>The coefficients output provides the estimated coefficients, and their standard errors, plus a Wald Z statistic, which is just the estimated coefficient divided by its standard error. This is compared to a standard Normal distribution to obtain the two-tailed p values summarized in the <code>Pr(&gt;|z|)</code> column.</p>
<ul>
<li>The interesting result is <code>resection</code>, which has a Wald Z = 3.327, yielding a <em>p</em> value of 0.00088.</li>
<li>The <em>p</em> value assesses whether the estimated coefficient of <code>resection</code>, 0.7417, is different from 0. If the coefficient (on the logit scale) for <code>resection</code> was truly 0, this would mean that:
<ul>
<li>the log odds of death did not change based on the <code>resection</code> size,</li>
<li>the odds of death were unchanged based on the <code>resection</code> size (the odds ratio would be 1), and</li>
<li>the probability of death was unchanged based on the <code>resection</code> size.</li>
</ul></li>
</ul>
<p>In our case, we have a change in the log odds of <code>died</code> associated with changes in <code>resection</code>, according to this <em>p</em> value. We conclude that <code>resection</code> size is associated with a positive impact on death rates (death rates are generally higher for people with larger resections.)</p>
</section>
<section id="confidence-intervals-for-the-coefficients" class="level3" data-number="20.5.2">
<h3 data-number="20.5.2" class="anchored" data-anchor-id="confidence-intervals-for-the-coefficients"><span class="header-section-number">20.5.2</span> Confidence Intervals for the Coefficients</h3>
<p>As in linear regression, we can obtain 95% confidence intervals (to get other levels, change the <code>level</code> parameter in <code>confint</code>) for the intercept and slope coefficients.</p>
<p>Here, we see, for example, that the coefficient of <code>resection</code> has a point estimate of 0.7417, and a confidence interval of (0.3229, 1.208). Since this is on the logit scale, it’s not that interpretable, but we will often exponentiate the model and its confidence interval to obtain a more interpretable result on the odds ratio scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(res_modA, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, conf.low, conf.high)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  term        estimate conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   0.0119  0.00176    0.0575
2 resection     2.10    1.38       3.35  </code></pre>
</div>
</div>
<p>From this output, we can estimate the odds ratio for death associated with a 1 cm increase in resection size is 2.099, with a 95% CI of (1.38, 3.35). - If the odds ratio was 1, it would indicate that the odds of death did not change based on the change in resection size. - Here, it’s clear that the estimated odds of death will be larger (odds &gt; 1) for subjects with larger resection sizes. Larger odds of death also indicate larger probabilities of death. This confidence interval indicates that with 95% confidence, we conclude that increases in resection size are associated with increases in the odds of death. - If the odds ratio was less than 1 (remember that it cannot be less than 0) that would mean that subjects with larger resection sizes were associated with smaller estimated odds of death.</p>
</section>
<section id="deviance-residuals" class="level3" data-number="20.5.3">
<h3 data-number="20.5.3" class="anchored" data-anchor-id="deviance-residuals"><span class="header-section-number">20.5.3</span> Deviance Residuals</h3>
<p>In logistic regression, it’s certainly a good idea to check to see how well the model fits the data. However, there are a few different types of residuals. The residuals presented here by default are called deviance residuals. Other types of residuals are available for generalized linear models, such as Pearson residuals, working residuals, and response residuals. Logistic regression model diagnostics often make use of multiple types of residuals.</p>
<p>The deviance residuals for each individual subject sum up to the deviance statistic for the model, and describe the contribution of each point to the model likelihood function.</p>
<p>The deviance residual, <span class="math inline">\(d_i\)</span>, for the i<sup>th</sup> observation in a model predicting <span class="math inline">\(y_i\)</span> (a binary variable), with the estimate being <span class="math inline">\(\hat{\pi}_i\)</span> is:</p>
<p><span class="math display">\[
d_i = s_i \sqrt{-2 [y_i log \hat{\pi_i} + (1 - y_i) log(1 - \hat{\pi_i})]},
\]</span></p>
<p>where <span class="math inline">\(s_i\)</span> is 1 if <span class="math inline">\(y_i = 1\)</span> and <span class="math inline">\(s_i = -1\)</span> if <span class="math inline">\(y_i = 0\)</span>.</p>
<p>Again, the sum of the deviance residuals is the deviance.</p>
</section>
<section id="dispersion-parameter" class="level3" data-number="20.5.4">
<h3 data-number="20.5.4" class="anchored" data-anchor-id="dispersion-parameter"><span class="header-section-number">20.5.4</span> Dispersion Parameter</h3>
<p>The dispersion parameter is taken to be 1 for <code>glm</code> fit using either the <code>binomial</code> or <code>Poisson</code> families. For other sorts of generalized linear models, the dispersion parameter will be of some importance in estimating standard errors sensibly.</p>
</section>
<section id="fisher-scoring-iterations" class="level3" data-number="20.5.5">
<h3 data-number="20.5.5" class="anchored" data-anchor-id="fisher-scoring-iterations"><span class="header-section-number">20.5.5</span> Fisher Scoring iterations</h3>
<p>The solution of a logistic regression model involves maximizing a likelihood function. Fisher’s scoring algorithm in our <code>res_modA</code> needed five iterations to perform the logistic regression fit. All that this tells you is that the model converged, and didn’t require a lot of time to do so.</p>
</section>
</section>
<section id="plotting-a-simple-logistic-regression-model" class="level2" data-number="20.6">
<h2 data-number="20.6" class="anchored" data-anchor-id="plotting-a-simple-logistic-regression-model"><span class="header-section-number">20.6</span> Plotting a Simple Logistic Regression Model</h2>
<p>Let’s plot the logistic regression model <code>res_modA</code> for <code>died</code> using the extent of the resection in terms of probabilities. We can use either of two different approaches:</p>
<ul>
<li>we can plot the fitted values from our specific model against the original data, using the <code>augment</code> function from the <code>broom</code> package, or</li>
<li>we can create a smooth function called <code>binomial_smooth</code> that plots a simple logistic model in an analogous way to <code>geom_smooth(method = "lm")</code> for a simple linear regression.</li>
</ul>
<section id="using-augment-to-capture-the-fitted-probabilities" class="level3" data-number="20.6.1">
<h3 data-number="20.6.1" class="anchored" data-anchor-id="using-augment-to-capture-the-fitted-probabilities"><span class="header-section-number">20.6.1</span> Using <code>augment</code> to capture the fitted probabilities</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>res_A_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(res_modA, resect, </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res_A_aug)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  subj_id   age prior resection intubated  died .fitted .resid    .hat .sigma
    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1       1    34     1       2.5         0     0  0.0705 -0.382 0.0100   0.826
2       2    57     0       5           0     0  0.326  -0.889 0.0337   0.823
3       3    60     1       4           1     1  0.187   1.83  0.0120   0.811
4       4    62     1       4.2         0     0  0.211  -0.689 0.0143   0.824
5       5    28     0       6           1     1  0.504   1.17  0.0818   0.820
6       6    52     0       3           0     0  0.0990 -0.457 0.00922  0.826
# ℹ 2 more variables: .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
<p>This approach augments the <code>resect</code> data set with fitted, residual and other summaries of each observation’s impact on the fit, using the “response” type of prediction, which yields the fitted probabilities in the <code>.fitted</code> column.</p>
</section>
<section id="plotting-a-logistic-regression-models-fitted-values" class="level3" data-number="20.6.2">
<h3 data-number="20.6.2" class="anchored" data-anchor-id="plotting-a-logistic-regression-models-fitted-values"><span class="header-section-number">20.6.2</span> Plotting a Logistic Regression Model’s Fitted Values</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(res_A_aug, <span class="fu">aes</span>(<span class="at">x =</span> resection, <span class="at">y =</span> died)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> resection, <span class="at">y =</span> .fitted), </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Logistic Regression from Model res_modA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="plotting-a-simple-logistic-model-using-binomial_smooth" class="level3" data-number="20.6.3">
<h3 data-number="20.6.3" class="anchored" data-anchor-id="plotting-a-simple-logistic-model-using-binomial_smooth"><span class="header-section-number">20.6.3</span> Plotting a Simple Logistic Model using <code>binomial_smooth</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>binomial_smooth <span class="ot">&lt;-</span> <span class="cf">function</span>(...) {</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>), ...)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resect, <span class="fu">aes</span>(<span class="at">x =</span> resection, <span class="at">y =</span> died)) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">binomial_smooth</span>() <span class="sc">+</span> <span class="do">## ...smooth(se=FALSE) to leave out interval</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Logistic Regression from Model A"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As expected, we see an increase in the model probability of death as the extent of the resection grows larger.</p>
</section>
</section>
<section id="how-well-does-model-a-classify-subjects" class="level2" data-number="20.7">
<h2 data-number="20.7" class="anchored" data-anchor-id="how-well-does-model-a-classify-subjects"><span class="header-section-number">20.7</span> How well does Model A classify subjects?</h2>
<p>A natural question to ask is how well does our model classify patients in terms of likelihood of death.</p>
<p>We could specify a particular rule, for example: if the predicted probability of death is 0.5 or greater, then predict “Died”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>res_A_aug<span class="sc">$</span>rule<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(res_A_aug<span class="sc">$</span>.fitted <span class="sc">&gt;=</span> <span class="fl">0.5</span>, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Predict Died"</span>, <span class="st">"Predict Alive"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res_A_aug<span class="sc">$</span>rule<span class="fl">.5</span>, res_A_aug<span class="sc">$</span>died)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                  0   1
  Predict Alive 114  16
  Predict Died    3   1</code></pre>
</div>
</div>
<p>And perhaps build the linked table of row probabilities which tells us, for example, that 87.69% of the patients predicted by the model to be alive actually did survive.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">prop.table</span>(</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">table</span>(res_A_aug<span class="sc">$</span>rule<span class="fl">.5</span>, res_A_aug<span class="sc">$</span>died), <span class="dv">1</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                    0     1
  Predict Alive 87.69 12.31
  Predict Died  75.00 25.00</code></pre>
</div>
</div>
<p>Or the table of column probabilities which tell us, for example, that 97.44% of those who actually survived were predicted by the model to be alive.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">prop.table</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">table</span>(res_A_aug<span class="sc">$</span>rule<span class="fl">.5</span>, res_A_aug<span class="sc">$</span>died), <span class="dv">2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                    0     1
  Predict Alive 97.44 94.12
  Predict Died   2.56  5.88</code></pre>
</div>
</div>
<p>We’ll discuss various measures of concordance derived from this sort of classification later.</p>
</section>
<section id="the-confusion-matrix" class="level2" data-number="20.8">
<h2 data-number="20.8" class="anchored" data-anchor-id="the-confusion-matrix"><span class="header-section-number">20.8</span> The Confusion Matrix</h2>
<p>Let’s build this misclassification table in standard epidemiological format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>res_A_aug <span class="ot">&lt;-</span> res_A_aug <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">death_predicted =</span> <span class="fu">factor</span>(.fitted <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">death_actual =</span> <span class="fu">factor</span>(died <span class="sc">==</span> <span class="st">"1"</span>),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">death_predicted =</span> <span class="fu">fct_relevel</span>(death_predicted, <span class="st">"TRUE"</span>),</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">death_actual =</span> <span class="fu">fct_relevel</span>(death_actual, <span class="st">"TRUE"</span>)) </span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>confuseA_small <span class="ot">&lt;-</span> <span class="fu">table</span>(res_A_aug<span class="sc">$</span>death_predicted, res_A_aug<span class="sc">$</span>death_actual)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>confuseA_small</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        TRUE FALSE
  TRUE     1     3
  FALSE   16   114</code></pre>
</div>
</div>
<p>In total, we have 134 observations.</p>
<ul>
<li>115 correct predictions, or 85.8% accuracy</li>
<li>17 subjects who died, or 12.6% prevalence of death</li>
<li>4 subjects who were predicted to die, or 3.0% detection prevalence.</li>
</ul>
<p>The sensitivity (also called recall) here is 1 / (1 + 16) = 5.9%.</p>
<ul>
<li>5.9% of the subjects who actually died were predicted to die by the model.</li>
</ul>
<p>The specificity here is 114 / (114 + 3) = 97.4%.</p>
<ul>
<li>97.4% of the subjects who actually survived were predicted to survive by the model.</li>
</ul>
<p>The positive predictive value (PPV: also called precision) is 1 / (1 + 3) = 25%</p>
<ul>
<li>Our predictions of death were correct 25% of the time.</li>
</ul>
<p>The negative predictive value (NPV) is 114 / (114 + 16) = 87.7%</p>
<ul>
<li>Our predictions of survival were correct 87.7% of the time.</li>
</ul>
</section>
<section id="using-the-confusionmatrix-tool-from-the-caret-package" class="level2" data-number="20.9">
<h2 data-number="20.9" class="anchored" data-anchor-id="using-the-confusionmatrix-tool-from-the-caret-package"><span class="header-section-number">20.9</span> Using the <code>confusionMatrix</code> tool from the <code>caret</code> package</h2>
<p>This provides a more detailed summary of the classification results from our logistic regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> <span class="fu">factor</span>(res_A_aug<span class="sc">$</span>.fitted <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">reference =</span> <span class="fu">factor</span>(res_A_aug<span class="sc">$</span>died <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">positive =</span> <span class="st">"TRUE"</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction FALSE TRUE
     FALSE   114   16
     TRUE      3    1
                                          
               Accuracy : 0.8582          
                 95% CI : (0.7875, 0.9124)
    No Information Rate : 0.8731          
    P-Value [Acc &gt; NIR] : 0.747802        
                                          
                  Kappa : 0.0493          
                                          
 Mcnemar's Test P-Value : 0.005905        
                                          
            Sensitivity : 0.058824        
            Specificity : 0.974359        
         Pos Pred Value : 0.250000        
         Neg Pred Value : 0.876923        
             Prevalence : 0.126866        
         Detection Rate : 0.007463        
   Detection Prevalence : 0.029851        
      Balanced Accuracy : 0.516591        
                                          
       'Positive' Class : TRUE            
                                          </code></pre>
</div>
</div>
<ul>
<li>The No Information Rate or NIR is just the percentage of correct predictions we’d get if we just predicted the more common classification (not dead) for every subject.</li>
<li>Kappa is a correlation statistic ranging from -1 to +1. It measures the inter-rater reliability of our predictions and the true classifications, in this context. Complete agreement would be +1, and complete disagreement would be -1.</li>
</ul>
</section>
<section id="receiver-operating-characteristic-curve-analysis" class="level2" data-number="20.10">
<h2 data-number="20.10" class="anchored" data-anchor-id="receiver-operating-characteristic-curve-analysis"><span class="header-section-number">20.10</span> Receiver Operating Characteristic Curve Analysis</h2>
<p>One way to assess the predictive accuracy within the model development sample in a logistic regression is to consider an analyses based on the receiver operating characteristic (ROC) curve. ROC curves are commonly used in assessing diagnoses in medical settings, and in signal detection applications.</p>
<p>The accuracy of a “test” can be evaluated by considering two types of errors: false positives and false negatives.</p>
<p>In our <code>res_modA</code> model, we use <code>resection</code> size to predict whether the patient <code>died</code>. Suppose we established a value R, so that if the resection size was larger than R cm, we would predict that the patient <code>died</code>, and otherwise we would predict that the patient did not die.</p>
<p>A good outcome of our model’s “test”, then, would be when the resection size is larger than R for a patient who actually died. Another good outcome would be when the resection size is smaller than R for a patient who survived.</p>
<p>But we can make errors, too.</p>
<ul>
<li>A false positive error in this setting would occur when the resection size is larger than R (so we predict the patient dies) but in fact the patient does not die.</li>
<li>A false negative error in this case would occur when the resection size is smaller than R (so we predict the patient survives) but in fact the patient dies.</li>
</ul>
<p>Formally, the true positive fraction (TPF) for a specific resection cutoff <span class="math inline">\(R\)</span>, is the probability of a positive test (a prediction that the patient will die) among the people who have the outcome died = 1 (those who actually die).</p>
<p><span class="math display">\[
TPF(R) = Pr(resection &gt; R | subject died)
\]</span></p>
<p>Similarly, the false positive fraction (FPF) for a specific cutoff <span class="math inline">\(R\)</span> is the probability of a positive test (prediction that the patient will die) among the people with died = 0 (those who don’t actually die)</p>
<p><span class="math display">\[
FPF(R) = Pr(resection &gt; R | subject did not die)
\]</span></p>
<p>The True Positive Rate is referred to as the sensitivity of a diagnostic test, and the True Negative rate (1 - the False Positive rate) is referred to as the specificity of a diagnostic test.</p>
<p>Since the cutoff <span class="math inline">\(R\)</span> is not fixed in advanced, we can plot the value of TPF (on the y axis) against FPF (on the x axis) for all possible values of <span class="math inline">\(R\)</span>, and this is what the ROC curve is. Others refer to the Sensitivity on the Y axis, and 1-Specificity on the X axis, and this is the same idea.</p>
<p>Before we get too far into the weeds, let me show you some simple situations so you can understand what you might learn from the ROC curve. The web page http://blog.yhat.com/posts/roc-curves.html provides source materials.</p>
<section id="interpreting-the-area-under-the-roc-curve" class="level3" data-number="20.10.1">
<h3 data-number="20.10.1" class="anchored" data-anchor-id="interpreting-the-area-under-the-roc-curve"><span class="header-section-number">20.10.1</span> Interpreting the Area under the ROC curve</h3>
<p>The AUC or Area under the ROC curve is the amount of space underneath the ROC curve. Often referred to as the c statistic, the AUC represents the quality of your TPR and FPR overall in a single number. The C statistic ranges from 0 to 1, with C = 0.5 for a prediction that is no better than random guessing, and C = 1 for a perfect prediction model.</p>
<p>Next, I’ll build a simulation to demonstrate several possible ROC curves in the sections that follow.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">432999</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>sim.temp <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">200</span>), </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">prob =</span> <span class="fu">exp</span>(x)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(x)), </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> <span class="fu">as.numeric</span>(<span class="dv">1</span> <span class="sc">*</span> <span class="fu">runif</span>(<span class="dv">200</span>) <span class="sc">&lt;</span> prob))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>sim.temp <span class="ot">&lt;-</span> sim.temp <span class="sc">|&gt;</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">p_guess =</span> <span class="dv">1</span>,</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">p_perfect =</span> y, </span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">p_bad =</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="dv">2</span><span class="sc">*</span>x) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="dv">2</span><span class="sc">*</span>x)),</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">p_ok =</span> prob <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>y)<span class="sc">*</span><span class="fu">runif</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="fl">0.05</span>),</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">p_good =</span> prob <span class="sc">+</span> y<span class="sc">*</span><span class="fu">runif</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="fl">0.27</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="what-if-we-are-guessing" class="level4" data-number="20.10.1.1">
<h4 data-number="20.10.1.1" class="anchored" data-anchor-id="what-if-we-are-guessing"><span class="header-section-number">20.10.1.1</span> What if we are guessing?</h4>
<p>If we’re guessing completely at random, then the model should correctly classify a subject (as died or not died) about 50% of the time, so the TPR and FPR will be equal. This yields a diagonal line in the ROC curve, and an area under the curve (C statistic) of 0.5.</p>
<p>There are several ways to do this on the web, but I’ll show this one, which has some bizarre code, but that’s a function of using a package called <code>ROCR</code> to do the work. It comes from <a href="http://blog.yhat.com/posts/roc-curves.html">this link</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>pred_guess <span class="ot">&lt;-</span> <span class="fu">prediction</span>(sim.temp<span class="sc">$</span>p_guess, sim.temp<span class="sc">$</span>y)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>perf_guess <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_guess, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>auc_guess <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_guess, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>auc_guess <span class="ot">&lt;-</span> <span class="fu">round</span>(auc_guess<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>roc_guess <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf_guess<span class="sc">@</span>x.values),</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">tpr=</span><span class="fu">unlist</span>(perf_guess<span class="sc">@</span>y.values),</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc_guess, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Guessing: ROC Curve w/ AUC="</span>, auc_guess)) <span class="sc">+</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="what-if-we-classify-things-perfectly" class="level4" data-number="20.10.1.2">
<h4 data-number="20.10.1.2" class="anchored" data-anchor-id="what-if-we-classify-things-perfectly"><span class="header-section-number">20.10.1.2</span> What if we classify things perfectly?</h4>
<p>If we’re classifying subjects perfectly, then we have a TPR of 1 and an FPR of 0. That yields an ROC curve that looks like the upper and left edges of a box. If our model correctly classifies a subject (as died or not died) 100% of the time, the area under the curve (c statistic) will be 1.0. We’ll add in the diagonal line here (in a dashed black line) to show how this model compares to random guessing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>pred_perf <span class="ot">&lt;-</span> <span class="fu">prediction</span>(sim.temp<span class="sc">$</span>p_perfect, sim.temp<span class="sc">$</span>y)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>perf_perf <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_perf, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>auc_perf <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_perf, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>auc_perf <span class="ot">&lt;-</span> <span class="fu">round</span>(auc_perf<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>roc_perf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf_perf<span class="sc">@</span>x.values),</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">tpr=</span><span class="fu">unlist</span>(perf_perf<span class="sc">@</span>y.values),</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc_perf, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Perfect Prediction: ROC Curve w/ AUC="</span>, auc_perf)) <span class="sc">+</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="what-does-worse-than-guessing-look-like" class="level4" data-number="20.10.1.3">
<h4 data-number="20.10.1.3" class="anchored" data-anchor-id="what-does-worse-than-guessing-look-like"><span class="header-section-number">20.10.1.3</span> What does “worse than guessing” look like?</h4>
<p>A bad classifier will appear below and to the right of the diagonal line we’d see if we were completely guessing. Such a model will have a c statistic below 0.5, and will be valueless.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>pred_bad <span class="ot">&lt;-</span> <span class="fu">prediction</span>(sim.temp<span class="sc">$</span>p_bad, sim.temp<span class="sc">$</span>y)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>perf_bad <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_bad, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>auc_bad <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_bad, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>auc_bad <span class="ot">&lt;-</span> <span class="fu">round</span>(auc_bad<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>roc_bad <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf_bad<span class="sc">@</span>x.values),</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">tpr=</span><span class="fu">unlist</span>(perf_bad<span class="sc">@</span>y.values),</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc_bad, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"A Bad Model: ROC Curve w/ AUC="</span>, auc_bad)) <span class="sc">+</span></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="what-does-better-than-guessing-look-like" class="level4" data-number="20.10.1.4">
<h4 data-number="20.10.1.4" class="anchored" data-anchor-id="what-does-better-than-guessing-look-like"><span class="header-section-number">20.10.1.4</span> What does “better than guessing” look like?</h4>
<p>An “OK” classifier will appear above and to the left of the diagonal line we’d see if we were completely guessing. Such a model will have a c statistic above 0.5, and might have some value. The plot below shows a very fairly poor model, but at least it’s better than guessing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>pred_ok <span class="ot">&lt;-</span> <span class="fu">prediction</span>(sim.temp<span class="sc">$</span>p_ok, sim.temp<span class="sc">$</span>y)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>perf_ok <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_ok, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>auc_ok <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_ok, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>auc_ok <span class="ot">&lt;-</span> <span class="fu">round</span>(auc_ok<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>roc_ok <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf_ok<span class="sc">@</span>x.values),</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">tpr=</span><span class="fu">unlist</span>(perf_ok<span class="sc">@</span>y.values),</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc_ok, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"A Mediocre Model: ROC Curve w/ AUC="</span>, auc_ok)) <span class="sc">+</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Sometimes people grasp for a rough guide as to the accuracy of a model’s predictions based on the area under the ROC curve. A common thought is to assess the C statistic much like you would a class grade.</p>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">C statistic</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.90 to 1.00</td>
<td>model does an excellent job at discriminating “yes” from “no” (A)</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.80 to 0.90</td>
<td>model does a good job (B)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.70 to 0.80</td>
<td>model does a fair job (C)</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.60 to 0.70</td>
<td>model does a poor job (D)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.50 to 0.60</td>
<td>model fails (F)</td>
</tr>
<tr class="even">
<td style="text-align: right;">below 0.50</td>
<td>model is worse than random guessing</td>
</tr>
</tbody>
</table>
</section>
<section id="what-does-pretty-good-look-like" class="level4" data-number="20.10.1.5">
<h4 data-number="20.10.1.5" class="anchored" data-anchor-id="what-does-pretty-good-look-like"><span class="header-section-number">20.10.1.5</span> What does “pretty good” look like?</h4>
<p>A strong and good classifier will appear above and to the left of the diagonal line we’d see if we were completely guessing, often with a nice curve that is continually increasing and appears to be pulled up towards the top left. Such a model will have a c statistic well above 0.5, but not as large as 1. The plot below shows a stronger model, which appears substantially better than guessing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>pred_good <span class="ot">&lt;-</span> <span class="fu">prediction</span>(sim.temp<span class="sc">$</span>p_good, sim.temp<span class="sc">$</span>y)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>perf_good <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_good, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>auc_good <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_good, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>auc_good <span class="ot">&lt;-</span> <span class="fu">round</span>(auc_good<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>roc_good <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf_good<span class="sc">@</span>x.values),</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">tpr=</span><span class="fu">unlist</span>(perf_good<span class="sc">@</span>y.values),</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc_good, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"A Pretty Good Model: ROC Curve w/ AUC="</span>, auc_good)) <span class="sc">+</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="the-roc-plot-for-res_moda" class="level2" data-number="20.11">
<h2 data-number="20.11" class="anchored" data-anchor-id="the-roc-plot-for-res_moda"><span class="header-section-number">20.11</span> The ROC Plot for <code>res_modA</code></h2>
<p>Let me show you the ROC curve for our <code>res_modA</code> model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="do">## requires ROCR package</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(res_modA, resect, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">prediction</span>(prob, resect<span class="sc">$</span>died)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>perf <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">round</span>(auc<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>roc.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>x.values),</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">tpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>y.values),</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc.data, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"ROC Curve w/ AUC="</span>, auc)) <span class="sc">+</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the C statistic (AUC = 0.771) this would rank somewhere near the high end of a “fair” predictive model by this standard, not quite to the level of a “good” model.</p>
<section id="another-way-to-plot-the-roc-curve" class="level3" data-number="20.11.1">
<h3 data-number="20.11.1" class="anchored" data-anchor-id="another-way-to-plot-the-roc-curve"><span class="header-section-number">20.11.1</span> Another way to plot the ROC Curve</h3>
<p>If we’ve loaded the <code>pROC</code> package, we can also use the following (admittedly simpler) approach to plot the ROC curve, without <code>ggplot2</code>, and to obtain the C statistic, and a 95% confidence interval around that C statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="do">## requires pROC package</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>roc.modA <span class="ot">&lt;-</span> </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">roc</span>(resect<span class="sc">$</span>died <span class="sc">~</span> <span class="fu">predict</span>(res_modA, <span class="at">type=</span><span class="st">"response"</span>),</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>roc.modA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
roc.formula(formula = resect$died ~ predict(res_modA, type = "response"),     ci = TRUE)

Data: predict(res_modA, type = "response") in 117 controls (resect$died 0) &lt; 17 cases (resect$died 1).
Area under the curve: 0.7707
95% CI: 0.67-0.8715 (DeLong)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc.modA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="assessing-residual-plots-from-model-a" class="level2" data-number="20.12">
<h2 data-number="20.12" class="anchored" data-anchor-id="assessing-residual-plots-from-model-a"><span class="header-section-number">20.12</span> Assessing Residual Plots from Model A</h2>
<blockquote class="blockquote">
<p>Residuals are certainly less informative for logistic regression than they are for linear regression: not only do yes/no outcomes inherently contain less information than continuous ones, but the fact that the adjusted response depends on the fit hampers our ability to use residuals as external checks on the model.</p>
</blockquote>
<blockquote class="blockquote">
<p>This is mitigated to some extent, however, by the fact that we are also making fewer distributional assumptions in logistic regression, so there is no need to inspect residuals for, say, skewness or heteroskedasticity.</p>
</blockquote>
<ul>
<li>Patrick Breheny, University of Kentucky, Slides on GLM Residuals and Diagnostics (no longer online, alas.)</li>
</ul>
<p>The usual residual plots are available in R for a logistic regression model, but most of them are irrelevant in the logistic regression setting. The residuals shouldn’t follow a standard Normal distribution, and they will not show constant variance over the range of the predictor variables, so plots looking into those issues aren’t helpful.</p>
<p>The only plot from the standard set that we’ll look at in many settings is plot 5, which helps us assess influence (via Cook’s distance contours), and a measure related to leverage (how unusual an observation is in terms of the predictors) and standardized Pearson residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_modA, <span class="at">which =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this case, I don’t see any highly influential points, as no points fall outside of the Cook’s distance (0.5 or 1) contours.</p>
</section>
<section id="model-b-a-kitchen-sink-logistic-regression-model" class="level2" data-number="20.13">
<h2 data-number="20.13" class="anchored" data-anchor-id="model-b-a-kitchen-sink-logistic-regression-model"><span class="header-section-number">20.13</span> Model B: A “Kitchen Sink” Logistic Regression Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>res_modB <span class="ot">&lt;-</span> <span class="fu">glm</span>(died <span class="sc">~</span> resection <span class="sc">+</span> age <span class="sc">+</span> prior <span class="sc">+</span> intubated,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> resect, <span class="at">family =</span> binomial)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>res_modB</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = died ~ resection + age + prior + intubated, family = binomial, 
    data = resect)

Coefficients:
(Intercept)    resection          age        prior    intubated  
  -5.152886     0.612211     0.001173     0.814691     2.810797  

Degrees of Freedom: 133 Total (i.e. Null);  129 Residual
Null Deviance:      101.9 
Residual Deviance: 67.36    AIC: 77.36</code></pre>
</div>
</div>
<section id="comparing-model-a-to-model-b" class="level3" data-number="20.13.1">
<h3 data-number="20.13.1" class="anchored" data-anchor-id="comparing-model-a-to-model-b"><span class="header-section-number">20.13.1</span> Comparing Model A to Model B</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(res_modA, res_modB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: died ~ resection
Model 2: died ~ resection + age + prior + intubated
  Resid. Df Resid. Dev Df Deviance
1       132     89.493            
2       129     67.359  3   22.134</code></pre>
</div>
</div>
<p>The addition of <code>age</code>, <code>prior</code> and <code>intubated</code> reduces the lack of fit by 22.134 points, at a cost of 3 degrees of freedom.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(res_modA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          102.     133  -44.7  93.5  99.3     89.5         132   134</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(res_modB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          102.     133  -33.7  77.4  91.8     67.4         129   134</code></pre>
</div>
</div>
<p>By either AIC or BIC, the larger model (<code>res_modB</code>) looks more effective.</p>
</section>
<section id="interpreting-model-b" class="level3" data-number="20.13.2">
<h3 data-number="20.13.2" class="anchored" data-anchor-id="interpreting-model-b"><span class="header-section-number">20.13.2</span> Interpreting Model B</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_modB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = died ~ resection + age + prior + intubated, family = binomial, 
    data = resect)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.7831  -0.3741  -0.2386  -0.2014   2.5228  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -5.152886   1.469453  -3.507 0.000454 ***
resection    0.612211   0.282807   2.165 0.030406 *  
age          0.001173   0.020646   0.057 0.954700    
prior        0.814691   0.704785   1.156 0.247705    
intubated    2.810797   0.658395   4.269 1.96e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 101.943  on 133  degrees of freedom
Residual deviance:  67.359  on 129  degrees of freedom
AIC: 77.359

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>It appears that the <code>intubated</code> predictor adds some value to the model, by the Wald test.</p>
<p>Let’s focus on the impact of these variables through odds ratios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(res_modB, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, conf.low, conf.high)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  term        estimate conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  0.00578 0.000241    0.0837
2 resection    1.84    1.08        3.35  
3 age          1.00    0.962       1.04  
4 prior        2.26    0.549       9.17  
5 intubated   16.6     4.75       64.6   </code></pre>
</div>
</div>
<p>At a 5% significance level, we might conclude that:</p>
<ul>
<li>larger sized <code>resection</code>s are associated with a meaningful rise (est OR: 1.84, 95% CI 1.08, 3.35) in the odds of death, holding all other predictors constant,</li>
<li>the need for <code>intubation</code> at the end of surgery is associated with a substantial rise (est OR: 16.6, 95% CI 4.7, 64.7) in the odds of death, holding all other predictors constant, but that</li>
<li>older <code>age</code> as well as having a <code>prior</code> tracheal surgery appears to be associated with an increase in death risk, but not with a small p value.</li>
</ul>
</section>
</section>
<section id="plotting-model-b" class="level2" data-number="20.14">
<h2 data-number="20.14" class="anchored" data-anchor-id="plotting-model-b"><span class="header-section-number">20.14</span> Plotting Model B</h2>
<p>Let’s think about plotting the fitted values from our model, in terms of probabilities.</p>
<section id="using-augment-to-capture-the-fitted-probabilities-1" class="level3" data-number="20.14.1">
<h3 data-number="20.14.1" class="anchored" data-anchor-id="using-augment-to-capture-the-fitted-probabilities-1"><span class="header-section-number">20.14.1</span> Using <code>augment</code> to capture the fitted probabilities</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>res_B_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(res_modB, resect, </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res_B_aug)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  subj_id   age prior resection intubated  died .fitted .resid   .hat .sigma
    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1       1    34     1       2.5         0     0  0.0591 -0.349 0.0267  0.725
2       2    57     0       5           0     0  0.117  -0.498 0.0380  0.724
3       3    60     1       4           1     1  0.729   0.794 0.114   0.722
4       4    62     1       4.2         0     0  0.155  -0.581 0.0704  0.723
5       5    28     0       6           1     1  0.796   0.675 0.131   0.723
6       6    52     0       3           0     0  0.0371 -0.275 0.0105  0.725
# ℹ 2 more variables: .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="plotting-model-b-fits-by-observed-mortality" class="level3" data-number="20.14.2">
<h3 data-number="20.14.2" class="anchored" data-anchor-id="plotting-model-b-fits-by-observed-mortality"><span class="header-section-number">20.14.2</span> Plotting Model B Fits by Observed Mortality</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(res_B_aug, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(died), <span class="at">y =</span> .fitted, <span class="at">col =</span> <span class="fu">factor</span>(died))) <span class="sc">+</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">col =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Certainly it appears as though most of our predicted probabilities (of death) for the subjects who actually survived are quite small, but not all of them. We also have at least 6 big “misses” among the 17 subjects who actually died.</p>
</section>
<section id="confusion-matrix-for-model-b" class="level3" data-number="20.14.3">
<h3 data-number="20.14.3" class="anchored" data-anchor-id="confusion-matrix-for-model-b"><span class="header-section-number">20.14.3</span> Confusion Matrix for Model B</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> <span class="fu">factor</span>(res_B_aug<span class="sc">$</span>.fitted <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">reference =</span> <span class="fu">factor</span>(res_B_aug<span class="sc">$</span>died <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">positive =</span> <span class="st">"TRUE"</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction FALSE TRUE
     FALSE   113    6
     TRUE      4   11
                                         
               Accuracy : 0.9254         
                 95% CI : (0.867, 0.9636)
    No Information Rate : 0.8731         
    P-Value [Acc &gt; NIR] : 0.03897        
                                         
                  Kappa : 0.6453         
                                         
 Mcnemar's Test P-Value : 0.75183        
                                         
            Sensitivity : 0.64706        
            Specificity : 0.96581        
         Pos Pred Value : 0.73333        
         Neg Pred Value : 0.94958        
             Prevalence : 0.12687        
         Detection Rate : 0.08209        
   Detection Prevalence : 0.11194        
      Balanced Accuracy : 0.80644        
                                         
       'Positive' Class : TRUE           
                                         </code></pre>
</div>
</div>
</section>
<section id="the-roc-curve-for-model-b" class="level3" data-number="20.14.4">
<h3 data-number="20.14.4" class="anchored" data-anchor-id="the-roc-curve-for-model-b"><span class="header-section-number">20.14.4</span> The ROC curve for Model B</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="do">## requires ROCR package</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(res_modB, resect, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">prediction</span>(prob, resect<span class="sc">$</span>died)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>perf <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">round</span>(auc<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>roc.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>x.values),</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">tpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>y.values),</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc.data, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Model B: ROC Curve w/ AUC="</span>, auc)) <span class="sc">+</span></span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The area under the curve (C-statistic) is 0.86, which certainly looks like a more discriminating fit than model A with resection alone.</p>
</section>
<section id="residuals-leverage-and-influence" class="level3" data-number="20.14.5">
<h3 data-number="20.14.5" class="anchored" data-anchor-id="residuals-leverage-and-influence"><span class="header-section-number">20.14.5</span> Residuals, Leverage and Influence</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_modB, <span class="at">which =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic2_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Again, we see no signs of deeply influential points in this model.</p>
<p>We’ll continue working with these <code>resect</code> data as we fit logistic regression models with the help of the <code>rms</code> package in our next Chapter.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-Long1997" class="csl-entry" role="doc-biblioentry">
Long, J. Scott. 1997. <em>Regression Models for Categorical and Limited Dependent Variables</em>. Thousand Oaks, CA: Sage Publications.
</div>
<div id="ref-Peduzzi1996" class="csl-entry" role="doc-biblioentry">
Peduzzi, Peter, John Concato, Elizabeth Kemper, Theodore R. Holford, and Alvan R. Feinstein. 1996. <span>“A Simulation Study of the Number of Events Per Variable in Logistic Regression Analysis.”</span> <em>Journal of Clinical Epidemiology</em> 49 (12): 1373–79.
</div>
<div id="ref-Riffenburgh2006" class="csl-entry" role="doc-biblioentry">
Riffenburgh, Robert H. 2006. <em>Statistics in Medicine</em>. Second Edition. Burlington, MA: Elsevier Academic Press.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./logistic1.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./logistic3.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>