<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 21&nbsp; Logistic Regression with lrm</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./effectsize.html" rel="next">
<link href="./logistic2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./logistic3.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with `lrm`</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
        <div class="sidebar-tools-main">
    <a href="./Data-Science-for-Biological,-Medical-and-Health-Research.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./incomplete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">This is work in progress</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinaloutcome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Time To Event / Survival Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lasso.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">NEW!! A Few LASSO Ideas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">NEW!! Bayes and a Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup-used-here" id="toc-r-setup-used-here" class="nav-link active" data-scroll-target="#r-setup-used-here"><span class="header-section-number">21.1</span> R Setup Used Here</a>
  <ul class="collapse">
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="header-section-number">21.1.1</span> Data Load</a></li>
  </ul></li>
  <li><a href="#logistic-regression-using-lrm" id="toc-logistic-regression-using-lrm" class="nav-link" data-scroll-target="#logistic-regression-using-lrm"><span class="header-section-number">21.2</span> Logistic Regression using <code>lrm</code></a>
  <ul class="collapse">
  <li><a href="#interpreting-nagelkerke-r2" id="toc-interpreting-nagelkerke-r2" class="nav-link" data-scroll-target="#interpreting-nagelkerke-r2"><span class="header-section-number">21.2.1</span> Interpreting Nagelkerke <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#interpreting-the-c-statistic-and-plotting-the-roc-curve" id="toc-interpreting-the-c-statistic-and-plotting-the-roc-curve" class="nav-link" data-scroll-target="#interpreting-the-c-statistic-and-plotting-the-roc-curve"><span class="header-section-number">21.2.2</span> Interpreting the C statistic and Plotting the ROC Curve</a></li>
  <li><a href="#the-c-statistic-and-somers-d" id="toc-the-c-statistic-and-somers-d" class="nav-link" data-scroll-target="#the-c-statistic-and-somers-d"><span class="header-section-number">21.2.3</span> The C statistic and Somers’ D</a></li>
  <li><a href="#validating-the-logistic-regression-model-summary-statistics" id="toc-validating-the-logistic-regression-model-summary-statistics" class="nav-link" data-scroll-target="#validating-the-logistic-regression-model-summary-statistics"><span class="header-section-number">21.2.4</span> Validating the Logistic Regression Model Summary Statistics</a></li>
  <li><a href="#plotting-the-summary-of-the-lrm-approach" id="toc-plotting-the-summary-of-the-lrm-approach" class="nav-link" data-scroll-target="#plotting-the-summary-of-the-lrm-approach"><span class="header-section-number">21.2.5</span> Plotting the Summary of the <code>lrm</code> approach</a></li>
  <li><a href="#plot-in-sample-predictions-for-model-c" id="toc-plot-in-sample-predictions-for-model-c" class="nav-link" data-scroll-target="#plot-in-sample-predictions-for-model-c"><span class="header-section-number">21.2.6</span> Plot In-Sample Predictions for Model C</a></li>
  <li><a href="#anova-from-the-lrm-approach" id="toc-anova-from-the-lrm-approach" class="nav-link" data-scroll-target="#anova-from-the-lrm-approach"><span class="header-section-number">21.2.7</span> ANOVA from the <code>lrm</code> approach</a></li>
  <li><a href="#are-any-points-particularly-influential" id="toc-are-any-points-particularly-influential" class="nav-link" data-scroll-target="#are-any-points-particularly-influential"><span class="header-section-number">21.2.8</span> Are any points particularly influential?</a></li>
  <li><a href="#a-nomogram-for-model-c" id="toc-a-nomogram-for-model-c" class="nav-link" data-scroll-target="#a-nomogram-for-model-c"><span class="header-section-number">21.2.9</span> A Nomogram for Model C</a></li>
  </ul></li>
  <li><a href="#model-d-an-augmented-kitchen-sink-model" id="toc-model-d-an-augmented-kitchen-sink-model" class="nav-link" data-scroll-target="#model-d-an-augmented-kitchen-sink-model"><span class="header-section-number">21.3</span> Model D: An Augmented Kitchen Sink Model</a>
  <ul class="collapse">
  <li><a href="#spearman-rho2-plot" id="toc-spearman-rho2-plot" class="nav-link" data-scroll-target="#spearman-rho2-plot"><span class="header-section-number">21.3.1</span> Spearman <span class="math inline">\(\rho^2\)</span> Plot</a></li>
  <li><a href="#fitting-model-d-using-lrm" id="toc-fitting-model-d-using-lrm" class="nav-link" data-scroll-target="#fitting-model-d-using-lrm"><span class="header-section-number">21.3.2</span> Fitting Model D using <code>lrm</code></a></li>
  <li><a href="#assessing-model-d-using-lrms-tools" id="toc-assessing-model-d-using-lrms-tools" class="nav-link" data-scroll-target="#assessing-model-d-using-lrms-tools"><span class="header-section-number">21.3.3</span> Assessing Model D using <code>lrm</code>’s tools</a></li>
  <li><a href="#anova-and-wald-tests-for-model-d" id="toc-anova-and-wald-tests-for-model-d" class="nav-link" data-scroll-target="#anova-and-wald-tests-for-model-d"><span class="header-section-number">21.3.4</span> ANOVA and Wald Tests for Model D</a></li>
  <li><a href="#effect-sizes-in-model-d" id="toc-effect-sizes-in-model-d" class="nav-link" data-scroll-target="#effect-sizes-in-model-d"><span class="header-section-number">21.3.5</span> Effect Sizes in Model D</a></li>
  <li><a href="#plot-in-sample-predictions-for-model-d" id="toc-plot-in-sample-predictions-for-model-d" class="nav-link" data-scroll-target="#plot-in-sample-predictions-for-model-d"><span class="header-section-number">21.3.6</span> Plot In-Sample Predictions for Model D</a></li>
  <li><a href="#plotting-the-roc-curve-for-model-d" id="toc-plotting-the-roc-curve-for-model-d" class="nav-link" data-scroll-target="#plotting-the-roc-curve-for-model-d"><span class="header-section-number">21.3.7</span> Plotting the ROC curve for Model D</a></li>
  <li><a href="#validation-of-model-d-summaries" id="toc-validation-of-model-d-summaries" class="nav-link" data-scroll-target="#validation-of-model-d-summaries"><span class="header-section-number">21.3.8</span> Validation of Model D summaries</a></li>
  </ul></li>
  <li><a href="#model-e-fitting-a-reduced-model-in-light-of-model-d" id="toc-model-e-fitting-a-reduced-model-in-light-of-model-d" class="nav-link" data-scroll-target="#model-e-fitting-a-reduced-model-in-light-of-model-d"><span class="header-section-number">21.4</span> Model E: Fitting a Reduced Model in light of Model D</a>
  <ul class="collapse">
  <li><a href="#a-plot-comparing-the-two-intubation-groups" id="toc-a-plot-comparing-the-two-intubation-groups" class="nav-link" data-scroll-target="#a-plot-comparing-the-two-intubation-groups"><span class="header-section-number">21.4.1</span> A Plot comparing the two intubation groups</a></li>
  <li><a href="#nomogram-for-model-e" id="toc-nomogram-for-model-e" class="nav-link" data-scroll-target="#nomogram-for-model-e"><span class="header-section-number">21.4.2</span> Nomogram for Model E</a></li>
  <li><a href="#effect-sizes-from-model-e" id="toc-effect-sizes-from-model-e" class="nav-link" data-scroll-target="#effect-sizes-from-model-e"><span class="header-section-number">21.4.3</span> Effect Sizes from Model E</a></li>
  <li><a href="#plot-in-sample-predictions-for-model-e" id="toc-plot-in-sample-predictions-for-model-e" class="nav-link" data-scroll-target="#plot-in-sample-predictions-for-model-e"><span class="header-section-number">21.4.4</span> Plot In-Sample Predictions for Model E</a></li>
  <li><a href="#anova-for-model-e" id="toc-anova-for-model-e" class="nav-link" data-scroll-target="#anova-for-model-e"><span class="header-section-number">21.4.5</span> ANOVA for Model E</a></li>
  <li><a href="#validation-of-model-e" id="toc-validation-of-model-e" class="nav-link" data-scroll-target="#validation-of-model-e"><span class="header-section-number">21.4.6</span> Validation of Model E</a></li>
  <li><a href="#do-any-points-seem-particularly-influential" id="toc-do-any-points-seem-particularly-influential" class="nav-link" data-scroll-target="#do-any-points-seem-particularly-influential"><span class="header-section-number">21.4.7</span> Do any points seem particularly influential?</a></li>
  <li><a href="#fitting-model-e-using-glm-to-get-plots-about-influence" id="toc-fitting-model-e-using-glm-to-get-plots-about-influence" class="nav-link" data-scroll-target="#fitting-model-e-using-glm-to-get-plots-about-influence"><span class="header-section-number">21.4.8</span> Fitting Model E using <code>glm</code> to get plots about influence</a></li>
  </ul></li>
  <li><a href="#concordance-comparing-model-c-d-and-es-predictions" id="toc-concordance-comparing-model-c-d-and-es-predictions" class="nav-link" data-scroll-target="#concordance-comparing-model-c-d-and-es-predictions"><span class="header-section-number">21.5</span> Concordance: Comparing Model C, D and E’s predictions</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">21.6</span> Conclusions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="r-setup-used-here" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="r-setup-used-here"><span class="header-section-number">21.1</span> R Setup Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-load" class="level3" data-number="21.1.1">
<h3 data-number="21.1.1" class="anchored" data-anchor-id="data-load"><span class="header-section-number">21.1.1</span> Data Load</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>resect <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/resect.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="logistic-regression-using-lrm" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="logistic-regression-using-lrm"><span class="header-section-number">21.2</span> Logistic Regression using <code>lrm</code></h2>
<p>To obtain the Nagelkerke <span class="math inline">\(R^2\)</span> and the C statistic, as well as some other summaries, I’ll now demonstrate the use of <code>lrm</code> from the <code>rms</code> package to fit a logistic regression model.</p>
<p>We’ll return to the original model, predicting death using resection size alone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">datadist</span>(resect)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">datadist=</span><span class="st">"dd"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>res_modC <span class="ot">&lt;-</span> <span class="fu">lrm</span>(died <span class="sc">~</span> resection, <span class="at">data=</span>resect, <span class="at">x=</span><span class="cn">TRUE</span>, <span class="at">y=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>res_modC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = died ~ resection, data = resect, x = TRUE, y = TRUE)

                      Model Likelihood     Discrimination    Rank Discrim.    
                            Ratio Test            Indexes          Indexes    
Obs           134    LR chi2     12.45     R2       0.167    C       0.771    
 0            117    d.f.            1     R2(1,134)0.082    Dxy     0.541    
 1             17    Pr(&gt; chi2) 0.0004    R2(1,44.5)0.227    gamma   0.582    
max |deriv| 2e-06                          Brier    0.103    tau-a   0.121    

          Coef    S.E.   Wald Z Pr(&gt;|Z|)
Intercept -4.4337 0.8799 -5.04  &lt;0.0001 
resection  0.7417 0.2230  3.33  0.0009  </code></pre>
</div>
</div>
<p>This output specifies the following:</p>
<ul>
<li><code>Obs</code> = The number of observations used to fit the model, with <code>0</code> = the number of zeros and <code>1</code> = the number of ones in our outcome, <code>died</code>. Also specified is the maximum absolute value of the derivative at the point where the maximum likelihood function was estimated. I wouldn’t worry about that practically, as all you will care about is whether the iterative function-fitting process converged, and R will warn you in other ways if it doesn’t.</li>
<li>A likelihood ratio test (drop in deviance test) subtracting the residual deviance from the null deviance obtain the Likelihood Ratio <span class="math inline">\(\chi^2\)</span> statistic, subtracting residual df from null df to obtain degrees of freedom, and comparing the resulting test statistic to a <span class="math inline">\(\chi^2\)</span> distribution with the appropriate degrees of freedom to determine a <em>p</em> value.</li>
<li>A series of discrimination indexes, including the Nagelkerke <span class="math inline">\(R^2\)</span>, symbolized R2, and several others we’ll discuss shortly.</li>
<li>A series of rank discrimination indexes, including the C statistic (area under the ROC curve) and Somers’ D (Dxy), and several others.</li>
<li>A table of coefficients, standard errors, Wald Z statistics and <em>p</em> values based on those Wald statistics.</li>
</ul>
<p>The C statistic is estimated to be 0.771, with an associated (Nagelkerke) <span class="math inline">\(R^2\)</span> = 0.167, both indicating at best mediocre performance for this model, as it turns out.</p>
<section id="interpreting-nagelkerke-r2" class="level3" data-number="21.2.1">
<h3 data-number="21.2.1" class="anchored" data-anchor-id="interpreting-nagelkerke-r2"><span class="header-section-number">21.2.1</span> Interpreting Nagelkerke <span class="math inline">\(R^2\)</span></h3>
<p>There are many ways to calculate <span class="math inline">\(R^2\)</span> for logistic regression.</p>
<ul>
<li>At the <a href="https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faq-what-are-pseudo-r-squareds/">URL linked here</a> there is a nice summary of the key issue, which is that there are at least three different ways to think about <span class="math inline">\(R^2\)</span> in linear regression that are equivalent in that context, but when you move to a categorical outcome, which interpretation you use leads you down a different path for extension to the new type of outcome. In linear regression…
<ul>
<li>You might think of <span class="math inline">\(R^2\)</span> as a measure of the proportion of variability explained.</li>
<li>You might think of <span class="math inline">\(R^2\)</span> as measuring the improvement from a null model to a fitted model.</li>
<li>You might think of <span class="math inline">\(R^2\)</span> as the square of the correlation coefficient.</li>
</ul></li>
<li>Paul Allison, for instance, describes several at <a href="http://statisticalhorizons.com/r2logistic">this link</a> in a post entitled “What’s the Best R-Squared for Logistic Regression?”</li>
<li>Jonathan Bartlett looks at McFadden’s pseudo <span class="math inline">\(R^2\)</span> in some detail (including some R code) at <a href="http://thestatsgeek.com/2014/02/08/r-squared-in-logistic-regression/">this link</a>, in a post entitled “R squared in logistic regression”</li>
</ul>
<p>The Nagelkerke approach that is presented as <code>R2</code> in the <code>lrm</code> output is as good as most of the available approaches, and has the positive feature that it does reach 1 if the fitted model shows as much improvement as possible over the null model (which predicts the mean response for all subjects, and has <span class="math inline">\(R^2\)</span> = 0). The greater the improvement, the higher the Nagelkerke <span class="math inline">\(R^2\)</span>.</p>
<p>For model A, our Nagelkerke <span class="math inline">\(R^2\)</span> = 0.167, which is pretty poor. It doesn’t technically mean that 16.7% of any sort of variation has been explained, though.</p>
</section>
<section id="interpreting-the-c-statistic-and-plotting-the-roc-curve" class="level3" data-number="21.2.2">
<h3 data-number="21.2.2" class="anchored" data-anchor-id="interpreting-the-c-statistic-and-plotting-the-roc-curve"><span class="header-section-number">21.2.2</span> Interpreting the C statistic and Plotting the ROC Curve</h3>
<p>The C statistic is a measure of the area under the receiver operating characteristic curve. <a href="http://blog.yhat.com/posts/roc-curves.html">This link</a> has some nice material that provides some insight into the C statistic and ROC curve.</p>
<ul>
<li>Recall that C ranges from 0 to 1. 0 = BAD, 1 = GOOD.
<ul>
<li>values of C less than 0.5 indicate that your prediction model is not even as good as simple random guessing of “yes” or “no” for your response.</li>
<li>C = 0.5 for random guessing</li>
<li>C = 1 indicates a perfect classification scheme - one that correctly guesses “yes” for all “yes” patients, and for none of the “no” patients.</li>
</ul></li>
<li>The closer C is to 1, the happier we’ll be, most of the time.
<ul>
<li>Often we’ll call models with 0.5 &lt; C &lt; 0.8 poor or weak in terms of predictive ability by this measure</li>
<li>0.8 <span class="math inline">\(\leq\)</span> C &lt; 0.9 are moderately strong in terms of predictive power (indicate good discrimination)</li>
<li>C <span class="math inline">\(\geq\)</span> 0.9 usually indicates a very strong model in this regard (indicate excellent discrimination)</li>
</ul></li>
</ul>
<p>We’ve seen the ROC curve for this model before, when we looked at model <code>res_modA</code> fitted using <code>glm</code> in the previous chapter. But, just for completeness, I’ll include it.</p>
<p><strong>Note.</strong> I change the initial <code>predict</code> call from <code>type = "response"</code> for a <code>glm</code> fit to <code>type = "fitted"</code> in a <code>lrm</code> fit. Otherwise, this is the same approach.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## requires ROCR package</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(res_modC, resect, <span class="at">type=</span><span class="st">"fitted"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">prediction</span>(prob, resect<span class="sc">$</span>died)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>perf <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">round</span>(auc<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>roc.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>x.values),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">tpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>y.values),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc.data, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Model C: ROC Curve w/ AUC="</span>, auc)) <span class="sc">+</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="the-c-statistic-and-somers-d" class="level3" data-number="21.2.3">
<h3 data-number="21.2.3" class="anchored" data-anchor-id="the-c-statistic-and-somers-d"><span class="header-section-number">21.2.3</span> The C statistic and Somers’ D</h3>
<ul>
<li>The C statistic is directly related to <strong>Somers’ D statistic</strong>, abbreviated <span class="math inline">\(D_{xy}\)</span>, by the equation C = 0.5 + (D/2).
<ul>
<li>Somers’ D and the ROC area only measure how well predicted values from the model can rank-order the responses. For example, predicted probabilities of 0.01 and 0.99 for a pair of subjects are no better than probabilities of 0.2 and 0.8 using rank measures, if the first subject had a lower response value than the second.</li>
<li>Thus, the C statistic (or <span class="math inline">\(D_{xy}\)</span>) may not be very sensitive ways to choose between models, even though they provide reasonable summaries of the models individually.</li>
<li>This is especially true when the models are strong. The Nagelkerke <span class="math inline">\(R^2\)</span> may be more sensitive.</li>
</ul></li>
<li>But as it turns out, we sometimes have to look at the ROC shapes, as the summary statistic alone isn’t enough.</li>
</ul>
<p>In our case, Somers D (Dxy) = .541, so the C statistic is 0.771.</p>
</section>
<section id="validating-the-logistic-regression-model-summary-statistics" class="level3" data-number="21.2.4">
<h3 data-number="21.2.4" class="anchored" data-anchor-id="validating-the-logistic-regression-model-summary-statistics"><span class="header-section-number">21.2.4</span> Validating the Logistic Regression Model Summary Statistics</h3>
<p>Like other regression-fitting tools in <code>rms</code>, the <code>lrm</code> function has a special <code>validate</code> tool to help perform resampling validation of a model, with or without backwards step-wise variable selection. Here, we’ll validate our model’s summary statistics using 100 bootstrap replications.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">432001</span>) </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">validate</span>(res_modC, <span class="at">B =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          index.orig training   test optimism index.corrected   n
Dxy           0.5415   0.5422 0.5415   0.0007          0.5408 100
R2            0.1666   0.1748 0.1666   0.0083          0.1583 100
Intercept     0.0000   0.0000 0.1631  -0.1631          0.1631 100
Slope         1.0000   1.0000 1.0463  -0.0463          1.0463 100
Emax          0.0000   0.0000 0.0428   0.0428          0.0428 100
D             0.0854   0.0909 0.0854   0.0055          0.0800 100
U            -0.0149  -0.0149 0.0017  -0.0167          0.0017 100
Q             0.1004   0.1058 0.0837   0.0221          0.0783 100
B             0.1025   0.0986 0.1051  -0.0065          0.1090 100
g             1.0369   1.0677 1.0369   0.0308          1.0061 100
gp            0.1101   0.1080 0.1101  -0.0021          0.1122 100</code></pre>
</div>
</div>
<p>Recall that our area under the curve (C statistic) = <code>0.5 + (Dxy/2)</code>, so that we can also use the first row of statistics to validate the C statistic. Accounting for optimism in this manner, our validation-corrected estimates are Dxy = 0.5408, so C = 0.7704, and, from the second row of statistics, we can read off the validated Nagelkerke <span class="math inline">\(R^2\)</span>, which is 0.1583.</p>
</section>
<section id="plotting-the-summary-of-the-lrm-approach" class="level3" data-number="21.2.5">
<h3 data-number="21.2.5" class="anchored" data-anchor-id="plotting-the-summary-of-the-lrm-approach"><span class="header-section-number">21.2.5</span> Plotting the Summary of the <code>lrm</code> approach</h3>
<p>The <code>summary</code> function applied to an <code>lrm</code> fit shows the effect size comparing the 25th percentile to the 75th percentile of resection.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summary</span>(res_modC))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_modC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Effects              Response : died 

 Factor      Low High Diff. Effect S.E.    Lower 0.95 Upper 0.95
 resection   2   4    2     1.4834 0.44591 0.6094      2.3574   
  Odds Ratio 2   4    2     4.4078      NA 1.8393     10.5630   </code></pre>
</div>
</div>
<p>So, a move from a resection of 2 cm to a resection of 4 cm is associated with an estimated effect on the log odds of death of 1.48 (with standard error 0.45), or with an estimated effect on the odds ratio for death of 4.41, with 95% CI (1.84, 10.56).</p>
</section>
<section id="plot-in-sample-predictions-for-model-c" class="level3" data-number="21.2.6">
<h3 data-number="21.2.6" class="anchored" data-anchor-id="plot-in-sample-predictions-for-model-c"><span class="header-section-number">21.2.6</span> Plot In-Sample Predictions for Model C</h3>
<p>Here we plot the effect of <code>resection</code> (and 95% confidence intervals) across the range of observed values of <code>resection</code> on the log odds of death. Note the linear effect of <code>resection</code> size on the log odds scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">Predict</span>(res_modC))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>By applying the <code>plogis</code> function within the <code>Predict</code> command, we can plot the effect of <code>resection</code> on the estimated probability of death. Note the non-linear effect on this probability in this logistic regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">Predict</span>(res_modC, <span class="at">fun =</span> plogis)) <span class="sc">+</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Predicted probability from Model C"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Model C with the resect data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The <code>Predict</code> function itself provides the raw material being captured in this plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">Predict</span>(res_modC, <span class="at">fun =</span> plogis))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            resection       yhat       lower      upper .predictor.
resection.1  1.000000 0.02431476 0.006636502 0.08505223   resection
resection.2  1.020101 0.02467096 0.006789313 0.08559056   resection
resection.3  1.040201 0.02503224 0.006945549 0.08613277   resection
resection.4  1.060302 0.02539867 0.007105283 0.08667889   resection
resection.5  1.080402 0.02577033 0.007268589 0.08722896   resection
resection.6  1.100503 0.02614728 0.007435542 0.08778304   resection

Response variable (y):  

Limits are 0.95 confidence limits</code></pre>
</div>
</div>
</section>
<section id="anova-from-the-lrm-approach" class="level3" data-number="21.2.7">
<h3 data-number="21.2.7" class="anchored" data-anchor-id="anova-from-the-lrm-approach"><span class="header-section-number">21.2.7</span> ANOVA from the <code>lrm</code> approach</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(res_modC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Wald Statistics          Response: died 

 Factor     Chi-Square d.f. P    
 resection  11.07      1    9e-04
 TOTAL      11.07      1    9e-04</code></pre>
</div>
</div>
<p>The ANOVA approach applied to a <code>lrm</code> fit provides a Wald test for the model as a whole. Here, the use of <code>resection</code> is a significant improvement over a null (intercept-only) model. The <em>p</em> value is 9 x 10<sup>-4</sup>.</p>
</section>
<section id="are-any-points-particularly-influential" class="level3" data-number="21.2.8">
<h3 data-number="21.2.8" class="anchored" data-anchor-id="are-any-points-particularly-influential"><span class="header-section-number">21.2.8</span> Are any points particularly influential?</h3>
<p>I’ll use a cutoff for <code>dfbeta</code> here of 0.3, instead of the default 0.2, because I want to focus on truly influential points. Note that we have to use the data frame version of <code>resect</code> as <code>show.influence</code> isn’t tibble-friendly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>inf.C <span class="ot">&lt;-</span> <span class="fu">which.influence</span>(res_modC, <span class="at">cutoff=</span><span class="fl">0.3</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>inf.C</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Intercept
[1]  84 128

$resection
[1] 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show.influence</span>(<span class="at">object =</span> inf.C, <span class="at">dframe =</span> <span class="fu">data.frame</span>(resect))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Count resection
84      2      *2.0
128     1       2.5</code></pre>
</div>
</div>
<p>It appears that observation 84 may have a meaningful effect on both the intercept and the coefficient for <code>resection</code>.</p>
</section>
<section id="a-nomogram-for-model-c" class="level3" data-number="21.2.9">
<h3 data-number="21.2.9" class="anchored" data-anchor-id="a-nomogram-for-model-c"><span class="header-section-number">21.2.9</span> A Nomogram for Model C</h3>
<p>We use the <code>plogis</code> function within a nomogram call to get R to produce fitted probabilities (of our outcome, <code>died</code>) in this case.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">nomogram</span>(res_modC, <span class="at">fun=</span>plogis, </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun.at=</span><span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>, <span class="at">by =</span> <span class="fl">0.1</span>), <span class="fl">0.95</span>), </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">funlabel=</span><span class="st">"Pr(died)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Since there’s no non-linearity in the right hand side of our simple logistic regression model, the nomogram is straightforward. We calculate the points based on the resection by traveling up, and then travel down in a straight vertical line from total points through the linear (log odds) predictor straight to a fitted probability. Note that fitted probabilities above 0.5 are not possible within the range of observed <code>resection</code> values in this case.</p>
</section>
</section>
<section id="model-d-an-augmented-kitchen-sink-model" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="model-d-an-augmented-kitchen-sink-model"><span class="header-section-number">21.3</span> Model D: An Augmented Kitchen Sink Model</h2>
<p>Can we predict survival from the patient’s age, whether the patient had prior tracheal surgery or not, the extent of the resection, and whether intubation was required at the end of surgery?</p>
<section id="spearman-rho2-plot" class="level3" data-number="21.3.1">
<h3 data-number="21.3.1" class="anchored" data-anchor-id="spearman-rho2-plot"><span class="header-section-number">21.3.1</span> Spearman <span class="math inline">\(\rho^2\)</span> Plot</h3>
<p>Let’s start by considering the limited use of non-linear terms for predictors that look important in a Spearman <span class="math inline">\(\rho^2\)</span> plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">spearman2</span>(died <span class="sc">~</span> age <span class="sc">+</span> prior <span class="sc">+</span> resection <span class="sc">+</span> intubated, <span class="at">data=</span>resect))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The most important variable appears to be whether intubation was required, so I’ll include <code>intubated</code>’s interaction with the linear effect of the next most (apparently) important variable, <code>resection</code>, and also a cubic spline for <code>resection</code>, with three knots. Since <code>prior</code> and <code>age</code> look less important, I’ll simply add them as linear terms.</p>
</section>
<section id="fitting-model-d-using-lrm" class="level3" data-number="21.3.2">
<h3 data-number="21.3.2" class="anchored" data-anchor-id="fitting-model-d-using-lrm"><span class="header-section-number">21.3.2</span> Fitting Model D using <code>lrm</code></h3>
<p>Note the use of <code>%ia%</code> here. This insures that only the linear part of the <code>resection</code> term will be used in the interaction with <code>intubated</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">datadist</span>(resect)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">datadist=</span><span class="st">"dd"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>res_modD <span class="ot">&lt;-</span> <span class="fu">lrm</span>(died <span class="sc">~</span> age <span class="sc">+</span> prior <span class="sc">+</span> <span class="fu">rcs</span>(resection, <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                 intubated <span class="sc">+</span> intubated <span class="sc">%ia%</span> resection, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">data=</span>resect, <span class="at">x=</span><span class="cn">TRUE</span>, <span class="at">y=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="assessing-model-d-using-lrms-tools" class="level3" data-number="21.3.3">
<h3 data-number="21.3.3" class="anchored" data-anchor-id="assessing-model-d-using-lrms-tools"><span class="header-section-number">21.3.3</span> Assessing Model D using <code>lrm</code>’s tools</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>res_modD</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = died ~ age + prior + rcs(resection, 3) + intubated + 
    intubated %ia% resection, data = resect, x = TRUE, y = TRUE)

                       Model Likelihood     Discrimination    Rank Discrim.    
                             Ratio Test            Indexes          Indexes    
Obs           134    LR chi2      38.08     R2       0.464    C       0.880    
 0            117    d.f.             6     R2(6,134)0.213    Dxy     0.759    
 1             17    Pr(&gt; chi2) &lt;0.0001    R2(6,44.5)0.513    gamma   0.770    
max |deriv| 9e-08                           Brier    0.067    tau-a   0.169    

                      Coef     S.E.   Wald Z Pr(&gt;|Z|)
Intercept             -11.3636 4.9099 -2.31  0.0206  
age                     0.0000 0.0210  0.00  0.9988  
prior                   0.6269 0.7367  0.85  0.3947  
resection               3.3799 1.9700  1.72  0.0862  
resection'             -4.2104 2.7035 -1.56  0.1194  
intubated               0.4576 2.7848  0.16  0.8695  
intubated * resection   0.6188 0.7306  0.85  0.3970  </code></pre>
</div>
</div>
<ul>
<li>The model likelihood ratio test suggests that at least some of these predictors are helpful.</li>
<li>The Nagelkerke <span class="math inline">\(R^2\)</span> of 0.46, and the C statistic of 0.88 indicate a meaningful improvement in discrimination over our model with <code>resection</code> alone.</li>
<li>The Wald Z tests see some potential need to prune the model, as none of the elements reaches statistical significance without the others. The product term between <code>intubated</code> and <code>resection</code>, in particular, doesn’t appear to have helped much, once we already had the main effects.</li>
</ul>
</section>
<section id="anova-and-wald-tests-for-model-d" class="level3" data-number="21.3.4">
<h3 data-number="21.3.4" class="anchored" data-anchor-id="anova-and-wald-tests-for-model-d"><span class="header-section-number">21.3.4</span> ANOVA and Wald Tests for Model D</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(res_modD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Wald Statistics          Response: died 

 Factor                                               Chi-Square d.f. P     
 age                                                   0.00      1    0.9988
 prior                                                 0.72      1    0.3947
 resection  (Factor+Higher Order Factors)              4.95      3    0.1753
  All Interactions                                     0.72      1    0.3970
  Nonlinear                                            2.43      1    0.1194
 intubated  (Factor+Higher Order Factors)             16.45      2    0.0003
  All Interactions                                     0.72      1    0.3970
 intubated * resection  (Factor+Higher Order Factors)  0.72      1    0.3970
 TOTAL NONLINEAR + INTERACTION                         2.56      2    0.2783
 TOTAL                                                23.90      6    0.0005</code></pre>
</div>
</div>
<p>Neither the interaction term nor the non-linearity from the cubic spline appears to be statistically significant, based on the Wald tests via ANOVA. However it is clear that <code>intubated</code> has a significant impact as a main effect.</p>
</section>
<section id="effect-sizes-in-model-d" class="level3" data-number="21.3.5">
<h3 data-number="21.3.5" class="anchored" data-anchor-id="effect-sizes-in-model-d"><span class="header-section-number">21.3.5</span> Effect Sizes in Model D</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summary</span>(res_modD))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_modD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Effects              Response : died 

 Factor      Low High Diff. Effect      S.E.    Lower 0.95 Upper 0.95
 age         36  61   25    -0.00080933 0.52409 -1.02800     1.0264  
  Odds Ratio 36  61   25     0.99919000      NA  0.35772     2.7910  
 prior        0   1    1     0.62693000 0.73665 -0.81688     2.0707  
  Odds Ratio  0   1    1     1.87190000      NA  0.44181     7.9307  
 resection    2   4    2     2.42930000 1.43510 -0.38342     5.2419  
  Odds Ratio  2   4    2    11.35000000      NA  0.68153   189.0400  
 intubated    0   1    1     2.00470000 1.11220 -0.17513     4.1845  
  Odds Ratio  0   1    1     7.42380000      NA  0.83934    65.6610  

Adjusted to: resection=2.5 intubated=0  </code></pre>
</div>
</div>
<p>The effect sizes are perhaps best described in terms of odds ratios. The odds ratio for death isn’t significantly different from 1 for any variable, but the impact of <code>resection</code> and <code>intubated</code>, though not strong enough to be significant, look more substantial (if poorly estimated) than the effects of <code>age</code> and <code>prior</code>.</p>
</section>
<section id="plot-in-sample-predictions-for-model-d" class="level3" data-number="21.3.6">
<h3 data-number="21.3.6" class="anchored" data-anchor-id="plot-in-sample-predictions-for-model-d"><span class="header-section-number">21.3.6</span> Plot In-Sample Predictions for Model D</h3>
<p>Here are plots of the effects across the range of each predictor (holding the others constant) on the log odds scale. Note the non-linear effect of resection implied by the use of a spline there.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">Predict</span>(res_modD))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can also capture and plot these results on the probability scale, as follows<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">Predict</span>(res_modD, <span class="at">fun =</span> plogis))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="plotting-the-roc-curve-for-model-d" class="level3" data-number="21.3.7">
<h3 data-number="21.3.7" class="anchored" data-anchor-id="plotting-the-roc-curve-for-model-d"><span class="header-section-number">21.3.7</span> Plotting the ROC curve for Model D</h3>
<p>Again, remember to use <code>type = "fitted"</code> with a <code>lrm</code> fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## requires ROCR package</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(res_modD, resect, <span class="at">type=</span><span class="st">"fitted"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">prediction</span>(prob, resect<span class="sc">$</span>died)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>perf <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">round</span>(auc<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>roc.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>x.values),</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">tpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>y.values),</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">model=</span><span class="st">"GLM"</span>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc.data, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"ROC Curve w/ AUC="</span>, auc)) <span class="sc">+</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The AUC fitted with <code>ROCR</code> (0.883) is slightly different than what <code>lrm</code> has told us (0.880), and this also happens if we use the <code>pROC</code> approach, demonstrated below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">## requires pROC package</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>roc.modD <span class="ot">&lt;-</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">roc</span>(resect<span class="sc">$</span>died <span class="sc">~</span> <span class="fu">predict</span>(res_modD, <span class="at">type=</span><span class="st">"fitted"</span>),</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>roc.modD</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
roc.formula(formula = resect$died ~ predict(res_modD, type = "fitted"),     ci = TRUE)

Data: predict(res_modD, type = "fitted") in 117 controls (resect$died 0) &lt; 17 cases (resect$died 1).
Area under the curve: 0.8826
95% CI: 0.7952-0.97 (DeLong)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc.modD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="validation-of-model-d-summaries" class="level3" data-number="21.3.8">
<h3 data-number="21.3.8" class="anchored" data-anchor-id="validation-of-model-d-summaries"><span class="header-section-number">21.3.8</span> Validation of Model D summaries</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">432002</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">validate</span>(res_modD, <span class="at">B =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Divergence or singularity in 5 samples</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          index.orig training    test optimism index.corrected  n
Dxy           0.7652   0.8080  0.7352   0.0727          0.6925 95
R2            0.4643   0.5347  0.4119   0.1228          0.3416 95
Intercept     0.0000   0.0000 -0.3533   0.3533         -0.3533 95
Slope         1.0000   1.0000  0.7658   0.2342          0.7658 95
Emax          0.0000   0.0000  0.1308   0.1308          0.1308 95
D             0.2767   0.3415  0.2407   0.1008          0.1759 95
U            -0.0149  -0.0149  0.0883  -0.1032          0.0883 95
Q             0.2916   0.3564  0.1524   0.2040          0.0876 95
B             0.0673   0.0640  0.0736  -0.0096          0.0769 95
g             2.3819   4.0387  2.4635   1.5751          0.8068 95
gp            0.1720   0.1910  0.1632   0.0278          0.1442 95</code></pre>
</div>
</div>
<p>The C statistic indicates fairly strong discrimination, at C = 0.88, although after validation, this looks much weaker (based on Dxy = 0.6925, we would have C = 0.5 + 0.6925/2 = 0.85) and the Nagelkerke <span class="math inline">\(R^2\)</span> is also reasonably good, at 0.46, although this, too, is overly optimistic, and we bias-correct through our validation study to 0.34.</p>
</section>
</section>
<section id="model-e-fitting-a-reduced-model-in-light-of-model-d" class="level2" data-number="21.4">
<h2 data-number="21.4" class="anchored" data-anchor-id="model-e-fitting-a-reduced-model-in-light-of-model-d"><span class="header-section-number">21.4</span> Model E: Fitting a Reduced Model in light of Model D</h2>
<p>Can you suggest a reduced model (using a subset of the independent variables in model D) that adequately predicts survival?</p>
<p>Based on the anova for model D and the Spearman rho-squared plot, it appears that a two-predictor model using intubation and resection may be sufficient. Neither of the other potential predictors shows a statistically detectable effect in its Wald test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>res_modE <span class="ot">&lt;-</span> <span class="fu">lrm</span>(died <span class="sc">~</span> intubated <span class="sc">+</span> resection, <span class="at">data=</span>resect, </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">x=</span><span class="cn">TRUE</span>, <span class="at">y=</span><span class="cn">TRUE</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>res_modE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = died ~ intubated + resection, data = resect, x = TRUE, 
    y = TRUE)

                       Model Likelihood     Discrimination    Rank Discrim.    
                             Ratio Test            Indexes          Indexes    
Obs           134    LR chi2      33.27     R2       0.413    C       0.867    
 0            117    d.f.             2     R2(2,134)0.208    Dxy     0.734    
 1             17    Pr(&gt; chi2) &lt;0.0001    R2(2,44.5)0.505    gamma   0.757    
max |deriv| 5e-10                           Brier    0.073    tau-a   0.164    

          Coef    S.E.   Wald Z Pr(&gt;|Z|)
Intercept -4.6370 1.0430 -4.45  &lt;0.0001 
intubated  2.8640 0.6479  4.42  &lt;0.0001 
resection  0.5475 0.2689  2.04  0.0418  </code></pre>
</div>
</div>
<p>The model equation is that the log odds of death is -4.637 + 2.864 <code>intubated</code> + 0.548 <code>resection</code>.</p>
<p>This implies that:</p>
<ul>
<li>for intubated patients, the equation is -1.773 + 0.548 <code>resection</code>, while</li>
<li>for non-intubated patients, the equation is -4.637 + 0.548 <code>resection</code>.</li>
</ul>
<p>We can use the <code>ilogit</code> function within the <code>faraway</code> package to help plot this.</p>
<section id="a-plot-comparing-the-two-intubation-groups" class="level3" data-number="21.4.1">
<h3 data-number="21.4.1" class="anchored" data-anchor-id="a-plot-comparing-the-two-intubation-groups"><span class="header-section-number">21.4.1</span> A Plot comparing the two intubation groups</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resect, <span class="fu">aes</span>(<span class="at">x =</span> resection, <span class="at">y =</span> died, </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">col =</span> <span class="fu">factor</span>(intubated))) <span class="sc">+</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">height =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> resection, </span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">y =</span> faraway<span class="sc">::</span><span class="fu">ilogit</span>(<span class="sc">-</span><span class="fl">4.637</span> <span class="sc">+</span> <span class="fl">0.548</span><span class="sc">*</span>resection)),</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> resection,</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">y =</span> faraway<span class="sc">::</span><span class="fu">ilogit</span>(<span class="sc">-</span><span class="fl">1.773</span> <span class="sc">+</span> <span class="fl">0.548</span><span class="sc">*</span>resection)),</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="fl">0.2</span>, <span class="at">label =</span> <span class="st">"Not Intubated"</span>, </span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">col=</span><span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="at">x =</span> <span class="fl">2.5</span>, <span class="at">y =</span> <span class="fl">0.6</span>, <span class="at">label =</span> <span class="st">"Intubated Patients"</span>, </span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">col=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Extent of Resection (in cm.)"</span>,</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Death (1,0) and estimated probability of death"</span>,</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"resect data, Model E"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The effect of <code>intubation</code> appears to be very large, compared to the resection size effect.</p>
</section>
<section id="nomogram-for-model-e" class="level3" data-number="21.4.2">
<h3 data-number="21.4.2" class="anchored" data-anchor-id="nomogram-for-model-e"><span class="header-section-number">21.4.2</span> Nomogram for Model E</h3>
<p>A nomogram of the model would help, too.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">nomogram</span>(res_modE, <span class="at">fun=</span>plogis, </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun.at=</span><span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>, <span class="at">by=</span><span class="fl">0.1</span>), <span class="fl">0.95</span>), </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">funlabel=</span><span class="st">"Pr(died)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Again, we see that the effect of intubation is enormous, compared to the effect of resection. Another way to see this is to plot the effect sizes directly.</p>
</section>
<section id="effect-sizes-from-model-e" class="level3" data-number="21.4.3">
<h3 data-number="21.4.3" class="anchored" data-anchor-id="effect-sizes-from-model-e"><span class="header-section-number">21.4.3</span> Effect Sizes from Model E</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summary</span>(res_modE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_modE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Effects              Response : died 

 Factor      Low High Diff. Effect  S.E.    Lower 0.95 Upper 0.95
 intubated   0   1    1      2.8640 0.64790 1.59410     4.1338   
  Odds Ratio 0   1    1     17.5310      NA 4.92390    62.4160   
 resection   2   4    2      1.0949 0.53783 0.04082     2.1491   
  Odds Ratio 2   4    2      2.9890      NA 1.04170     8.5769   </code></pre>
</div>
</div>
</section>
<section id="plot-in-sample-predictions-for-model-e" class="level3" data-number="21.4.4">
<h3 data-number="21.4.4" class="anchored" data-anchor-id="plot-in-sample-predictions-for-model-e"><span class="header-section-number">21.4.4</span> Plot In-Sample Predictions for Model E</h3>
<p>Here are plots of the effects across the range of each predictor (holding the other constant) on the log odds scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">Predict</span>(res_modE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can also capture and plot these results on the probability scale, as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">Predict</span>(res_modE, <span class="at">fun =</span> plogis))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="anova-for-model-e" class="level3" data-number="21.4.5">
<h3 data-number="21.4.5" class="anchored" data-anchor-id="anova-for-model-e"><span class="header-section-number">21.4.5</span> ANOVA for Model E</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(res_modE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Wald Statistics          Response: died 

 Factor     Chi-Square d.f. P     
 intubated  19.54      1    &lt;.0001
 resection   4.14      1    0.0418
 TOTAL      25.47      2    &lt;.0001</code></pre>
</div>
</div>
</section>
<section id="validation-of-model-e" class="level3" data-number="21.4.6">
<h3 data-number="21.4.6" class="anchored" data-anchor-id="validation-of-model-e"><span class="header-section-number">21.4.6</span> Validation of Model E</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">validate</span>(res_modE, <span class="at">method=</span><span class="st">"boot"</span>, <span class="at">B=</span><span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          index.orig training    test optimism index.corrected  n
Dxy           0.7340   0.6896  0.7326  -0.0430          0.7771 40
R2            0.4128   0.3814  0.4025  -0.0211          0.4339 40
Intercept     0.0000   0.0000  0.1367  -0.1367          0.1367 40
Slope         1.0000   1.0000  1.0472  -0.0472          1.0472 40
Emax          0.0000   0.0000  0.0369   0.0369          0.0369 40
D             0.2408   0.2183  0.2339  -0.0157          0.2565 40
U            -0.0149  -0.0149 -0.0001  -0.0148         -0.0001 40
Q             0.2558   0.2332  0.2340  -0.0009          0.2566 40
B             0.0727   0.0727  0.0759  -0.0032          0.0759 40
g             1.3970   1.3391  1.3577  -0.0186          1.4156 40
gp            0.1597   0.1446  0.1563  -0.0117          0.1714 40</code></pre>
</div>
</div>
<p>Our bootstrap validated assessments of discrimination and goodness of fit look somewhat more reasonable now.</p>
</section>
<section id="do-any-points-seem-particularly-influential" class="level3" data-number="21.4.7">
<h3 data-number="21.4.7" class="anchored" data-anchor-id="do-any-points-seem-particularly-influential"><span class="header-section-number">21.4.7</span> Do any points seem particularly influential?</h3>
<p>As a last step, I’ll look at influence, and residuals, associated with model E.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>inf.E <span class="ot">&lt;-</span> <span class="fu">which.influence</span>(res_modE, <span class="at">cutoff=</span><span class="fl">0.3</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>inf.E</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Intercept
[1] 84 94

$resection
[1] 84 94</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show.influence</span>(inf.E, <span class="at">dframe =</span> <span class="fu">data.frame</span>(resect))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Count resection
84     2        *2
94     2        *6</code></pre>
</div>
</div>
</section>
<section id="fitting-model-e-using-glm-to-get-plots-about-influence" class="level3" data-number="21.4.8">
<h3 data-number="21.4.8" class="anchored" data-anchor-id="fitting-model-e-using-glm-to-get-plots-about-influence"><span class="header-section-number">21.4.8</span> Fitting Model E using <code>glm</code> to get plots about influence</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>res_modEglm <span class="ot">&lt;-</span> <span class="fu">glm</span>(died <span class="sc">~</span> intubated <span class="sc">+</span> resection, </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data=</span>resect, <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_modEglm, <span class="at">which=</span><span class="fu">c</span>(<span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Using this <code>glm</code> residuals approach, we again see that points 84 and 94 have the largest influence on our model E.</p>
</section>
</section>
<section id="concordance-comparing-model-c-d-and-es-predictions" class="level2" data-number="21.5">
<h2 data-number="21.5" class="anchored" data-anchor-id="concordance-comparing-model-c-d-and-es-predictions"><span class="header-section-number">21.5</span> Concordance: Comparing Model C, D and E’s predictions</h2>
<p>To start, we’ll gather the predictions made by each model (C, D and E) on the probability scale, in one place. Sadly, <code>augment</code> from <code>broom</code> doesn’t work well with <code>lrm</code> fits, so we have to do this on our own.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>resect_preds <span class="ot">&lt;-</span> resect <span class="sc">|&gt;</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">C =</span> <span class="fu">predict</span>(res_modC, <span class="at">type =</span> <span class="st">"fitted"</span>),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">D =</span> <span class="fu">predict</span>(res_modD, <span class="at">type =</span> <span class="st">"fitted"</span>),</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">E =</span> <span class="fu">predict</span>(res_modE, <span class="at">type =</span> <span class="st">"fitted"</span>))</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(resect_preds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  subj_id   age prior resection intubated  died      C      D      E
    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1       1    34     1       2.5         0     0 0.0705 0.0632 0.0367
2       2    57     0       5           0     0 0.326  0.0620 0.130 
3       3    60     1       4           1     1 0.187  0.791  0.603 
4       4    62     1       4.2         0     0 0.211  0.158  0.0881
5       5    28     0       6           1     1 0.504  0.711  0.819 
6       6    52     0       3           0     0 0.0990 0.0737 0.0477</code></pre>
</div>
</div>
<p>And now, we’ll use the <code>pivot_longer()</code> function from the <strong>tidyr</strong> package (part of the tidyverse) to arrange the models and predicted probabilities in a more useful manner for plotting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>res_p <span class="ot">&lt;-</span> resect_preds <span class="sc">|&gt;</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">names_to =</span> <span class="st">"model"</span>, <span class="at">values_to =</span> <span class="st">"prediction"</span>) <span class="sc">|&gt;</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subj_id, died, model, prediction)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res_p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  subj_id  died model prediction
    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
1       1     0 C         0.0705
2       1     0 D         0.0632
3       1     0 E         0.0367
4       2     0 C         0.326 
5       2     0 D         0.0620
6       2     0 E         0.130 </code></pre>
</div>
</div>
<p>Here’s the resulting plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(res_p, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(died), <span class="at">y =</span> prediction, </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">group =</span> model, <span class="at">col =</span> model)) <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.25</span>) <span class="sc">+</span> </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>( <span class="sc">~</span> model) <span class="sc">+</span> </span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">color =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Comparing Predictions for our Three Models"</span>,</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"A graphical view of concordance"</span>,</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Actual mortality status (1 = died)"</span>,</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Predicted probability of death"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic3_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We could specify a particular rule, for example: if the predicted probability of death is 0.5 or greater, then predict “Died”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>res_p<span class="sc">$</span>rule<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(res_p<span class="sc">$</span>prediction <span class="sc">&gt;=</span> <span class="fl">0.5</span>, </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Predict Died"</span>, <span class="st">"Predict Alive"</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ftable</span>(<span class="fu">table</span>(res_p<span class="sc">$</span>model, res_p<span class="sc">$</span>rule<span class="fl">.5</span>, res_p<span class="sc">$</span>died))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   0   1
                        
C Predict Alive  114  16
  Predict Died     3   1
D Predict Alive  113   7
  Predict Died     4  10
E Predict Alive  114   8
  Predict Died     3   9</code></pre>
</div>
</div>
<p>And perhaps build the linked table of row probabilities…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">prop.table</span>(</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ftable</span>(<span class="fu">table</span>(res_p<span class="sc">$</span>model, res_p<span class="sc">$</span>rule<span class="fl">.5</span>, res_p<span class="sc">$</span>died))</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>    ,<span class="dv">1</span>),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     0     1
                            
C Predict Alive  87.69 12.31
  Predict Died   75.00 25.00
D Predict Alive  94.17  5.83
  Predict Died   28.57 71.43
E Predict Alive  93.44  6.56
  Predict Died   25.00 75.00</code></pre>
</div>
</div>
<p>For example, in model E, 93.44% of those predicted to be alive actually survived, and 75% of those predicted to die actually died.</p>
<ul>
<li>Model D does a little better in one direction (94.17% of those predicted by Model D to be alive actually survived) but worse in the other (71.43% of those predicted by Model D to die actually died.)</li>
<li>Model C does worse than each of the others in both predicting those who survive and those who die.</li>
</ul>
<p>Note that the approaches discussed here would be useful if we had a new sample to predict on, as well. We could then compare the errors for that new data made by this sort of classification scheme either graphically or in a table.</p>
</section>
<section id="conclusions" class="level2" data-number="21.6">
<h2 data-number="21.6" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">21.6</span> Conclusions</h2>
<p>It appears that <code>intubated</code> status and, to a lesser degree, the extent of the <code>resection</code> both play a meaningful role in predicting death associated with tracheal carina resection surgery. Patients who are intubated are associated with worse outcomes (greater risk of death) and more extensive resections are also associated with worse outcomes.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Although I’ve yet to figure out how to get the y axis relabeled properly without simply dumping the Predict results into a new tibble and starting over with creating the plots.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./logistic2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./effectsize.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>