<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 17&nbsp; Multiple Imputation and Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./tableone.html" rel="next">
<link href="./prostate2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">R Setup</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./incomplete.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">NOTE: Work in progress.</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup-used-here" id="toc-r-setup-used-here" class="nav-link active" data-scroll-target="#r-setup-used-here"><span class="toc-section-number">17.1</span>  R Setup Used Here</a></li>
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="toc-section-number">17.2</span>  Data Load</a></li>
  <li><a href="#developing-a-smart_16-data-set" id="toc-developing-a-smart_16-data-set" class="nav-link" data-scroll-target="#developing-a-smart_16-data-set"><span class="toc-section-number">17.3</span>  Developing a <code>smart_16</code> data set</a>
  <ul class="collapse">
  <li><a href="#any-missing-values" id="toc-any-missing-values" class="nav-link" data-scroll-target="#any-missing-values"><span class="toc-section-number">17.3.1</span>  Any missing values?</a></li>
  </ul></li>
  <li><a href="#obtaining-a-simple-imputation-with-mice" id="toc-obtaining-a-simple-imputation-with-mice" class="nav-link" data-scroll-target="#obtaining-a-simple-imputation-with-mice"><span class="toc-section-number">17.4</span>  Obtaining a Simple Imputation with <code>mice</code></a></li>
  <li><a href="#linear-regression-considering-a-transformation-of-the-outcome" id="toc-linear-regression-considering-a-transformation-of-the-outcome" class="nav-link" data-scroll-target="#linear-regression-considering-a-transformation-of-the-outcome"><span class="toc-section-number">17.5</span>  Linear Regression: Considering a Transformation of the Outcome</a></li>
  <li><a href="#linear-regression-considering-non-linearity-in-the-predictors" id="toc-linear-regression-considering-non-linearity-in-the-predictors" class="nav-link" data-scroll-target="#linear-regression-considering-non-linearity-in-the-predictors"><span class="toc-section-number">17.6</span>  Linear Regression: Considering Non-Linearity in the Predictors</a></li>
  <li><a href="#main-effects-linear-regression-with-lm-on-the-complete-cases" id="toc-main-effects-linear-regression-with-lm-on-the-complete-cases" class="nav-link" data-scroll-target="#main-effects-linear-regression-with-lm-on-the-complete-cases"><span class="toc-section-number">17.7</span>  “Main Effects” Linear Regression with <code>lm</code> on the Complete Cases</a>
  <ul class="collapse">
  <li><a href="#quality-of-fit-statistics" id="toc-quality-of-fit-statistics" class="nav-link" data-scroll-target="#quality-of-fit-statistics"><span class="toc-section-number">17.7.1</span>  Quality of Fit Statistics</a></li>
  <li><a href="#interpreting-effect-sizes" id="toc-interpreting-effect-sizes" class="nav-link" data-scroll-target="#interpreting-effect-sizes"><span class="toc-section-number">17.7.2</span>  Interpreting Effect Sizes</a></li>
  <li><a href="#making-predictions-with-the-model" id="toc-making-predictions-with-the-model" class="nav-link" data-scroll-target="#making-predictions-with-the-model"><span class="toc-section-number">17.7.3</span>  Making Predictions with the Model</a></li>
  </ul></li>
  <li><a href="#augmented-linear-regression-with-lm-on-the-complete-cases" id="toc-augmented-linear-regression-with-lm-on-the-complete-cases" class="nav-link" data-scroll-target="#augmented-linear-regression-with-lm-on-the-complete-cases"><span class="toc-section-number">17.8</span>  “Augmented” Linear Regression with <code>lm</code> on the Complete Cases</a>
  <ul class="collapse">
  <li><a href="#quality-of-fit-statistics-1" id="toc-quality-of-fit-statistics-1" class="nav-link" data-scroll-target="#quality-of-fit-statistics-1"><span class="toc-section-number">17.8.1</span>  Quality of Fit Statistics</a></li>
  <li><a href="#anova-assessing-the-impact-of-the-non-linear-terms" id="toc-anova-assessing-the-impact-of-the-non-linear-terms" class="nav-link" data-scroll-target="#anova-assessing-the-impact-of-the-non-linear-terms"><span class="toc-section-number">17.8.2</span>  ANOVA assessing the impact of the non-linear terms</a></li>
  <li><a href="#interpreting-effect-sizes-1" id="toc-interpreting-effect-sizes-1" class="nav-link" data-scroll-target="#interpreting-effect-sizes-1"><span class="toc-section-number">17.8.3</span>  Interpreting Effect Sizes</a></li>
  <li><a href="#making-predictions-with-the-model-1" id="toc-making-predictions-with-the-model-1" class="nav-link" data-scroll-target="#making-predictions-with-the-model-1"><span class="toc-section-number">17.8.4</span>  Making Predictions with the Model</a></li>
  </ul></li>
  <li><a href="#using-mice-to-perform-multiple-imputation" id="toc-using-mice-to-perform-multiple-imputation" class="nav-link" data-scroll-target="#using-mice-to-perform-multiple-imputation"><span class="toc-section-number">17.9</span>  Using <code>mice</code> to perform Multiple Imputation</a></li>
  <li><a href="#running-the-linear-regression-in-lm-with-multiple-imputation" id="toc-running-the-linear-regression-in-lm-with-multiple-imputation" class="nav-link" data-scroll-target="#running-the-linear-regression-in-lm-with-multiple-imputation"><span class="toc-section-number">17.10</span>  Running the Linear Regression in <code>lm</code> with Multiple Imputation</a></li>
  <li><a href="#fit-the-multiple-imputation-model-with-aregimpute" id="toc-fit-the-multiple-imputation-model-with-aregimpute" class="nav-link" data-scroll-target="#fit-the-multiple-imputation-model-with-aregimpute"><span class="toc-section-number">17.11</span>  Fit the Multiple Imputation Model with <code>aregImpute</code></a></li>
  <li><a href="#fit-linear-regression-using-ols-and-fit.mult.impute" id="toc-fit-linear-regression-using-ols-and-fit.mult.impute" class="nav-link" data-scroll-target="#fit-linear-regression-using-ols-and-fit.mult.impute"><span class="toc-section-number">17.12</span>  Fit Linear Regression using <code>ols</code> and <code>fit.mult.impute</code></a>
  <ul class="collapse">
  <li><a href="#summaries-and-coefficients" id="toc-summaries-and-coefficients" class="nav-link" data-scroll-target="#summaries-and-coefficients"><span class="toc-section-number">17.12.1</span>  Summaries and Coefficients</a></li>
  <li><a href="#effect-sizes" id="toc-effect-sizes" class="nav-link" data-scroll-target="#effect-sizes"><span class="toc-section-number">17.12.2</span>  Effect Sizes</a></li>
  <li><a href="#making-predictions-with-this-model" id="toc-making-predictions-with-this-model" class="nav-link" data-scroll-target="#making-predictions-with-this-model"><span class="toc-section-number">17.12.3</span>  Making Predictions with this Model</a></li>
  <li><a href="#nomogram" id="toc-nomogram" class="nav-link" data-scroll-target="#nomogram"><span class="toc-section-number">17.12.4</span>  Nomogram</a></li>
  <li><a href="#validating-summary-statistics" id="toc-validating-summary-statistics" class="nav-link" data-scroll-target="#validating-summary-statistics"><span class="toc-section-number">17.12.5</span>  Validating Summary Statistics</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="r-setup-used-here" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="r-setup-used-here"><span class="header-section-number">17.1</span> R Setup Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-load" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="data-load"><span class="header-section-number">17.2</span> Data Load</h2>
<p>In this chapter, we’ll return to the <code>smart_ohio</code> file based on data from BRFSS 2017 that we built and cleaned back in <a href="smart.html"><span>Chapter&nbsp;6</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>smart_ohio <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/smart_ohio.Rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="developing-a-smart_16-data-set" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="developing-a-smart_16-data-set"><span class="header-section-number">17.3</span> Developing a <code>smart_16</code> data set</h2>
<p>We’re going to look at a selection of variables from this tibble, among subjects who have been told they have diabetes, and who also provided a response to our <code>physhealth</code> (Number of Days Physical Health Not Good) variable, which asks “Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?” We’ll build two models. In this chapter, we’ll look at a linear model for <code>physhealth</code> and in the next chapter, we’ll look at a logistic regression describing whether or not the subject’s <code>physhealth</code> response was at least 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>smart_16 <span class="ot">&lt;-</span> smart_ohio <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(dm_status <span class="sc">==</span> <span class="st">"Diabetes"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">complete.cases</span>(physhealth)) <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">bad_phys =</span> <span class="fu">ifelse</span>(physhealth <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">comor =</span> hx_mi <span class="sc">+</span> hx_chd <span class="sc">+</span> hx_stroke <span class="sc">+</span> hx_asthma <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>               hx_skinc <span class="sc">+</span> hx_otherc <span class="sc">+</span> hx_copd <span class="sc">+</span> hx_arthr) <span class="sc">|&gt;</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(SEQNO, mmsa, physhealth, bad_phys, age_imp, smoke100,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>           comor, hx_depress, bmi, activity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The variables included in this <code>smart_16</code> tibble are:</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 84%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>SEQNO</code></td>
<td>respondent identification number (all begin with 2016)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>mmsa</code></td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>physhealth</code></td>
<td>Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>bad_phys</code></td>
<td>Is <code>physhealth</code> 1 or more?</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>age_imp</code></td>
<td>Age in years (imputed from age categories)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>smoke100</code></td>
<td>Have you smoked at least 100 cigarettes in your life? (1 = yes, 0 = no)</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>hx_depress</code></td>
<td>Has a doctor, nurse, or other health professional ever told you that you have a depressive disorder, including depression, major depression, dysthymia, or minor depression?</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>bmi</code></td>
<td>Body mass index, in kg/m<sup>2</sup></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>activity</code></td>
<td>Physical activity (Highly Active, Active, Insufficiently Active, Inactive)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>comor</code></td>
<td>Sum of 8 potential groups of comorbidities (see below)</td>
</tr>
</tbody>
</table>
<p>The <code>comor</code> variable is the sum of the following 8 variables, each of which is measured on a 1 = Yes, 0 = No scale, and begin with “Has a doctor, nurse, or other health professional ever told you that you had …”</p>
<ul>
<li><code>hx_mi</code>: a heart attack, also called a myocardial infarction?</li>
<li><code>hx_chd</code>: angina or coronary heart disease?</li>
<li><code>hx_stroke</code>: a stroke?</li>
<li><code>hx_asthma</code>: asthma?</li>
<li><code>hx_skinc</code>: skin cancer?</li>
<li><code>hx_otherc</code>: any other types of cancer?</li>
<li><code>hx_copd</code>: Chronic Obstructive Pulmonary Disease or COPD, emphysema or chronic bronchitis?</li>
<li><code>hx_arthr</code>: some form of arthritis, rheumatoid arthritis, gout, lupus, or fibromyalgia?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>smart_16 <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(comor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> comor   n     percent valid_percent
     0 224 0.211920530   0.221782178
     1 315 0.298013245   0.311881188
     2 228 0.215704825   0.225742574
     3 130 0.122989593   0.128712871
     4  72 0.068117313   0.071287129
     5  29 0.027436140   0.028712871
     6   9 0.008514664   0.008910891
     7   3 0.002838221   0.002970297
    NA  47 0.044465468            NA</code></pre>
</div>
</div>
<section id="any-missing-values" class="level3" data-number="17.3.1">
<h3 data-number="17.3.1" class="anchored" data-anchor-id="any-missing-values"><span class="header-section-number">17.3.1</span> Any missing values?</h3>
<p>We have 1057 observations (rows) in the <code>smart_16</code> data set, of whom 860 have complete data on all variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(smart_16)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1057   10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">n_case_complete</span>(smart_16)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 860</code></pre>
</div>
</div>
<p>Which variables are missing?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_summary</span>(smart_16)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   variable   n_miss pct_miss
   &lt;chr&gt;       &lt;int&gt;    &lt;dbl&gt;
 1 activity       85    8.04 
 2 bmi            84    7.95 
 3 comor          47    4.45 
 4 smoke100       24    2.27 
 5 age_imp        12    1.14 
 6 hx_depress      3    0.284
 7 SEQNO           0    0    
 8 mmsa            0    0    
 9 physhealth      0    0    
10 bad_phys        0    0    </code></pre>
</div>
</div>
<p>Note that our outcomes (<code>physhealth</code> and the derived <code>bad_phys</code>) have no missing values here, by design. We will be performing multiple imputation to account appropriately for missingness in the predictors with missing values.</p>
</section>
</section>
<section id="obtaining-a-simple-imputation-with-mice" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="obtaining-a-simple-imputation-with-mice"><span class="header-section-number">17.4</span> Obtaining a Simple Imputation with <code>mice</code></h2>
<p>The <code>mice</code> package provides several approaches we can use for imputation in building models of all kinds. Here, we’ll use it just to obtain a single set of imputed results that we can apply to “complete” our data for the purposes of thinking about (a) transforming our outcome and (b) considering the addition of non-linear predictor terms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># requires library(mice)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">432</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create small data set including only variables to</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># be used in building the imputation model</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>sm16 <span class="ot">&lt;-</span> smart_16 <span class="sc">|&gt;</span> </span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(physhealth, activity, age_imp, bmi, comor, </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>           hx_depress, smoke100)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>smart_16_mice1 <span class="ot">&lt;-</span> <span class="fu">mice</span>(sm16, <span class="at">m =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   1  activity  age_imp  bmi  comor  hx_depress  smoke100</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>smart_16_imp1 <span class="ot">&lt;-</span> mice<span class="sc">::</span><span class="fu">complete</span>(smart_16_mice1)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">n_case_miss</span>(smart_16_imp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>And now we’ll use this completed <code>smart_16_imp1</code> data set (the product of just a single imputation) to help us address the next two issues.</p>
</section>
<section id="linear-regression-considering-a-transformation-of-the-outcome" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="linear-regression-considering-a-transformation-of-the-outcome"><span class="header-section-number">17.5</span> Linear Regression: Considering a Transformation of the Outcome</h2>
<p>A plausible strategy here would be to try to identify an outcome transformation only after some accounting for missing predictor values, perhaps through a simple imputation approach. However, to keep things simple here, I’ll just use the complete cases in this section.</p>
<p>Recall that our outcome here, <code>physhealth</code> can take the value 0, and is thus not strictly positive.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span> physhealth, <span class="at">data =</span> smart_16_imp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> min Q1 median Q3 max     mean       sd    n missing
   0  0      2 20  30 9.227058 11.92676 1057       0</code></pre>
</div>
</div>
<p>So, if we want to investigate a potential transformation with a Box-Cox plot, we’ll have to add a small value to each <code>physhealth</code> value. We’ll add 1, so that the range of potential values is now from 1-31.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>smart_16_imp1 <span class="ot">&lt;-</span> smart_16_imp1 <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">phplus1 =</span> physhealth <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>test_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(phplus1 <span class="sc">~</span> age_imp <span class="sc">+</span> comor <span class="sc">+</span> smoke100 <span class="sc">+</span> </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                   hx_depress <span class="sc">+</span> bmi <span class="sc">+</span> activity, <span class="at">data =</span> smart_16_imp1)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">boxCox</span>(test_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="multiple_imp_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It looks like the logarithm is a reasonable transformation in this setting. So we’ll create a new outcome, that is the natural logarithm of (<code>physhealth</code> + 1), which we’ll call <code>phys_tr</code> to remind us that a transformation is involved that we’ll eventually need to back out of to make predictions. We’ll build this new variable in both our original <code>smart_16</code> data set and in the simply imputed data set we’re using for just these early stages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>smart_16_imp1 <span class="ot">&lt;-</span> smart_16_imp1 <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">phys_tr =</span> <span class="fu">log</span>(physhealth <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>smart_16 <span class="ot">&lt;-</span> smart_16 <span class="sc">|&gt;</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">phys_tr =</span> <span class="fu">log</span>(physhealth <span class="sc">+</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So we have <code>phys_tr</code> = log(<code>physhealth</code> + 1)</p>
<ul>
<li>where we are referring above to the natural (base <span class="math inline">\(e\)</span> logarithm).</li>
</ul>
<p>We can also specify our back-transformation to the original <code>physhealth</code> values from our new <code>phys_tr</code> as <code>physhealth</code> = exp(<code>phys_tr</code>) - 1.</p>
</section>
<section id="linear-regression-considering-non-linearity-in-the-predictors" class="level2" data-number="17.6">
<h2 data-number="17.6" class="anchored" data-anchor-id="linear-regression-considering-non-linearity-in-the-predictors"><span class="header-section-number">17.6</span> Linear Regression: Considering Non-Linearity in the Predictors</h2>
<p>Consider the following Spearman <span class="math inline">\(\rho^2\)</span> plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">spearman2</span>(phys_tr <span class="sc">~</span> age_imp <span class="sc">+</span> comor <span class="sc">+</span> smoke100 <span class="sc">+</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>           hx_depress <span class="sc">+</span> bmi <span class="sc">+</span> activity, <span class="at">data =</span> smart_16_imp1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="multiple_imp_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>After our single imputation, we have the same <code>N</code> value in all rows of this plot, which is what we want to see. It appears that in considering potential non-linear terms, <code>comor</code> and <code>hx_depress</code> and perhaps <code>activity</code> are worthy of increased attention. I’ll make a couple of arbitrary choices, to add a raw cubic polynomial to represent the <code>comor</code> information, and we’ll add an interaction term between <code>hx_depress</code> and <code>activity</code>.</p>
</section>
<section id="main-effects-linear-regression-with-lm-on-the-complete-cases" class="level2" data-number="17.7">
<h2 data-number="17.7" class="anchored" data-anchor-id="main-effects-linear-regression-with-lm-on-the-complete-cases"><span class="header-section-number">17.7</span> “Main Effects” Linear Regression with <code>lm</code> on the Complete Cases</h2>
<p>Recall that we have 860 complete cases in our <code>smart_16</code> data, out of a total of 1057 observations in total. A model using only the complete cases should thus drop the remaining 197 subjects. Let’s see if a main effects only model for our newly transformed <code>phys_tr</code> outcome does in fact do this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>m_1cc <span class="ot">&lt;-</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lm</span>(phys_tr <span class="sc">~</span> age_imp <span class="sc">+</span> comor <span class="sc">+</span> smoke100 <span class="sc">+</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>           hx_depress <span class="sc">+</span> bmi <span class="sc">+</span> activity, <span class="at">data =</span> smart_16)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_1cc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = phys_tr ~ age_imp + comor + smoke100 + hx_depress + 
    bmi + activity, data = smart_16)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0801 -1.0389 -0.2918  1.1029  2.8478 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    0.581959   0.370847   1.569  0.11696    
age_imp                       -0.007043   0.003813  -1.847  0.06511 .  
comor                          0.301773   0.033105   9.116  &lt; 2e-16 ***
smoke100                       0.099038   0.090280   1.097  0.27295    
hx_depress                     0.471949   0.104232   4.528 6.81e-06 ***
bmi                            0.016375   0.006295   2.601  0.00945 ** 
activityActive                -0.229927   0.154912  -1.484  0.13812    
activityInsufficiently_Active -0.116998   0.139440  -0.839  0.40168    
activityInactive               0.256118   0.115266   2.222  0.02655 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.303 on 851 degrees of freedom
  (197 observations deleted due to missingness)
Multiple R-squared:  0.1806,    Adjusted R-squared:  0.1729 
F-statistic: 23.45 on 8 and 851 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Note that the appropriate number of observations are listed as “deleted due to missingness.”</p>
<section id="quality-of-fit-statistics" class="level3" data-number="17.7.1">
<h3 data-number="17.7.1" class="anchored" data-anchor-id="quality-of-fit-statistics"><span class="header-section-number">17.7.1</span> Quality of Fit Statistics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(m_1cc) <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(r.squared, adj.r.squared, sigma, AIC, BIC) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.173</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">2906.3</td>
<td style="text-align: right;">2953.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="interpreting-effect-sizes" class="level3" data-number="17.7.2">
<h3 data-number="17.7.2" class="anchored" data-anchor-id="interpreting-effect-sizes"><span class="header-section-number">17.7.2</span> Interpreting Effect Sizes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m_1cc, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate, std.error, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 44%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.582</td>
<td style="text-align: right;">0.371</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">1.310</td>
</tr>
<tr class="even">
<td style="text-align: left;">age_imp</td>
<td style="text-align: right;">-0.007</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-0.015</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">comor</td>
<td style="text-align: right;">0.302</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">0.237</td>
<td style="text-align: right;">0.367</td>
</tr>
<tr class="even">
<td style="text-align: left;">smoke100</td>
<td style="text-align: right;">0.099</td>
<td style="text-align: right;">0.090</td>
<td style="text-align: right;">-0.078</td>
<td style="text-align: right;">0.276</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hx_depress</td>
<td style="text-align: right;">0.472</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.267</td>
<td style="text-align: right;">0.677</td>
</tr>
<tr class="even">
<td style="text-align: left;">bmi</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityActive</td>
<td style="text-align: right;">-0.230</td>
<td style="text-align: right;">0.155</td>
<td style="text-align: right;">-0.534</td>
<td style="text-align: right;">0.074</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInsufficiently_Active</td>
<td style="text-align: right;">-0.117</td>
<td style="text-align: right;">0.139</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">0.157</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInactive</td>
<td style="text-align: right;">0.256</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.482</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We’ll interpret three of the predictors here to demonstrate ideas: <code>comor</code>, <code>hx_depress</code> and <code>activity</code>.</p>
<div class="cell">

</div>
<ul>
<li>If we have two subjects with the same values of <code>age_imp</code>, <code>smoke100</code>, <code>hx_depress</code>, <code>bmi</code>, and <code>activity</code>, but Harry has a <code>comor</code> score that is one point higher than Sally’s, then the model predicts that Harry’s transformed outcome (specifically the natural logarithm of (his <code>physhealth</code> days + 1)) will be 0.302 higher than Sally’s, with a 95% confidence interval around that estimate ranging from (<code>round(a$conf.low,3)</code>, <code>round(a$conf.high,3)</code>).</li>
</ul>
<div class="cell">

</div>
<ul>
<li>If we have two subjects with the same values of <code>age_imp</code>, <code>comor</code>, <code>smoke100</code>, <code>bmi</code>, and <code>activity</code>, but Harry has a history of depression (<code>hx_depress</code> = 1) while Sally does not have such a history (so Sally’s <code>hx_depress</code> = 0), then the model predicts that Harry’s transformed outcome (specifically the natural logarithm of (his <code>physhealth</code> days + 1)) will be 0.472 higher than Sally’s, with a 95% confidence interval around that estimate ranging from (<code>round(a$conf.low,3)</code>, <code>round(a$conf.high,3)</code>).</li>
</ul>
<div class="cell">

</div>
<ul>
<li>The <code>activity</code> variable has four categories as indicated in the table below. The model uses the “Highly_Active” category as the reference group.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>smart_16_imp1 <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(activity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              activity   n   percent
         Highly_Active 252 0.2384106
                Active 135 0.1277200
 Insufficiently_Active 193 0.1825922
              Inactive 477 0.4512772</code></pre>
</div>
</div>
<div class="cell">

</div>
<ul>
<li>From the tidied set of coefficients, we can describe the <code>activity</code> effects as follows.
<ul>
<li>If Sally is “Highly Active” and Harry is “Active” but they otherwise have the same values of all predictors, then our prediction is that Harry’s transformed outcome (specifically the natural logarithm of (his <code>physhealth</code> days + 1)) will be 0.23 lower than Sally’s, with a 95% confidence interval around that estimate ranging from (<code>round(a$conf.low,3)</code>, <code>round(a$conf.high,3)</code>).</li>
<li>If instead Harry is “Insufficiently Active” but nothing else changes, then our prediction is that Harry’s transformed outcome will be 0.117 lower than Sally’s, with a 95% confidence interval around that estimate ranging from (<code>round(a2$conf.low,3)</code>, <code>round(a2$conf.high,3)</code>).</li>
<li>If instead Harry is “Inactive” but nothing else changes, then our prediction is that Harry’s transformed outcome will be -0.117 higher than Sally’s, with a 95% confidence interval around that estimate ranging from (<code>round(a2$conf.low,3)</code>, <code>round(a2$conf.high,3)</code>).</li>
</ul></li>
</ul>
</section>
<section id="making-predictions-with-the-model" class="level3" data-number="17.7.3">
<h3 data-number="17.7.3" class="anchored" data-anchor-id="making-predictions-with-the-model"><span class="header-section-number">17.7.3</span> Making Predictions with the Model</h3>
<p>Let’s describe two subjects, and use this model (and the ones that follow) to predict their <code>physhealth</code> values.</p>
<ul>
<li>Sheena is age 50, has 2 comorbidities, has smoked 100 cigarettes in her life, has no history of depression, a BMI of 25, and is Highly Active.</li>
<li>Jacob is age 65, has 4 comorbidities, has never smoked, has a history of depression, a BMI of 32 and is Inactive.</li>
</ul>
<p>We’ll first build predictions for Sheena and Jacob (with 95% prediction intervals) for <code>phys_tr</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">c</span>(<span class="st">"Sheena"</span>, <span class="st">"Jacob"</span>),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_imp =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">65</span>),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">comor =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoke100 =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">hx_depress =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">bmi =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">32</span>),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">activity =</span> <span class="fu">c</span>(<span class="st">"Highly_Active"</span>, <span class="st">"Inactive"</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>preds_m_1cc <span class="ot">&lt;-</span> <span class="fu">predict</span>(m_1cc, <span class="at">newdata =</span> new2, </span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">interval =</span> <span class="st">"prediction"</span>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>preds_m_1cc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 1.341778 -1.22937 3.912925
2 2.583336  0.01399 5.152681</code></pre>
</div>
</div>
<p>The model makes predictions for our transformed outcome, <code>phys_tr</code>. Now, we need to back-transform the predictions and the confidence intervals to build predictions for <code>physhealth</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>preds_m_1cc <span class="ot">&lt;-</span> preds_m_1cc <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tbl_df</span>() <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Sheena"</span>, <span class="st">"Jacob"</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">pred_physhealth =</span> <span class="fu">exp</span>(fit) <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf_low =</span> <span class="fu">exp</span>(lwr) <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf_high =</span> <span class="fu">exp</span>(upr) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(names, pred_physhealth, conf_low, conf_high, </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `tbl_df()` was deprecated in dplyr 1.0.0.
ℹ Please use `tibble::as_tibble()` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>preds_m_1cc <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">names</th>
<th style="text-align: right;">pred_physhealth</th>
<th style="text-align: right;">conf_low</th>
<th style="text-align: right;">conf_high</th>
<th style="text-align: right;">fit</th>
<th style="text-align: right;">lwr</th>
<th style="text-align: right;">upr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sheena</td>
<td style="text-align: right;">2.826</td>
<td style="text-align: right;">-0.708</td>
<td style="text-align: right;">49.045</td>
<td style="text-align: right;">1.342</td>
<td style="text-align: right;">-1.229</td>
<td style="text-align: right;">3.913</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jacob</td>
<td style="text-align: right;">12.241</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">171.894</td>
<td style="text-align: right;">2.583</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">5.153</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="augmented-linear-regression-with-lm-on-the-complete-cases" class="level2" data-number="17.8">
<h2 data-number="17.8" class="anchored" data-anchor-id="augmented-linear-regression-with-lm-on-the-complete-cases"><span class="header-section-number">17.8</span> “Augmented” Linear Regression with <code>lm</code> on the Complete Cases</h2>
<p>Now, we’ll add the non-linear terms we discussed earlier. We’ll add a (raw) cubic polynomial to represent the <code>comor</code> information, and we’ll add an interaction term between <code>hx_depress</code> and <code>activity</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>m_2cc <span class="ot">&lt;-</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lm</span>(phys_tr <span class="sc">~</span> age_imp <span class="sc">+</span> <span class="fu">pol</span>(comor, <span class="dv">3</span>) <span class="sc">+</span> smoke100 <span class="sc">+</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>           bmi <span class="sc">+</span> hx_depress<span class="sc">*</span>activity, <span class="at">data =</span> smart_16)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_2cc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = phys_tr ~ age_imp + pol(comor, 3) + smoke100 + bmi + 
    hx_depress * activity, data = smart_16)

Residuals:
   Min     1Q Median     3Q    Max 
-2.907 -1.063 -0.267  1.143  2.924 

Coefficients:
                                          Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                               0.514823   0.376203   1.368  0.17153
age_imp                                  -0.008100   0.003865  -2.096  0.03640
pol(comor, 3)comor                        0.634274   0.160630   3.949 8.51e-05
pol(comor, 3)comor^2                     -0.130626   0.073525  -1.777  0.07599
pol(comor, 3)comor^3                      0.012508   0.008977   1.393  0.16386
smoke100                                  0.089345   0.090336   0.989  0.32294
bmi                                       0.015203   0.006315   2.408  0.01627
hx_depress                                0.647054   0.229696   2.817  0.00496
activityActive                           -0.202196   0.172300  -1.174  0.24092
activityInsufficiently_Active            -0.005815   0.166221  -0.035  0.97210
activityInactive                          0.290380   0.132198   2.197  0.02832
hx_depress:activityActive                -0.124836   0.395415  -0.316  0.75230
hx_depress:activityInsufficiently_Active -0.376355   0.310160  -1.213  0.22531
hx_depress:activityInactive              -0.172952   0.267427  -0.647  0.51798
                                            
(Intercept)                                 
age_imp                                  *  
pol(comor, 3)comor                       ***
pol(comor, 3)comor^2                     .  
pol(comor, 3)comor^3                        
smoke100                                    
bmi                                      *  
hx_depress                               ** 
activityActive                              
activityInsufficiently_Active               
activityInactive                         *  
hx_depress:activityActive                   
hx_depress:activityInsufficiently_Active    
hx_depress:activityInactive                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.301 on 846 degrees of freedom
  (197 observations deleted due to missingness)
Multiple R-squared:  0.187, Adjusted R-squared:  0.1745 
F-statistic: 14.97 on 13 and 846 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Note again that the appropriate number of observations are listed as “deleted due to missingness.”</p>
<section id="quality-of-fit-statistics-1" class="level3" data-number="17.8.1">
<h3 data-number="17.8.1" class="anchored" data-anchor-id="quality-of-fit-statistics-1"><span class="header-section-number">17.8.1</span> Quality of Fit Statistics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(m_2cc) <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(r.squared, adj.r.squared, sigma, AIC, BIC) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.175</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">2909.5</td>
<td style="text-align: right;">2980.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="anova-assessing-the-impact-of-the-non-linear-terms" class="level3" data-number="17.8.2">
<h3 data-number="17.8.2" class="anchored" data-anchor-id="anova-assessing-the-impact-of-the-non-linear-terms"><span class="header-section-number">17.8.2</span> ANOVA assessing the impact of the non-linear terms</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m_1cc, m_2cc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: phys_tr ~ age_imp + comor + smoke100 + hx_depress + bmi + activity
Model 2: phys_tr ~ age_imp + pol(comor, 3) + smoke100 + bmi + hx_depress * 
    activity
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    851 1444.0                           
2    846 1432.8  5    11.265 1.3303  0.249</code></pre>
</div>
</div>
<p>The difference between the models doesn’t meet the standard for statistical detectabilty at our usual <span class="math inline">\(\alpha\)</span> levels.</p>
</section>
<section id="interpreting-effect-sizes-1" class="level3" data-number="17.8.3">
<h3 data-number="17.8.3" class="anchored" data-anchor-id="interpreting-effect-sizes-1"><span class="header-section-number">17.8.3</span> Interpreting Effect Sizes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m_2cc, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate, std.error, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 51%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.515</td>
<td style="text-align: right;">0.376</td>
<td style="text-align: right;">-0.224</td>
<td style="text-align: right;">1.253</td>
</tr>
<tr class="even">
<td style="text-align: left;">age_imp</td>
<td style="text-align: right;">-0.008</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-0.016</td>
<td style="text-align: right;">-0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pol(comor, 3)comor</td>
<td style="text-align: right;">0.634</td>
<td style="text-align: right;">0.161</td>
<td style="text-align: right;">0.319</td>
<td style="text-align: right;">0.950</td>
</tr>
<tr class="even">
<td style="text-align: left;">pol(comor, 3)comor^2</td>
<td style="text-align: right;">-0.131</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">-0.275</td>
<td style="text-align: right;">0.014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pol(comor, 3)comor^3</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">-0.005</td>
<td style="text-align: right;">0.030</td>
</tr>
<tr class="even">
<td style="text-align: left;">smoke100</td>
<td style="text-align: right;">0.089</td>
<td style="text-align: right;">0.090</td>
<td style="text-align: right;">-0.088</td>
<td style="text-align: right;">0.267</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bmi</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.028</td>
</tr>
<tr class="even">
<td style="text-align: left;">hx_depress</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">0.230</td>
<td style="text-align: right;">0.196</td>
<td style="text-align: right;">1.098</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityActive</td>
<td style="text-align: right;">-0.202</td>
<td style="text-align: right;">0.172</td>
<td style="text-align: right;">-0.540</td>
<td style="text-align: right;">0.136</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInsufficiently_Active</td>
<td style="text-align: right;">-0.006</td>
<td style="text-align: right;">0.166</td>
<td style="text-align: right;">-0.332</td>
<td style="text-align: right;">0.320</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInactive</td>
<td style="text-align: right;">0.290</td>
<td style="text-align: right;">0.132</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: right;">0.550</td>
</tr>
<tr class="even">
<td style="text-align: left;">hx_depress:activityActive</td>
<td style="text-align: right;">-0.125</td>
<td style="text-align: right;">0.395</td>
<td style="text-align: right;">-0.901</td>
<td style="text-align: right;">0.651</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hx_depress:activityInsufficiently_Active</td>
<td style="text-align: right;">-0.376</td>
<td style="text-align: right;">0.310</td>
<td style="text-align: right;">-0.985</td>
<td style="text-align: right;">0.232</td>
</tr>
<tr class="even">
<td style="text-align: left;">hx_depress:activityInactive</td>
<td style="text-align: right;">-0.173</td>
<td style="text-align: right;">0.267</td>
<td style="text-align: right;">-0.698</td>
<td style="text-align: right;">0.352</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Let’s focus first on interpreting the interaction terms between <code>hx_depress</code> and <code>activity</code>.</p>
<p>Assume first that we have a set of subjects with the same values of <code>age_imp</code>, <code>smoke100</code>, <code>bmi</code>, and <code>comor</code>.</p>
<ul>
<li>Arnold has <code>hx_depress</code> = 1 and is Inactive</li>
<li>Betty has <code>hx_depress</code> = 1 and is Insufficiently Active</li>
<li>Carlos has <code>hx_depress</code> = 1 and is Active</li>
<li>Debbie has <code>hx_depress</code> = 1 and is Highly Active</li>
<li>Eamon has <code>hx_depress</code> = 0 and is Inactive</li>
<li>Florence has <code>hx_depress</code> = 0 and is Insufficiently Active</li>
<li>Garry has <code>hx_depress</code> = 0 and is Active</li>
<li>Harry has <code>hx_depress</code> = 0 and is Highly Active</li>
</ul>
<p>So the model, essentially can be used to compare each of the first seven people on that list to Harry (who has the reference levels of both <code>hx_depress</code> and <code>activity</code>.) Let’s compare Arnold to Harry.</p>
<p>For instance, as compared to Harry, Arnold is expected to have a transformed outcome (specifically the natural logarithm of (his <code>physhealth</code> days + 1)) that is:</p>
<div class="cell">

</div>
<ul>
<li>0.647 higher because Arnold’s <code>hx_depress</code> = 1, and</li>
<li>0.29 higher still because Arnold’s <code>activity</code> is “Inactive”, and</li>
<li>0.173 lower because of the combination (see the `hx_depress:activityInactive” row)</li>
</ul>
<p>So, in total, we expect Arnold’s transformed outcome to be 0.647 + 0.29 + (-0.173), or 0.764 higher than Harry’s.</p>
<p>If we want to compare Arnold to, for instance, Betty, we first calculate Betty’s difference from Harry, and then compare the two differences.</p>
<p>As compared to Harry, Betty is expected to have a transformed outcome (specifically the natural logarithm of (her <code>physhealth</code> days + 1)) that is:</p>
<div class="cell">

</div>
<ul>
<li>0.647 higher because Betty’s <code>hx_depress</code> = 1, and</li>
<li>0.006 lower still because Betty’s <code>activity</code> is “Insufficiently Active”, and</li>
<li>0.376 lower because of the combination (see the `hx_depress:activityInsufficiently_Active” row)</li>
</ul>
<p>So, in total, we expect Betty’s transformed outcome to be 0.647 + (-0.006) + (-0.376), or 0.265 higher than Harry’s.</p>
<p>And thus we can compare Betty and Arnold directly.</p>
<ul>
<li>Arnold is predicted to have an outcome that is 0.764 higher than Harry’s.</li>
<li>Betty is predicted to have an outcome that is 0.265 higher than Harry’s.</li>
<li>And so Arnold’s predicted outcome (<code>phys_tr</code>) is 0.499 larger than Betty’s.</li>
</ul>
<p>Now, suppose we want to look at our cubic polynomial in <code>comor</code>.</p>
<ul>
<li>Suppose Harry and Sally have the same values for all other predictors in the model, but Harry has 1 comorbidity where Sally has none. Then the three terms in the model related to <code>comor</code> will be 1 for Harry and 0 for Sally, and the interpretation becomes pretty straightforward.</li>
<li>But suppose instead that nothing has changed except Harry has 2 comorbidities and Sally has just 1. The size of the impact of this Harry - Sally difference is far larger in this situation, because the <code>comor</code> variable enters the model in a non-linear way. This is an area where fitting the model using <code>ols</code> can be helpful because of the ability to generate plots (of effects, nomograms, etc.) that can show this non-linearity in a clear way.</li>
</ul>
<p>Suppose for instance, that Harry and Sally share the following values for the other predictors: each is age 40, has never smoked, has no history of depression, a BMI of 30 and is Highly Active.</p>
<ul>
<li>Now, if Harry has 1 comorbidity and Sally has none, the predicted <code>phys_tr</code> values for Harry and Sally are as indicated below.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>hands1 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">c</span>(<span class="st">"Harry"</span>, <span class="st">"Sally"</span>),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_imp =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">40</span>),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">comor =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoke100 =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">hx_depress =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">bmi =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">30</span>),</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">activity =</span> <span class="fu">c</span>(<span class="st">"Highly_Active"</span>, <span class="st">"Highly_Active"</span>)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m_2cc, <span class="at">newdata =</span> hands1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2 
1.1630840 0.6469282 </code></pre>
</div>
</div>
<p>But if Harry has 2 comorbidities and Sally 1, the predictions are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>hands2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">c</span>(<span class="st">"Harry"</span>, <span class="st">"Sally"</span>),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_imp =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">40</span>),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">comor =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="co"># only thing that changes</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoke100 =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">hx_depress =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">bmi =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">30</span>),</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">activity =</span> <span class="fu">c</span>(<span class="st">"Highly_Active"</span>, <span class="st">"Highly_Active"</span>)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m_2cc, <span class="at">newdata =</span> hands2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
1.493035 1.163084 </code></pre>
</div>
</div>
<p>Note that the difference in predictions between Harry and Sally is much smaller now than it was previously.</p>
</section>
<section id="making-predictions-with-the-model-1" class="level3" data-number="17.8.4">
<h3 data-number="17.8.4" class="anchored" data-anchor-id="making-predictions-with-the-model-1"><span class="header-section-number">17.8.4</span> Making Predictions with the Model</h3>
<p>As before, we’ll use the new model to predict <code>physhealth</code> values for Sheena and Jacob.</p>
<ul>
<li>Sheena is age 50, has 2 comorbidities, has smoked 100 cigarettes in her life, has no history of depression, a BMI of 25, and is Highly Active.</li>
<li>Jacob is age 65, has 4 comorbidities, has never smoked, has a history of depression, a BMI of 32 and is Inactive.</li>
</ul>
<p>We’ll first build predictions for Sheena and Jacob (with 95% prediction intervals) for <code>phys_tr</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">c</span>(<span class="st">"Sheena"</span>, <span class="st">"Jacob"</span>),</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_imp =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">65</span>),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">comor =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoke100 =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">hx_depress =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">bmi =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">32</span>),</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">activity =</span> <span class="fu">c</span>(<span class="st">"Highly_Active"</span>, <span class="st">"Inactive"</span>)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>preds_m_2cc <span class="ot">&lt;-</span> <span class="fu">predict</span>(m_2cc, <span class="at">newdata =</span> new2, </span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">interval =</span> <span class="st">"prediction"</span>)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>preds_m_2cc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit         lwr      upr
1 1.425362 -1.14707613 3.997801
2 2.486907 -0.08635658 5.060171</code></pre>
</div>
</div>
<p>Now, we need to back-transform the predictions and the confidence intervals that describe <code>phys_tr</code> to build predictions for <code>physhealth</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>preds_m_2cc <span class="ot">&lt;-</span> preds_m_2cc <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tbl_df</span>() <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Sheena"</span>, <span class="st">"Jacob"</span>),</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">pred_physhealth =</span> <span class="fu">exp</span>(fit) <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf_low =</span> <span class="fu">exp</span>(lwr) <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf_high =</span> <span class="fu">exp</span>(upr) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(names, pred_physhealth, conf_low, conf_high, </span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">everything</span>())</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>preds_m_2cc <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">names</th>
<th style="text-align: right;">pred_physhealth</th>
<th style="text-align: right;">conf_low</th>
<th style="text-align: right;">conf_high</th>
<th style="text-align: right;">fit</th>
<th style="text-align: right;">lwr</th>
<th style="text-align: right;">upr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sheena</td>
<td style="text-align: right;">3.159</td>
<td style="text-align: right;">-0.682</td>
<td style="text-align: right;">53.478</td>
<td style="text-align: right;">1.425</td>
<td style="text-align: right;">-1.147</td>
<td style="text-align: right;">3.998</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jacob</td>
<td style="text-align: right;">11.024</td>
<td style="text-align: right;">-0.083</td>
<td style="text-align: right;">156.617</td>
<td style="text-align: right;">2.487</td>
<td style="text-align: right;">-0.086</td>
<td style="text-align: right;">5.060</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="using-mice-to-perform-multiple-imputation" class="level2" data-number="17.9">
<h2 data-number="17.9" class="anchored" data-anchor-id="using-mice-to-perform-multiple-imputation"><span class="header-section-number">17.9</span> Using <code>mice</code> to perform Multiple Imputation</h2>
<p>Let’s focus on the main effects model, and look at the impact of performing multiple imputation to account for the missing data. Recall that in our <code>smart_16</code> data, the most “missingness” is shown in the <code>activity</code> variable, which is still missing less than 10% of the time. So we’ll try a set of 10 imputations, using the default settings in the <code>mice</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># requires library(mice)</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">432</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create small data set including only variables to</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="co"># be used in building the imputation model</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>sm16 <span class="ot">&lt;-</span> smart_16 <span class="sc">|&gt;</span> </span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(physhealth, phys_tr, activity, age_imp, bmi, comor, </span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>           hx_depress, smoke100)</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>smart_16_mice10 <span class="ot">&lt;-</span> <span class="fu">mice</span>(sm16, <span class="at">m =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   2  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   3  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   4  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   5  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   6  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   7  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   8  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   9  activity  age_imp  bmi  comor  hx_depress  smoke100
  1   10  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   2  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   3  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   4  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   5  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   6  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   7  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   8  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   9  activity  age_imp  bmi  comor  hx_depress  smoke100
  2   10  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   2  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   3  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   4  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   5  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   6  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   7  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   8  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   9  activity  age_imp  bmi  comor  hx_depress  smoke100
  3   10  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   2  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   3  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   4  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   5  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   6  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   7  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   8  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   9  activity  age_imp  bmi  comor  hx_depress  smoke100
  4   10  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   1  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   2  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   3  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   4  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   5  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   6  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   7  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   8  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   9  activity  age_imp  bmi  comor  hx_depress  smoke100
  5   10  activity  age_imp  bmi  comor  hx_depress  smoke100</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(smart_16_mice10)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Class: mids
Number of multiple imputations:  10 
Imputation methods:
physhealth    phys_tr   activity    age_imp        bmi      comor hx_depress 
        ""         ""  "polyreg"      "pmm"      "pmm"      "pmm"      "pmm" 
  smoke100 
     "pmm" 
PredictorMatrix:
           physhealth phys_tr activity age_imp bmi comor hx_depress smoke100
physhealth          0       1        1       1   1     1          1        1
phys_tr             1       0        1       1   1     1          1        1
activity            1       1        0       1   1     1          1        1
age_imp             1       1        1       0   1     1          1        1
bmi                 1       1        1       1   0     1          1        1
comor               1       1        1       1   1     0          1        1</code></pre>
</div>
</div>
</section>
<section id="running-the-linear-regression-in-lm-with-multiple-imputation" class="level2" data-number="17.10">
<h2 data-number="17.10" class="anchored" data-anchor-id="running-the-linear-regression-in-lm-with-multiple-imputation"><span class="header-section-number">17.10</span> Running the Linear Regression in <code>lm</code> with Multiple Imputation</h2>
<p>Next, we’ll run the linear model (main effects) on each of the 10 imputed data sets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>m10_mods <span class="ot">&lt;-</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">with</span>(smart_16_mice10, <span class="fu">lm</span>(phys_tr <span class="sc">~</span> age_imp <span class="sc">+</span> comor <span class="sc">+</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                                 smoke100 <span class="sc">+</span> hx_depress <span class="sc">+</span> </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                                 bmi <span class="sc">+</span> activity))</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m10_mods)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 90 × 6
   term                          estimate std.error statistic  p.value  nobs
   &lt;chr&gt;                            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
 1 (Intercept)                    0.317     0.326       0.971 3.32e- 1  1057
 2 age_imp                       -0.00489   0.00334    -1.47  1.43e- 1  1057
 3 comor                          0.313     0.0295     10.6   4.72e-25  1057
 4 smoke100                       0.135     0.0799      1.69  9.22e- 2  1057
 5 hx_depress                     0.500     0.0929      5.38  9.14e- 8  1057
 6 bmi                            0.0187    0.00564     3.31  9.64e- 4  1057
 7 activityActive                -0.202     0.138      -1.46  1.44e- 1  1057
 8 activityInsufficiently_Active -0.0695    0.124      -0.561 5.75e- 1  1057
 9 activityInactive               0.262     0.103       2.54  1.11e- 2  1057
10 (Intercept)                    0.363     0.332       1.10  2.74e- 1  1057
# … with 80 more rows</code></pre>
</div>
</div>
<p>Then, we’ll pool results across the 10 imputations</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>m10_pool <span class="ot">&lt;-</span> <span class="fu">pool</span>(m10_mods)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m10_pool, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>statistic, <span class="sc">-</span>df) <span class="sc">|&gt;</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 42%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">2.5 %</th>
<th style="text-align: right;">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.444</td>
<td style="text-align: right;">0.342</td>
<td style="text-align: right;">0.194</td>
<td style="text-align: right;">-0.227</td>
<td style="text-align: right;">1.114</td>
</tr>
<tr class="even">
<td style="text-align: left;">age_imp</td>
<td style="text-align: right;">-0.005</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.128</td>
<td style="text-align: right;">-0.012</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">comor</td>
<td style="text-align: right;">0.309</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.249</td>
<td style="text-align: right;">0.369</td>
</tr>
<tr class="even">
<td style="text-align: left;">smoke100</td>
<td style="text-align: right;">0.114</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">0.171</td>
<td style="text-align: right;">-0.049</td>
<td style="text-align: right;">0.278</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hx_depress</td>
<td style="text-align: right;">0.512</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.327</td>
<td style="text-align: right;">0.696</td>
</tr>
<tr class="even">
<td style="text-align: left;">bmi</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.027</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityActive</td>
<td style="text-align: right;">-0.204</td>
<td style="text-align: right;">0.140</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: right;">-0.479</td>
<td style="text-align: right;">0.071</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInsufficiently_Active</td>
<td style="text-align: right;">-0.044</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">0.735</td>
<td style="text-align: right;">-0.298</td>
<td style="text-align: right;">0.210</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInactive</td>
<td style="text-align: right;">0.260</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">0.469</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>And we can compare these results to the complete case analysis we completed earlier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m_1cc, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate, std.error, p.value, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 39%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.582</td>
<td style="text-align: right;">0.371</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">1.310</td>
</tr>
<tr class="even">
<td style="text-align: left;">age_imp</td>
<td style="text-align: right;">-0.007</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: right;">-0.015</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">comor</td>
<td style="text-align: right;">0.302</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.237</td>
<td style="text-align: right;">0.367</td>
</tr>
<tr class="even">
<td style="text-align: left;">smoke100</td>
<td style="text-align: right;">0.099</td>
<td style="text-align: right;">0.090</td>
<td style="text-align: right;">0.273</td>
<td style="text-align: right;">-0.078</td>
<td style="text-align: right;">0.276</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hx_depress</td>
<td style="text-align: right;">0.472</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.267</td>
<td style="text-align: right;">0.677</td>
</tr>
<tr class="even">
<td style="text-align: left;">bmi</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityActive</td>
<td style="text-align: right;">-0.230</td>
<td style="text-align: right;">0.155</td>
<td style="text-align: right;">0.138</td>
<td style="text-align: right;">-0.534</td>
<td style="text-align: right;">0.074</td>
</tr>
<tr class="even">
<td style="text-align: left;">activityInsufficiently_Active</td>
<td style="text-align: right;">-0.117</td>
<td style="text-align: right;">0.139</td>
<td style="text-align: right;">0.402</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">0.157</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activityInactive</td>
<td style="text-align: right;">0.256</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.482</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Note that there are some sizeable differences here, although nothing enormous.</p>
<p>If we want the pooled <span class="math inline">\(R^2\)</span> or pooled adjusted <span class="math inline">\(R^2\)</span> after imputation, R will provide it (and a 95% confidence interval around the estimate) with …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pool.r.squared</span>(m10_mods)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          est     lo 95     hi 95        fmi
R^2 0.1912561 0.1482819 0.2369623 0.08061427</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pool.r.squared</span>(m10_mods, <span class="at">adjusted =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              est     lo 95     hi 95        fmi
adj R^2 0.1850807 0.1425132 0.2305277 0.08312639</code></pre>
</div>
</div>
<p>We can see the fraction of missing information about each coefficient due to non-response (<code>fmi</code>) and other details with the following code…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>m10_pool</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Class: mipo    m = 10 
                           term  m    estimate         ubar            b
1                   (Intercept) 10  0.44377168 1.078194e-01 8.002900e-03
2                       age_imp 10 -0.00522810 1.123668e-05 4.824290e-07
3                         comor 10  0.30871888 8.801039e-04 5.466082e-05
4                      smoke100 10  0.11415718 6.474388e-03 4.130673e-04
5                    hx_depress 10  0.51155722 8.669413e-03 1.582684e-04
6                           bmi 10  0.01576150 3.182381e-05 3.425191e-06
7                activityActive 10 -0.20412627 1.914250e-02 4.851040e-04
8 activityInsufficiently_Active 10 -0.04383739 1.565925e-02 9.855183e-04
9              activityInactive 10  0.26046070 1.069627e-02 5.023887e-04
             t dfcom       df        riv     lambda        fmi
1 1.166226e-01  1048 599.8172 0.08164758 0.07548446 0.07855177
2 1.176735e-05  1048 814.9042 0.04722675 0.04509697 0.04743197
3 9.402308e-04  1048 677.6361 0.06831796 0.06394909 0.06669961
4 6.928762e-03  1048 666.2487 0.07018023 0.06557795 0.06837041
5 8.843508e-03  1048 982.0512 0.02008154 0.01968621 0.02167660
6 3.559152e-05  1048 432.0874 0.11839279 0.10585976 0.10996992
7 1.967611e-02  1048 939.5064 0.02787591 0.02711992 0.02918437
8 1.674332e-02  1048 672.0473 0.06922874 0.06474643 0.06751736
9 1.124890e-02  1048 785.1905 0.05166545 0.04912727 0.05154007</code></pre>
</div>
</div>
</section>
<section id="fit-the-multiple-imputation-model-with-aregimpute" class="level2" data-number="17.11">
<h2 data-number="17.11" class="anchored" data-anchor-id="fit-the-multiple-imputation-model-with-aregimpute"><span class="header-section-number">17.11</span> Fit the Multiple Imputation Model with <code>aregImpute</code></h2>
<p>Here, we’ll use <code>aregImpute</code> to deal with missing values through multiple imputation, and use the <code>ols</code> function in the <code>rms</code> package to fit the model.</p>
<p>The first step is to fit the multiple imputation model. We’ll use <code>n.impute</code> = 10 imputations, with <code>B</code> = 10 bootstrap samples for the preditive mean matching, and fit both linear models and models with restricted cubic splines with 3 knots (<code>nk = c(0, 3)</code>) allowing the target variable to have a non-linear transformation when <code>nk</code> is 3, via <code>tlinear = FALSE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">43201602</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">datadist</span>(smart_16)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">datadist =</span> <span class="st">"dd"</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>fit16_imp <span class="ot">&lt;-</span> </span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aregImpute</span>(<span class="sc">~</span> phys_tr <span class="sc">+</span> age_imp <span class="sc">+</span> comor <span class="sc">+</span> smoke100 <span class="sc">+</span> </span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>                   hx_depress <span class="sc">+</span> bmi <span class="sc">+</span> activity,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">nk =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>), <span class="at">tlinear =</span> <span class="cn">FALSE</span>, </span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> smart_16, <span class="at">B =</span> <span class="dv">10</span>, <span class="at">n.impute =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Iteration 1 
Iteration 2 
Iteration 3 
Iteration 4 
Iteration 5 
Iteration 6 
Iteration 7 
Iteration 8 
Iteration 9 
Iteration 10 
Iteration 11 
Iteration 12 
Iteration 13 </code></pre>
</div>
</div>
<p>Here are the results of that imputation model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>fit16_imp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Multiple Imputation using Bootstrap and PMM

aregImpute(formula = ~phys_tr + age_imp + comor + smoke100 + 
    hx_depress + bmi + activity, data = smart_16, n.impute = 10, 
    nk = c(0, 3), tlinear = FALSE, B = 10)

n: 1057     p: 7    Imputations: 10     nk: 0 

Number of NAs:
   phys_tr    age_imp      comor   smoke100 hx_depress        bmi   activity 
         0         12         47         24          3         84         85 

           type d.f.
phys_tr       s    1
age_imp       s    1
comor         s    1
smoke100      l    1
hx_depress    l    1
bmi           s    1
activity      c    3

R-squares for Predicting Non-Missing Values for Each Variable
Using Last Imputations of Predictors
   age_imp      comor   smoke100 hx_depress        bmi   activity 
     0.224      0.206      0.059      0.167      0.169      0.057 

Resampling results for determining the complexity of imputation models

Variable being imputed: age_imp 
                                          nk=0   nk=3
Bootstrap bias-corrected R^2             0.186  0.215
10-fold cross-validated  R^2             0.211  0.215
Bootstrap bias-corrected mean   |error|  9.108 10.894
10-fold cross-validated  mean   |error| 65.169 10.919
Bootstrap bias-corrected median |error|  7.290  8.784
10-fold cross-validated  median |error| 66.006  8.613

Variable being imputed: comor 
                                         nk=0  nk=3
Bootstrap bias-corrected R^2            0.183 0.182
10-fold cross-validated  R^2            0.184 0.193
Bootstrap bias-corrected mean   |error| 0.987 1.184
10-fold cross-validated  mean   |error| 1.759 1.171
Bootstrap bias-corrected median |error| 0.828 0.910
10-fold cross-validated  median |error| 1.574 0.892

Variable being imputed: smoke100 
                                          nk=0   nk=3
Bootstrap bias-corrected R^2            0.0224 0.0187
10-fold cross-validated  R^2            0.0358 0.0217
Bootstrap bias-corrected mean   |error| 0.4853 0.4866
10-fold cross-validated  mean   |error| 0.9462 0.9561
Bootstrap bias-corrected median |error| 0.4788 0.4772
10-fold cross-validated  median |error| 0.8479 0.8706

Variable being imputed: hx_depress 
                                         nk=0  nk=3
Bootstrap bias-corrected R^2            0.157 0.138
10-fold cross-validated  R^2            0.147 0.148
Bootstrap bias-corrected mean   |error| 0.355 0.360
10-fold cross-validated  mean   |error| 0.801 0.783
Bootstrap bias-corrected median |error| 0.333 0.337
10-fold cross-validated  median |error| 0.711 0.673

Variable being imputed: bmi 
                                          nk=0  nk=3
Bootstrap bias-corrected R^2             0.125 0.122
10-fold cross-validated  R^2             0.134 0.133
Bootstrap bias-corrected mean   |error|  5.221 6.822
10-fold cross-validated  mean   |error| 32.458 6.884
Bootstrap bias-corrected median |error|  4.178 5.782
10-fold cross-validated  median |error| 31.330 5.932

Variable being imputed: activity 
                                          nk=0   nk=3
Bootstrap bias-corrected R^2            0.0312 0.0275
10-fold cross-validated  R^2            0.0450 0.0402
Bootstrap bias-corrected mean   |error| 1.8774 1.8884
10-fold cross-validated  mean   |error| 1.1121 1.1043
Bootstrap bias-corrected median |error| 2.0000 2.0000
10-fold cross-validated  median |error| 1.0000 1.0000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit16_imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="multiple_imp_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The plot helps us see where the imputations are happening.</p>
</section>
<section id="fit-linear-regression-using-ols-and-fit.mult.impute" class="level2" data-number="17.12">
<h2 data-number="17.12" class="anchored" data-anchor-id="fit-linear-regression-using-ols-and-fit.mult.impute"><span class="header-section-number">17.12</span> Fit Linear Regression using <code>ols</code> and <code>fit.mult.impute</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>m16_imp <span class="ot">&lt;-</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit.mult.impute</span>(phys_tr <span class="sc">~</span> age_imp <span class="sc">+</span> comor <span class="sc">+</span> smoke100 <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                        hx_depress <span class="sc">+</span> bmi <span class="sc">+</span> activity,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">fitter =</span> ols, <span class="at">xtrans =</span> fit16_imp,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> smart_16, <span class="at">x =</span> <span class="cn">TRUE</span>, <span class="at">y =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Variance Inflation Factors Due to Imputation:

                     Intercept                        age_imp 
                          1.03                           1.01 
                         comor                       smoke100 
                          1.03                           1.06 
                    hx_depress                            bmi 
                          1.02                           1.06 
               activity=Active activity=Insufficiently_Active 
                          1.19                           1.14 
             activity=Inactive 
                          1.23 

Rate of Missing Information:

                     Intercept                        age_imp 
                          0.03                           0.01 
                         comor                       smoke100 
                          0.03                           0.06 
                    hx_depress                            bmi 
                          0.02                           0.06 
               activity=Active activity=Insufficiently_Active 
                          0.16                           0.13 
             activity=Inactive 
                          0.19 

d.f. for t-distribution for Tests of Single Coefficients:

                     Intercept                        age_imp 
                       8176.67                       45410.80 
                         comor                       smoke100 
                      13030.27                        2670.64 
                    hx_depress                            bmi 
                      28199.30                        2935.89 
               activity=Active activity=Insufficiently_Active 
                        354.62                         571.56 
             activity=Inactive 
                        258.42 

The following fit components were averaged over the 10 model fits:

  fitted.values stats linear.predictors </code></pre>
</div>
</div>
<section id="summaries-and-coefficients" class="level3" data-number="17.12.1">
<h3 data-number="17.12.1" class="anchored" data-anchor-id="summaries-and-coefficients"><span class="header-section-number">17.12.1</span> Summaries and Coefficients</h3>
<p>Here are the results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>m16_imp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression Model
 
 fit.mult.impute(formula = phys_tr ~ age_imp + comor + smoke100 + 
     hx_depress + bmi + activity, fitter = ols, xtrans = fit16_imp, 
     data = smart_16, x = TRUE, y = TRUE)
 
                 Model Likelihood    Discrimination    
                       Ratio Test           Indexes    
 Obs    1057    LR chi2    219.94    R2       0.188    
 sigma1.2881    d.f.            8    R2 adj   0.182    
 d.f.   1048    Pr(&gt; chi2) 0.0000    g        0.687    
 
 Residuals
 
     Min      1Q  Median      3Q     Max 
 -3.0621 -1.0327 -0.2878  1.1104  2.8018 
 
 
                                Coef    S.E.   t     Pr(&gt;|t|)
 Intercept                       0.4052 0.3352  1.21 0.2271  
 age_imp                        -0.0049 0.0034 -1.46 0.1437  
 comor                           0.3078 0.0302 10.20 &lt;0.0001 
 smoke100                        0.1259 0.0830  1.52 0.1296  
 hx_depress                      0.5120 0.0940  5.45 &lt;0.0001 
 bmi                             0.0164 0.0058  2.83 0.0048  
 activity=Active                -0.1773 0.1513 -1.17 0.2416  
 activity=Insufficiently_Active -0.0396 0.1342 -0.30 0.7680  
 activity=Inactive               0.2401 0.1144  2.10 0.0360  
 </code></pre>
</div>
</div>
</section>
<section id="effect-sizes" class="level3" data-number="17.12.2">
<h3 data-number="17.12.2" class="anchored" data-anchor-id="effect-sizes"><span class="header-section-number">17.12.2</span> Effect Sizes</h3>
<p>We can plot and summarize the effect sizes using the usual <code>ols</code> tools:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m16_imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Effects              Response : phys_tr 

 Factor                                    Low   High  Diff. Effect    S.E.    
 age_imp                                   57.00 73.00 16.00 -0.079163 0.054107
 comor                                      1.00  2.00  1.00  0.307790 0.030171
 smoke100                                   0.00  1.00  1.00  0.125890 0.083000
 hx_depress                                 0.00  1.00  1.00  0.511980 0.094007
 bmi                                       27.29 36.65  9.36  0.153530 0.054322
 activity - Highly_Active:Inactive          4.00  1.00    NA -0.240070 0.114350
 activity - Active:Inactive                 4.00  2.00    NA -0.417320 0.137640
 activity - Insufficiently_Active:Inactive  4.00  3.00    NA -0.279650 0.115000
 Lower 0.95 Upper 0.95
 -0.185330   0.027008 
  0.248590   0.366990 
 -0.036973   0.288760 
  0.327520   0.696450 
  0.046932   0.260120 
 -0.464450  -0.015686 
 -0.687400  -0.147250 
 -0.505310  -0.054002 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summary</span>(m16_imp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="multiple_imp_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="making-predictions-with-this-model" class="level3" data-number="17.12.3">
<h3 data-number="17.12.3" class="anchored" data-anchor-id="making-predictions-with-this-model"><span class="header-section-number">17.12.3</span> Making Predictions with this Model</h3>
<p>Once again, let’s make predictions for our two subjects, and use this model (and the ones that follow) to predict their <code>physhealth</code> values.</p>
<ul>
<li>Sheena is age 50, has 2 comorbidities, has smoked 100 cigarettes in her life, has no history of depression, a BMI of 25, and is Highly Active.</li>
<li>Jacob is age 65, has 4 comorbidities, has never smoked, has a history of depression, a BMI of 32 and is Inactive.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">c</span>(<span class="st">"Sheena"</span>, <span class="st">"Jacob"</span>),</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_imp =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">65</span>),</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">comor =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>),</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoke100 =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">hx_depress =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">bmi =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">32</span>),</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">activity =</span> <span class="fu">c</span>(<span class="st">"Highly_Active"</span>, <span class="st">"Inactive"</span>)</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>preds_m_16imp <span class="ot">&lt;-</span> <span class="fu">predict</span>(m16_imp, </span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>                         <span class="at">newdata =</span> <span class="fu">data.frame</span>(new2))</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>preds_m_16imp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
1.309306 2.591649 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>preds_m_16imp <span class="ot">&lt;-</span> preds_m_16imp <span class="sc">|&gt;</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tbl_df</span>() <span class="sc">|&gt;</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Sheena"</span>, <span class="st">"Jacob"</span>),</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">pred_physhealth =</span> <span class="fu">exp</span>(value) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(names, pred_physhealth)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>preds_m_16imp <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">names</th>
<th style="text-align: right;">pred_physhealth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sheena</td>
<td style="text-align: right;">2.704</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jacob</td>
<td style="text-align: right;">12.352</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="nomogram" class="level3" data-number="17.12.4">
<h3 data-number="17.12.4" class="anchored" data-anchor-id="nomogram"><span class="header-section-number">17.12.4</span> Nomogram</h3>
<p>We can also develop a nomogram, if we like. As a special touch, we’ll add a prediction at the bottom which back-transforms out of the predicted <code>phys_tr</code> back to the <code>physhealth</code> days.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">nomogram</span>(m16_imp, </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun =</span> <span class="fu">list</span>(<span class="cf">function</span>(x) <span class="fu">exp</span>(x) <span class="sc">-</span> <span class="dv">1</span>),</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">funlabel =</span> <span class="st">"Predicted physhealth days"</span>,</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">fun.at =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="dv">3</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="multiple_imp_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see the big role of <code>comor</code> and <code>hx_depress</code> in this model.</p>
</section>
<section id="validating-summary-statistics" class="level3" data-number="17.12.5">
<h3 data-number="17.12.5" class="anchored" data-anchor-id="validating-summary-statistics"><span class="header-section-number">17.12.5</span> Validating Summary Statistics</h3>
<p>We can cross-validate summary measures, like <span class="math inline">\(R^2\)</span>…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">validate</span>(m16_imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          index.orig training   test optimism index.corrected  n
R-square      0.1867   0.1984 0.1793   0.0192          0.1676 40
MSE           1.6472   1.6168 1.6623  -0.0455          1.6927 40
g             0.6876   0.7031 0.6749   0.0282          0.6594 40
Intercept     0.0000   0.0000 0.0677  -0.0677          0.0677 40
Slope         1.0000   1.0000 0.9636   0.0364          0.9636 40</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>

<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./prostate2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./tableone.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>