<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 27&nbsp; Modeling an Ordinal Categorical Outcome</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./multinomial.html" rel="next">
<link href="./count3.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ordinaloutcome.html"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
        <div class="sidebar-tools-main">
    <a href="./Data-Science-for-Biological,-Medical-and-Health-Research.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./incomplete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">This is work in progress</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinaloutcome.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Time To Event / Survival Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup-used-here" id="toc-r-setup-used-here" class="nav-link active" data-scroll-target="#r-setup-used-here"><span class="header-section-number">27.1</span> R Setup Used Here</a>
  <ul class="collapse">
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="header-section-number">27.1.1</span> Data Load</a></li>
  </ul></li>
  <li><a href="#a-subset-of-the-ohio-smart-data" id="toc-a-subset-of-the-ohio-smart-data" class="nav-link" data-scroll-target="#a-subset-of-the-ohio-smart-data"><span class="header-section-number">27.2</span> A subset of the Ohio SMART data</a>
  <ul class="collapse">
  <li><a href="#several-ways-of-storing-multi-categorical-data" id="toc-several-ways-of-storing-multi-categorical-data" class="nav-link" data-scroll-target="#several-ways-of-storing-multi-categorical-data"><span class="header-section-number">27.2.1</span> Several Ways of Storing Multi-Categorical data</a></li>
  </ul></li>
  <li><a href="#building-cross-tabulations" id="toc-building-cross-tabulations" class="nav-link" data-scroll-target="#building-cross-tabulations"><span class="header-section-number">27.3</span> Building Cross-Tabulations</a>
  <ul class="collapse">
  <li><a href="#using-base-table-functions" id="toc-using-base-table-functions" class="nav-link" data-scroll-target="#using-base-table-functions"><span class="header-section-number">27.3.1</span> Using base <code>table</code> functions</a></li>
  <li><a href="#using-xtabs" id="toc-using-xtabs" class="nav-link" data-scroll-target="#using-xtabs"><span class="header-section-number">27.3.2</span> Using <code>xtabs</code></a></li>
  <li><a href="#storing-a-table-in-a-tibble" id="toc-storing-a-table-in-a-tibble" class="nav-link" data-scroll-target="#storing-a-table-in-a-tibble"><span class="header-section-number">27.3.3</span> Storing a table in a tibble</a></li>
  <li><a href="#using-crosstable-from-the-gmodels-package" id="toc-using-crosstable-from-the-gmodels-package" class="nav-link" data-scroll-target="#using-crosstable-from-the-gmodels-package"><span class="header-section-number">27.3.4</span> Using <code>CrossTable</code> from the <code>gmodels</code> package</a></li>
  </ul></li>
  <li><a href="#graphing-categorical-data" id="toc-graphing-categorical-data" class="nav-link" data-scroll-target="#graphing-categorical-data"><span class="header-section-number">27.4</span> Graphing Categorical Data</a>
  <ul class="collapse">
  <li><a href="#a-bar-chart-for-a-single-variable" id="toc-a-bar-chart-for-a-single-variable" class="nav-link" data-scroll-target="#a-bar-chart-for-a-single-variable"><span class="header-section-number">27.4.1</span> A Bar Chart for a Single Variable</a></li>
  <li><a href="#a-counts-chart-for-a-2-way-cross-tabulation" id="toc-a-counts-chart-for-a-2-way-cross-tabulation" class="nav-link" data-scroll-target="#a-counts-chart-for-a-2-way-cross-tabulation"><span class="header-section-number">27.4.2</span> A Counts Chart for a 2-Way Cross-Tabulation</a></li>
  </ul></li>
  <li><a href="#building-a-model-for-genh-using-veg_day" id="toc-building-a-model-for-genh-using-veg_day" class="nav-link" data-scroll-target="#building-a-model-for-genh-using-veg_day"><span class="header-section-number">27.5</span> Building a Model for <code>genh</code> using <code>veg_day</code></a>
  <ul class="collapse">
  <li><a href="#a-little-eda" id="toc-a-little-eda" class="nav-link" data-scroll-target="#a-little-eda"><span class="header-section-number">27.5.1</span> A little EDA</a></li>
  <li><a href="#describing-the-proportional-odds-cumulative-logit-model" id="toc-describing-the-proportional-odds-cumulative-logit-model" class="nav-link" data-scroll-target="#describing-the-proportional-odds-cumulative-logit-model"><span class="header-section-number">27.5.2</span> Describing the Proportional-Odds Cumulative Logit Model</a></li>
  <li><a href="#fitting-a-proportional-odds-logistic-regression-with-polr" id="toc-fitting-a-proportional-odds-logistic-regression-with-polr" class="nav-link" data-scroll-target="#fitting-a-proportional-odds-logistic-regression-with-polr"><span class="header-section-number">27.5.3</span> Fitting a Proportional Odds Logistic Regression with <code>polr</code></a></li>
  </ul></li>
  <li><a href="#interpreting-model-m1" id="toc-interpreting-model-m1" class="nav-link" data-scroll-target="#interpreting-model-m1"><span class="header-section-number">27.6</span> Interpreting Model <code>m1</code></a>
  <ul class="collapse">
  <li><a href="#looking-at-predictions" id="toc-looking-at-predictions" class="nav-link" data-scroll-target="#looking-at-predictions"><span class="header-section-number">27.6.1</span> Looking at Predictions</a></li>
  <li><a href="#making-predictions-for-harry-and-sally-with-predict" id="toc-making-predictions-for-harry-and-sally-with-predict" class="nav-link" data-scroll-target="#making-predictions-for-harry-and-sally-with-predict"><span class="header-section-number">27.6.2</span> Making Predictions for Harry (and Sally) with <code>predict</code></a></li>
  <li><a href="#predicting-the-actual-classification-of-genh" id="toc-predicting-the-actual-classification-of-genh" class="nav-link" data-scroll-target="#predicting-the-actual-classification-of-genh"><span class="header-section-number">27.6.3</span> Predicting the actual classification of <code>genh</code></a></li>
  <li><a href="#a-cross-tabulation-of-predictions" id="toc-a-cross-tabulation-of-predictions" class="nav-link" data-scroll-target="#a-cross-tabulation-of-predictions"><span class="header-section-number">27.6.4</span> A Cross-Tabulation of Predictions?</a></li>
  <li><a href="#the-fitted-model-equations" id="toc-the-fitted-model-equations" class="nav-link" data-scroll-target="#the-fitted-model-equations"><span class="header-section-number">27.6.5</span> The Fitted Model Equations</a></li>
  <li><a href="#interpreting-the-veg_day-coefficient" id="toc-interpreting-the-veg_day-coefficient" class="nav-link" data-scroll-target="#interpreting-the-veg_day-coefficient"><span class="header-section-number">27.6.6</span> Interpreting the <code>veg_day</code> coefficient</a></li>
  <li><a href="#exponentiating-the-slope-coefficient-to-facilitate-interpretation" id="toc-exponentiating-the-slope-coefficient-to-facilitate-interpretation" class="nav-link" data-scroll-target="#exponentiating-the-slope-coefficient-to-facilitate-interpretation"><span class="header-section-number">27.6.7</span> Exponentiating the Slope Coefficient to facilitate Interpretation</a></li>
  <li><a href="#comparison-to-a-null-model" id="toc-comparison-to-a-null-model" class="nav-link" data-scroll-target="#comparison-to-a-null-model"><span class="header-section-number">27.6.8</span> Comparison to a Null Model</a></li>
  </ul></li>
  <li><a href="#the-assumption-of-proportional-odds" id="toc-the-assumption-of-proportional-odds" class="nav-link" data-scroll-target="#the-assumption-of-proportional-odds"><span class="header-section-number">27.7</span> The Assumption of Proportional Odds</a>
  <ul class="collapse">
  <li><a href="#testing-the-proportional-odds-assumption" id="toc-testing-the-proportional-odds-assumption" class="nav-link" data-scroll-target="#testing-the-proportional-odds-assumption"><span class="header-section-number">27.7.1</span> Testing the Proportional Odds Assumption</a></li>
  </ul></li>
  <li><a href="#can-model-m1-be-fit-using-rms-tools" id="toc-can-model-m1-be-fit-using-rms-tools" class="nav-link" data-scroll-target="#can-model-m1-be-fit-using-rms-tools"><span class="header-section-number">27.8</span> Can model <code>m1</code> be fit using <code>rms</code> tools?</a></li>
  <li><a href="#building-a-three-predictor-model" id="toc-building-a-three-predictor-model" class="nav-link" data-scroll-target="#building-a-three-predictor-model"><span class="header-section-number">27.9</span> Building a Three-Predictor Model</a>
  <ul class="collapse">
  <li><a href="#scatterplot-matrix" id="toc-scatterplot-matrix" class="nav-link" data-scroll-target="#scatterplot-matrix"><span class="header-section-number">27.9.1</span> Scatterplot Matrix</a></li>
  <li><a href="#our-three-predictor-model-m2" id="toc-our-three-predictor-model-m2" class="nav-link" data-scroll-target="#our-three-predictor-model-m2"><span class="header-section-number">27.9.2</span> Our Three-Predictor Model, <code>m2</code></a></li>
  <li><a href="#does-the-three-predictor-model-outperform-m1" id="toc-does-the-three-predictor-model-outperform-m1" class="nav-link" data-scroll-target="#does-the-three-predictor-model-outperform-m1"><span class="header-section-number">27.9.3</span> Does the three-predictor model outperform <code>m1</code>?</a></li>
  <li><a href="#wald-tests-for-individual-predictors" id="toc-wald-tests-for-individual-predictors" class="nav-link" data-scroll-target="#wald-tests-for-individual-predictors"><span class="header-section-number">27.9.4</span> Wald tests for individual predictors</a></li>
  <li><a href="#a-cross-tabulation-of-predictions-1" id="toc-a-cross-tabulation-of-predictions-1" class="nav-link" data-scroll-target="#a-cross-tabulation-of-predictions-1"><span class="header-section-number">27.9.5</span> A Cross-Tabulation of Predictions?</a></li>
  <li><a href="#interpreting-the-effect-sizes" id="toc-interpreting-the-effect-sizes" class="nav-link" data-scroll-target="#interpreting-the-effect-sizes"><span class="header-section-number">27.9.6</span> Interpreting the Effect Sizes</a></li>
  <li><a href="#quality-of-the-model-fit" id="toc-quality-of-the-model-fit" class="nav-link" data-scroll-target="#quality-of-the-model-fit"><span class="header-section-number">27.9.7</span> Quality of the Model Fit</a></li>
  <li><a href="#validating-the-summary-statistics-in-m2_lrm" id="toc-validating-the-summary-statistics-in-m2_lrm" class="nav-link" data-scroll-target="#validating-the-summary-statistics-in-m2_lrm"><span class="header-section-number">27.9.8</span> Validating the Summary Statistics in <code>m2_lrm</code></a></li>
  <li><a href="#testing-the-proportional-odds-assumption-1" id="toc-testing-the-proportional-odds-assumption-1" class="nav-link" data-scroll-target="#testing-the-proportional-odds-assumption-1"><span class="header-section-number">27.9.9</span> Testing the Proportional Odds Assumption</a></li>
  <li><a href="#plotting-the-fitted-model" id="toc-plotting-the-fitted-model" class="nav-link" data-scroll-target="#plotting-the-fitted-model"><span class="header-section-number">27.9.10</span> Plotting the Fitted Model</a></li>
  </ul></li>
  <li><a href="#a-larger-model-including-income-group" id="toc-a-larger-model-including-income-group" class="nav-link" data-scroll-target="#a-larger-model-including-income-group"><span class="header-section-number">27.10</span> A Larger Model, including income group</a>
  <ul class="collapse">
  <li><a href="#cross-tabulation-of-predictedobserved-classifications" id="toc-cross-tabulation-of-predictedobserved-classifications" class="nav-link" data-scroll-target="#cross-tabulation-of-predictedobserved-classifications"><span class="header-section-number">27.10.1</span> Cross-Tabulation of Predicted/Observed Classifications</a></li>
  <li><a href="#nomogram-1" id="toc-nomogram-1" class="nav-link" data-scroll-target="#nomogram-1"><span class="header-section-number">27.10.2</span> Nomogram</a></li>
  <li><a href="#using-predict-and-showing-mean-prediction-on-1-5-scale-1" id="toc-using-predict-and-showing-mean-prediction-on-1-5-scale-1" class="nav-link" data-scroll-target="#using-predict-and-showing-mean-prediction-on-1-5-scale-1"><span class="header-section-number">27.10.3</span> Using Predict and showing mean prediction on 1-5 scale</a></li>
  <li><a href="#validating-the-summary-statistics-in-m3_lrm" id="toc-validating-the-summary-statistics-in-m3_lrm" class="nav-link" data-scroll-target="#validating-the-summary-statistics-in-m3_lrm"><span class="header-section-number">27.10.4</span> Validating the Summary Statistics in <code>m3_lrm</code></a></li>
  </ul></li>
  <li><a href="#references-for-this-chapter" id="toc-references-for-this-chapter" class="nav-link" data-scroll-target="#references-for-this-chapter"><span class="header-section-number">27.11</span> References for this Chapter</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="r-setup-used-here" class="level2" data-number="27.1">
<h2 data-number="27.1" class="anchored" data-anchor-id="r-setup-used-here"><span class="header-section-number">27.1</span> R Setup Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-load" class="level3" data-number="27.1.1">
<h3 data-number="27.1.1" class="anchored" data-anchor-id="data-load"><span class="header-section-number">27.1.1</span> Data Load</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>smart_oh <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/smart_ohio.Rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="a-subset-of-the-ohio-smart-data" class="level2" data-number="27.2">
<h2 data-number="27.2" class="anchored" data-anchor-id="a-subset-of-the-ohio-smart-data"><span class="header-section-number">27.2</span> A subset of the Ohio SMART data</h2>
<p>Let’s consider the following data, which uses part of the <code>smart_oh</code> data we built in <a href="smart.html"><span>Chapter&nbsp;6</span></a>. The outcome we’ll study now is <code>genhealth</code>, which has five ordered categories. I’ll include the subset of all observations in <code>smart_oh</code> with complete data on these 7 variables.</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 83%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>SEQNO</code></td>
<td>Subject identification code</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>genhealth</code></td>
<td>Five categories (1 = Excellent, 2 = Very Good, 3 = Good, 4 = Fair, 5 = Poor) on general health</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>physhealth</code></td>
<td>Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>veg_day</code></td>
<td>mean number of vegetable servings consumed per day</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>costprob</code></td>
<td>1 indicates Yes to “Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?”, and 0 otherwise.</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>incomegroup</code></td>
<td>8 income groups from &lt; 10,000 to 75,000 or more</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>bmi</code></td>
<td>body-mass index</td>
</tr>
</tbody>
</table>
<p>To make my life easier later, I’m going to drop any subjects with missing data on these variables. I’m also going to drop the subjects who have no missing data, but have a listed <code>bmi</code> above 60.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sm1 <span class="ot">&lt;-</span> smart_oh <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(SEQNO, genhealth, physhealth, costprob, veg_day,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>           incomegroup, bmi) <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(bmi <span class="sc">&lt;=</span> <span class="dv">60</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In total, we have 5394 subjects in the <code>sm1</code> sample.</p>
<section id="several-ways-of-storing-multi-categorical-data" class="level3" data-number="27.2.1">
<h3 data-number="27.2.1" class="anchored" data-anchor-id="several-ways-of-storing-multi-categorical-data"><span class="header-section-number">27.2.1</span> Several Ways of Storing Multi-Categorical data</h3>
<p>We will store the information in our outcome, <code>genhealth</code> in both a numeric form (<code>gen_n</code>) and an ordered factor (<code>gen_h</code>) with some abbreviated labels) because we’ll have some use for each approach in this material.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sm1 <span class="ot">&lt;-</span> sm1 <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">genh =</span> <span class="fu">fct_recode</span>(genhealth,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"1-E"</span> <span class="ot">=</span> <span class="st">"1_Excellent"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"2_VG"</span> <span class="ot">=</span> <span class="st">"2_VeryGood"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"3_G"</span> <span class="ot">=</span> <span class="st">"3_Good"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"4_F"</span> <span class="ot">=</span> <span class="st">"4_Fair"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"5_P"</span> <span class="ot">=</span> <span class="st">"5_Poor"</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">genh =</span> <span class="fu">factor</span>(genh, <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">gen_n =</span> <span class="fu">as.numeric</span>(genhealth))</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>sm1 <span class="sc">|&gt;</span> <span class="fu">count</span>(genh, gen_n, genhealth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  genh  gen_n genhealth       n
  &lt;ord&gt; &lt;dbl&gt; &lt;fct&gt;       &lt;int&gt;
1 1-E       1 1_Excellent   822
2 2_VG      2 2_VeryGood   1805
3 3_G       3 3_Good       1667
4 4_F       4 4_Fair        801
5 5_P       5 5_Poor        299</code></pre>
</div>
</div>
</section>
</section>
<section id="building-cross-tabulations" class="level2" data-number="27.3">
<h2 data-number="27.3" class="anchored" data-anchor-id="building-cross-tabulations"><span class="header-section-number">27.3</span> Building Cross-Tabulations</h2>
<p>Is income group associated with general health?</p>
<section id="using-base-table-functions" class="level3" data-number="27.3.1">
<h3 data-number="27.3.1" class="anchored" data-anchor-id="using-base-table-functions"><span class="header-section-number">27.3.1</span> Using base <code>table</code> functions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">table</span>(sm1<span class="sc">$</span>incomegroup, sm1<span class="sc">$</span>genh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
          1-E 2_VG  3_G  4_F  5_P  Sum
  0-9K     14   45   60   74   40  233
  10-14K   12   41   66   93   46  258
  15-19K   40   76  119   96   61  392
  20-24K   51  129  175  100   50  505
  25-34K   51  172  215  123   36  597
  35-49K   97  270  303  118   24  812
  50-74K  128  337  265   94   16  840
  75K+    429  735  464  103   26 1757
  Sum     822 1805 1667  801  299 5394</code></pre>
</div>
</div>
<p>More people answer Very Good and Good than choose the other categories. It might be easier to look at percentages here.</p>
<section id="adding-percentages-within-each-row" class="level4" data-number="27.3.1.1">
<h4 data-number="27.3.1.1" class="anchored" data-anchor-id="adding-percentages-within-each-row"><span class="header-section-number">27.3.1.1</span> Adding percentages within each row</h4>
<p>Here are the percentages giving each <code>genhealth</code> response within each income group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">prop.table</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">table</span>(sm1<span class="sc">$</span>incomegroup, sm1<span class="sc">$</span>genh)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        ,<span class="dv">1</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        ,<span class="dv">1</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
           1-E  2_VG   3_G   4_F   5_P   Sum
  0-9K     6.0  19.3  25.8  31.8  17.2 100.1
  10-14K   4.7  15.9  25.6  36.0  17.8 100.0
  15-19K  10.2  19.4  30.4  24.5  15.6 100.1
  20-24K  10.1  25.5  34.7  19.8   9.9 100.0
  25-34K   8.5  28.8  36.0  20.6   6.0  99.9
  35-49K  11.9  33.3  37.3  14.5   3.0 100.0
  50-74K  15.2  40.1  31.5  11.2   1.9  99.9
  75K+    24.4  41.8  26.4   5.9   1.5 100.0
  Sum     91.0 224.1 247.7 164.3  72.9 800.0</code></pre>
</div>
</div>
<p>So, for example, 11.3% of the <code>genhealth</code> responses in subjects with incomes between 25 and 34 thousand dollars were Excellent.</p>
</section>
<section id="adding-percentages-within-each-column" class="level4" data-number="27.3.1.2">
<h4 data-number="27.3.1.2" class="anchored" data-anchor-id="adding-percentages-within-each-column"><span class="header-section-number">27.3.1.2</span> Adding percentages within each column</h4>
<p>Here are the percentages in each <code>incomegroup</code> within each <code>genhealth</code> response.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">prop.table</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">table</span>(sm1<span class="sc">$</span>incomegroup, sm1<span class="sc">$</span>genh)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>        ,<span class="dv">2</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        ,<span class="dv">1</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
           1-E  2_VG   3_G   4_F   5_P   Sum
  0-9K     1.7   2.5   3.6   9.2  13.4  30.4
  10-14K   1.5   2.3   4.0  11.6  15.4  34.8
  15-19K   4.9   4.2   7.1  12.0  20.4  48.6
  20-24K   6.2   7.1  10.5  12.5  16.7  53.0
  25-34K   6.2   9.5  12.9  15.4  12.0  56.0
  35-49K  11.8  15.0  18.2  14.7   8.0  67.7
  50-74K  15.6  18.7  15.9  11.7   5.4  67.3
  75K+    52.2  40.7  27.8  12.9   8.7 142.3
  Sum    100.1 100.0 100.0 100.0 100.0 500.1</code></pre>
</div>
</div>
<p>From this table, we see that 7.4% of the Excellent <code>genhealth</code> responses were given by people with incomes between 25 and 34 thousand dollars.</p>
</section>
</section>
<section id="using-xtabs" class="level3" data-number="27.3.2">
<h3 data-number="27.3.2" class="anchored" data-anchor-id="using-xtabs"><span class="header-section-number">27.3.2</span> Using <code>xtabs</code></h3>
<p>The <code>xtabs</code> function provides a formula method for obtaining cross-tabulations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> incomegroup <span class="sc">+</span> genh, <span class="at">data =</span> sm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           genh
incomegroup 1-E 2_VG 3_G 4_F 5_P
     0-9K    14   45  60  74  40
     10-14K  12   41  66  93  46
     15-19K  40   76 119  96  61
     20-24K  51  129 175 100  50
     25-34K  51  172 215 123  36
     35-49K  97  270 303 118  24
     50-74K 128  337 265  94  16
     75K+   429  735 464 103  26</code></pre>
</div>
</div>
</section>
<section id="storing-a-table-in-a-tibble" class="level3" data-number="27.3.3">
<h3 data-number="27.3.3" class="anchored" data-anchor-id="storing-a-table-in-a-tibble"><span class="header-section-number">27.3.3</span> Storing a table in a tibble</h3>
<p>We can store the elements of a cross-tabulation in a tibble, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(sm1.tableA <span class="ot">&lt;-</span> sm1 <span class="sc">|&gt;</span> <span class="fu">count</span>(incomegroup, genh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 3
   incomegroup genh      n
   &lt;fct&gt;       &lt;ord&gt; &lt;int&gt;
 1 0-9K        1-E      14
 2 0-9K        2_VG     45
 3 0-9K        3_G      60
 4 0-9K        4_F      74
 5 0-9K        5_P      40
 6 10-14K      1-E      12
 7 10-14K      2_VG     41
 8 10-14K      3_G      66
 9 10-14K      4_F      93
10 10-14K      5_P      46
# ℹ 30 more rows</code></pre>
</div>
</div>
<p>From such a tibble, we can visualize the data in many ways, but we can also return to <code>xtabs</code> and include the frequencies (<code>n</code>) in that setup.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(n <span class="sc">~</span> incomegroup <span class="sc">+</span> genh, <span class="at">data =</span> sm1.tableA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           genh
incomegroup 1-E 2_VG 3_G 4_F 5_P
     0-9K    14   45  60  74  40
     10-14K  12   41  66  93  46
     15-19K  40   76 119  96  61
     20-24K  51  129 175 100  50
     25-34K  51  172 215 123  36
     35-49K  97  270 303 118  24
     50-74K 128  337 265  94  16
     75K+   429  735 464 103  26</code></pre>
</div>
</div>
<p>And, we can get the <span class="math inline">\(\chi^2\)</span> test of independence, with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">xtabs</span>(n <span class="sc">~</span> incomegroup <span class="sc">+</span> genh, <span class="at">data =</span> sm1.tableA))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: xtabs(formula = n ~ incomegroup + genh, data = sm1.tableA)
Number of cases in table: 5394 
Number of factors: 2 
Test for independence of all factors:
    Chisq = 894.2, df = 28, p-value = 3.216e-170</code></pre>
</div>
</div>
</section>
<section id="using-crosstable-from-the-gmodels-package" class="level3" data-number="27.3.4">
<h3 data-number="27.3.4" class="anchored" data-anchor-id="using-crosstable-from-the-gmodels-package"><span class="header-section-number">27.3.4</span> Using <code>CrossTable</code> from the <code>gmodels</code> package</h3>
<p>The <code>CrossTable</code> function from the <code>gmodels</code> package produces a cross-tabulation with various counts and proportions like people often generate with SPSS and SAS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(sm1<span class="sc">$</span>incomegroup, sm1<span class="sc">$</span>genh, <span class="at">chisq =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  5394 

 
                | sm1$genh 
sm1$incomegroup |       1-E |      2_VG |       3_G |       4_F |       5_P | Row Total | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
           0-9K |        14 |        45 |        60 |        74 |        40 |       233 | 
                |    13.027 |    13.941 |     2.002 |    44.865 |    56.796 |           | 
                |     0.060 |     0.193 |     0.258 |     0.318 |     0.172 |     0.043 | 
                |     0.017 |     0.025 |     0.036 |     0.092 |     0.134 |           | 
                |     0.003 |     0.008 |     0.011 |     0.014 |     0.007 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
         10-14K |        12 |        41 |        66 |        93 |        46 |       258 | 
                |    18.980 |    23.806 |     2.366 |    78.061 |    70.259 |           | 
                |     0.047 |     0.159 |     0.256 |     0.360 |     0.178 |     0.048 | 
                |     0.015 |     0.023 |     0.040 |     0.116 |     0.154 |           | 
                |     0.002 |     0.008 |     0.012 |     0.017 |     0.009 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
         15-19K |        40 |        76 |       119 |        96 |        61 |       392 | 
                |     6.521 |    23.208 |     0.038 |    24.531 |    70.973 |           | 
                |     0.102 |     0.194 |     0.304 |     0.245 |     0.156 |     0.073 | 
                |     0.049 |     0.042 |     0.071 |     0.120 |     0.204 |           | 
                |     0.007 |     0.014 |     0.022 |     0.018 |     0.011 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
         20-24K |        51 |       129 |       175 |       100 |        50 |       505 | 
                |     8.756 |     9.463 |     2.296 |     8.340 |    17.301 |           | 
                |     0.101 |     0.255 |     0.347 |     0.198 |     0.099 |     0.094 | 
                |     0.062 |     0.071 |     0.105 |     0.125 |     0.167 |           | 
                |     0.009 |     0.024 |     0.032 |     0.019 |     0.009 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
         25-34K |        51 |       172 |       215 |       123 |        36 |       597 | 
                |    17.567 |     3.862 |     5.042 |    13.307 |     0.255 |           | 
                |     0.085 |     0.288 |     0.360 |     0.206 |     0.060 |     0.111 | 
                |     0.062 |     0.095 |     0.129 |     0.154 |     0.120 |           | 
                |     0.009 |     0.032 |     0.040 |     0.023 |     0.007 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
         35-49K |        97 |       270 |       303 |       118 |        24 |       812 | 
                |     5.779 |     0.011 |    10.798 |     0.055 |     9.808 |           | 
                |     0.119 |     0.333 |     0.373 |     0.145 |     0.030 |     0.151 | 
                |     0.118 |     0.150 |     0.182 |     0.147 |     0.080 |           | 
                |     0.018 |     0.050 |     0.056 |     0.022 |     0.004 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
         50-74K |       128 |       337 |       265 |        94 |        16 |       840 | 
                |     0.000 |    11.121 |     0.112 |     7.575 |    20.061 |           | 
                |     0.152 |     0.401 |     0.315 |     0.112 |     0.019 |     0.156 | 
                |     0.156 |     0.187 |     0.159 |     0.117 |     0.054 |           | 
                |     0.024 |     0.062 |     0.049 |     0.017 |     0.003 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
           75K+ |       429 |       735 |       464 |       103 |        26 |      1757 | 
                |    97.108 |    36.780 |    11.492 |    95.573 |    52.335 |           | 
                |     0.244 |     0.418 |     0.264 |     0.059 |     0.015 |     0.326 | 
                |     0.522 |     0.407 |     0.278 |     0.129 |     0.087 |           | 
                |     0.080 |     0.136 |     0.086 |     0.019 |     0.005 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|
   Column Total |       822 |      1805 |      1667 |       801 |       299 |      5394 | 
                |     0.152 |     0.335 |     0.309 |     0.148 |     0.055 |           | 
----------------|-----------|-----------|-----------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  894.1685     d.f. =  28     p =  3.216132e-170 


 </code></pre>
</div>
</div>
</section>
</section>
<section id="graphing-categorical-data" class="level2" data-number="27.4">
<h2 data-number="27.4" class="anchored" data-anchor-id="graphing-categorical-data"><span class="header-section-number">27.4</span> Graphing Categorical Data</h2>
<section id="a-bar-chart-for-a-single-variable" class="level3" data-number="27.4.1">
<h3 data-number="27.4.1" class="anchored" data-anchor-id="a-bar-chart-for-a-single-variable"><span class="header-section-number">27.4.1</span> A Bar Chart for a Single Variable</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm1, <span class="fu">aes</span>(<span class="at">x =</span> genhealth, <span class="at">fill =</span> genhealth)) <span class="sc">+</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>or, you might prefer to plot percentages, perhaps like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm1, <span class="fu">aes</span>(<span class="at">x =</span> genhealth, <span class="at">fill =</span> genhealth)) <span class="sc">+</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> (..count..)<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> (..count..)<span class="sc">/</span><span class="fu">sum</span>(..count..), </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>((..count..) <span class="sc">/</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                                        <span class="fu">sum</span>(..count..))),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">stat =</span> <span class="st">"count"</span>, <span class="at">vjust =</span> <span class="dv">1</span>, </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Dark2"</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Percentage"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Use bar charts, rather than pie charts.</p>
</section>
<section id="a-counts-chart-for-a-2-way-cross-tabulation" class="level3" data-number="27.4.2">
<h3 data-number="27.4.2" class="anchored" data-anchor-id="a-counts-chart-for-a-2-way-cross-tabulation"><span class="header-section-number">27.4.2</span> A Counts Chart for a 2-Way Cross-Tabulation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm1, <span class="fu">aes</span>(<span class="at">x =</span> genhealth, <span class="at">y =</span> incomegroup)) <span class="sc">+</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_count</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="building-a-model-for-genh-using-veg_day" class="level2" data-number="27.5">
<h2 data-number="27.5" class="anchored" data-anchor-id="building-a-model-for-genh-using-veg_day"><span class="header-section-number">27.5</span> Building a Model for <code>genh</code> using <code>veg_day</code></h2>
<p>To begin, we’ll predict each subject’s <code>genh</code> response using just one predictor, <code>veg_day</code>.</p>
<section id="a-little-eda" class="level3" data-number="27.5.1">
<h3 data-number="27.5.1" class="anchored" data-anchor-id="a-little-eda"><span class="header-section-number">27.5.1</span> A little EDA</h3>
<p>Let’s start with a quick table of summary statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>sm1 <span class="sc">|&gt;</span> <span class="fu">group_by</span>(genh) <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="fu">n</span>(), <span class="fu">mean</span>(veg_day), <span class="fu">sd</span>(veg_day), <span class="fu">median</span>(veg_day))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  genh  `n()` `mean(veg_day)` `sd(veg_day)` `median(veg_day)`
  &lt;ord&gt; &lt;int&gt;           &lt;dbl&gt;         &lt;dbl&gt;             &lt;dbl&gt;
1 1-E     822            2.16          1.46              1.87
2 2_VG   1805            1.99          1.13              1.78
3 3_G    1667            1.86          1.11              1.71
4 4_F     801            1.74          1.18              1.57
5 5_P     299            1.71          1.06              1.57</code></pre>
</div>
</div>
<p>To actually see what’s going on, we might build a comparison boxplot, or violin plot. The plot below shows both, together, with the violin plot helping to indicate the skewed nature of the <code>veg_day</code> data and the boxplot indicating quartiles and outlying values within each <code>genhealth</code> category.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sm1, <span class="fu">aes</span>(<span class="at">x =</span> genhealth, <span class="at">y =</span> veg_day)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_violin</span>(<span class="fu">aes</span>(<span class="at">fill =</span> genhealth), <span class="at">trim =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>, <span class="at">color =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="describing-the-proportional-odds-cumulative-logit-model" class="level3" data-number="27.5.2">
<h3 data-number="27.5.2" class="anchored" data-anchor-id="describing-the-proportional-odds-cumulative-logit-model"><span class="header-section-number">27.5.2</span> Describing the Proportional-Odds Cumulative Logit Model</h3>
<p>To fit the ordinal logistic regression model (specifically, a proportional-odds cumulative-logit model) in this situation, we’ll use the <code>polr</code> function in the <code>MASS</code> package.</p>
<ul>
<li>Our outcome is <code>genh</code>, which has five ordered levels, with <code>1-E</code> best and <code>5-P</code> worst.</li>
<li>Our model will include one quantitative predictor, <code>veg_day</code>.</li>
</ul>
<p>The model will have four logit equations:</p>
<ul>
<li>one estimating the log odds that <code>genh</code> will be less than or equal to 1 (i.e.&nbsp;<code>genhealth</code> = 1_Excellent,)</li>
<li>one estimating the log odds that <code>genh</code> <span class="math inline">\(\leq\)</span> 2 (i.e.&nbsp;<code>genhealth</code> = 1_Excellent or 2_VeryGood,)</li>
<li>another estimating the log odds that <code>genh</code> <span class="math inline">\(\leq\)</span> 3 (i.e.&nbsp;<code>genhealth</code> = 1_Excellent, 2_VeryGood or 3_Good,) and, finally,</li>
<li>one estimating the log odds that <code>genh</code> <span class="math inline">\(\leq\)</span> 4 (i.e.&nbsp;<code>genhealth</code> = 1_Excellent, 2_VeryGood, 3_Good or 4_Fair)</li>
</ul>
<p>That’s all we need to estimate the five categories, since Pr(<code>genh</code> <span class="math inline">\(\leq\)</span> 5) = 1, because (5_Poor) is the maximum category for <code>genhealth</code>.</p>
<p>We’ll have a total of five free parameters when we add in the slope for <code>veg_day</code>, and I’ll label these parameters as <span class="math inline">\(\zeta_1, \zeta_2, \zeta_3, \zeta_4\)</span> and <span class="math inline">\(\beta_1\)</span>. The <span class="math inline">\(\zeta\)</span>s are read as “zeta” values, and the people who built the <code>polr</code> function use that term.</p>
<p>The four logistic equations that will be fit differ only by their intercepts. They are:</p>
<p><span class="math display">\[
logit[Pr(genh \leq 1)] = log \frac{Pr(genh \leq 1}{Pr(genh &gt; 1)} = \zeta_1 - \beta_1 veg_day
\]</span></p>
<p>which describes the log odds of a <code>genh</code> value of 1 (Excellent) as compared to a <code>genh</code> value greater than 1 (which includes Very Good, Good, Fair and Poor).</p>
<p>The second logit model is:</p>
<p><span class="math display">\[
logit[Pr(genh \leq 2)] = log \frac{Pr(genh \leq 2}{Pr(genh &gt; 2)} = \zeta_2 - \beta_1 veg_day
\]</span></p>
<p>which describes the log odds of a <code>genh</code> value of 1 (Excellent) or 2 (Very Good) as compared to a <code>genh</code> value greater than 2 (which includes Good, Fair and Poor).</p>
<p>Next we have:</p>
<p><span class="math display">\[
logit[Pr(genh \leq 3)] = log \frac{Pr(genh \leq 3}{Pr(genh &gt; 3)} = \zeta_3 - \beta_1 veg_day
\]</span></p>
<p>which describes the log odds of a <code>genh</code> value of 1 (Excellent) or 2 (Very Good) or 3 (Good) as compared to a <code>genh</code> value greater than 3 (which includes Fair and Poor).</p>
<p>Finally, we have</p>
<p><span class="math display">\[
logit[Pr(genh \leq 4)] = log \frac{Pr(genh \leq 4}{Pr(genh &gt; 4)} = \zeta_4 - \beta_1 veg_day
\]</span></p>
<p>which describes the log odds of a <code>genh</code> value of 4 or less, which includes Excellent, Very Good, Good and Fair as compared to a <code>genh</code> value greater than 4 (which is Poor).</p>
<p>Again, the intercept term is the only piece that varies across the four equations.</p>
<p>In this case, a positive coefficient <span class="math inline">\(\beta_1\)</span> for <code>veg_day</code> means that increasing the value of <code>veg_day</code> would increase the <code>genh</code> category (describing a worse level of general health, since higher values of <code>genh</code> are associated with worse health.)</p>
</section>
<section id="fitting-a-proportional-odds-logistic-regression-with-polr" class="level3" data-number="27.5.3">
<h3 data-number="27.5.3" class="anchored" data-anchor-id="fitting-a-proportional-odds-logistic-regression-with-polr"><span class="header-section-number">27.5.3</span> Fitting a Proportional Odds Logistic Regression with <code>polr</code></h3>
<p>Our model <code>m1</code> will use proportional odds logistic regression (sometimes called an <em>ordered logit</em> model) to predict <code>genh</code> on the basis of <code>veg_day</code>. The <code>polr</code> function from the MASS package will be our main tool. Note that we include <code>Hess = TRUE</code> to retain what is called the <em>Hessian</em> matrix, which lets R calculate standard errors more effectively in <code>summary</code> and other follow-up descriptions of the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">polr</span>(genh <span class="sc">~</span> veg_day, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> sm1, <span class="at">Hess =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = genh ~ veg_day, data = sm1, Hess = TRUE)

Coefficients:
          Value Std. Error t value
veg_day -0.1847    0.02178   -8.48

Intercepts:
         Value    Std. Error t value 
1-E|2_VG  -2.0866   0.0584   -35.7590
2_VG|3_G  -0.4065   0.0498    -8.1621
3_G|4_F    1.0202   0.0521    19.5771
4_F|5_P    2.5002   0.0710    35.2163

Residual Deviance: 15669.85 
AIC: 15679.85 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     2.5 %     97.5 % 
-0.2277073 -0.1423088 </code></pre>
</div>
</div>
</section>
</section>
<section id="interpreting-model-m1" class="level2" data-number="27.6">
<h2 data-number="27.6" class="anchored" data-anchor-id="interpreting-model-m1"><span class="header-section-number">27.6</span> Interpreting Model <code>m1</code></h2>
<section id="looking-at-predictions" class="level3" data-number="27.6.1">
<h3 data-number="27.6.1" class="anchored" data-anchor-id="looking-at-predictions"><span class="header-section-number">27.6.1</span> Looking at Predictions</h3>
<p>Consider two individuals:</p>
<ul>
<li>Harry, who eats an average of 2.0 servings of vegetables per day, so Harry’s <code>veg_day</code> = 2, and</li>
<li>Sally, who eats an average of 1.0 serving of vegetables per day, so Sally’s <code>veg_day</code> = 1.</li>
</ul>
<p>We’re going to start by using our model <code>m1</code> to predict the <code>genh</code> for Harry and Sally, so we can see the effect (on the predicted <code>genh</code> probabilities) of a change of one unit in <code>veg_day</code>.</p>
<p>For example, what are the log odds that Harry, with <code>veg_day</code> = 2, will describe his <code>genh</code> as Excellent (<code>genh</code> <span class="math inline">\(\leq\)</span> 1)?</p>
<p><span class="math display">\[
logit[Pr(genh \leq 1)] = \zeta_1 - \beta_1 veg\_day
\]</span></p>
<p><span class="math display">\[
logit[Pr(genh \leq 1)] = -2.0866 - (-0.1847) veg\_day
\]</span></p>
<p><span class="math display">\[
logit[Pr(genh \leq 1)] = -2.0866 - (-0.1847) (2) = -1.7172
\]</span></p>
<p>That’s not much help. So we’ll convert it to a probability by taking the inverse logit. The formula is</p>
<p><span class="math display">\[
Pr(genh \leq 1) = \frac{exp(\zeta_1 + \beta_1 veg_day)}{1 + exp(\zeta_1 + \beta_1 veg_day)} =
\frac{exp(-1.7172)}{1 + exp(-1.7172)} = \frac{0.180}{1.180} = 0.15
\]</span></p>
<p>So the model estimates a 15% probability that Harry will describe his <code>genh</code> as Excellent.</p>
<p>OK. Now, what are the log odds that Harry, who eats 2 servings per day, will describe his <code>genh</code> as either Excellent or Very Good (<code>genh</code> <span class="math inline">\(\leq\)</span> 2)?</p>
<p><span class="math display">\[
logit[Pr(genh \leq 2)] = \zeta_2 - \beta_1 veg\_day
\]</span></p>
<p><span class="math display">\[
logit[Pr(genh \leq 2)] = -0.4065 - (-0.1847) veg\_day \\
\]</span></p>
<p><span class="math display">\[
logit[Pr(genh \leq 2)] = -0.4065 - (-0.1847) (2) = -0.0371
\]</span></p>
<p>Again, we’ll convert this to a probability by taking the inverse logit.</p>
<p><span class="math display">\[
Pr(genh \leq 2) = \frac{exp(\zeta_2 + \beta_1 veg_day)}{1 + exp(\zeta_2 + \beta_1 veg_day)} =
\frac{exp(-0.0371)}{1 + exp(-0.0371)} = \frac{0.964}{1.964} = 0.49
\]</span></p>
<p>So, the model estimates a probability of .49 that Harry will describe his <code>genh</code> as either Excellent or Very Good, so by subtraction, that’s a probability of .34 that Harry describes his <code>genh</code> as Very Good.</p>
<p>Happily, that’s the last time we’ll calculate this by hand.</p>
</section>
<section id="making-predictions-for-harry-and-sally-with-predict" class="level3" data-number="27.6.2">
<h3 data-number="27.6.2" class="anchored" data-anchor-id="making-predictions-for-harry-and-sally-with-predict"><span class="header-section-number">27.6.2</span> Making Predictions for Harry (and Sally) with <code>predict</code></h3>
<p>Suppose Harry eats 2 servings of vegetables per day on average, and Sally eats 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>temp.dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">name =</span> <span class="fu">c</span>(<span class="st">"Harry"</span>, <span class="st">"Sally"</span>), </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">veg_day =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m1, temp.dat, <span class="at">type =</span> <span class="st">"p"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1-E      2_VG       3_G       4_F        5_P
1 0.1522351 0.3385119 0.3097906 0.1457864 0.05367596
2 0.1298931 0.3148971 0.3246105 0.1667285 0.06387071</code></pre>
</div>
</div>
<p>The predicted probabilities of falling into each category of <code>genh</code> are:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Subject</th>
<th style="text-align: right;"><code>veg_day</code></th>
<th style="text-align: right;">Pr(1_E)</th>
<th style="text-align: right;">Pr(2_VG)</th>
<th style="text-align: right;">Pr(3_G)</th>
<th style="text-align: right;">Pr(4_F)</th>
<th style="text-align: right;">Pr(5_P)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Harry</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15.2</td>
<td style="text-align: right;">33.9</td>
<td style="text-align: right;">31.0</td>
<td style="text-align: right;">14.6</td>
<td style="text-align: right;">5.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">Sally</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.0</td>
<td style="text-align: right;">31.4</td>
<td style="text-align: right;">32.5</td>
<td style="text-align: right;">16.7</td>
<td style="text-align: right;">6.4</td>
</tr>
</tbody>
</table>
<ul>
<li>Harry has a higher predicted probability of lower (healthier) values of <code>genh</code>. Specifically, Harry has a higher predicted probability than Sally of falling into the Excellent and Very Good categories, and a lower probability than Sally of falling into the Good, Fair and Poor categories.</li>
<li>This means that Harry, with a higher <code>veg_day</code> is predicted to have, on average, a lower (that is to say, healthier) value of <code>genh</code>.</li>
<li>As we’ll see, this association will be indicated by a negative coefficient of <code>veg_day</code> in the proportional odds logistic regression model.</li>
</ul>
</section>
<section id="predicting-the-actual-classification-of-genh" class="level3" data-number="27.6.3">
<h3 data-number="27.6.3" class="anchored" data-anchor-id="predicting-the-actual-classification-of-genh"><span class="header-section-number">27.6.3</span> Predicting the actual classification of <code>genh</code></h3>
<p>The default prediction approach actually returns the predicted <code>genh</code> classification for Harry and Sally, which is just the classification with the largest predicted probability. Here, for Harry that is Very Good, and for Sally, that’s Good.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m1, temp.dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2_VG 3_G 
Levels: 1-E 2_VG 3_G 4_F 5_P</code></pre>
</div>
</div>
</section>
<section id="a-cross-tabulation-of-predictions" class="level3" data-number="27.6.4">
<h3 data-number="27.6.4" class="anchored" data-anchor-id="a-cross-tabulation-of-predictions"><span class="header-section-number">27.6.4</span> A Cross-Tabulation of Predictions?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">table</span>(<span class="fu">predict</span>(m1), sm1<span class="sc">$</span>genh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      
        1-E 2_VG  3_G  4_F  5_P  Sum
  1-E     6    3    3    3    0   15
  2_VG  647 1398 1198  525  192 3960
  3_G   169  404  466  273  107 1419
  4_F     0    0    0    0    0    0
  5_P     0    0    0    0    0    0
  Sum   822 1805 1667  801  299 5394</code></pre>
</div>
</div>
<p>The <code>m1</code> model classifies all subjects in the <code>sm1</code> sample as either Excellent, Very Good or Good, and most subjects as Very Good or Good.</p>
</section>
<section id="the-fitted-model-equations" class="level3" data-number="27.6.5">
<h3 data-number="27.6.5" class="anchored" data-anchor-id="the-fitted-model-equations"><span class="header-section-number">27.6.5</span> The Fitted Model Equations</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = genh ~ veg_day, data = sm1, Hess = TRUE)

Coefficients:
          Value Std. Error t value
veg_day -0.1847    0.02178   -8.48

Intercepts:
         Value    Std. Error t value 
1-E|2_VG  -2.0866   0.0584   -35.7590
2_VG|3_G  -0.4065   0.0498    -8.1621
3_G|4_F    1.0202   0.0521    19.5771
4_F|5_P    2.5002   0.0710    35.2163

Residual Deviance: 15669.85 
AIC: 15679.85 </code></pre>
</div>
</div>
<p>The first part of the output provides coefficient estimates for the <code>veg_day</code> predictor, and these are followed by the estimates for the various model intercepts. Plugging in the estimates, we have:</p>
<p><span class="math display">\[
logit[Pr(genh \leq 1)] = -2.0866 - (-0.1847) veg_day
\]</span></p>
<p><span class="math display">\[
logit[Pr(genh \leq 2)]  = -0.4065 - (-0.1847) veg_day
\]</span></p>
<p><span class="math display">\[
logit[Pr(genh \leq 3)]  =  1.0202 - (-0.1847) veg_day
\]</span></p>
<p><span class="math display">\[
logit[Pr(genh \leq 4)] =  2.5002 - (-0.1847) veg_day
\]</span></p>
<p>Note that we can obtain these pieces separately as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>m1<span class="sc">$</span>zeta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1-E|2_VG   2_VG|3_G    3_G|4_F    4_F|5_P 
-2.0866313 -0.4064704  1.0202035  2.5001655 </code></pre>
</div>
</div>
<p>shows the boundary intercepts, and</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>m1<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   veg_day 
-0.1847272 </code></pre>
</div>
</div>
<p>shows the regression coefficient for <code>veg_day</code>.</p>
</section>
<section id="interpreting-the-veg_day-coefficient" class="level3" data-number="27.6.6">
<h3 data-number="27.6.6" class="anchored" data-anchor-id="interpreting-the-veg_day-coefficient"><span class="header-section-number">27.6.6</span> Interpreting the <code>veg_day</code> coefficient</h3>
<p>The first part of the output provides coefficient estimates for the <code>veg_day</code> predictor.</p>
<ul>
<li>The estimated slope for <code>veg_day</code> is -0.1847
<ul>
<li>Remember Harry and Sally, who have the same values of <code>bmi</code> and <code>costprob</code>, but Harry eats one more serving than Sally does. We noted that Harry is predicted by the model to have a smaller (i.e.&nbsp;healthier) <code>genh</code> response than Sally.</li>
<li>So a negative coefficient here means that higher values of <code>veg_day</code> are associated with more of the probability distribution falling in lower values of <code>genh</code>.</li>
<li>We usually don’t interpret this slope (on the log odds scale) directly, but rather exponentiate it.</li>
</ul></li>
</ul>
</section>
<section id="exponentiating-the-slope-coefficient-to-facilitate-interpretation" class="level3" data-number="27.6.7">
<h3 data-number="27.6.7" class="anchored" data-anchor-id="exponentiating-the-slope-coefficient-to-facilitate-interpretation"><span class="header-section-number">27.6.7</span> Exponentiating the Slope Coefficient to facilitate Interpretation</h3>
<p>We can compute the odds ratio associated with <code>veg_day</code> and its confidence interval as follows…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  veg_day 
0.8313311 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    2.5 %    97.5 % 
0.7963573 0.8673534 </code></pre>
</div>
</div>
<ul>
<li>So, if Harry eats one more serving of vegetables than Sally, our model predicts that Harry will have 83.1% of the odds of Sally of having a larger <code>genh</code> score. That means that Harry is likelier to have a smaller <code>genh</code> score.
<ul>
<li>Since <code>genh</code> gets larger as a person’s general health gets worse (moves from Excellent towards Poor), this means that since Harry is predicted to have smaller odds of a larger <code>genh</code> score, he is also predicted to have smaller odds of worse general health.</li>
<li>Our 95% confidence interval around that estimated odds ratio of 0.831 is (0.796, 0.867). Since that interval is entirely below 1, the odds of having the larger (worse) <code>genh</code> for Harry are detectably lower than the odds for Sally.</li>
<li>So, an increase in <code>veg_day</code> is associated with smaller (better) <code>genh</code> scores.</li>
</ul></li>
</ul>
</section>
<section id="comparison-to-a-null-model" class="level3" data-number="27.6.8">
<h3 data-number="27.6.8" class="anchored" data-anchor-id="comparison-to-a-null-model"><span class="header-section-number">27.6.8</span> Comparison to a Null Model</h3>
<p>We can fit a model with intercepts only to test the significance of <code>veg_day</code> in our model <code>m1</code>, using the <code>anova</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">polr</span>(genh <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> sm1)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1, m0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of ordinal regression models

Response: genh
    Model Resid. df Resid. Dev   Test    Df LR stat. Pr(Chi)
1       1      5390   15744.89                              
2 veg_day      5389   15669.85 1 vs 2     1 75.04297       0</code></pre>
</div>
</div>
<p>We could also compare model <code>m1</code> to the null model <code>m0</code> with AIC or BIC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(m1, m0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df      AIC
m1  5 15679.85
m0  4 15752.89</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(m1,m0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df      BIC
m1  5 15712.81
m0  4 15779.26</code></pre>
</div>
</div>
</section>
</section>
<section id="the-assumption-of-proportional-odds" class="level2" data-number="27.7">
<h2 data-number="27.7" class="anchored" data-anchor-id="the-assumption-of-proportional-odds"><span class="header-section-number">27.7</span> The Assumption of Proportional Odds</h2>
<p>Let us calculate the odds for all levels of <code>genh</code> if a person eats two servings of vegetables. First, we’ll get the probabilities, in another way, to demonstrate how to do so…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>(prob<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">exp</span>(m1<span class="sc">$</span>zeta <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>m1<span class="sc">$</span>coefficients)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(m1<span class="sc">$</span>zeta <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>m1<span class="sc">$</span>coefficients)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 1-E|2_VG  2_VG|3_G   3_G|4_F   4_F|5_P 
0.1522351 0.4907471 0.8005376 0.9463240 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>(prob<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">exp</span>(m1<span class="sc">$</span>zeta <span class="sc">-</span> <span class="dv">1</span><span class="sc">*</span>m1<span class="sc">$</span>coefficients)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(m1<span class="sc">$</span>zeta <span class="sc">-</span> <span class="dv">1</span><span class="sc">*</span>m1<span class="sc">$</span>coefficients)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 1-E|2_VG  2_VG|3_G   3_G|4_F   4_F|5_P 
0.1298931 0.4447902 0.7694008 0.9361293 </code></pre>
</div>
</div>
<p>Now, we’ll calculate the odds, first for a subject eating two servings:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">odds.2 =</span> prob<span class="fl">.2</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>prob<span class="fl">.2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1-E|2_VG   2_VG|3_G    3_G|4_F    4_F|5_P 
 0.1795724  0.9636607  4.0134766 17.6303153 </code></pre>
</div>
</div>
<p>And here are the odds, for a subject eating one serving per day:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">odds.1 =</span> prob<span class="fl">.1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>prob<span class="fl">.1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1-E|2_VG   2_VG|3_G    3_G|4_F    4_F|5_P 
 0.1492841  0.8011211  3.3365277 14.6566285 </code></pre>
</div>
</div>
<p>Now, let’s take the ratio of the odds for someone who eats two servings over the odds for someone who eats one.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>odds<span class="fl">.2</span><span class="sc">/</span>odds<span class="fl">.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1-E|2_VG 2_VG|3_G  3_G|4_F  4_F|5_P 
 1.20289  1.20289  1.20289  1.20289 </code></pre>
</div>
</div>
<p>They are all the same. The odds ratios are equal, which means they are proportional. For any level of <code>genh</code>, the estimated odds that a person who eats 2 servings has better (lower) <code>genh</code> is about 1.2 times the odds for someone who eats one serving. Those who eat more vegetables have higher odds of better (lower) <code>genh</code>. Less than 1 means lower odds, and more than 1 means greater odds.</p>
<p>Now, let’s take the log of the odds ratios:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(odds<span class="fl">.2</span><span class="sc">/</span>odds<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 1-E|2_VG  2_VG|3_G   3_G|4_F   4_F|5_P 
0.1847272 0.1847272 0.1847272 0.1847272 </code></pre>
</div>
</div>
<p>That should be familiar. It is the slope coefficient in the model summary, without the minus sign. R tacks on a minus sign so that higher levels of predictors correspond to the ordinal outcome falling in the higher end of its scale.</p>
<p>If we exponentiate the slope estimated by R (-0.1847), we get 0.83. If we have two people, and A eats one more serving of vegetables on average than B, then the estimated odds of A having a higher ‘genh’ (i.e.&nbsp;worse general health) are 83% as high as B’s.</p>
<section id="testing-the-proportional-odds-assumption" class="level3" data-number="27.7.1">
<h3 data-number="27.7.1" class="anchored" data-anchor-id="testing-the-proportional-odds-assumption"><span class="header-section-number">27.7.1</span> Testing the Proportional Odds Assumption</h3>
<p>One way to test the proportional odds assumption is to compare the fit of the proportional odds logistic regression to a model that does not make that assumption. A natural candidate is a <strong>multinomial logit</strong> model, which is typically used to model unordered multi-categorical outcomes, and fits a slope to each level of the <code>genh</code> outcome in this case, as opposed to the proportional odds logit, which fits only one slope across all levels.</p>
<p>Since the proportional odds logistic regression model is nested in the multinomial logit, we can perform a likelihood ratio test. To do this, we first fit the multinomial logit model, with the <code>multinom</code> function from the <code>nnet</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>(m1_multi <span class="ot">&lt;-</span> <span class="fu">multinom</span>(genh <span class="sc">~</span> veg_day, <span class="at">data =</span> sm1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  15 (8 variable)
initial  value 8681.308100 
iter  10 value 7890.985276
final  value 7835.248471 
converged</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = genh ~ veg_day, data = sm1)

Coefficients:
     (Intercept)     veg_day
2_VG   0.9791063 -0.09296694
3_G    1.0911990 -0.19260067
4_F    0.5708594 -0.31080687
5_P   -0.3583310 -0.34340619

Residual Deviance: 15670.5 
AIC: 15686.5 </code></pre>
</div>
</div>
<p>The multinomial logit fits four intercepts and four slopes, for a total of 8 estimated parameters. The proportional odds logit, as we’ve seen, fits four intercepts and one slope, for a total of 5. The difference is 3, and we use that number in the sequence below to build our test of the proportional odds assumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>LL_1 <span class="ot">&lt;-</span> <span class="fu">logLik</span>(m1)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>LL_1m <span class="ot">&lt;-</span> <span class="fu">logLik</span>(m1_multi)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>(G <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> (LL_1[<span class="dv">1</span>] <span class="sc">-</span> LL_1m[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.6488392</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(G, <span class="dv">3</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>The <em>p</em> value is very large, so it indicates that the proportional odds model fits about as well as the more complex multinomial logit. A non-significant <em>p</em> value here isn’t always the best way to assess the proportional odds assumption, but it does provide some evidence of model adequacy.</p>
</section>
</section>
<section id="can-model-m1-be-fit-using-rms-tools" class="level2" data-number="27.8">
<h2 data-number="27.8" class="anchored" data-anchor-id="can-model-m1-be-fit-using-rms-tools"><span class="header-section-number">27.8</span> Can model <code>m1</code> be fit using <code>rms</code> tools?</h2>
<p>Yes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">datadist</span>(sm1)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">datadist =</span> <span class="st">"d"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>m1_lrm <span class="ot">&lt;-</span> <span class="fu">lrm</span>(genh <span class="sc">~</span> veg_day, <span class="at">data =</span> sm1, <span class="at">x =</span> T, <span class="at">y =</span> T)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>m1_lrm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = genh ~ veg_day, data = sm1, x = T, y = T)


Frequencies of Responses

 1-E 2_VG  3_G  4_F  5_P 
 822 1805 1667  801  299 

                       Model Likelihood     Discrimination    Rank Discrim.    
                             Ratio Test            Indexes          Indexes    
Obs          5394    LR chi2      75.04     R2       0.015    C       0.555    
max |deriv| 2e-13    d.f.             1    R2(1,5394)0.014    Dxy     0.111    
                     Pr(&gt; chi2) &lt;0.0001    R2(1,4995)0.015    gamma   0.111    
                                            Brier    0.247    tau-a   0.082    

        Coef    S.E.   Wald Z Pr(&gt;|Z|)
y&gt;=2_VG  2.0866 0.0584  35.76 &lt;0.0001 
y&gt;=3_G   0.4065 0.0498   8.16 &lt;0.0001 
y&gt;=4_F  -1.0202 0.0521 -19.58 &lt;0.0001 
y&gt;=5_P  -2.5002 0.0710 -35.22 &lt;0.0001 
veg_day -0.1847 0.0218  -8.48 &lt;0.0001 </code></pre>
</div>
</div>
<p>The model is highly significant (remember the large sample size) but very weak, with a Nagelkerke <span class="math inline">\(R^2\)</span> of 0.015, and a C statistic of 0.555.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_lrm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Effects              Response : genh 

 Factor      Low  High Diff. Effect   S.E.     Lower 0.95 Upper 0.95
 veg_day     1.21 2.36 1.15  -0.21243 0.025051 -0.26153   -0.16334  
  Odds Ratio 1.21 2.36 1.15   0.80861       NA  0.76987    0.84931  </code></pre>
</div>
</div>
<p>A change from 1.21 to 2.36 servings in <code>veg_day</code> is associated with an odds ratio of 0.81, with 95% confidence interval (0.77, 0.85). Since these values are all below 1, we have a clear indication of a statistically detectable effect of <code>veg_day</code> with higher <code>veg_day</code> associated with lower <code>genh</code>, which means, in this case, better health.</p>
<p>There is also a tool in <code>rms</code> called <code>orm</code> which may be used to fit a wide array of ordinal regression models. I suggest you read Frank Harrell’s book on <em>Regression Modeling Strategies</em> if you want to learn more.</p>
</section>
<section id="building-a-three-predictor-model" class="level2" data-number="27.9">
<h2 data-number="27.9" class="anchored" data-anchor-id="building-a-three-predictor-model"><span class="header-section-number">27.9</span> Building a Three-Predictor Model</h2>
<p>Now, we’ll model <code>genh</code> using <code>veg_day</code>, <code>bmi</code> and <code>costprob</code>.</p>
<section id="scatterplot-matrix" class="level3" data-number="27.9.1">
<h3 data-number="27.9.1" class="anchored" data-anchor-id="scatterplot-matrix"><span class="header-section-number">27.9.1</span> Scatterplot Matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(sm1 <span class="sc">|&gt;</span> </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">select</span>(bmi, veg_day, costprob, genh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We might choose to plot the <code>costprob</code> data as a binary factor, rather than the raw 0-1 numbers included above, but not at this time.</p>
</section>
<section id="our-three-predictor-model-m2" class="level3" data-number="27.9.2">
<h3 data-number="27.9.2" class="anchored" data-anchor-id="our-three-predictor-model-m2"><span class="header-section-number">27.9.2</span> Our Three-Predictor Model, <code>m2</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">polr</span>(genh <span class="sc">~</span> veg_day <span class="sc">+</span> bmi <span class="sc">+</span> costprob, <span class="at">data =</span> sm1)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = genh ~ veg_day + bmi + costprob, data = sm1)

Coefficients:
            Value Std. Error t value
veg_day  -0.17130   0.021783  -7.864
bmi       0.06673   0.003855  17.311
costprob  0.96825   0.084871  11.409

Intercepts:
         Value   Std. Error t value
1-E|2_VG -0.1252  0.1229    -1.0183
2_VG|3_G  1.6358  0.1234    13.2572
3_G|4_F   3.1534  0.1294    24.3755
4_F|5_P   4.6881  0.1412    33.1928

Residual Deviance: 15229.24 
AIC: 15243.24 </code></pre>
</div>
</div>
<p>This model contains four intercepts (to cover the five <code>genh</code> categories) and three slopes (one each for <code>veg_day</code>, <code>bmi</code> and <code>costprob</code>.)</p>
</section>
<section id="does-the-three-predictor-model-outperform-m1" class="level3" data-number="27.9.3">
<h3 data-number="27.9.3" class="anchored" data-anchor-id="does-the-three-predictor-model-outperform-m1"><span class="header-section-number">27.9.3</span> Does the three-predictor model outperform <code>m1</code>?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1, m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of ordinal regression models

Response: genh
                     Model Resid. df Resid. Dev   Test    Df LR stat. Pr(Chi)
1                  veg_day      5389   15669.85                              
2 veg_day + bmi + costprob      5387   15229.24 1 vs 2     2 440.6041       0</code></pre>
</div>
</div>
<p>There is a statistically significant improvement in fit from model 1 to model 2. The AIC and BIC are also better for the three-predictor model than they were for the model with <code>veg_day</code> alone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(m1, m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df      AIC
m1  5 15679.85
m2  7 15243.24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(m1, m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df      BIC
m1  5 15712.81
m2  7 15289.40</code></pre>
</div>
</div>
</section>
<section id="wald-tests-for-individual-predictors" class="level3" data-number="27.9.4">
<h3 data-number="27.9.4" class="anchored" data-anchor-id="wald-tests-for-individual-predictors"><span class="header-section-number">27.9.4</span> Wald tests for individual predictors</h3>
<p>To obtain the appropriate Wald tests, we can use <code>lrm</code> to fit the model instead.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">datadist</span>(sm1)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">datadist =</span> <span class="st">"d"</span>)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>m2_lrm <span class="ot">&lt;-</span> <span class="fu">lrm</span>(genh <span class="sc">~</span> veg_day <span class="sc">+</span> bmi <span class="sc">+</span> costprob, </span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> sm1, <span class="at">x =</span> T, <span class="at">y =</span> T)</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>m2_lrm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = genh ~ veg_day + bmi + costprob, data = sm1, x = T, 
    y = T)


Frequencies of Responses

 1-E 2_VG  3_G  4_F  5_P 
 822 1805 1667  801  299 

                       Model Likelihood     Discrimination    Rank Discrim.    
                             Ratio Test            Indexes          Indexes    
Obs          5394    LR chi2     515.65     R2       0.096    C       0.629    
max |deriv| 4e-09    d.f.             3    R2(3,5394)0.091    Dxy     0.258    
                     Pr(&gt; chi2) &lt;0.0001    R2(3,4995)0.098    gamma   0.258    
                                            Brier    0.231    tau-a   0.192    

         Coef    S.E.   Wald Z Pr(&gt;|Z|)
y&gt;=2_VG   0.1252 0.1229   1.02 0.3085  
y&gt;=3_G   -1.6358 0.1234 -13.26 &lt;0.0001 
y&gt;=4_F   -3.1534 0.1294 -24.38 &lt;0.0001 
y&gt;=5_P   -4.6881 0.1412 -33.19 &lt;0.0001 
veg_day  -0.1713 0.0218  -7.86 &lt;0.0001 
bmi       0.0667 0.0039  17.31 &lt;0.0001 
costprob  0.9683 0.0849  11.41 &lt;0.0001 </code></pre>
</div>
</div>
<p>It appears that each of the added predictors (<code>bmi</code> and <code>costprob</code>) adds statistically detectable value to the model.</p>
</section>
<section id="a-cross-tabulation-of-predictions-1" class="level3" data-number="27.9.5">
<h3 data-number="27.9.5" class="anchored" data-anchor-id="a-cross-tabulation-of-predictions-1"><span class="header-section-number">27.9.5</span> A Cross-Tabulation of Predictions?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">table</span>(<span class="fu">predict</span>(m2), sm1<span class="sc">$</span>genh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      
        1-E 2_VG  3_G  4_F  5_P  Sum
  1-E     6    5    4    1    0   16
  2_VG  686 1295  950  388  141 3460
  3_G   128  495  672  374  135 1804
  4_F     1    9   38   36   20  104
  5_P     1    1    3    2    3   10
  Sum   822 1805 1667  801  299 5394</code></pre>
</div>
</div>
<p>At least the <code>m2</code> model predicted that a few of the cases will fall in the Fair and Poor categories, but still, this isn’t impressive.</p>
</section>
<section id="interpreting-the-effect-sizes" class="level3" data-number="27.9.6">
<h3 data-number="27.9.6" class="anchored" data-anchor-id="interpreting-the-effect-sizes"><span class="header-section-number">27.9.6</span> Interpreting the Effect Sizes</h3>
<p>We can do this in two ways:</p>
<ul>
<li>By exponentiating the <code>polr</code> output, which shows the effect of increasing each predictor by a single unit
<ul>
<li>Increasing <code>veg_day</code> by 1 serving while holding the other predictors constant is associated with reducing the odds (by a factor of 0.84 with 95% CI 0.81, 0.88)) of higher values of <code>genh</code>: hence increasing <code>veg_day</code> is associated with increasing the odds of a response indicating better health.</li>
<li>Increasing <code>bmi</code> by 1 kg/m<sup>2</sup> while holding the other predictors constant is associated with increasing the odds (by a factor of 1.07 with 95% CI 1.06, 1.08)) of higher values of <code>genh</code>: hence increasing <code>bmi</code> is associated with reducing the odds of a response indicating better health.</li>
<li>Increasing <code>costprob</code> from 0 to 1 while holding the other predictors constant is associated with an increase (by a factor of 2.63 with 95% CI 2.23, 3.11)) of a higher <code>genh</code> value. Since higher <code>genh</code> values indicate worse health, those with <code>costprob</code> = 1 are modeled to have generally worse health.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  veg_day       bmi  costprob 
0.8425722 1.0690045 2.6333356 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(m2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 %   97.5 %
veg_day  0.8071346 0.879096
bmi      1.0609722 1.077126
costprob 2.2301783 3.110633</code></pre>
</div>
</div>
<ul>
<li>Or by looking at the summary provided by <code>lrm</code>, which like all such summaries produced by <code>rms</code> shows the impact of moving from the 25th to the 75th percentile on all continuous predictors.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2_lrm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Effects              Response : genh 

 Factor      Low   High   Diff.  Effect   S.E.     Lower 0.95 Upper 0.95
 veg_day      1.21  2.360 1.1500 -0.19699 0.025051 -0.24609   -0.14789  
  Odds Ratio  1.21  2.360 1.1500  0.82120       NA  0.78185    0.86252  
 bmi         24.33 31.988 7.6575  0.51097 0.029515  0.45312    0.56882  
  Odds Ratio 24.33 31.988 7.6575  1.66690       NA  1.57320    1.76620  
 costprob     0.00  1.000 1.0000  0.96825 0.084871  0.80191    1.13460  
  Odds Ratio  0.00  1.000 1.0000  2.63330       NA  2.22980    3.10990  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summary</span>(m2_lrm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="quality-of-the-model-fit" class="level3" data-number="27.9.7">
<h3 data-number="27.9.7" class="anchored" data-anchor-id="quality-of-the-model-fit"><span class="header-section-number">27.9.7</span> Quality of the Model Fit</h3>
<p>Model <code>m2</code>, as we can see from the <code>m2_lrm</code> output, is still weak, with a Nagelkerke <span class="math inline">\(R^2\)</span> of 0.10, and a C statistic of 0.63.</p>
</section>
<section id="validating-the-summary-statistics-in-m2_lrm" class="level3" data-number="27.9.8">
<h3 data-number="27.9.8" class="anchored" data-anchor-id="validating-the-summary-statistics-in-m2_lrm"><span class="header-section-number">27.9.8</span> Validating the Summary Statistics in <code>m2_lrm</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">43203</span>); <span class="fu">validate</span>(m2_lrm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          index.orig training    test optimism index.corrected  n
Dxy           0.2583   0.2625  0.2579   0.0046          0.2537 40
R2            0.0964   0.0989  0.0960   0.0029          0.0935 40
Intercept     0.0000   0.0000 -0.0023   0.0023         -0.0023 40
Slope         1.0000   1.0000  0.9876   0.0124          0.9876 40
Emax          0.0000   0.0000  0.0031   0.0031          0.0031 40
D             0.0954   0.0980  0.0950   0.0030          0.0924 40
U            -0.0004  -0.0004 -1.5149   1.5146         -1.5149 40
Q             0.0958   0.0984  1.6099  -1.5115          1.6073 40
B             0.2314   0.2308  0.2315  -0.0007          0.2321 40
g             0.6199   0.6278  0.6182   0.0096          0.6103 40
gp            0.1434   0.1448  0.1430   0.0018          0.1417 40</code></pre>
</div>
</div>
<p>As in our work with binary logistic regression, we can convert the index-corrected Dxy to an index-corrected C with C = 0.5 + (Dxy/2). Both the <span class="math inline">\(R^2\)</span> and C statistics are pretty consistent with what we saw above.</p>
</section>
<section id="testing-the-proportional-odds-assumption-1" class="level3" data-number="27.9.9">
<h3 data-number="27.9.9" class="anchored" data-anchor-id="testing-the-proportional-odds-assumption-1"><span class="header-section-number">27.9.9</span> Testing the Proportional Odds Assumption</h3>
<p>Again, we’ll fit the analogous multinomial logit model, with the <code>multinom</code> function from the <code>nnet</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>(m2_multi <span class="ot">&lt;-</span> <span class="fu">multinom</span>(genh <span class="sc">~</span> veg_day <span class="sc">+</span> bmi <span class="sc">+</span> costprob, </span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> sm1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  25 (16 variable)
initial  value 8681.308100 
iter  10 value 8025.745934
iter  20 value 7605.878993
final  value 7595.767250 
converged</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = genh ~ veg_day + bmi + costprob, data = sm1)

Coefficients:
     (Intercept)    veg_day        bmi  costprob
2_VG  -0.9126285 -0.0905958 0.06947231 0.3258568
3_G   -2.1886806 -0.1893454 0.11552563 1.0488262
4_F   -3.4095145 -0.3056028 0.13679908 1.4422074
5_P   -4.2629564 -0.3384199 0.13178846 1.8612088

Residual Deviance: 15191.53 
AIC: 15223.53 </code></pre>
</div>
</div>
<p>The multinomial logit fits four intercepts and 12 slopes, for a total of 16 estimated parameters. The proportional odds logit in model <code>m2</code>, as we’ve seen, fits four intercepts and three slopes, for a total of 7. The difference is 9, and we use that number in the sequence below to build our test of the proportional odds assumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>LL_2 <span class="ot">&lt;-</span> <span class="fu">logLik</span>(m2)</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>LL_2m <span class="ot">&lt;-</span> <span class="fu">logLik</span>(m2_multi)</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>(G <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> (LL_2[<span class="dv">1</span>] <span class="sc">-</span> LL_2m[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37.70952</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(G, <span class="dv">9</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.965186e-05</code></pre>
</div>
</div>
<p>The result is highly significant, suggesting that we have a problem somewhere with the proportional odds assumption. When this happens, I suggest you build the following plot of score residuals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">resid</span>(m2_lrm, <span class="st">'score.binary'</span>, <span class="at">pl=</span><span class="cn">TRUE</span>)</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this plot, <code>bmi</code> (especially) and <code>costprob</code> vary as we move from the Very Good toward the Poor cutpoints, relative to <code>veg_day</code>, which is more stable.</p>
</section>
<section id="plotting-the-fitted-model" class="level3" data-number="27.9.10">
<h3 data-number="27.9.10" class="anchored" data-anchor-id="plotting-the-fitted-model"><span class="header-section-number">27.9.10</span> Plotting the Fitted Model</h3>
<section id="nomogram" class="level4" data-number="27.9.10.1">
<h4 data-number="27.9.10.1" class="anchored" data-anchor-id="nomogram"><span class="header-section-number">27.9.10.1</span> Nomogram</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>fun.ge3 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">plogis</span>(x <span class="sc">-</span> m2_lrm<span class="sc">$</span>coef[<span class="dv">1</span>] <span class="sc">+</span> m2_lrm<span class="sc">$</span>coef[<span class="dv">2</span>])</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>fun.ge4 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">plogis</span>(x <span class="sc">-</span> m2_lrm<span class="sc">$</span>coef[<span class="dv">1</span>] <span class="sc">+</span> m2_lrm<span class="sc">$</span>coef[<span class="dv">3</span>])</span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>fun.ge5 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">plogis</span>(x <span class="sc">-</span> m2_lrm<span class="sc">$</span>coef[<span class="dv">1</span>] <span class="sc">+</span> m2_lrm<span class="sc">$</span>coef[<span class="dv">4</span>])</span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">nomogram</span>(m2_lrm, <span class="at">fun=</span><span class="fu">list</span>(<span class="st">'Prob Y &gt;= 2 (VG or worse)'</span> <span class="ot">=</span> plogis, </span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'Prob Y &gt;= 3 (Good or worse)'</span> <span class="ot">=</span> fun.ge3,</span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'Prob Y &gt;= 4 (Fair or Poor)'</span> <span class="ot">=</span> fun.ge4,</span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'Prob Y = 5 (Poor)'</span> <span class="ot">=</span> fun.ge5)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="960"></p>
</div>
</div>
</section>
<section id="using-predict-and-showing-mean-prediction-on-1-5-scale" class="level4" data-number="27.9.10.2">
<h4 data-number="27.9.10.2" class="anchored" data-anchor-id="using-predict-and-showing-mean-prediction-on-1-5-scale"><span class="header-section-number">27.9.10.2</span> Using Predict and showing mean prediction on 1-5 scale</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">Predict</span>(m2_lrm, <span class="at">fun =</span> <span class="fu">Mean</span>(m2_lrm, <span class="at">code =</span> <span class="cn">TRUE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The nomogram and Predict results would be more interesting, of course, if we included a spline or interaction term. Let’s do that in model <code>m3_lrm</code>, and also add the <code>incomegroup</code> information.</p>
</section>
</section>
</section>
<section id="a-larger-model-including-income-group" class="level2" data-number="27.10">
<h2 data-number="27.10" class="anchored" data-anchor-id="a-larger-model-including-income-group"><span class="header-section-number">27.10</span> A Larger Model, including income group</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>m3_lrm <span class="ot">&lt;-</span> <span class="fu">lrm</span>(gen_n <span class="sc">~</span> <span class="fu">rcs</span>(veg_day,<span class="dv">3</span>) <span class="sc">+</span> <span class="fu">rcs</span>(bmi, <span class="dv">4</span>) <span class="sc">+</span> </span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>                  incomegroup <span class="sc">+</span> <span class="fu">catg</span>(costprob) <span class="sc">+</span> </span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>                  bmi <span class="sc">%ia%</span> costprob, </span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> sm1, <span class="at">x =</span> T, <span class="at">y =</span> T)</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>m3_lrm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = gen_n ~ rcs(veg_day, 3) + rcs(bmi, 4) + incomegroup + 
    catg(costprob) + bmi %ia% costprob, data = sm1, x = T, y = T)


Frequencies of Responses

   1    2    3    4    5 
 822 1805 1667  801  299 

                       Model Likelihood      Discrimination    Rank Discrim.    
                             Ratio Test             Indexes          Indexes    
Obs          5394    LR chi2    1190.35      R2       0.209    C       0.696    
max |deriv| 1e-11    d.f.            14    R2(14,5394)0.196    Dxy     0.391    
                     Pr(&gt; chi2) &lt;0.0001    R2(14,4995)0.210    gamma   0.392    
                                             Brier    0.214    tau-a   0.291    

                   Coef    S.E.   Wald Z Pr(&gt;|Z|)
y&gt;=2                3.7535 0.4852   7.74 &lt;0.0001 
y&gt;=3                1.8717 0.4838   3.87 0.0001  
y&gt;=4                0.2035 0.4831   0.42 0.6737  
y&gt;=5               -1.4386 0.4846  -2.97 0.0030  
veg_day            -0.2602 0.0633  -4.11 &lt;0.0001 
veg_day'            0.1756 0.0693   2.53 0.0113  
bmi                -0.0325 0.0203  -1.60 0.1086  
bmi'                0.5422 0.0989   5.48 &lt;0.0001 
bmi''              -1.4579 0.2663  -5.47 &lt;0.0001 
incomegroup=10-14K  0.2445 0.1705   1.43 0.1516  
incomegroup=15-19K -0.2626 0.1582  -1.66 0.0969  
incomegroup=20-24K -0.6434 0.1501  -4.29 &lt;0.0001 
incomegroup=25-34K -0.7427 0.1459  -5.09 &lt;0.0001 
incomegroup=35-49K -1.1621 0.1415  -8.21 &lt;0.0001 
incomegroup=50-74K -1.4579 0.1418 -10.28 &lt;0.0001 
incomegroup=75K+   -1.8592 0.1361 -13.66 &lt;0.0001 
costprob=1          1.4576 0.3528   4.13 &lt;0.0001 
bmi * costprob     -0.0259 0.0116  -2.24 0.0250  </code></pre>
</div>
</div>
<p>Another option here would have been to consider building <code>incomegroup</code> as a <code>scored</code> variable, with an order on its own, but I won’t force that here. Here’s the <code>polr</code> version…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">polr</span>(genh <span class="sc">~</span> <span class="fu">rcs</span>(veg_day,<span class="dv">3</span>) <span class="sc">+</span> <span class="fu">rcs</span>(bmi, <span class="dv">4</span>) <span class="sc">+</span> </span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>               incomegroup <span class="sc">+</span> costprob <span class="sc">+</span> </span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>               bmi <span class="sc">%ia%</span> costprob, <span class="at">data =</span> sm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="cross-tabulation-of-predictedobserved-classifications" class="level3" data-number="27.10.1">
<h3 data-number="27.10.1" class="anchored" data-anchor-id="cross-tabulation-of-predictedobserved-classifications"><span class="header-section-number">27.10.1</span> Cross-Tabulation of Predicted/Observed Classifications</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">table</span>(<span class="fu">predict</span>(m3), sm1<span class="sc">$</span>genh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      
        1-E 2_VG  3_G  4_F  5_P  Sum
  1-E     3    2    0    0    0    5
  2_VG  642 1200  815  221   49 2927
  3_G   170  565  754  468  182 2139
  4_F     7   37   96  108   65  313
  5_P     0    1    2    4    3   10
  Sum   822 1805 1667  801  299 5394</code></pre>
</div>
</div>
<p>This model predicts more Fair results, but still far too many Very Good with no Excellent at all.</p>
</section>
<section id="nomogram-1" class="level3" data-number="27.10.2">
<h3 data-number="27.10.2" class="anchored" data-anchor-id="nomogram-1"><span class="header-section-number">27.10.2</span> Nomogram</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>fun.ge3 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">plogis</span>(x <span class="sc">-</span> m3_lrm<span class="sc">$</span>coef[<span class="dv">1</span>] <span class="sc">+</span> m3_lrm<span class="sc">$</span>coef[<span class="dv">2</span>])</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>fun.ge4 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">plogis</span>(x <span class="sc">-</span> m3_lrm<span class="sc">$</span>coef[<span class="dv">1</span>] <span class="sc">+</span> m3_lrm<span class="sc">$</span>coef[<span class="dv">3</span>])</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a>fun.ge5 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">plogis</span>(x <span class="sc">-</span> m3_lrm<span class="sc">$</span>coef[<span class="dv">1</span>] <span class="sc">+</span> m3_lrm<span class="sc">$</span>coef[<span class="dv">4</span>])</span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">nomogram</span>(m3_lrm, <span class="at">fun=</span><span class="fu">list</span>(<span class="st">'Prob Y &gt;= 2 (VG or worse)'</span> <span class="ot">=</span> plogis, </span>
<span id="cb120-6"><a href="#cb120-6" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'Prob Y &gt;= 3 (Good or worse)'</span> <span class="ot">=</span> fun.ge3,</span>
<span id="cb120-7"><a href="#cb120-7" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'Prob Y &gt;= 4 (Fair or Poor)'</span> <span class="ot">=</span> fun.ge4,</span>
<span id="cb120-8"><a href="#cb120-8" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'Prob Y = 5 (Poor)'</span> <span class="ot">=</span> fun.ge5)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="960"></p>
</div>
</div>
</section>
<section id="using-predict-and-showing-mean-prediction-on-1-5-scale-1" class="level3" data-number="27.10.3">
<h3 data-number="27.10.3" class="anchored" data-anchor-id="using-predict-and-showing-mean-prediction-on-1-5-scale-1"><span class="header-section-number">27.10.3</span> Using Predict and showing mean prediction on 1-5 scale</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">Predict</span>(m3_lrm, <span class="at">fun =</span> <span class="fu">Mean</span>(m3_lrm, <span class="at">code =</span> <span class="cn">TRUE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ordinaloutcome_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, we’re plotting the mean score on the 1-5 <code>gen_n</code> scale.</p>
</section>
<section id="validating-the-summary-statistics-in-m3_lrm" class="level3" data-number="27.10.4">
<h3 data-number="27.10.4" class="anchored" data-anchor-id="validating-the-summary-statistics-in-m3_lrm"><span class="header-section-number">27.10.4</span> Validating the Summary Statistics in <code>m3_lrm</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">43221</span>); <span class="fu">validate</span>(m3_lrm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          index.orig training    test optimism index.corrected  n
Dxy           0.3915   0.3928  0.3899   0.0029          0.3886 40
R2            0.2093   0.2112  0.2071   0.0041          0.2053 40
Intercept     0.0000   0.0000  0.0019  -0.0019          0.0019 40
Slope         1.0000   1.0000  0.9871   0.0129          0.9871 40
Emax          0.0000   0.0000  0.0032   0.0032          0.0032 40
D             0.2205   0.2227  0.2179   0.0049          0.2156 40
U            -0.0004  -0.0004 -1.4667   1.4663         -1.4667 40
Q             0.2209   0.2231  1.6845  -1.4614          1.6823 40
B             0.2137   0.2134  0.2142  -0.0007          0.2145 40
g             1.0363   1.0410  1.0276   0.0133          1.0229 40
gp            0.2262   0.2265  0.2244   0.0022          0.2240 40</code></pre>
</div>
</div>
<p>Still not very impressive, but much better than where we started. It’s not crazy to suggest that in new data, we might expect a Nagelkerke <span class="math inline">\(R^2\)</span> of 0.205 and a C statistic of 0.5 + (0.3886/2) = 0.6943.</p>
</section>
</section>
<section id="references-for-this-chapter" class="level2" data-number="27.11">
<h2 data-number="27.11" class="anchored" data-anchor-id="references-for-this-chapter"><span class="header-section-number">27.11</span> References for this Chapter</h2>
<ol type="1">
<li><p>Some of the material here is adapted from http://stats.idre.ucla.edu/r/dae/ordinal-logistic-regression/.</p></li>
<li><p>I also found great guidance at http://data.library.virginia.edu/fitting-and-interpreting-a-proportional-odds-model/</p></li>
<li><p>Other parts are based on the work of Jeffrey S. Simonoff (2003) <em>Analyzing Categorical Data</em> in Chapter 10. Related data and R code are available at http://people.stern.nyu.edu/jsimonof/AnalCatData/Splus/.</p></li>
<li><p>Another good source for a simple example is https://onlinecourses.science.psu.edu/stat504/node/177.</p></li>
<li><p>Also helpful is https://onlinecourses.science.psu.edu/stat504/node/178 which shows a more complex example nicely.</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./count3.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./multinomial.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>