<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Biological, Medical and Health Research - 15&nbsp; A Model for Prostate Cancer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./prostate2.html" rel="next">
<link href="./olsfitting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Biological, Medical and Health Research</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./incomplete.html" class="sidebar-item-text sidebar-link">This is work in progress</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">R Setup</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Building the <code>nh432</code> example</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nh432cb.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook for <code>nh432</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">431 Review: Comparing Means</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">431 Review: Comparing Rates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./431review3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">431 Review: Fitting Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">BRFSS SMART Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleimputation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Missingness: Single Imputation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasummaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing <code>smart_cle1</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovasmart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance with SMART</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovaexamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Interaction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_emphysema.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova_smart.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance with the SMART data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonlinearity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Adding Non-linear Terms to a Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./olsfitting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate1.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prostate2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple_imp.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Imputation and Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tableone.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Building Table 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic Regression: The Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>glm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Logistic Regression with <code>lrm</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./effectsize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimating and Interpreting Effect Sizes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binaryregression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Colorectal Cancer Screening and Some Special Cases</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling a Count Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Negative Binomial Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Zero-Inflated Models for Count Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinaloutcome.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modeling an Ordinal Categorical Outcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multinomial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Time To Event / Survival Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Cox Regression Models, Part 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup-used-here" id="toc-r-setup-used-here" class="nav-link active" data-scroll-target="#r-setup-used-here"><span class="toc-section-number">15.1</span>  R Setup Used Here</a>
  <ul class="collapse">
  <li><a href="#data-load" id="toc-data-load" class="nav-link" data-scroll-target="#data-load"><span class="toc-section-number">15.1.1</span>  Data Load</a></li>
  </ul></li>
  <li><a href="#data-load-and-background" id="toc-data-load-and-background" class="nav-link" data-scroll-target="#data-load-and-background"><span class="toc-section-number">15.2</span>  Data Load and Background</a></li>
  <li><a href="#code-book" id="toc-code-book" class="nav-link" data-scroll-target="#code-book"><span class="toc-section-number">15.3</span>  Code Book</a></li>
  <li><a href="#additions-for-later-use" id="toc-additions-for-later-use" class="nav-link" data-scroll-target="#additions-for-later-use"><span class="toc-section-number">15.4</span>  Additions for Later Use</a></li>
  <li><a href="#fitting-and-evaluating-a-two-predictor-model" id="toc-fitting-and-evaluating-a-two-predictor-model" class="nav-link" data-scroll-target="#fitting-and-evaluating-a-two-predictor-model"><span class="toc-section-number">15.5</span>  Fitting and Evaluating a Two-Predictor Model</a>
  <ul class="collapse">
  <li><a href="#using-tidy" id="toc-using-tidy" class="nav-link" data-scroll-target="#using-tidy"><span class="toc-section-number">15.5.1</span>  Using <code>tidy</code></a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="toc-section-number">15.5.2</span>  Interpretation</a></li>
  </ul></li>
  <li><a href="#exploring-model-prost_a" id="toc-exploring-model-prost_a" class="nav-link" data-scroll-target="#exploring-model-prost_a"><span class="toc-section-number">15.6</span>  Exploring Model <code>prost_A</code></a>
  <ul class="collapse">
  <li><a href="#summary-for-model-prost_a" id="toc-summary-for-model-prost_a" class="nav-link" data-scroll-target="#summary-for-model-prost_a"><span class="toc-section-number">15.6.1</span>  <code>summary</code> for Model <code>prost_A</code></a></li>
  <li><a href="#adjusted-r2" id="toc-adjusted-r2" class="nav-link" data-scroll-target="#adjusted-r2"><span class="toc-section-number">15.6.2</span>  Adjusted <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#coefficient-confidence-intervals" id="toc-coefficient-confidence-intervals" class="nav-link" data-scroll-target="#coefficient-confidence-intervals"><span class="toc-section-number">15.6.3</span>  Coefficient Confidence Intervals</a></li>
  <li><a href="#anova-for-model-prost_a" id="toc-anova-for-model-prost_a" class="nav-link" data-scroll-target="#anova-for-model-prost_a"><span class="toc-section-number">15.6.4</span>  ANOVA for Model <code>prost_A</code></a></li>
  <li><a href="#residuals-fitted-values-and-standard-errors-with-augment" id="toc-residuals-fitted-values-and-standard-errors-with-augment" class="nav-link" data-scroll-target="#residuals-fitted-values-and-standard-errors-with-augment"><span class="toc-section-number">15.6.5</span>  Residuals, Fitted Values and Standard Errors with <code>augment</code></a></li>
  <li><a href="#making-predictions-with-prost_a" id="toc-making-predictions-with-prost_a" class="nav-link" data-scroll-target="#making-predictions-with-prost_a"><span class="toc-section-number">15.6.6</span>  Making Predictions with <code>prost_A</code></a></li>
  </ul></li>
  <li><a href="#plotting-model-prost_a" id="toc-plotting-model-prost_a" class="nav-link" data-scroll-target="#plotting-model-prost_a"><span class="toc-section-number">15.7</span>  Plotting Model <code>prost_A</code></a>
  <ul class="collapse">
  <li><a href="#residual-plots-of-prost_a" id="toc-residual-plots-of-prost_a" class="nav-link" data-scroll-target="#residual-plots-of-prost_a"><span class="toc-section-number">15.7.1</span>  Residual Plots of <code>prost_A</code></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">A Model for Prostate Cancer</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="r-setup-used-here" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="r-setup-used-here"><span class="header-section-number">15.1</span> R Setup Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-load" class="level3" data-number="15.1.1">
<h3 data-number="15.1.1" class="anchored" data-anchor-id="data-load"><span class="header-section-number">15.1.1</span> Data Load</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>prost <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/prost.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="data-load-and-background" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="data-load-and-background"><span class="header-section-number">15.2</span> Data Load and Background</h2>
<p>The data in <code>prost.csv</code> is derived from <span class="citation" data-cites="Stamey1989">Stamey et al. (<a href="references.html#ref-Stamey1989" role="doc-biblioref">1989</a>)</span> who examined the relationship between the level of prostate-specific antigen and a number of clinical measures in 97 men who were about to receive a radical prostatectomy. The <code>prost</code> data, as I’ll name it in R, contains 97 rows and 11 columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>prost</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 97 × 10
   subject   lpsa lcavol lweight   age bph      svi   lcp gleason pgg45
     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;
 1       1 -0.431 -0.580    2.77    50 Low        0 -1.39 6           0
 2       2 -0.163 -0.994    3.32    58 Low        0 -1.39 6           0
 3       3 -0.163 -0.511    2.69    74 Low        0 -1.39 7          20
 4       4 -0.163 -1.20     3.28    58 Low        0 -1.39 6           0
 5       5  0.372  0.751    3.43    62 Low        0 -1.39 6           0
 6       6  0.765 -1.05     3.23    50 Low        0 -1.39 6           0
 7       7  0.765  0.737    3.47    64 Medium     0 -1.39 6           0
 8       8  0.854  0.693    3.54    58 High       0 -1.39 6           0
 9       9  1.05  -0.777    3.54    47 Low        0 -1.39 6           0
10      10  1.05   0.223    3.24    63 Low        0 -1.39 6           0
# ℹ 87 more rows</code></pre>
</div>
</div>
<p>Note that a related <code>prost</code> data frame is also available as part of several R packages, including the <code>faraway</code> package, but there is an error in the <code>lweight</code> data for subject 32 in those presentations. The value of <code>lweight</code> for subject 32 should not be 6.1, corresponding to a prostate that is 449 grams in size, but instead the <code>lweight</code> value should be 3.804438, corresponding to a 44.9 gram prostate<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>I’ve also changed the <code>gleason</code> and <code>bph</code> variables from their presentation in other settings, to let me teach some additional details.</p>
</section>
<section id="code-book" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="code-book"><span class="header-section-number">15.3</span> Code Book</h2>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>subject</code></td>
<td>subject number (1 to 97)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>lpsa</code></td>
<td>log(prostate specific antigen in ng/ml), our <strong>outcome</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>lcavol</code></td>
<td>log(cancer volume in cm<sup>3</sup>)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>lweight</code></td>
<td>log(prostate weight, in g)</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>age</code></td>
<td>age</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>bph</code></td>
<td>benign prostatic hyperplasia amount (Low, Medium, or High)</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>svi</code></td>
<td>seminal vesicle invasion (1 = yes, 0 = no)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>lcp</code></td>
<td>log(capsular penetration, in cm)</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>gleason</code></td>
<td>combined Gleason score (6, 7, or &gt; 7 here)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>pgg45</code></td>
<td>percentage Gleason scores 4 or 5</td>
</tr>
</tbody>
</table>
<p>Notes:</p>
<ul>
<li>in general, higher levels of PSA are stronger indicators of prostate cancer. An old standard (established almost exclusively with testing in white males, and definitely flawed) suggested that values below 4 were normal, and above 4 needed further testing. A PSA of 4 corresponds to an <code>lpsa</code> of 1.39.</li>
<li>all logarithms are natural (base <em>e</em>) logarithms, obtained in R with the function <code>log()</code></li>
<li>all variables other than <code>subject</code> and <code>lpsa</code> are candidate predictors</li>
<li>the <code>gleason</code> variable captures the highest combined Gleason score[^Scores range (in these data) from 6 (a well-differentiated, or low-grade cancer) to 9 (a high-grade cancer), although the maximum possible score is 10. 6 is the lowest score used for cancerous prostates. As this combination value increases, the rate at which the cancer grows and spreads should increase. This score refers to the combined Gleason grade, which is based on the sum of two areas (each scored 1-5) that make up most of the cancer.] in a biopsy, and higher scores indicate more aggressive cancer cells. It’s stored here as 6, 7, or &gt; 7.</li>
<li>the <code>pgg45</code> variable captures the percentage of individual Gleason scores[^The 1-5 scale for individual biopsies are defined so that 1 indicates something that looks like normal prostate tissue, and 5 indicates that the cells and their growth patterns look very abnormal. In this study, the percentage of 4s and 5s shown in the data appears to be based on 5-20 individual scores in most subjects.] that are 4 or 5, on a 1-5 scale, where higher scores indicate more abnormal cells.</li>
</ul>
</section>
<section id="additions-for-later-use" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="additions-for-later-use"><span class="header-section-number">15.4</span> Additions for Later Use</h2>
<p>The code below adds to the <code>prost</code> tibble:</p>
<ul>
<li>a factor version of the <code>svi</code> variable, called <code>svi_f</code>, with levels No and Yes,</li>
<li>a factor version of <code>gleason</code> called <code>gleason_f</code>, with the levels ordered &gt; 7, 7, and finally 6,</li>
<li>a factor version of <code>bph</code> called <code>bph_f</code>, with levels ordered Low, Medium, High,</li>
<li>a centered version of <code>lcavol</code> called <code>lcavol_c</code>,</li>
<li>exponentiated <code>cavol</code> and <code>psa</code> results derived from the natural logarithms <code>lcavol</code> and <code>lpsa</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>prost <span class="ot">&lt;-</span> prost <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">svi_f =</span> <span class="fu">fct_recode</span>(<span class="fu">factor</span>(svi), <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"0"</span>, <span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"1"</span>),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">gleason_f =</span> <span class="fu">fct_relevel</span>(gleason, <span class="fu">c</span>(<span class="st">"&gt; 7"</span>, <span class="st">"7"</span>, <span class="st">"6"</span>)),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">bph_f =</span> <span class="fu">fct_relevel</span>(bph, <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>)),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">lcavol_c =</span> lcavol <span class="sc">-</span> <span class="fu">mean</span>(lcavol),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">cavol =</span> <span class="fu">exp</span>(lcavol),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">psa =</span> <span class="fu">exp</span>(lpsa))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(prost)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 97
Columns: 16
$ subject   &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
$ lpsa      &lt;dbl&gt; -0.4307829, -0.1625189, -0.1625189, -0.1625189, 0.3715636, 0…
$ lcavol    &lt;dbl&gt; -0.5798185, -0.9942523, -0.5108256, -1.2039728, 0.7514161, -…
$ lweight   &lt;dbl&gt; 2.769459, 3.319626, 2.691243, 3.282789, 3.432373, 3.228826, …
$ age       &lt;dbl&gt; 50, 58, 74, 58, 62, 50, 64, 58, 47, 63, 65, 63, 63, 67, 57, …
$ bph       &lt;chr&gt; "Low", "Low", "Low", "Low", "Low", "Low", "Medium", "High", …
$ svi       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ lcp       &lt;dbl&gt; -1.3862944, -1.3862944, -1.3862944, -1.3862944, -1.3862944, …
$ gleason   &lt;chr&gt; "6", "6", "7", "6", "6", "6", "6", "6", "6", "6", "6", "6", …
$ pgg45     &lt;dbl&gt; 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 5, 5, 0, 30, 0, 0, …
$ svi_f     &lt;fct&gt; No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, …
$ gleason_f &lt;fct&gt; 6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 6, 7, 6, 6, 6, …
$ bph_f     &lt;fct&gt; Low, Low, Low, Low, Low, Low, Medium, High, Low, Low, Low, M…
$ lcavol_c  &lt;dbl&gt; -1.9298281, -2.3442619, -1.8608352, -2.5539824, -0.5985935, …
$ cavol     &lt;dbl&gt; 0.56, 0.37, 0.60, 0.30, 2.12, 0.35, 2.09, 2.00, 0.46, 1.25, …
$ psa       &lt;dbl&gt; 0.65, 0.85, 0.85, 0.85, 1.45, 2.15, 2.15, 2.35, 2.85, 2.85, …</code></pre>
</div>
</div>
</section>
<section id="fitting-and-evaluating-a-two-predictor-model" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="fitting-and-evaluating-a-two-predictor-model"><span class="header-section-number">15.5</span> Fitting and Evaluating a Two-Predictor Model</h2>
<p>To begin, let’s use two predictors (<code>lcavol</code> and <code>svi</code>) and their interaction in a linear regression model that predicts <code>lpsa</code>. I’ll call this model <code>prost_A</code></p>
<p>Earlier, we centered the <code>lcavol</code> values to facilitate interpretation of the terms. I’ll use that centered version (called <code>lcavol_c</code>) of the quantitative predictor, and the 1/0 version of the <code>svi</code> variable[^We could certainly use the factor version of <code>svi</code> here, but it won’t change the model in any meaningful way. There’s no distinction in model <em>fitting</em> via <code>lm</code> between a 0/1 numeric variable and a No/Yes factor variable. The factor version of this information will be useful elsewhere, for instance in plotting the model.].</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>prost_A <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol_c <span class="sc">*</span> svi, <span class="at">data =</span> prost)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(prost_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lpsa ~ lcavol_c * svi, data = prost)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6305 -0.5007  0.1266  0.4886  1.6847 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.33134    0.09128  25.540  &lt; 2e-16 ***
lcavol_c      0.58640    0.08207   7.145 1.98e-10 ***
svi           0.60132    0.35833   1.678   0.0967 .  
lcavol_c:svi  0.06479    0.26614   0.243   0.8082    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7595 on 93 degrees of freedom
Multiple R-squared:  0.5806,    Adjusted R-squared:  0.5671 
F-statistic: 42.92 on 3 and 93 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="using-tidy" class="level3" data-number="15.5.1">
<h3 data-number="15.5.1" class="anchored" data-anchor-id="using-tidy"><span class="header-section-number">15.5.1</span> Using <code>tidy</code></h3>
<p>It can be very useful to build a data frame of the model’s results. We can use the <code>tidy</code> function in the <code>broom</code> package to do so.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(prost_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term         estimate std.error statistic  p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    2.33      0.0913    25.5   8.25e-44
2 lcavol_c       0.586     0.0821     7.15  1.98e-10
3 svi            0.601     0.358      1.68  9.67e- 2
4 lcavol_c:svi   0.0648    0.266      0.243 8.08e- 1</code></pre>
</div>
</div>
<p>This makes it much easier to pull out individual elements of the model fit.</p>
<p>For example, to specify the coefficient for <strong>svi</strong>, rounded to three decimal places, I could use</p>
<pre><code>tidy(prost_A) |&gt; filter(term == "svi") |&gt; select(estimate) |&gt; round(3)</code></pre>
<ul>
<li>The result is 0.601.</li>
<li>If you look at the Markdown file, you’ll see that the number shown in the bullet point above this one was generated using inline R code, and the function specified above.</li>
</ul>
</section>
<section id="interpretation" class="level3" data-number="15.5.2">
<h3 data-number="15.5.2" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">15.5.2</span> Interpretation</h3>
<ol type="1">
<li>The intercept, 2.33, for the model is the predicted value of <code>lpsa</code> when <code>lcavol</code> is at its average and there is no seminal vesicle invasion (e.g.&nbsp;<code>svi</code> = 0).</li>
<li>The coefficient for <code>lcavol_c</code>, 0.59, is the predicted change in <code>lpsa</code> associated with a one unit increase in <code>lcavol</code> (or <code>lcavol_c</code>) when there is no seminal vesicle invasion.</li>
<li>The coefficient for <code>svi</code>, 0.6, is the predicted change in <code>lpsa</code> associated with having no <code>svi</code> to having an <code>svi</code> while the <code>lcavol</code> remains at its average.</li>
<li>The coefficient for <code>lcavol_c:svi</code>, the product term, which is 0.06, is the difference in the slope of <code>lcavol_c</code> for a subject with <code>svi</code> as compared to one with no <code>svi</code>.</li>
</ol>
</section>
</section>
<section id="exploring-model-prost_a" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="exploring-model-prost_a"><span class="header-section-number">15.6</span> Exploring Model <code>prost_A</code></h2>
<p>The <code>glance</code> function from the <code>broom</code> package builds a nice one-row summary for the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(prost_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.581         0.567 0.759      42.9 1.68e-17     3  -109.  228.  241.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>This summary includes, in order,</p>
<ul>
<li>the model <span class="math inline">\(R^2\)</span>, adjusted <span class="math inline">\(R^2\)</span> and <span class="math inline">\(\hat{\sigma}\)</span>, the residual standard deviation,</li>
<li>the ANOVA F statistic and associated <em>p</em> value,</li>
<li>the number of degrees of freedom used by the model, and its log-likelihood ratio</li>
<li>the model’s AIC (Akaike Information Criterion) and BIC (Bayesian Information Criterion)</li>
<li>the model’s deviance statistic and residual degrees of freedom</li>
</ul>
<section id="summary-for-model-prost_a" class="level3" data-number="15.6.1">
<h3 data-number="15.6.1" class="anchored" data-anchor-id="summary-for-model-prost_a"><span class="header-section-number">15.6.1</span> <code>summary</code> for Model <code>prost_A</code></h3>
<p>If necessary, we can also run <code>summary</code> on this <code>prost_A</code> object to pick up some additional summaries. Since the <code>svi</code> variable is binary, the interaction term is, too, so the <em>t</em> test here and the <em>F</em> test in the ANOVA yield the same result.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(prost_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lpsa ~ lcavol_c * svi, data = prost)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6305 -0.5007  0.1266  0.4886  1.6847 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.33134    0.09128  25.540  &lt; 2e-16 ***
lcavol_c      0.58640    0.08207   7.145 1.98e-10 ***
svi           0.60132    0.35833   1.678   0.0967 .  
lcavol_c:svi  0.06479    0.26614   0.243   0.8082    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7595 on 93 degrees of freedom
Multiple R-squared:  0.5806,    Adjusted R-squared:  0.5671 
F-statistic: 42.92 on 3 and 93 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If you’ve forgotten the details of the pieces of this summary, review the Part C Notes from 431.</p>
</section>
<section id="adjusted-r2" class="level3" data-number="15.6.2">
<h3 data-number="15.6.2" class="anchored" data-anchor-id="adjusted-r2"><span class="header-section-number">15.6.2</span> Adjusted <span class="math inline">\(R^2\)</span></h3>
<p><span class="math inline">\(R^2\)</span> is greedy.</p>
<ul>
<li><span class="math inline">\(R^2\)</span> will always suggest that we make our models as big as possible, often including variables of dubious predictive value.</li>
<li>As a result, there are various methods for penalizing <span class="math inline">\(R^2\)</span> so that we wind up with smaller models.</li>
<li>The <strong>adjusted <span class="math inline">\(R^2\)</span></strong> is often a useful way to compare multiple models for the same response.
<ul>
<li><span class="math inline">\(R^2_{adj} = 1 - \frac{(1-R^2)(n - 1)}{n - k}\)</span>, where <span class="math inline">\(n\)</span> = the number of observations and <span class="math inline">\(k\)</span> is the number of coefficients estimated by the regression (including the intercept and any slopes).</li>
<li>So, in this case, <span class="math inline">\(R^2_{adj} = 1 - \frac{(1 - 0.5806)(97 - 1)}{97 - 4} = 0.5671\)</span></li>
<li>The adjusted <span class="math inline">\(R^2\)</span> value is not, technically, a proportion of anything, but it is comparable across models for the same outcome.</li>
<li>The adjusted <span class="math inline">\(R^2\)</span> will always be less than the (unadjusted) <span class="math inline">\(R^2\)</span>.</li>
</ul></li>
</ul>
</section>
<section id="coefficient-confidence-intervals" class="level3" data-number="15.6.3">
<h3 data-number="15.6.3" class="anchored" data-anchor-id="coefficient-confidence-intervals"><span class="header-section-number">15.6.3</span> Coefficient Confidence Intervals</h3>
<p>Here are the 90% confidence intervals for the coefficients in Model A. Adjust the <code>level</code> to get different intervals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(prost_A, <span class="at">level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     5 %      95 %
(Intercept)   2.17968697 2.4830012
lcavol_c      0.45004577 0.7227462
svi           0.00599401 1.1966454
lcavol_c:svi -0.37737623 0.5069622</code></pre>
</div>
</div>
<p>What can we conclude from this about the utility of the interaction term?</p>
</section>
<section id="anova-for-model-prost_a" class="level3" data-number="15.6.4">
<h3 data-number="15.6.4" class="anchored" data-anchor-id="anova-for-model-prost_a"><span class="header-section-number">15.6.4</span> ANOVA for Model <code>prost_A</code></h3>
<p>The interaction term appears unnecessary. We might wind up fitting the model without it. A complete ANOVA test is available, including a <em>p</em> value, if you want it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(prost_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: lpsa
             Df Sum Sq Mean Sq  F value    Pr(&gt;F)    
lcavol_c      1 69.003  69.003 119.6289 &lt; 2.2e-16 ***
svi           1  5.237   5.237   9.0801  0.003329 ** 
lcavol_c:svi  1  0.034   0.034   0.0593  0.808191    
Residuals    93 53.643   0.577                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Note that the <code>anova</code> approach for a <code>lm</code> object is sequential. The first row shows the impact of <code>lcavol_c</code> as compared to a model with no predictors (just an intercept). The second row shows the impact of adding <code>svi</code> to a model that already contains <code>lcavol_c</code>. The third row shows the impact of adding the interaction (product) term to the model with the two main effects. So the order in which the variables are added to the regression model matters for this ANOVA. The F tests here describe the incremental impact of each covariate in turn.</p>
</section>
<section id="residuals-fitted-values-and-standard-errors-with-augment" class="level3" data-number="15.6.5">
<h3 data-number="15.6.5" class="anchored" data-anchor-id="residuals-fitted-values-and-standard-errors-with-augment"><span class="header-section-number">15.6.5</span> Residuals, Fitted Values and Standard Errors with <code>augment</code></h3>
<p>The <code>augment</code> function in the <code>broom</code> package builds a data frame including the data used in the model, along with predictions (fitted values), residuals and other useful information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>prost_A_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(prost_A)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(prost_A_aug)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      lpsa            lcavol_c             svi            .fitted      
 Min.   :-0.4308   Min.   :-2.69708   Min.   :0.0000   Min.   :0.7498  
 1st Qu.: 1.7317   1st Qu.:-0.83719   1st Qu.:0.0000   1st Qu.:1.8404  
 Median : 2.5915   Median : 0.09691   Median :0.0000   Median :2.3950  
 Mean   : 2.4784   Mean   : 0.00000   Mean   :0.2165   Mean   :2.4784  
 3rd Qu.: 3.0564   3rd Qu.: 0.77703   3rd Qu.:0.0000   3rd Qu.:3.0709  
 Max.   : 5.5829   Max.   : 2.47099   Max.   :1.0000   Max.   :4.5417  
     .resid             .hat             .sigma          .cooksd         
 Min.   :-1.6305   Min.   :0.01316   Min.   :0.7423   Min.   :0.0000069  
 1st Qu.:-0.5007   1st Qu.:0.01562   1st Qu.:0.7569   1st Qu.:0.0007837  
 Median : 0.1266   Median :0.02498   Median :0.7617   Median :0.0034699  
 Mean   : 0.0000   Mean   :0.04124   Mean   :0.7595   Mean   :0.0111314  
 3rd Qu.: 0.4886   3rd Qu.:0.04939   3rd Qu.:0.7631   3rd Qu.:0.0103533  
 Max.   : 1.6847   Max.   :0.24627   Max.   :0.7636   Max.   :0.1341093  
   .std.resid       
 Min.   :-2.194508  
 1st Qu.:-0.687945  
 Median : 0.168917  
 Mean   : 0.001249  
 3rd Qu.: 0.653612  
 Max.   : 2.261830  </code></pre>
</div>
</div>
<p>Elements shown here include:</p>
<ul>
<li><code>.fitted</code> Fitted values of model (or predicted values)</li>
<li><code>.se.fit</code> Standard errors of fitted values</li>
<li><code>.resid</code> Residuals (observed - fitted values)</li>
<li><code>.hat</code> Diagonal of the hat matrix (these indicate <em>leverage</em> - points with high leverage indicate unusual combinations of predictors - values more than 2-3 times the mean leverage are worth some study - leverage is always between 0 and 1, and measures the amount by which the predicted value would change if the observation’s y value was increased by one unit - a point with leverage 1 would cause the line to follow that point perfectly)</li>
<li><code>.sigma</code> Estimate of residual standard deviation when corresponding observation is dropped from model</li>
<li><code>.cooksd</code> Cook’s distance, which helps identify influential points (values of Cook’s d &gt; 0.5 may be influential, values &gt; 1.0 almost certainly are - an influential point changes the fit substantially when it is removed from the data)</li>
<li><code>.std.resid</code> Standardized residuals (values above 2 in absolute value are worth some study - treat these as normal deviates [Z scores], essentially)</li>
</ul>
<p>See <code>?augment.lm</code> in R for more details.</p>
</section>
<section id="making-predictions-with-prost_a" class="level3" data-number="15.6.6">
<h3 data-number="15.6.6" class="anchored" data-anchor-id="making-predictions-with-prost_a"><span class="header-section-number">15.6.6</span> Making Predictions with <code>prost_A</code></h3>
<p>Suppose we want to predict the <code>lpsa</code> for a patient with cancer volume equal to this group’s mean, for both a patient with and without seminal vesicle invasion, and in each case, we want to use a 90% prediction interval?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">lcavol_c =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">svi =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(prost_A, newdata, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 2.331344 1.060462 3.602226
2 2.932664 1.545742 4.319586</code></pre>
</div>
</div>
<p>Since the predicted value in <code>fit</code> refers to the natural logarithm of PSA, to make the predictions in terms of PSA, we would need to exponentiate. The code below will accomplish that task.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(prost_A, newdata, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.90</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 10.29177 2.887706 36.67978
2 18.77758 4.691450 75.15750</code></pre>
</div>
</div>
</section>
</section>
<section id="plotting-model-prost_a" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="plotting-model-prost_a"><span class="header-section-number">15.7</span> Plotting Model <code>prost_A</code></h2>
<section id="plot-logs-conventionally" class="level4" data-number="15.7.0.1">
<h4 data-number="15.7.0.1" class="anchored" data-anchor-id="plot-logs-conventionally"><span class="header-section-number">15.7.0.1</span> Plot logs conventionally</h4>
<p>Here, we’ll use <code>ggplot2</code> to plot the logarithms of the variables as they came to us, on a conventional coordinate scale. Note that the lines are nearly parallel. What does this suggest about our Model A?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(prost, <span class="fu">aes</span>(<span class="at">x =</span> lcavol, <span class="at">y =</span> lpsa, <span class="at">group =</span> svi_f, <span class="at">color =</span> svi_f)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_discrete</span>(<span class="at">name =</span> <span class="st">"Seminal Vesicle Invasion?"</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Log (cancer volume, cc)"</span>, </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Log (Prostate Specific Antigen, ng/ml)"</span>, </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Two Predictor Model prost_A, including Interaction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="prostate1_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="plot-on-log-log-scale" class="level4" data-number="15.7.0.2">
<h4 data-number="15.7.0.2" class="anchored" data-anchor-id="plot-on-log-log-scale"><span class="header-section-number">15.7.0.2</span> Plot on log-log scale</h4>
<p>Another approach (which might be easier in some settings) would be to plot the raw values of Cancer Volume and PSA, but use logarithmic axes, again using the natural (base <em>e</em>) logarithm, as follows. If we use the default choice with `trans = “log”, we’ll find a need to select some useful break points for the grid, as I’ve done in what follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(prost, <span class="fu">aes</span>(<span class="at">x =</span> cavol, <span class="at">y =</span> psa, <span class="at">group =</span> svi_f, <span class="at">color =</span> svi_f)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_discrete</span>(<span class="at">name =</span> <span class="st">"Seminal Vesicle Invasion?"</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>, </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">25</span>, <span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>, </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">10</span>, <span class="dv">25</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>)) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cancer volume, in cubic centimeters"</span>, </span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Prostate Specific Antigen, in ng/ml"</span>, </span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Two Predictor Model prost_A, including Interaction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="prostate1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I’ve used the break point of 4 on the Y axis because of the old rule suggesting further testing for asymptomatic men with PSA of 4 or higher, but the other break points are arbitrary - they seemed to work for me, and used round numbers.</p>
</section>
<section id="residual-plots-of-prost_a" class="level3" data-number="15.7.1">
<h3 data-number="15.7.1" class="anchored" data-anchor-id="residual-plots-of-prost_a"><span class="header-section-number">15.7.1</span> Residual Plots of <code>prost_A</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(prost_A, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="prostate1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(prost_A, <span class="at">which =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="prostate1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In our next Chapter, we’ll see how well this model can be validated.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-Stamey1989" class="csl-entry" role="doc-biblioentry">
Stamey, J. N. Kabalin, T. A. et al. 1989. <span>“Prostate Specific Antigen in the Diagnosis and Treatment of Adenocarcinoma of the Prostate: II. Radical Prostatectomy Treated Patients.”</span> <em>Journal of Urology</em> 141(5): 1076–83. <a href="https://www.ncbi.nlm.nih.gov/pubmed/2468795">https://www.ncbi.nlm.nih.gov/pubmed/2468795</a>.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>https://statweb.stanford.edu/~tibs/ElemStatLearn/ attributes the correction to Professor Stephen W. Link.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./olsfitting.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./prostate2.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Validating our Prostate Cancer Model</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>